pulpcore/app/models/upload.py

Fix the referenced field

---

CHANGES/9003.bugfix
pulpcore/download/base.py
pulpcore/download/file.py

closes: #9003
https://pulp.plan.io/issues/9003

Fix syncs of repos from file:// urls

---

.ci/assets/bindings/test_bindings.rb
CHANGES/9015.bugfix
CHANGES/9025.bugfix
pulpcore/app/serializers/__init__.py
pulpcore/app/serializers/base.py
pulpcore/app/serializers/exporter.py
pulpcore/app/serializers/task.py
pulpcore/download/base.py
pulpcore/download/file.py

3.14.1 backports

---

CHANGES.rst

3.14.1 changelog

---

pulpcore/tests/functional/api/using_plugin/constants.py
pulpcore/tests/functional/api/using_plugin/test_distributions.py

Fixup test w/ PR suggestsions

---

CHANGES/9039.bugfix
pulpcore/app/models/publication.py
pulpcore/content/handler.py

closes: #9039
https://pulp.plan.io/issues/9039

Make auto-distribute feature more intuitive

---

CHANGES/8954.bugfix
pulpcore/app/serializers/fields.py
pulpcore/tests/functional/api/using_plugin/test_crud_repos.py

Replace DictField with JSONField

---

CHANGES/9074.bugfix
pulpcore/cache/cache.py
pulpcore/tests/functional/api/using_plugin/test_content_cache.py
pulpcore/tests/unit/test_cache.py

fixes: #9074
https://pulp.plan.io/issues/9074
Thanks @lubosmj for finding this bug.

Fix cache error when getting invalid files

---

pulpcore/tests/upgrade/pre/test_publish.py

https://pulp.plan.io/issues/9010
[noissue]

Fix upgrade test

---

.github/workflows/scripts/before_install.sh

Fix CLI test after config file name change

---

CHANGES/8500.bugfix
pulpcore/app/viewsets/base.py
pulpcore/app/viewsets/user.py

Validate objects in GroupObjectPermissionViewSet

---

CHANGES/8855.removal
docs/contributing/style-guide.rst
docs/installation/instructions.rst
setup.py

Drop support for Python 3.6 and 3.7

---

.github/dependabot.yml
CHANGES/plugin_api/9018.feature
pulpcore/app/settings.py
pulpcore/tasking/pulpcore_worker.py
pulpcore/tasking/tasks.py
pulpcore/tasking/worker.py
requirements.txt

Bump django to 3.2

---

CHANGES/8931.feature
pulpcore/app/models/task.py
pulpcore/tasking/pulpcore_worker.py

All workers that are considered offline will be removed from the database
periodically.
fixes #8931

Added worker_cleanup to the tasking system

---

pulpcore/app/serializers/repository.py

Add some help text for repository remote field

---

CHANGES/9120.misc
pulpcore/app/settings.py

Fixed ``AutoField`` deprecation warnings

---

CHANGES.rst

The automation failed at auto-creating this due to merge conflicts. This
is the same as https://github.com/pulp/pulpcore/commit/6b57ccecc9272871d15b80ad5868a721ef84049e
[noissue]

Add 3.7.7 changelog

---

requirements.txt

Update aioredis dependency to 2.0.0 (from 2.0.0a1)

---

CHANGES/8459.feature
CHANGES/plugin_api/8459.feature
docs/workflows/index.rst
docs/workflows/reclaim-disk-space.rst
pulpcore/app/models/content.py
pulpcore/app/serializers/__init__.py
pulpcore/app/serializers/reclaim.py
pulpcore/app/tasks/__init__.py
pulpcore/app/tasks/reclaim_space.py
pulpcore/app/urls.py
pulpcore/app/viewsets/__init__.py
pulpcore/app/viewsets/reclaim.py
pulpcore/tests/functional/api/using_plugin/test_reclaim_disk_space.py

Reclaim disk space story.

---

docs/contributing/style-guide.rst

Add a section specifying docs format

---

docs/workflows/reclaim-disk-space.rst
pulpcore/app/serializers/reclaim.py
pulpcore/app/viewsets/reclaim.py

Do not expose to the users ``force`` option for the reclaim disk space.

---

.github/workflows/scripts/install.sh
CHANGES/8824.feature
CHANGES/plugin_api/8824.feature
docs/configuration/settings.rst
pulpcore/app/models/content.py
pulpcore/app/serializers/orphans.py
pulpcore/app/settings.py
pulpcore/app/tasks/orphan.py
pulpcore/app/viewsets/orphans.py
pulpcore/tasking/pulpcore_worker.py
pulpcore/tasking/tasks.py
pulpcore/tests/functional/api/using_plugin/test_orphans.py
pulpcore/tests/functional/api/using_plugin/test_reclaim_disk_space.py
template_config.yml

Orphan clean up is no longer a blocking call.

---

pulpcore/tests/functional/api/using_plugin/test_filesystemexport.py

Use bindings delete_orphans() in tests.

---

CHANGES/8870.bugfix
CHANGES/plugin_api/8870.feature
pulpcore/app/models/publication.py
pulpcore/content/handler.py
pulpcore/tests/functional/api/using_plugin/test_distributions.py

fixes: #8870
https://pulp.plan.io/issues/8870

Prevent access to unpublish content from content app

---

CHANGES/9126.bugfix
CHANGES/9130.bugfix
CHANGES/9179.misc
CHANGES/9202.bugfix
CHANGES/plugin_api/9126.feature
CHANGES/plugin_api/9130.bugfix
pulpcore/app/checks.py
pulpcore/app/files.py
pulpcore/app/models/publication.py
pulpcore/app/models/storage.py
pulpcore/app/settings.py
pulpcore/content/handler.py
pulpcore/plugin/repo_version_utils.py
pulpcore/plugin/stages/artifact_stages.py
pulpcore/tests/functional/api/using_plugin/test_distributions.py
pulpcore/tests/unit/test_files.py

3.14.4 cherrypicks

---

CHANGES/9216.bugfix
pulpcore/content/handler.py

Properly set Content-Type header for artifacts served from S3

---

CHANGES/5582.misc
pulpcore/app/models/repository.py

closes: #5582
https://pulp.plan.io/issues/5582

Fixed an outdated docstring

---

CHANGES/plugin_api/9269.feature
pulpcore/app/models/__init__.py
pulpcore/app/models/content.py
pulpcore/plugin/models/__init__.py
pulpcore/plugin/stages/content_stages.py

closes: #9269
https://pulp.plan.io/issues/9269

Fix issue where plugins with custom content managers can't use touch()

---

CHANGES/8951.feature
pulpcore/content/__init__.py
pulpcore/content/authentication.py

fixes: #8951
https://pulp.plan.io/issues/8951

Add authentication to content app

---

CHANGES.rst

[noissue]
(cherry picked from commit 125c82e321e32f42cd871658fc7c691c316f377c)

Building changelog for 3.7.8

---

CHANGES/plugin_api/9129.deprecation
pulpcore/app/models/progress.py

Docstring tweaks

---

CHANGES/plugin_api/9307.bugfix
pulpcore/plugin/importexport.py

Set WIDGET_MAP for model resources to handle JSON fields

---

CHANGES/8859.doc
docs/contributing/dev-setup.rst

Note the requirements explicitly

---

CHANGES/9100.doc
docs/configuration/settings.rst
docs/installation/instructions.rst

Fix the usages of MEDIA_ROOT

---

CHANGES.rst

3.14.6 changelog

---

CHANGES/9322.removal
pulpcore/app/urls.py

Removed OpenAPI browsable API

---

CHANGES/9326.feature
pulpcore/app/viewsets/reclaim.py
pulpcore/app/viewsets/repository.py

Shared resources

---

CHANGES/plugin_api/9340.removal
pulpcore/app/serializers/acs.py
pulpcore/tests/functional/api/using_plugin/test_acs.py

Remove ACS path validation

---

CHANGES/plugin_api/8748.feature
pulpcore/app/models/content.py
pulpcore/plugin/stages/__init__.py
pulpcore/plugin/stages/artifact_stages.py
pulpcore/plugin/stages/declarative_version.py

New optional stage for ACS. 
Be aware that this PR is on top commit used in https://github.com/pulp/pulpcore/pull/1437. Before merge please rebase and drop commit with ACS models.

Acs artifact stage

---

CHANGES/8749.feature
pulpcore/content/handler.py

Add support for ACSes in the content app

---

CHANGES/9375.feature
CHANGES/plugin_api/9375.feature
pulpcore/app/models/acs.py
pulpcore/app/serializers/acs.py

Add remote type validation to the ACS.

---

pulpcore/tests/functional/api/using_plugin/test_acs.py

Fixed ACS paths update test.

---

CHANGES/9353.misc
pulpcore/tasking/entrypoint.py

Re-enable DJANGO_ASYNC_UNSAFE

---

CHANGES/9409.bugfix
pulpcore/app/models/content.py

fixes #9409
~This is a suggestion. It would need a ticket if this is desired.~

Use fields attname for natural key calculations

---

CHANGES/plugin_api/9163.removal
pulpcore/app/apps.py

Removed drf-access-policy workaround for condition/condition_expession.

---

CHANGES/9266.bugfix
pulpcore/app/tasks/repository.py
pulpcore/plugin/actions.py

Do bulk_touch instead of touching one by one

---

CHANGES/9432.misc
pulpcore/plugin/stages/artifact_stages.py

closes: #9432
https://pulp.plan.io/issues/9432

Fix a coroutine that wasn't awaited

---

CHANGES.rst

Fix a formatting typo in the changelog

---

CHANGES/9443.misc
pulpcore/app/urls.py

closes: #9443
https://pulp.plan.io/issues/9443

Use new-style urlpatterns

---

CHANGES/9436.doc
docs/installation/instructions.rst

Correct a fact about Redis in the software stack

---

pulpcore/content/handler.py

Fix bad docstring in the content app

---

CHANGES.rst

3.14.7 changelog

---

CHANGES/9251.doc
docs/workflows/alternate-content-sources.rst

Update ACS docs to use CLI commands

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/scripts/install.sh
pulpcore/tests/functional/api/using_plugin/test_distributions.py
template_config.yml

Enable azure tests

---

CHANGES/9301.bugfix
pulpcore/download/base.py
pulpcore/download/http.py
pulpcore/exceptions/__init__.py
pulpcore/exceptions/base.py

Improved messaging around timeout requests.

---

CHANGES/9353.misc
pulpcore/app/tasks/repository.py
pulpcore/tasking/entrypoint.py

closes: #9353
https://pulp.plan.io/issues/9353

Disable DJANGO_ALLOW_ASYNC_UNSAFE for tasking system

---

CHANGES/9434.bugfix
pulpcore/app/serializers/publication.py

Fixed DistibutorSerializer validation for repository/repo_version/publication.

---

CHANGES/9518.feature
CHANGES/plugin_api/9518.feature
pulpcore/content/handler.py
setup.py

Send headers when creating redirect url for Azure

---

pulpcore/tests/functional/api/using_plugin/test_distributions.py

Stop skipping azure tests

---

CHANGES/9527.doc
docs/installation/hardware-requirements.rst

Fix the path to uploaded artifacts

---

CHANGES/9550.bugfix
pulpcore/app/tasks/upload.py

fixes: #9550
https://pulp.plan.io/issues/9550

Assembles chunked_uploads in workers working directory

---

CHANGES/plugin_api/9554.feature
pulpcore/app/models/repository.py
pulpcore/content/handler.py

Add request parameter to Remote.get_remote_artifact_url

---

CHANGES.rst
docs/configuration/settings.rst
docs/contributing/platform-api/app/index.rst
docs/contributing/platform-api/tasking.rst
docs/installation/index.rst

Fixes some docs formatting issues discovered with Sphinx 4.3.0

---

CHANGES/plugin_api/9579.feature
pulpcore/app/models/repository.py

closes #9579
https://pulp.plan.io/issues/9579

Add initialize_new_version function to Repository model

---

CHANGES/9573.bugfix
doc_requirements.txt
docs/Makefile
functest_requirements.txt
pulpcore/download/factory.py
pulpcore/download/http.py

fixes #9573
Should i create cherry-picks to the branches 3.8, 3.9 and 3.10 too?

Fix leaking proxy credentials

---

CHANGES.rst

Adds 3.7.9 changelog

---

pulpcore/tests/unit/models/test_content.py

SimpleTestCase does not allow database access.
[noissue]
(cherry picked from commit 342587a8732085108a74d38a5aa7b302e8f6d36d)

Fix unittests

---

CHANGES.rst

Adds 3.15.3 changelog

---

CHANGES/9496.bugfix
pulpcore/app/viewsets/base.py

Fix erroneous order fields for `StableOrderingFilter` backend

---

CHANGES.rst

Adds 3.16.1 changelog

---

doc_requirements.txt

Pin the version for mistune

---

pulpcore/tests/functional/api/using_plugin/test_distributions.py
pulpcore/tests/functional/api/using_plugin/utils.py

Improves reliability of the db restart test for content app

---

CHANGES/plugin_api/9615.feature
pulpcore/app/models/content.py

Add async sign method to `SigningService`

---

CHANGES/9606.feature
pulpcore/app/viewsets/access_policy.py

Add endpoint to reset an access policy

---

pulpcore/app/models/repository.py
pulpcore/app/serializers/repository.py

Clarify the rate_limit option.

---

CHANGES/8610.bugfix
pulpcore/app/tasks/importer.py

Taught import-task to extract into current-working-dir.

---

pulpcore/app/models/base.py
pulpcore/app/models/generic.py
pulpcore/app/models/role.py
pulpcore/app/serializers/user.py

Allow proxy models in GenericForeignKey fields

---

CHANGES/plugin_api/9621.feature
docs/plugins/reference/metadata-signing.rst
pulpcore/app/models/content.py

Pass environment variables to the signing script.

---

pulpcore/app/viewsets/user.py

Fix erroneous permission in group access policy

---

CHANGES/plugin_api/9637.bugfix
pulpcore/app/global_access_conditions.py

closes #9637
https://pulp.plan.io/issues/9637

Use a plugin provided serializer in the has_remote_*_perms

---

CHANGES/9642.bugfix

Adds changelog for migration 81 bugfix

---

CHANGES/9634.bugfix
pulpcore/app/importexport.py
pulpcore/app/tasks/upload.py

Fixed "Too many open files" error during upload.

---

CHANGES/8798.bugfix
CHANGES/9481.bugfix
pulpcore/app/models/repository.py
pulpcore/tests/functional/api/using_plugin/test_repo_versions.py

Fix repository version listing after version deletion

---

CHANGES/plugin_api/9665.bugfix
pulpcore/plugin/apps.py

Export adjust_roles in the plugin api

---

CHANGES/9667.misc
pulpcore/download/http.py

closes: #9667
https://pulp.plan.io/issues/9667

Retry downloads on checksum mismatch

---

CHANGES.rst

Fix sphinx links

---

pulpcore/tests/functional/api/using_plugin/test_crud_repos.py
pyproject.toml

Mark a few tests as parallel

---

docs/authentication/basic.rst
docs/bugs-features.rst

Fix broken docs

---

CHANGES.rst

Clean changelog from duplicated numbers

---

pulpcore/app/views/orphans.py

Stop logging calls against deprecated HTTP endpoints

---

pulpcore/app/models/repository.py

Eliminate a couple of unnecessary delete queries

---

.ci/ansible/smash-config.json
.ci/scripts/validate_commit_message.py
doc_requirements.txt
template_config.yml

Update 3.16 CI

---

CHANGES/plugin_api/2123.removal
pulpcore/download/base.py

Deprecate custom_file_object in BaseDownloader

---

pyproject.toml

Updates the issue link template.

---

pulpcore/app/management/commands/handle-artifact-checksums.py
pulpcore/app/serializers/exporter.py
pulpcore/app/tasks/importer.py

Make black 22.1 happy

---

CHANGES/plugin_api/2185.bugfix
pulpcore/app/models/__init__.py
pulpcore/plugin/models/role.py

fixes: [pulp#2185](https://github.com/pulp/pulpcore/issues/2185)

Fixes circular import for plugins with custom user model

---

CHANGES/2173.misc
pulpcore/tests/functional/api/using_plugin/test_proxy.py
pulpcore/tests/functional/api/using_plugin/test_sync.py

Adds various proxy.py tests

---

.gitignore
docs/Makefile
docs/conf.py

Make docs easier to run locally

---

CHANGES/2200.feature
pulpcore/app/management/commands/analyze-publication.py

Add a management command for viewing publication contents

---

CHANGES/2148.feature
docs/configuration/settings.rst
pulpcore/app/settings.py
pulpcore/app/templatetags/pulp_urls.py
pulpcore/app/urls.py
pulpcore/constants.py
pulpcore/openapi/__init__.py

Use the new API_ROOT setting to reroot Pulp.
closes #2148

Adds API_ROOT setting to allow API rerooting

---

CHANGES/2229.bugfix
pulpcore/app/models/content.py

Teach touch() to use std Django and remove raw-sql exec.

---

CHANGES/2229.bugfix
pulpcore/app/models/content.py

fixes #2229.
[nocoverage]
(cherry picked from commit e4666b5fc3dab72b66a871aa5105aabe8fa8113d)

[3.14] Teach touch() top use std Django and remove raw-sql exec.

---

pulpcore/app/settings.py

Allow API_ROOT to be a read setting

---

docs/Makefile

Adds `PULP_API_ROOT` support to `make html`

---

CHANGES/2187.bugfix
pulpcore/content/handler.py

Return a concise message exception on 500 in case file is missing on the FS.

---

CHANGES/1945.feature
docs/workflows/index.rst
docs/workflows/plugin-removal.rst
pulpcore/app/apps.py
pulpcore/app/management/commands/remove-plugin.py
pulpcore/tests/conftest_pulp_file.py
pulpcore/tests/functional/api/using_plugin/test_remove_plugin.py

closes #1945
Overall approach and related notes are in this doc https://hackmd.io/cKZ-MwkdSUiFKJo0W5zQ_A.

Add a remove-plugin command

---

docs/Makefile

Update docs makefile

---

.github/workflows/changelog.yml

Fix update changelog job

---

CHANGES/plugin_api/2262.feature
pulpcore/plugin/authentication/__init__.py

Expose PulpRemoteUserAuthentication to plugin writers

---

CHANGES/2084.bugfix
CHANGES/2085.bugfix
CHANGES/2268.bugfix
pulpcore/app/models/repository.py
pulpcore/tests/functional/api/using_plugin/test_repo_versions.py

fixes #2268
(cherry picked from commit d2e86334041c553e5fea45a315a7a16cb0a61bd7)
Made on behalf of patchback.

Harden operations around repository versions

---

CHANGES.rst

Cherrypick changelogs for releases

---

.github/workflows/scripts/before_install.sh

Pin pulp-smash to a specific commit

---

CHANGES.rst

Cherrypick 3.14.13 changelog

---

CHANGES/2101.bugfix
pulpcore/app/migrations/0064_add_new_style_task_columns.py

Fix new-task-system migration to clean up task and taskreservedresource.

---

pulpcore/app/models/repository.py
pulpcore/tests/conftest_pulp_file.py

[noissue]
Don't really know where to put these...

Small improvement

---

CHANGES/2330.bugfix
pulpcore/app/viewsets/repository.py

[noissue]
This also fixes the bindings asking for the wrong arguement.

Correctly expose the serializer for RepositoryVersion repair

---

docs/plugins/reference/index.rst
docs/plugins/reference/task-scheduling.rst
pulpcore/tasking/pulpcore_worker.py
pulpcore/tests/functional/api/test_workers.py

Add comments and docs to task schedules

---

CHANGES/2329.doc
CHANGES/2329.feature
docs/configuration/settings.rst
docs/plugins/plugin-writer/concepts/index.rst
docs/plugins/plugin-writer/concepts/tasks/diagnostics.rst
pulpcore/app/settings.py
pulpcore/constants.py
pulpcore/tasking/pulpcore_worker.py

Adds TASK_DIAGNOSTIC setting and docs

---

CHANGES/2069.bugfix
CHANGES/plugin_api/2069.bugfix
pulpcore/plugin/stages/api.py

Revert "[PR #2338/eefe634d backport][3.16] Reduces queue size between stages from 1000 to 1"

---

CHANGES/2069.bugfix
CHANGES/plugin_api/2069.bugfix
pulpcore/plugin/stages/api.py

Revert "[PR #2338/eefe634d backport][3.18] Reduces queue size between stages from 1000 to 1"

---

CHANGES/2069.bugfix
CHANGES/plugin_api/2069.bugfix
pulpcore/plugin/stages/api.py

Revert "[PR #2338/eefe634d backport][3.17] Reduces queue size between stages from 1000 to 1"

---

.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/scripts/publish_docs.sh
.github/workflows/scripts/script.sh
.github/workflows/scripts/stage-changelog-for-default-branch.py

Publish bindings docs

---

.github/workflows/release.yml

Fix 3.15 install

---

CHANGES/2381.bugfix
pulpcore/plugin/stages/artifact_stages.py

Fixes RemoteArtifact duplicate key error

---

CHANGES/plugin_api/2364.feature
pulpcore/app/global_access_conditions.py

Add more global access conditions

---

CHANGES/2065.feature
pulpcore/app/serializers/reclaim.py
pulpcore/tests/functional/api/using_plugin/test_reclaim_disk_space.py

Allow specifying all repos for reclaim

---

CHANGES/2379.feature
pulpcore/app/viewsets/__init__.py
pulpcore/app/viewsets/publication.py
pulpcore/tests/functional/api/using_plugin/test_distributions.py

Add a generic distribution list endpoint

---

CHANGES/2260.doc
docs/authentication/basic.rst
docs/authentication/overview.rst
docs/authentication/webserver.rst

Update the auth docs

---

doc_requirements.txt

Temporarily pin jinja for building docs

---

CHANGES/2059.feature
pulpcore/content/handler.py

Log streaming in content app

---

pulpcore/app/serializers/orphans.py

Fix the note about a default value

---

.ci/scripts/update_ci_branches.py
.github/workflows/update_ci.yml
template_config.yml

Ref: https://github.com/pulp/plugin_template/pull/608

Update CI branches starting from 3.14

---

CHANGES/2506.bugfix
pulpcore/tasking/pulpcore_worker.py

Fix a bug where workers miss notifications

---

CHANGES/2269.bugfix
docs/workflows/import-export.rst
pulpcore/app/tasks/importer.py
pulpcore/tests/unit/test_import_checks.py

Loosened import version-restriction to x.y instead of x.y.z.

---

CHANGES/2506.bugfix
pulpcore/tasking/pulpcore_worker.py

fixes #2506
(cherry picked from commit 4cdba449ad8cb7b3ab1a2e0f59f90be830554302)

[3.14] Fix a bug where workers miss notifications

---

.ci/scripts/update_ci_branches.py
.ci/scripts/upper_bound.py
.github/workflows/release.yml
.github/workflows/scripts/script.sh
.github/workflows/scripts/update_ci.sh
.github/workflows/update_ci.yml

Update 3.19 CI

---

.ci/scripts/upper_bound.py
.github/workflows/release.yml
.github/workflows/scripts/script.sh
.github/workflows/scripts/update_ci.sh
.github/workflows/update_ci.yml

Update 3.17 CI

---

.ci/scripts/upper_bound.py
.github/workflows/release.yml
.github/workflows/scripts/script.sh
.github/workflows/scripts/update_ci.sh
.github/workflows/update_ci.yml

Update 3.18 CI

---

pulpcore/content/handler.py

this is a follow-up from https://github.com/pulp/pulpcore/pull/2515 which has an issue already

Improved reason error message for PathNotResolved.

---

CHANGES/2559.removal
pulpcore/app/access_policy.py
pulpcore/app/apps.py

Remove interface for unregistered creation_hooks

---

CHANGES/2050.removal
pulpcore/app/serializers/__init__.py
pulpcore/app/serializers/user.py
pulpcore/app/viewsets/__init__.py
pulpcore/app/viewsets/user.py

Remove group permission viewsets

---

CHANGES/2573.bugfix
pulpcore/app/files.py

Fix OOM error after uploading large chunked file

---

pulpcore/download/http.py

Ensure download retry fix occurs for all http subclasses

---

pulpcore/tests/functional/__init__.py

Add a fixture for signing services

---

CHANGES/2477.bugfix
CHANGES/plugin_api/2477.doc
docs/plugins/plugin-writer/concepts/index.rst
pulpcore/app/apps.py
pulpcore/app/management/commands/add-signing-service.py
pulpcore/app/management/commands/analyze-publication.py
pulpcore/app/management/commands/datarepair-2327.py
pulpcore/app/management/commands/handle-artifact-checksums.py
pulpcore/app/management/commands/remove-plugin.py
pulpcore/app/management/commands/reset-admin-password.py
pulpcore/app/management/commands/stage-profile-summary.py
pulpcore/app/migrations/0061_call_handle_artifact_checksums_command.py
pulpcore/app/models/repository.py
pulpcore/app/models/task.py
pulpcore/app/settings.py
pulpcore/app/tasks/export.py
pulpcore/app/tasks/importer.py
pulpcore/app/tasks/repository.py
pulpcore/app/viewsets/base.py
pulpcore/content/__init__.py
pulpcore/content/handler.py
pulpcore/plugin/stages/api.py
pulpcore/plugin/stages/artifact_stages.py
pulpcore/tasking/pulpcore_worker.py
pulpcore/tasking/tasks.py
pulpcore/tasking/util.py

il8n should only be for using facing strings. This updates the code as
best as I could tell the difference, and also documents that expectation
for plugin writers.
closes #2477

Removes il8n from log messages and adds docs

---

CHANGES/2642.doc
docs/bugs-features.rst
docs/conf.py
docs/contributing/git.rst
docs/contributing/pull-request-walkthrough.rst
docs/index.rst
docs/installation/instructions.rst

Remove a lot of old Redmine stuff from docs

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/scripts/install.sh
CHANGES/plugin_api/2537.feature
pulpcore/plugin/content.py
template_config.yml

Also export ArtifactResonse in the plugin api.

Test stream

---

CHANGES/2589.bugfix
pulpcore/app/tasks/importer.py

Taught pulp-import to retry up to three times on collisions.

---

CHANGES/1944.doc
docs/configuration/settings.rst
docs/configuration/viewing.rst
docs/index.rst
docs/troubleshooting.rst

Adds docs on how to enable DEBUG logging

---

CHANGES/2605.misc
requirements.txt

Add an uppper bound to all requirements

---

pulpcore/tests/functional/__init__.py

Add anonymous_user to the pulpcore fixtures.

---

requirements.txt

[3.18] Add an upper bound to all requirements

---

docs/plugins/plugin-writer/concepts/index.rst
docs/plugins/plugin-writer/concepts/tasks/export.rst

Remove redundant section

---

requirements.txt

[noissue]
(cherry picked from commit 157842021ea51613f052276caaef26ecabf60bda)

[3.14] Add an upper bound to all requirements

---

requirements.txt

[noissue]
(cherry picked from commit 157842021ea51613f052276caaef26ecabf60bda)

[3.15] Add an upper bound to all requirements

---

requirements.txt

[noissue]
(cherry picked from commit 157842021ea51613f052276caaef26ecabf60bda)

[3.16] Add an upper bound to all requirements

---

requirements.txt

[noissue]
(cherry picked from commit 157842021ea51613f052276caaef26ecabf60bda)

[3.17] Add an upper bound to all requirements

---

pulpcore/tests/functional/__init__.py

Adds a content guard generic api fixture

---

CHANGES/2075.bugfix
pulpcore/content/handler.py

Fix S3 URL

---

requirements.txt

Set an upper bound for setuptools in requirements.txt

---

CHANGES/1852.doc
docs/contributing/pull-request-walkthrough.rst
docs/contributing/tests.rst

Adds docs cleaning up the PR walkthrough

---

pulpcore/tests/functional/__init__.py

Add a fixture for artifacts

---

CHANGES/2724.feature
CHANGES/plugin_api/2724.feature
pulpcore/app/apps.py
pulpcore/app/models/content.py
pulpcore/app/viewsets/content.py

fixes: #2724
Required PR: https://github.com/pulp/pulp_file/pull/703

Add Content queryset scoping implementation

---

CHANGES/2703.bugfix
CHANGES/2765.feature
pulpcore/app/serializers/user.py
pulpcore/app/viewsets/user.py

fixes #2703
fixes #2765
cc @himdel @jerabekjiri

Usability improvements on user and group roles API

---

pulpcore/tests/functional/__init__.py

Add several api fixtures to pytest plugin

---

CHANGES/2758.doc
pulpcore/app/serializers/user.py

Add a note about assigning model-level permissions

---

CHANGES/2798.bugfix
pulpcore/app/models/content.py
pulpcore/app/util.py

Create validation data inside the Pulp's working directory

---

docs/workflows/signed-metadata.rst

Clarify that env vars in the signing script cannot be changed.

---

pulpcore/tests/functional/__init__.py

`random_artifact` fixture for pulpcore

---

CHANGES/plugin_api/2796.feature
docs/plugins/plugin-writer/concepts/rbac/queryset_scoping.rst
pulpcore/app/global_access_conditions.py

Add new access condition for content uploads

---

CHANGES/2817.bugfix
pulpcore/app/tasks/export.py

Raise runtime errors

---

CHANGES/2810.bugfix
pulpcore/app/serializers/orphans.py
pulpcore/app/viewsets/orphans.py

Clear up docs about orphan protection time default

---

CHANGES/plugin_api/2052.feature
pulpcore/plugin/actions.py

Expose a method for verifying existing content units

---

pulpcore/app/serializers/repository.py
pulpcore/download/base.py
pulpcore/download/file.py
pulpcore/download/http.py

This reverts commit 207eb3cd486b85357e7709b6b64ad27d1823e7b4.
[noissue]

Revert "Cleanups"

---

CHANGES/2802.bugfix
pulpcore/app/access_policy.py
pulpcore/app/viewsets/base.py

fixes: #2802
Also fixed the comments on some of the methods of NamedModelViewSet.

Reduce queries for AccessPolicy

---

CHANGES/2816.misc
pulpcore/content/__init__.py
pulpcore/content/handler.py

closes #2816
(cherry picked from commit 1a8c7c53031f80a1d571f99add06651233e0b8fb)
(cherry picked from commit d492eacbe0225849282eaa0a05adaa5a93176d02)

Fix a misuse of async code resulting in a database connection leak

---

pulpcore/plugin/actions.py

Fixed import for ``raise_for_unknown_content_units``.

---

docs/workflows/alternate-content-sources.rst

Add more details to the description of ACS

---

pulpcore/app/global_access_conditions.py

Provide a more user friendly error.

---

CHANGES/2340.bugfix
pulpcore/app/urls.py
pulpcore/tests/functional/__init__.py
pulpcore/tests/functional/api/test_root_endpoint.py
pulpcore/tests/functional/utils.py

Define a custom API root endpoint class

---

pulpcore/app/tasks/repository.py

Fixes incorrect typo in docstring

---

pulpcore/tests/functional/__init__.py
pulpcore/tests/functional/gpg_ascii_armor_signing_service.py

Rename the fixture to better describe its meaning

---

CHANGES/2964.bugfix
pulpcore/download/factory.py
pulpcore/download/http.py

Configure aiohttp to not rewrite redirect URLs

---

CHANGES/plugin_api/2981.doc
docs/plugins/plugin-writer/concepts/index.rst

Adds plugin writer docs on Master/Detail pattern

---

CHANGES/2977.bugfix
pulpcore/content/handler.py

Fix inaccurate 404 error message for content app

---

CHANGES/3019.dev
dev_requirements.txt
pulpcore/app/serializers/exporter.py
pulpcore/app/tasks/importer.py
pulpcore/openapi/__init__.py

by limiting django-extensions to versions <3.2.0.
fixes: #3019

Fix installing dev_requirements.txt breaking pulpcore

---

CHANGES/2864.feature
pulpcore/app/viewsets/custom_filters.py
pulpcore/app/viewsets/repository.py

Add Remote filter for Repositories

---

CHANGES/3063.misc
pulpcore/app/tasks/base.py

Remove unnecessary db lookup in general_create

---

CHANGES/3075.bugfix
pulpcore/app/tasks/importer.py

Yield the result immediately once the import succeeds

---

CHANGES/plugin_api/3085.doc
docs/plugins/plugin-writer/concepts/rbac/access_policy.rst
docs/plugins/plugin-writer/concepts/rbac/overview.rst

Add plugin writer docs for RolesMixin

---

CHANGES/3051.doc
docs/configuration/applying.rst
docs/installation/hardware-requirements.rst
docs/installation/instructions.rst

Multiple updates to the PyPI (manual) install instructions.

---

pulpcore/app/management/commands/dump-publications-to-fs.py
pulpcore/app/tasks/export.py

Simple way to dump a publication straight to disk.  At the very least it would simplify debugging.
[noissue]

Publication filesystem export management command

---

CHANGES/3064.bugfix
pulpcore/app/tasks/importer.py

When importing add only content to repository

---

CHANGES/3113.bugfix
pulpcore/app/tasks/importer.py

Fix the counter for imported content units

---

CHANGES/2445.misc
docs/plugins/api-reference/profiling.rst
pulpcore/plugin/stages/api.py
pulpcore/plugin/stages/profiler.py

Asynchronously wait for results while profiling the pipeline

---

CHANGES/3122.bugfix
pulpcore/app/apps.py
pulpcore/app/util.py
pulpcore/tasking/pulpcore_worker.py

Move telemetry setup to pulpcore-worker startup

---

CHANGES/3080.bugfix
pulpcore/app/apps.py
pulpcore/app/migrations/0050_namespace_access_policies.py
pulpcore/app/viewsets/access_policy.py

Limit access policy ops to routable viewsets

---

CHANGES/plugin_api/3157.feature
pulpcore/plugin/models/__init__.py

Export EncryptedTextField in the plugin api

---

pulpcore/tests/functional/__init__.py

Add generic list apis to test fixtures

---

docs/troubleshooting.rst

Update docs on debug logging

---

CHANGES/3138.feature
pulpcore/app/serializers/status.py
pulpcore/app/views/status.py
pulpcore/tests/functional/api/test_status.py

Added a content_settings stanza to the /status/ output.

---

pulpcore/tests/functional/__init__.py

Add fixtures for filesystemexport API clients and cleanup

---

CHANGES/3238.feature
pulpcore/app/models/publication.py
pulpcore/tests/unit/test_content_guard.py

Add expiry time to preauthed urls

---

CHANGES/3124.bugfix
CHANGES/3244.bugfix
pulpcore/app/util.py
pulpcore/content/handler.py
pulpcore/tests/functional/api/test_artifact_distribution.py

Fixed content-disposition header for the object storage backend.

---

CHANGES/3204.doc
docs/index.rst
docs/plugins/reference/releasing.rst
docs/release_process.rst

Documented Pulpcore and Plugin release processes.

---

pulpcore/tests/functional/__init__.py

Add a fixture for ImportersPulpImportCheckApi clients

---

CHANGES/3263.bugfix
pulpcore/app/tasks/purge.py

Perform the slice operation inside a loop when purging tasks

---

pulpcore/tests/functional/__init__.py

Add a fixture for RepositoriesReclaimSpaceApi and download_content

---

pulpcore/tests/functional/__init__.py

Add a pytest fixture for RepairApi

---

CHANGES/3266.bugfix
CHANGES/plugin_api/3266.bugfix
docs/contributing/architecture/rest-api.rst
pulpcore/app/settings.py
pulpcore/app/viewsets/__init__.py
pulpcore/app/viewsets/access_policy.py
pulpcore/app/viewsets/acs.py
pulpcore/app/viewsets/base.py
pulpcore/app/viewsets/content.py
pulpcore/app/viewsets/exporter.py
pulpcore/app/viewsets/importer.py
pulpcore/app/viewsets/publication.py
pulpcore/app/viewsets/repository.py
pulpcore/app/viewsets/task.py
pulpcore/app/viewsets/user.py
pulpcore/filters.py
pulpcore/plugin/viewsets/__init__.py

Add ordering filter to NamedModelViewSet

---

pulpcore/tests/functional/__init__.py
pulpcore/tests/functional/api/test_api_docs.py
pulpcore/tests/functional/api/test_auth.py
pulpcore/tests/functional/api/test_crd_artifacts.py
pulpcore/tests/functional/api/test_status.py
pulpcore/tests/functional/api/test_upload.py
pulpcore/tests/functional/api/test_workers.py
pulpcore/tests/functional/utils.py

Convert tests to use bindings & pytest style

---

CHANGES/3280.feature
pulpcore/app/viewsets/custom_filters.py
pulpcore/app/viewsets/task.py

These new filters search for both shared and exclusive resources.
fixes #3280

Added reserved_resources filters to task list

---

CHANGES/3313.bugfix
pulpcore/app/tasks/export.py

Fix the number of parameters passed to UnexportableArtifactException

---

CHANGES/3299.bugfix
pulpcore/app/models/repository.py

Remove query from repository version content summary

---

CHANGES/3323.bugfix
pulpcore/app/tasks/importer.py

Co-authored-by: Grant Gainey <ggainey@redhat.com>
fixes #3323
[nocoverage]

Adding tarfile member sanitization to extractall().

---

CHANGES/3342.bugfix
pulpcore/content/handler.py

Fixed the content disposition header for content served from Azure 

---

pulpcore/app/models/task.py

Due to not being deferred properly, some times finished_at was not being reloaded.
[noissue]
re #3319

Fixup the fix for #3319

---

pulpcore/tests/functional/__init__.py

Add Generic RepositoryVersions API fixture

---

CHANGES/plugin_api/3340.feature
pulpcore/plugin/responses.py

Add ArtifactResponse to plugin api

---

CHANGES/3235.bugfix
pulpcore/app/viewsets/custom_filters.py
pulpcore/app/viewsets/task.py
pulpcore/tests/functional/api/test_tasking.py

Closes #3235
Co-authored-by: dkliban <dkliban@redhat.com>

Fixes the worker__in filter for the Tasks API

---

CHANGES/3398.bugfix
pulpcore/openapi/__init__.py

Fix fields and exclude_fields openapi definition

---

CHANGES/3391.bugfix
pulpcore/app/apps.py

Fix updating access policies when keys are missing

---

CHANGES/3333.misc
pulpcore/tests/functional/__init__.py
pulpcore/tests/functional/api/test_access_policy.py

Refactor test_access_policy

---

pulpcore/tests/functional/__init__.py

Delete orphans immediately

---

CHANGES/3351.bugfix
pulpcore/app/viewsets/__init__.py
pulpcore/app/viewsets/access_policy.py
pulpcore/app/viewsets/acs.py
pulpcore/app/viewsets/base.py
pulpcore/app/viewsets/custom_filters.py
pulpcore/app/viewsets/exporter.py
pulpcore/app/viewsets/importer.py
pulpcore/app/viewsets/publication.py
pulpcore/app/viewsets/repository.py
pulpcore/app/viewsets/task.py
pulpcore/app/viewsets/upload.py
pulpcore/app/viewsets/user.py
pulpcore/filters.py
pulpcore/plugin/viewsets/__init__.py

This fixes the apischema generation for the HyperlinkRelatedFilter.
fixes #3351

Rework filter defaults

---

CHANGES/3334.misc
pulpcore/tests/functional/api/test_users_groups.py

Rewrite test_users_groups to pytest style

---

CHANGES/2054.feature
pulpcore/content/handler.py

The dates represent the date that the content was created in Pulp.
closes: #2054

Adds dates to the distribution listing pages

---

CHANGES/3430.doc
docs/installation/instructions.rst

Remove the ansible collection from the recommendation

---

CHANGES/3436.bugfix
pulpcore/content/handler.py

Fixes the broken link on the root page of pulpcore-content.

---

CHANGES/3173.feature
pulpcore/content/handler.py

Revert the changes for trailing slash redirects and published artifacts orders

---

CHANGES/3400.bugfix
pulpcore/app/management/commands/datarepair-labels.py
pulpcore/app/migrations/0098_pulp_labels.py

Added a repair command and fixed the dependency issue.
[noissue]

Fixup pulp_label migration

---

.github/workflows/scripts/before_script.sh
CHANGES/3424.feature
pulpcore/app/settings.py
pulpcore/app/util.py
pulpcore/content/handler.py
pulpcore/tests/functional/api/test_artifact_distribution.py
setup.py

closes #3424
I've filed https://github.com/pulp/pulpcore/issues/3483
for adding docs

Add GCP support

---

CHANGES/3446.misc
pulpcore/app/models/importer.py
pulpcore/app/serializers/importer.py
pulpcore/app/viewsets/user.py
pulpcore/tests/functional/api/test_users_groups.py

Import-path will be tested in pulp_file.
fixes #3446

Fixed some error-log paths that potentially expose data.

---

CHANGES/3394.feature
pulpcore/app/viewsets/publication.py

Adds a repository exact and in filters to the Distributions API.

---

functest_requirements.txt
pulpcore/tests/functional/__init__.py
pulpcore/tests/functional/utils.py

Migrate Webserver, Proxy, TLS, and SSL fixtures off pulp-smash

---

.github/workflows/scripts/install.sh
pulpcore/tests/functional/__init__.py
pulpcore/tests/functional/api/test_artifact_distribution.py
pulpcore/tests/functional/api/test_openapi_schema.py
pulpcore/tests/functional/api/test_status.py
pulpcore/tests/functional/api/test_workers.py

Ref: https://github.com/pulp/pulp_installer/pull/1450
Ref: https://github.com/pulp/oci_env/pull/82
[noissue]

Use pytest fixtures instead of the pulp-smash config

---

CHANGES/3522.feature
docs/plugin_dev/reference/metadata-signing.rst
docs/workflows/signed-metadata.rst
pulpcore/app/models/content.py

Pass correlation id to signing script through ENV variable

---

CHANGES/3505.doc
docs/installation/instructions.rst

Also warn about the incompatibility with db connection pooling.
fixes #3505

Document compatible PostgreSQL version

---

requirements.txt

Raise Django minimum version to 3.2.16

---

requirements.txt

Bumps minimum Django version to 3.2.16

---

CHANGES/3507.feature
pulpcore/app/viewsets/__init__.py
pulpcore/app/viewsets/base.py
pulpcore/app/viewsets/repository.py
pulpcore/plugin/viewsets/__init__.py

Add retain_repo_versions filter

---

CHANGES/plugin_api/3520.bugfix
pulpcore/plugin/serializers/__init__.py

Adds HiddenFieldsMixin to the plugin api.

---

pulpcore/app/apps.py
pulpcore/app/authentication.py
pulpcore/app/management/commands/datarepair-2327.py
pulpcore/app/management/commands/handle-artifact-checksums.py
pulpcore/app/serializers/orphans.py
pulpcore/app/serializers/progress.py
pulpcore/app/serializers/publication.py
pulpcore/app/tasks/importer.py
pulpcore/app/tasks/repository.py
pulpcore/content/__init__.py
pulpcore/tests/functional/api/test_role.py
pulpcore/tests/functional/api/test_tasking.py
pulpcore/tests/unit/models/test_content.py

Update to match changes to black-formatting for 23.1.0.

---

CHANGES/3541.misc
pulpcore/plugin/stages/artifact_stages.py

[noissue]
If there are ACS that point to the same content, pick the first RA instead of last
Issue TBD

Pick the first occurence of RA in the ACSHandleStage.

---

CHANGES/3407.bugfix
pulpcore/app/tasks/test.py
pulpcore/tasking/pulpcore_worker.py
pulpcore/tests/functional/api/test_tasking.py
pulpcore/tests/functional/utils.py

Repeat to kill the process of a canceled task

---

CHANGES/3514.doc
docs/release_process.rst

Updated release-process documentation.

---

.github/workflows/scripts/release.py

Fix release-script for 3.14.

---

CHANGES/3404.bugfix
pulpcore/app/tasks/reclaim_space.py

Fixes a possible N+1 issue within reclaim_space task

---

CHANGES/3569.misc
doc_requirements.txt

Fixes docs search by pinning sphinx-rtd-theme

---

CHANGES/3574.misc
pulpcore/app/redis_connection.py
pulpcore/cache/cache.py
requirements.txt

closes #3574
https://github.com/pulp/pulpcore/issues/3574

Replace aioredis with redis-py

---

pulpcore/tests/functional/__init__.py

Add an aiohttp replacement for the http_get function

---

CHANGES/plugin_api/3570.bugfix
pulpcore/plugin/viewsets/__init__.py

Add LabelFilter to plugin api

---

CHANGES/3326.bugfix
pulpcore/app/serializers/repository.py
pulpcore/app/util.py
pulpcore/app/viewsets/base.py
pulpcore/plugin/actions.py

Add a child validator to the /repository/modify serializer

---

CHANGES/plugin_api/3604.feature
pulpcore/plugin/util.py

Expose extract_pk and raise_for_unknown_content_units

---

CHANGES/plugin_api/3604.deprecation

Deprecate extract_pk and raise_for_unknown_content_units

---

pulpcore/app/viewsets/base.py
pulpcore/plugin/actions.py

ref: https://github.com/pulp/pulpcore/commit/b2d65635a250be49fc8893dbd66bf338f09ec6fa
ref: https://github.com/pulp/pulpcore/commit/89a8fe3b6537ffe6b316c38aeb3dd3d9502af362
[noissue]

Fix the path of moved functions

---

pulpcore/tests/functional/__init__.py

Add fixtures to allow version dependent tests

---

CHANGES/3429.doc
docs/configuration/settings.rst
docs/plugin_dev/reference/metadata-signing.rst
docs/plugin_dev/reference/task-scheduling.rst
docs/workflows/alternate-content-sources.rst
docs/workflows/import-export.rst
docs/workflows/labels.rst
docs/workflows/plugin-removal.rst
docs/workflows/reclaim-disk-space.rst
docs/workflows/repairing-pulp.rst
docs/workflows/repo-versioning.rst
docs/workflows/signed-metadata.rst
pulpcore/app/management/commands/add-signing-service.py
pulpcore/app/management/commands/handle-artifact-checksums.py
pulpcore/app/management/commands/remove-plugin.py
pulpcore/app/management/commands/remove-signing-service.py
pulpcore/app/models/publication.py
pulpcore/app/serializers/repository.py
pulpcore/app/viewsets/exporter.py
pulpcore/app/viewsets/task.py
pulpcore/app/viewsets/user.py

Remove warnings for features that are no longer in tech preview

---

pulpcore/tests/functional/__init__.py

[noissue]
(cherry picked from commit 929faafdf750111f0eced3094349f660db7e8ded)

[3.21] Add an aiohttp replacement for the http_get function

---

CHANGES/3627.doc
docs/installation/instructions.rst

Adds links to Containerfiles used for building OCI images of Pulp.

---

CHANGES/plugin_api/1931.feature
pulpcore/plugin/stages/__init__.py
pulpcore/plugin/stages/artifact_stages.py

Refactor ArtifactDownloader stage to allow subclassing

---

CHANGES/3645.bugfix
pulpcore/app/views/repair.py

Raise exception in case of invalid data for the repair endpoint

---

CHANGES/3641.bugfix
pulpcore/app/viewsets/content.py

Return distinct content units from the queryset scope filtering

---

pulpcore/app/viewsets/repository.py

Raise an exception for invalid data for repository/repair/

---

.github/workflows/update_ci.yml
template_config.yml

Update CI for 3.23 release

---

CHANGES/3663.bugfix
pulpcore/app/modelresource.py
pulpcore/plugin/importexport.py

We can't export entities' domain-info.
fixes #3663.
[nocoverage]

Fixed import/export in the face of Domains.

---

CHANGES/3673.bugfix
pulpcore/content/handler.py

Escape special characters when constructing a regex

---

CHANGES/3667.doc
doc_requirements.txt
docs/conf.py

Fix the search bar bug

---

CHANGES/3653.bugfix
pulpcore/content/handler.py

Fix package timestamp on content app

---

.ci/ansible/Containerfile.j2

Experiment to fix release-workflow.

---

docs/contributing/git.rst

Document how to depend on another components PR

---

CHANGES/2975.feature
pulpcore/filters.py
pulpcore/tests/functional/api/test_filter.py

fixes: #2975
@daviddavis Would this work for you? These filters will be added to each endpoint.

Add `pulp_href__in` and `pulp_id__in` query filters

---

CHANGES/3715.bugfix
pulpcore/download/base.py

Attempt to keep the file extension intact when downloading files

---

CHANGES/3444.doc
docs/contributing/dev-setup.rst

Update contributor docs to point to oci-env

---

pulpcore/app/viewsets/repository.py
pulpcore/filters.py

Add special handling for RepositoryVersion pulp_href__in filter

---

CHANGES/3730.bugfix
pulpcore/app/settings.py
pulpcore/tests/functional/api/test_auth.py

Change the order of authentication classes

---

CHANGES/3656.feature
pulpcore/content/handler.py

Add file size to the content app directory

---

CHANGES/3408.feature
pulpcore/filters.py
pulpcore/tests/functional/api/test_filter.py

Add pulp_type filter for generic list endpoints

---

CHANGES/3023.bugfix
pulpcore/app/__init__.py
pulpcore/app/apps.py
pulpcore/app/settings.py
pulpcore/tests/unit/download/test_factory.py
pulpcore/tests/unit/viewsets/test_base.py

Fix some deprecation warnings

---

CHANGES/plugin_api/3614.removal
pulpcore/app/util.py
pulpcore/plugin/util.py

Remove verify_signature

---

template_config.yml

Add 3.24 to supported-ci-versions in template.

---

.github/workflows/scripts/install.sh
template_config.yml

[noissue]
Marking this a blocker for 3.25, because it is a huge piece of technical dept we already paid the interest rate for in the last release. I don't want to see us doing it again.

Run some tests with domains enabled

---

CHANGES/2993.misc
pulpcore/app/models/publication.py

Add a note about removing BaseDistribution

---

CHANGES/2865.feature
pulpcore/app/viewsets/repository.py
pulpcore/tests/functional/api/test_repos.py

Add content filters to repository endpoint

---

doc_requirements.txt

[noissue]
(cherry picked from commit c6cd331e153b2442b90e2aa9ec5eac04e24fffa3)

Pin sphinx to fix docs build

---

docs/authentication/other.rst
docs/authentication/overview.rst
docs/authentication/webserver.rst
docs/components.rst
docs/configuration/settings.rst
docs/installation/instructions.rst
docs/installation/storage.rst
docs/plugin_dev/plugin-writer/concepts/index.rst
docs/plugin_dev/plugin-writer/concepts/rbac/overview.rst
docs/plugin_dev/plugin-writer/concepts/rbac/permissions.rst
docs/plugin_dev/plugin-writer/concepts/subclassing/models.rst
docs/plugin_dev/reference/how-plugins-work.rst

Updated link references to django 4.2

---

CHANGES/3835.feature

Adds the CHANGEs entry for adding OpenTelemetry support to pulp-api.

---

.github/workflows/update_ci.yml
template_config.yml

Update update_ci branches for 3.26

---

CHANGES.rst

Remove a warning about adding RBAC to pulp

---

CHANGES.rst

Moved otel changelog snippet to proper release.
[noissue]

Fixup CHANGELOG

---

CHANGES/3786.bugfix
pulpcore/app/views/repair.py
pulpcore/app/viewsets/reclaim.py

Serialized global reclaim space, global repair artifacts tasks.

---

pulpcore/tests/functional/api/test_crud_domains.py

I noticed this in https://github.com/pulp/pulpcore/pull/3847, but the domain tests are done in parallel and this one test was sometimes selecting domains created in other tests that could be deleted before the test completes.

Fix race condition in parallel domains test

---

docs/installation/instructions.rst

Update supported Postgres version.

---

CHANGES/3867.doc
docs/components.rst

Add the documentation about OpenTelemetry support on pulp-api.

---

CHANGES/plugin_api/3876.bugfix
pulpcore/content/handler.py

Select the repository from a version when matching a distribution

---

CHANGES/3873.misc
CHANGES/plugin_api/3873.feature
pulpcore/app/models/base.py
pulpcore/app/models/repository.py
pulpcore/app/serializers/base.py
pulpcore/app/tasks/repository.py
pulpcore/app/util.py
pulpcore/content/handler.py
pulpcore/tests/unit/models/test_base.py

Refactor cast to do only one db call

---

CHANGES/3898.bugfix
pulpcore/app/models/base.py

Do not cast objects when initializing their string representation

---

.github/workflows/update_ci.yml
template_config.yml

Replace 3.26 -> 3.27 in ci branches

---

pulpcore/app/settings.py

Removed yet another reference to the installer.

---

.github/workflows/update_ci.yml
template_config.yml

Update CI for 3.28

---

CHANGES/3957.bugfix
pulpcore/app/models/role.py
pulpcore/app/role_util.py

https://github.com/pulp/pulp_container/pull/1294#issuecomment-1602282563

Defer get_user_model calls to prevent circular imports

---

CHANGES/3940.feature
pulpcore/tasking/pulpcore_worker.py

Add graceful shutdown to pulpcore-worker

---

template_config.yml

Update ci_update_branches to include 3.29

---

CHANGES/4042.bugfix
requirements.txt

Pin importlib-metadata to avoid an unsolvable dependency resolution by pip

---

CHANGES/4042.bugfix
requirements.txt

Fixes #4042
(cherry picked from commit bbb30b7a5de3cab3ac13e1913facb33f1292e2fe)

Pin importlib-metadata to 6.0.1

---

pulpcore/tests/functional/__init__.py

[noissue]
Required by: https://github.com/pulp/pulp_file/pull/990

Extract a function for recursive downloads from pulp-file tests

---

CHANGES/3923.misc
pulpcore/tests/functional/__init__.py

Taught monitor_task_group fixture to respond better to fatal errors.

---

CHANGES/3407.bugfix
pulpcore/app/tasks/test.py
pulpcore/tasking/pulpcore_worker.py
pulpcore/tests/functional/api/test_tasking.py
pulpcore/tests/functional/utils.py

fixes #3407
(cherry picked from commit dea600fe6674e68dd7c6fdd50630f000af8773bb)

Backport of #3540 Repeat to kill the process of a canceled task.

---

CHANGES/4119.bugfix
CHANGES/4121.bugfix
pulpcore/app/viewsets/replica.py
pulpcore/tests/functional/__init__.py
pulpcore/tests/functional/api/test_replication.py

This bug was only present when domains were enabled.
fixes: #4119

Fixes a bug in the Upstream Pulp Replicate API

---

pulpcore/app/settings.py

Clarify upload/tmp protection time settings.

---

CHANGES/4158.bugfix
pulpcore/app/replica.py
pulpcore/tests/functional/api/test_replication.py

Fixes bug where replication would delete repositories across domains

---

pulpcore/app/serializers/task.py
pulpcore/tests/functional/api/test_workers.py

Improve schedule test

---

pulpcore/app/tasks/importer.py

Fixed importer.py import for Worker.

---

CHANGES/4218.bugfix
pulpcore/app/replica.py

fixes: #4218
The test for this will be part of pulp_file.

Adds partial=True to all update tasks in replication.

---

CHANGES/4231.bugfix
pulpcore/app/importexport.py
pulpcore/app/tasks/export.py

Added to the fix for 4210 in export.

---

CHANGES/4219.bugfix
pulpcore/app/replica.py
pulpcore/app/tasks/replica.py

Sets ca_cert for replication remotes.

---

CHANGES/plugin_api/4229.feature
pulpcore/download/base.py

Accept extra_data in BaseDownloader.fetch()

---

CHANGES/4019.bugfix
pulpcore/content/handler.py
pulpcore/tests/functional/api/using_plugin/test_content_access.py

Taught FileDownloader to correctly handle on-demand remotes.

---

pulpcore/app/viewsets/base.py

Make the docs look a bit prettier:

Add schema summary for RolesMixin operations

---

docs/components.rst
docs/plugins.rst

* Mention pulp_gem as a plugin.
* Update the currently collected analytics data.
[noissue]

Fix small docs deficiencies

---

template_config.yml

Adds 3.32 to the list of branches to update CI on

---

CHANGES/4351.bugfix
pulpcore/app/tasks/export.py

Ensure monkeypatch is properly loaded

---

docs/installation/instructions.rst

Apply a small fix to the installation docs

---

CHANGES/4359.bugfix
pulpcore/app/models/fields.py
pulpcore/tests/unit/models/test_remote.py

Fix encrypted fields bulk_update corrupting data

---

CHANGES/4368.bugfix
pulpcore/app/entrypoint.py
pulpcore/content/entrypoint.py

Add --preload to pulpcore-{api/content}

---

CHANGES/plugin_api/3401.feature
pulpcore/migrations.py
pulpcore/plugin/migrations.py

Migrate version check

---

CHANGES/4411.bugfix
pulpcore/app/tasks/export.py

Ensure that non-chunked exports also use compressionlevel=1

---

CHANGES/+remove_old_script.removal
bin/pulp-content
docs/components.rst
setup.py

Remove pulp-content script

---

requirements.txt

Update pulp_glue to <0.22

---

CHANGES/4436.feature
dev_requirements.txt
docs/plugin_dev/plugin-writer/concepts/tasks/diagnostics.rst
pulpcore/tasking/worker.py

With TASK_DIAGNOSTICS enabled, tasks will be automatically profiled

---

pulpcore/app/importexport.py
pulpcore/app/models/progress.py
pulpcore/app/tasks/export.py
pulpcore/app/tasks/importer.py
pulpcore/app/util.py

Preparation for bigger stuff.  This can be more easily backported as-is.

Small import/export improvements

---

CHANGES/4456.feature
CHANGES/4457.feature
pulpcore/app/serializers/status.py
pulpcore/app/views/status.py
pulpcore/tests/functional/__init__.py
pulpcore/tests/functional/api/test_status.py

Update storage in status to be per domain for all storage types

---

pulpcore/app/importexport.py
pulpcore/app/models/progress.py
pulpcore/app/tasks/export.py
pulpcore/app/tasks/importer.py
pulpcore/app/util.py
requirements.txt

3.1.0 contains some performance improvements.
[noissue]

Bump django-import-export dependency version for performance reasons

---

CHANGES/4478.bugfix
pulpcore/app/role_util.py
pulpcore/tests/unit/roles/test_roles.py

Fix return value of get_users_with_perms_attached_roles

---

CHANGES/4436.misc
dev_requirements.txt
docs/plugin_dev/plugin-writer/concepts/tasks/diagnostics.rst
pulpcore/tasking/pulpcore_worker.py

[3.22] Backport task profiling functionality

---

pulpcore/app/importexport.py

Let's not create and delete a temporary directory for every artifact.
[noissue]

Optimize export_artifacts hot loop

---

CHANGES/4511.feature
docs/authentication/keycloak.rst
pulpcore/app/settings.py
pulpcore/app/urls.py

Addresses #4511  by using required config option `SOCIAL_AUTH_URL_NAMESPACE`

fix: social urls from config

---

pulpcore/app/importexport.py
pulpcore/app/tasks/export.py

Minor memory + perf export optimizations

---

CHANGES.rst
CHANGES/4348.feature
pulpcore/app/tasks/base.py
pulpcore/plugin/serializers/content.py
pulpcore/plugin/viewsets/content.py

Add upload to NoArtifactContentUploadSerializer

---

CHANGES/4348.feature
pulpcore/app/tasks/base.py
pulpcore/plugin/serializers/content.py
pulpcore/plugin/viewsets/content.py

This reverts commit 3bac2bb9baa3be0091bd8169b4e32b2abec31989.
Turned out to be a breaking change.
[noissue]

Revert "Add upload to NoArtifactContentUploadSerializer"

---

.github/workflows/scripts/install.sh
.github/workflows/scripts/pre_before_script.sh
CHANGES/4323.misc
pulpcore/tests/functional/__init__.py
pulpcore/tests/functional/api/test_status.py
pulpcore/tests/functional/assets/otel_server.py
template_config.yml

Tests checking OpenTelemetry payloads are now run in serial.
closes #4323
credits to @mdellweg for designing the machinery

Add test machinery for OpenTelemetry

---

CHANGES/4545.bugfix
pulpcore/app/tasks/importer.py

Read tar from chunks on import

---

pulpcore/app/importexport.py
pulpcore/app/tasks/export.py
pulpcore/app/tasks/importer.py
pulpcore/app/util.py
pulpcore/tests/unit/test_import_checks.py

[noissue]
This came up as a need for the pulp_file merger.

Make export version check more resilient

---

CHANGES/4383.removal
pulpcore/app/models/fields.py

Remove eval fallback to EncryptedJSONField

---

pulpcore/tests/functional/api/test_replication.py

Improves replication tests

---

.bumpversion.cfg
CHANGES/pulp_file/.gitignore
CHANGES/pulp_file/4633.bugfix
pulp_file/app/__init__.py

Fix reported pulp_file version

---

CHANGES/plugin_api/4644.bugfix
pulpcore/content/handler.py

Fixed how Distribtuion.content_handler() is called.

---

CHANGES/plugin_api/4634.bugfix
pulpcore/cache/cache.py
pulpcore/content/handler.py

Adds ADD_TRAILING_SLASH property to AsyncContentCache

---

CHANGES/plugin_api/4635.feature
docs/plugin_dev/api-reference/content-app.rst
pulpcore/content/handler.py

Allow content_handler to return a content artifact

---

CHANGES/4648.bugfix
pulpcore/app/serializers/base.py

Distinguish errors raised during validation in get_or_create

---

pulp_file/app/__init__.py

Fixup pulp_file dev version

---

docs/installation/instructions.rst
template_config.yml

Drop 3.16 from auto-ci-update, add 3.39

---

CHANGES/4679.bugfix
pulpcore/app/entrypoint.py
pulpcore/content/entrypoint.py

Restore the ability to set --max-requests-jitter

---

CHANGES/4681.bugfix
pulpcore/download/file.py
pulpcore/tests/functional/api/pulp_file/test_sync.py

Fix file:// syncs  deleting the original files

---

CHANGES/4681.bugfix
pulpcore/download/file.py

[3.39] Fix files being deleted during file:// syncs

---

CHANGES/4681.bugfix
pulpcore/download/file.py

[3.22] Fix files being deleted during file:// syncs

---

CHANGES/4681.bugfix
pulpcore/download/file.py

[3.21] Fix files being deleted during file:// syncs

---

pulpcore/tests/functional/gpg_ascii_armor_signing_service.py

Use new fixture signing key

---

pulpcore/app/entrypoint.py

Fix wording of API_APP_TTL warning

---

CHANGES/4845.bugfix
pulpcore/cache/cache.py

Ensure the Redis cache is actually respecting the TTL.

---

pulpcore/cache/cache.py

This helps avoid migration issues. Else responses set by the previous version of Pulp would never expire.
Closes #4845

Non-existence of new `expires` key should mean "already expired".

---

.github/workflows/scripts/build_all_docs.sh
.github/workflows/scripts/publish-staging-docs.sh
.github/workflows/staging-docs.yml
CHANGES/4850.misc

Adds workflow for publishing docs to staging-docs.pulpproject.org

---

.github/workflows/staging-docs.yml

Checkout pulpcore before trying to build the new docs site.

---

.github/workflows/staging-docs.yml

Specify the correct path for the archive of the staging docs

---

.github/workflows/scripts/build_all_docs.sh
.github/workflows/staging-docs.yml

Correct the name of the archive for the new docs.

---

.github/workflows/scripts/publish-staging-docs.sh

Fixes the script that publishes to staging-docs.pulpprojec.org

---

.github/workflows/scripts/publish-staging-docs.sh

Fixed username used for rsync of staging-docs

---

CHANGES/4881.misc
pulpcore/tests/functional/__init__.py

Fixes the download_content_unit fixture.

---

.github/workflows/staging-docs.yml

- Add python setup step before running pulp-docs
[noissue]

Fix staging-docs.yml workflow

---

requirements.txt

Bump depedencies versions

---

CHANGES/4923.bugfix
pulpcore/app/tasks/analytics.py
requirements.txt

Fix async_timeout import based on python version

---

CHANGES/4917.feature
pulpcore/app/entrypoint.py
pulpcore/app/pulpcore_gunicorn_application.py
pulpcore/content/entrypoint.py

Load gunicorn defaults before overriding with app settings

---

CHANGES/4925.bugfix
pulpcore/app/global_access_conditions.py
pulpcore/tests/functional/api/pulp_file/test_rbac.py

Fixes has_remote_param_obj_perms

---

CHANGES/3364.feature
pulpcore/app/models/content.py
pulpcore/app/viewsets/content.py
pulpcore/tests/functional/api/using_plugin/test_orphans.py

Add orphaned_for filter

---

CHANGES/4976.bugfix
pulpcore/app/serializers/domain.py
pulpcore/tests/functional/api/test_crud_domains.py

Verify if domain name has more than 50 chars

---

pulp_file/tests/functional/api/test_pulp_export.py

Deletion task was not properly awaited.
[noissue]

Fix crud exporter test

---

pulpcore/tests/functional/__init__.py

Backport the `--nightly` pytest arg

---

CHANGES/plugin_api/5024.feature
pulpcore/plugin/exceptions.py

Expose TimeoutException

---

CHANGES/5033.feature
pulpcore/app/serializers/base.py

Serialize `pulp_last_updated` field

---

CHANGES/4315.deprecation
CHANGES/4315.misc
pulpcore/app/replica.py
pulpcore/app/util.py
pulpcore/app/views/orphans.py
pulpcore/app/views/repair.py
pulpcore/app/viewsets/custom_filters.py
pulpcore/app/viewsets/orphans.py
pulpcore/app/viewsets/publication.py
pulpcore/app/viewsets/reclaim.py
pulpcore/app/viewsets/replica.py
pulpcore/app/viewsets/task.py
pulpcore/tasking/tasks.py
pulpcore/tests/functional/api/using_plugin/test_tasks.py

Introduce Pulp Resource Name (PRN) into task resource locking

---

pulpcore/app/wsgi.py

Fix import in wsgi preventing startup

---

.github/workflows/scripts/build_all_docs.sh

Change URL for pulp-docs repo

---

.github/workflows/scripts/build_all_docs.sh

Change dir before building docs

---

.github/workflows/scripts/build_all_docs.sh

This reverts commit f8fdec326d2710e034057c59938e901d082f9227.

Revert "Change dir before building docs"

---

CHANGES/5189.bugfix
pulpcore/app/wsgi.py

[Backport-3.49] Fix import in wsgi preventing startup

---

.github/workflows/scripts/install.sh
CHANGES/5010.misc
pulpcore/tests/functional/__init__.py
template_config.yml

Improves the `download_content_unit` test fixture.

---

pulpcore/tests/functional/api/using_plugin/test_pulpimport.py

There's way too many implicit dependencies that make it hard to test things.
[noissue]

Rewrite some of the import/export test fixtures for more flexibility

---

CHANGES/5259.bugfix
pulpcore/app/entrypoint.py
pulpcore/content/__init__.py
pulpcore/content/authentication.py

catch any DatabaseError, not only OperationalError to trigger reconnect

---

.github/workflows/scripts/install.sh
CHANGES/5179.feature
docs/authentication/json_header.rst
pulpcore/app/settings.py
pulpcore/openapi/__init__.py
pulpcore/tests/functional/api/test_openapi_schema.py
staging_docs/admin/guides/authentication/05-json_header.md
template_config.yml

Closes #5179
Checklist:
~~- [ ] Tests covering the settings validators~~

Include a new SecurityScheme for external authentication

---

requirements.txt

Allow gunicorn/22.0.0 to pick up gunicorn security fixes.

---

CHANGES/5250.bugfix
pulpcore/app/templates/rest_framework/api.html

Added csrf_token passing to django optional_logout

---

pulpcore/migrations.py

Fix RequireVersion missing backwards methods

---

CHANGES/5319.doc
docs/tech_preview.rst
docs/workflows/complex-filtering.rst
staging_docs/admin/learn/tech-preview.md
staging_docs/user/guides/use-complex-filters.md

Take the complex filtering out of the tech preview list

---

CHANGES/5134.bugfix
pulpcore/app/models/domain.py
pulpcore/app/util.py

Rename attribute "name" to "domain_name" for the domains' emitter

---

CHANGES/5358.bugfix
pulpcore/app/replica.py

Fixes a db query in the replication task

---

pulpcore/app/tasks/replica.py
requirements.txt

Asked by our friend @Odilhao
Signed-off-by: dependabot[bot] <support@github.com>

[noissue]: Update pulp-glue requirement

---

.github/workflows/nightly.yml
.github/workflows/publish.yml
template_config.yml

Disable docs publishing for this branch.

---

.github/workflows/scripts/install.sh
CHANGES/5378.feature
pulpcore/app/settings.py
pulpcore/app/tasks/purge.py
pulpcore/app/util.py
staging_docs/admin/learn/settings.md
template_config.yml

It is guarded by a setting and off by default.
fixes #5378

Add schedule for task purge

---

CHANGES/5420.misc
pulpcore/tests/functional/api/test_workers.py

Increased waiting time in flaky task schedule test

---

CHANGES/5415.removal
pulpcore/app/viewsets/custom_filters.py
pulpcore/app/viewsets/task.py

Remove deprecated reserved_resources_record filter

---

unittest_requirements.txt

Pin the pytest-redis requirement for unit tests

---

CHANGES/+spectacular.removal
pulpcore/openapi/__init__.py
pulpcore/tests/functional/api/test_openapi_schema.py
requirements.txt

Upgrade DRF spectacular to 0.27.2

---

CHANGES/5462.feature
pulpcore/app/checks.py
pulpcore/app/management/commands/openapi.py
pulpcore/app/settings.py
pulpcore/tests/unit/test_settings.py

This allows to generate api.json files without starting the whole infrastructure.
fixes #5462

Add openapi command to pulpcore-manager

---

pulpcore/openapi/__init__.py

This helps to make good use of the pulpcore-manager openapi command.
[noissue]

Backport the api doc component logic

---

pulpcore/app/models/domain.py
pulpcore/app/util.py

Artifacts are unique per domain.

---

CHANGES/5468.misc
pulpcore/app/models/domain.py
pulpcore/app/wsgi.py

Disable the Storage Metrics emmiter for now.

---

CHANGES/4253.bugfix
pulpcore/content/handler.py
pulpcore/tests/functional/api/using_plugin/test_content_directory.py

Fix content index title when domains are enabled

---

pulpcore/tasking/worker.py

Fix `AttributeError: 'NoneType' object has no attribute 'lower'` when `PULP_OTEL_ENABLED` is not set.
[noissue]

Fix AttributeError when PULP_OTEL_ENABLED is unset

---

staging_docs/admin/learn/architecture.md
staging_docs/dev/guides/plugin-walkthrough.md
staging_docs/dev/guides/pull-request-walkthrough.md
staging_docs/dev/guides/test-pulp.md
staging_docs/dev/learn/other/content-protection.md
staging_docs/dev/learn/other/how-plugins-work.md
staging_docs/dev/learn/other/object-relationships.md
staging_docs/dev/learn/other/planning-guide.md
staging_docs/dev/learn/plugin-concepts.md
staging_docs/reference/api-reference/index.md
staging_docs/user/guides/create-client-bindings.md
staging_docs/user/guides/upload-publish.md
staging_docs/user/learn/on-demand-downloading.md

I've used [lychee](https://lychee.cli.rs/introduction/) link-checker.
Here is the link-check workflow I've used: https://discourse.pulpproject.org/t/experimental-link-checking-workflow/1291

Fix some broken links

---

requirements.txt

Fix aiofiles UB to stop pointing at a never-released version.

---

CHANGES/5497.feature
pulpcore/app/tasks/test.py
pulpcore/app/viewsets/task.py
pulpcore/pytest_plugin.py
pulpcore/tests/functional/api/test_tasking.py

fixes: #5497
This should allow adding https://github.com/pulp/pulpcore/issues/4125 to make more sense.

Add RBAC for TaskGroups

---

CHANGES/5529.bugfix
pulpcore/app/checks.py
pulpcore/app/settings.py

Update the default value of SECRET_KEY to enable deployment checks

---

CHANGES/plugin_api/4608.feature
pulp_file/tests/functional/api/test_crud_content_unit.py
pulpcore/plugin/serializers/content.py

Add ability to download file for artifact/content uploads

---

CHANGES/5501.bugfix
pulpcore/app/serializers/content.py
pulpcore/tests/functional/api/using_plugin/test_content_access.py

Fix upload for existing on-demand content

---

requirements.txt

Bump cryptography to <42.0.9

---

CHANGES/5635.bugfix
pulpcore/app/tasks/reclaim_space.py

Implement batching for artifact deletion to handle large repositories

---

.github/workflows/all-docs.yml
.github/workflows/scripts/build_all_docs.sh
.github/workflows/scripts/publish_all_docs.sh

Python version 3.11 seems to be required.
[noissue]

Fix docs workflow

---

.bumpversion.cfg

Remove old doc file from bump-version config

---

requirements.txt

See dependabot PRs:
* https://github.com/pulp/pulpcore/pull/5644
* https://github.com/pulp/pulpcore/pull/5643
* https://github.com/pulp/pulpcore/pull/5642
* https://github.com/pulp/pulpcore/pull/5641
[noissue]

Update opentelemetry-related dependencies.

---

CHANGES/5683.bugfix
pulpcore/app/models/task.py
pulpcore/app/viewsets/task.py
pulpcore/tasking/_util.py
pulpcore/tests/functional/api/test_tasking.py

Fix incorrect RBAC permissions in object creation tasks

---

CHANGES/5703.doc
docs/user/guides/use-complex-filters.md
pulpcore/filters.py

Improve documentation for the complex filtering

---

CHANGES/4125.feature
pulpcore/app/serializers/task.py
pulpcore/app/viewsets/task.py
pulpcore/tasking/tasks.py
pulpcore/tests/functional/api/test_tasking.py

Add ability to cancel a TaskGroup

---

CHANGES/5525.bugfix
CHANGES/5525.deprecation
pulp_file/tests/functional/api/test_domains.py
pulpcore/app/viewsets/content.py
pulpcore/pytest_plugin.py
pulpcore/tests/functional/api/test_crd_artifacts.py
pulpcore/tests/functional/api/test_upload.py

Restrict non-admin users from uploading artifacts

---

pulpcore/tests/functional/api/test_workers.py

The timing in the task schedule tests seems to be a bit tight, leading to a flakey test. By adding two extra seconds waiting time, the test should be reliable again.
[noissue]

Backport task schedule test improvement

---

CHANGES/5693.feature
pulpcore/tasking/tasks.py
pulpcore/tasking/worker.py

Pulp-workers log now logs also domain name in which the task is excuted.

---

.github/dependabot.yml

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups

Group otel dependency updates

---

.github/dependabot.yml

Update otel depedency group to remove protobuf

---

CHANGES/4110.feature
pulpcore/app/viewsets/replica.py

Add filters for UpstreamPulps

---

CHANGES/5844.feature
pulpcore/app/util.py
pulpcore/app/wsgi.py
pulpcore/content/__init__.py
pulpcore/content/handler.py

Include the worker's name in the http.server.duration metric

---

CHANGES/5861.bugfix
pulpcore/tasking/worker.py

Ensure we're passing an int to randint

---

CHANGES/5762.feature
pulpcore/app/models/domain.py
pulpcore/app/tasks/telemetry.py
pulpcore/app/util.py
pulpcore/app/wsgi.py
pulpcore/tasking/_util.py

Re-enable Storage Metrics emiter and refactor it.

---

CHANGES/+fix-any-type.bugfix
pulpcore/app/serializers/domain.py
pulpcore/app/serializers/exporter.py
pulpcore/app/serializers/fields.py
pulpcore/app/serializers/importer.py
pulpcore/app/serializers/task.py

See https://github.com/pulp/pulp_rpm/issues/3639

[3.63] Fix Any serializer type regression breaking Ruby bindings

---

CHANGES/5934.bugfix
pulp_file/tests/functional/api/test_domains.py
pulpcore/app/models/repository.py
pulpcore/app/serializers/base.py
pulpcore/app/util.py

Ensure users can not add cross-domain content through modify endpoint

---

CHANGES/5943.feature
docs/admin/learn/architecture.md
docs/admin/reference/settings.md
pulpcore/app/settings.py
pulpcore/app/util.py
pulpcore/app/wsgi.py
pulpcore/cache/cache.py
pulpcore/content/__init__.py
pulpcore/content/handler.py
pulpcore/content/instrumentation.py
pulpcore/metrics.py
pulpcore/middleware.py
pulpcore/tasking/worker.py
pulpcore/tests/unit/metrics/conftest.py
pulpcore/tests/unit/metrics/test_aiohttp_instrumentation.py
pulpcore/tests/unit/metrics/test_django_instrumentation.py
requirements.txt
unittest_requirements.txt

Replace built-in metrics by custom instrumentation middleware

---

CONTRIBUTING.md

The new link is the entrypoint for devs documentation.

Update CONTRIBUTING.md docs link

---

CHANGES/6165.feature
pulpcore/app/viewsets/base.py
pulpcore/app/viewsets/task.py

Add a filter for `unblocked_at` for Tasks API

---

pulp_file/pytest_plugin.py

(cherry picked from commit 692d0a82c765278f20a5c9e75b73f60efdcc5b54)

Fix bad file test fixture server

---

.gitleaks.toml

Address some reported potential-security-leaks.

Update gitleaks to ignore example-keys.

---

docs/dev/learn/tasks/add-remove.md

An earth-shattering, life-changing, and mind-altering commit that fixes a one character typo in the documentation.

Fix minor typo in documentation

---

CHANGES/6261.bugfix
pulpcore/app/replica.py
pulpcore/app/tasks/replica.py

Fix replication in case of previous failure

---

CHANGES/6242.feature
docs/admin/reference/settings.md
pulpcore/app/settings.py
pulpcore/tasking/worker.py

The new setting is measured in seconds. Also added some clarification around graceful shutdown.
fixes #6242

Turn TASK_GRACE_INTERVAL into a setting

---

docs/admin/reference/tech-preview.md

Fixed a typo in the link to the checkpoint doc in the tech-preview doc.

Fixed a typo in the tech-preview doc.

---

docs/dev/learn/domains/domain.enabled.api.md
docs/dev/learn/domains/domain_enabled_api.md

Documenting how to create a domain enabled api endpoint

documenting domain enabled apis

---

CHANGES/6385.bugfix
pulpcore/content/handler.py
pulpcore/tests/unit/content/test_handler.py

fixes: #6385
(cherry picked from commit 068cb0d37cad3d27862c866855a3d20fcea3d89e)

Backport 3.63 - Fix pull-through cache for on-demand content

---

.ci/assets/ci_constraints.txt
.github/workflows/scripts/script.sh
CHANGES/+aiohttp_semver.bugfix
functest_requirements.txt
pyproject.toml

Semver is explicitely documented for this library.

[PULP-447] Pin the aiohttp dependency to semver boundaries.

---

.ci/assets/ci_constraints.txt
.github/workflows/scripts/script.sh
CHANGES/+aiohttp_semver.bugfix
functest_requirements.txt
pyproject.toml

Semver is explicitely documented for this library.
(cherry picked from commit b4466badab13a46a4940d52ef73a751a2e881c4f)

Pin the aiohttp dependency to semver boundaries.

---

CHANGES/6482.feature
pulpcore/tasking/tasks.py
pulpcore/tasking/worker.py

Add the task_name and if it's a task.immediate to the task log entry.

---

CHANGES/6491.bugfix
pulp_file/tests/functional/api/test_remote_settings.py
pulpcore/app/serializers/repository.py

[PULP-270] Validate and clean comments from Remote certs.

---

CHANGES/6481.doc
docs/admin/reference/settings.md
docs/dev/learn/tasks/diagnostics.md

Fix outdated TASK_DIAGNOSTICS documentation

---

pyproject.toml

Add memray and pyinstrument as optional dependencies

---

CHANGES/+performance_test.misc
pulpcore/tests/performance/test_performance.py

Import and useage of some utility-methods broke when pulp_file was pulled into pulpcore.

Fix test_performance.

---

pulpcore/content/handler.py
pulpcore/tests/functional/api/using_plugin/test_content_delivery.py

In the content app on-demand streaming error handler for digest errors, the TCP connection with the client must be closed. Possibly because of some confusion about what connection should be closed, the downloader session was also closed.
Closing the session is unnecessary to the error handling and it's incompatible with some downloaders. E.g, RpmFileDownloader doesn't have a session at all.
Also, there is no need to raise a runtime error from the error handling perspective, so a clean error log was used.
cherry-picked from: 3a3b6d4eee64a6e7d284208d24e47e1a8284751c (https://github.com/pulp/pulpcore/pull/6556)

[backport 3.77] Fix wrong downloader session close on on-demand streaming

---

CHANGES/6569.feature
pulpcore/tasking/tasks.py

Add the execution time of a task to its finishing log entry.

---

CHANGES/6609.doc
docs/user/guides/alternate-content-sources.md

Adds alternate content source docs

---

pulpcore/openapi/__init__.py

This logic was broken for ansible apis.

Fix some heuristic about domainized urls

---

pyproject.toml

See for more context:
https://github.com/pulp/pulpcore/pull/6695

[3.73] Pin pycares to avoid bug with aiodns combination

---

pyproject.toml

(cherry picked from commit 96e79a8f66c8ae8d5b5c2b3408d17f1110765700)

[3.80] Upper lowerbound for aiodns to fix hanging issue

---

CHANGES/plugin_api/6713.bugfix
pulpcore/app/serializers/content.py
pulpcore/app/serializers/fields.py

Replaces use of HStoreField with a custom PulpLabelsField

---

CHANGES/6630.bugfix
docs/admin/guides/configure-pulp/configure-storages.md
pulpcore/app/serializers/domain.py
pulpcore/app/settings.py

Fix S3 Storage Documentation, Validator and Serializer

---

CHANGES/6731.doc
docs/user/guides/protect-content.md

Update Protect Content documentation

---

CHANGES/6647.bugfix
pulpcore/content/handler.py
pulpcore/tests/functional/api/using_plugin/test_content_delivery.py
pyproject.toml

Stop writing data to client for on-demand HEAD requests

---

.ci/scripts/calc_constraints.py
requirements.txt

See for more context:
https://github.com/pulp/pulpcore/pull/6695
(cherry picked from commit b1560306741816770ddafa3d51dadbef4c7b072a)

[bp/3.28] Pin pycares to avoid bug with aiodns combination

---

pyproject.toml

Pin azure-storage-blob to fix Azurite issue

---

pyproject.toml

Unpin azure-storage-blob

---

CHANGES/6818.bugfix
pulpcore/tasking/worker.py

Fix task's domain info on worker logs

---

CHANGES/6897.feature
pulpcore/app/util.py
pulpcore/app/viewsets/domain.py
pulpcore/app/viewsets/repository.py
pulpcore/tests/functional/api/test_crud_domains.py
pulpcore/tests/functional/api/using_plugin/test_crud_repos.py

Update Remote API to skip task dispatch if no changes are needed
