- CHANGES/9101.bugfix
- pulpcore/plugin/stages/content_stages.py
- pulpcore/tests/functional/api/using_plugin/test_reclaim_disk_space.py
- pulpcore/tests/functional/api/using_plugin/test_sync.py
fixes: #9101
This needs to be backported to 3.14 by Tuesday for Satellite, but it contains changes to the sync pipeline that need to be updated for the 3.15 async changes here: https://github.com/pulp/pulpcore/pull/1553. 
> Properly update present ContentAtifacts after immediate sync

- CHANGES/plugin_api/9257.deprecation
- docs/plugins/plugin-writer/concepts/subclassing/viewsets.rst
- pulpcore/app/tasks/importer.py
- pulpcore/app/views/orphans.py
- pulpcore/app/views/repair.py
- pulpcore/app/viewsets/base.py
- pulpcore/app/viewsets/exporter.py
- pulpcore/app/viewsets/importer.py
- pulpcore/app/viewsets/orphans.py
- pulpcore/app/viewsets/reclaim.py
- pulpcore/app/viewsets/repository.py
- pulpcore/app/viewsets/upload.py
- pulpcore/plugin/actions.py
- pulpcore/plugin/viewsets/content.py
- pulpcore/tasking/tasks.py
@dralley This is based on #1526 but i'll open it for early review now.
If you think this is the way to go i'm happy to assign a ticket to it.
> Deprecate resources argument of dispatch

- CHANGES/9288.bugfix
- pulpcore/app/models/task.py
- pulpcore/tasking/util.py
Instead perform a simple xor on the first and second half of the task
uuid.
backports #9249
fixes #9288
(cherry picked from commit 1d77e5cdf4d03b7edff34f4fc3b60a2f70df3e88)
> Backport: Stop using blake2s to calulate lock identifiers

- CHANGES/9129.bugfix
- CHANGES/plugin_api/9129.deprecation
- CHANGES/plugin_api/9129.feature
- pulpcore/app/migrations/0010_pulp_fields.py
- pulpcore/app/models/progress.py
- pulpcore/plugin/stages/artifact_stages.py
- pulpcore/plugin/stages/content_stages.py
- pulpcore/plugin/sync.py
- pulpcore/tests/unit/stages/test_artifactdownloader.py
Django 3.2 opens up a new connection to the DB for each coroutine that accesses the DB. All ORM
interactions need to be wrapped in 'asgiref.sync.sync_to_async' in order to ensure that all DB
querries are executed using a single connection in a serial manner. This patch also provides
utility function `pulpcore.plugin.sync.sync_to_async_iterable` built on top of `sync_to_async`.
This functions is needed to operate on QuerySet objects and other synchronous iterables.
ProgressReport is enhanced with async interfaces: asave(), aincrease_by(), aincrement(),
__aenter__(), __aexit__(). Plugins should switch to the async interfaces in their Stages.
This patch also ensures that all transactions in the Stages API are run synchronously. This
requires deprecating the ContentStage._pre_save() and …
> Ensure that the Stages API uses a single connection to the DB.

- CHANGES/9314.bugfix
- pulpcore/app/viewsets/publication.py
fixes: #9314
I think this should be backported to 3.15.1
> Return 201 for RBAC content guard assign/remove endpoints

- CHANGES/9213.bugfix
- pulpcore/content/handler.py
aiohttp automatically enflates gzipped responses. Pulp clients always receive
uncompressed responses when requesting on_demand content.
fixes: #9213
> Don't send Content-Encoding header with streamed responses

- CHANGES/9338.bugfix
- pulpcore/tasking/entrypoint.py
For some strange reason some Openshift environments do not like the
runtime import the worker entrypoint used. Moving it to the top where it
belongs anyway resolves the problem.
closes #9338
> Fixes worker not starting on openshift

- CHANGES/9342.bugfix
- pulpcore/tasking/entrypoint.py
For some strange reason some Openshift environments do not like the
runtime import the worker entrypoint used. Moving it to the top where it
belongs anyway resolves the problem.
backports #9338
fixes #9342
(cherry picked from commit 022d2e390729401e157201edea84da14c77b49db)
> backports worker not starting on openshift

- CHANGES/9353.misc
- pulpcore/app/tasks/repository.py
- pulpcore/plugin/stages/artifact_stages.py
- pulpcore/tasking/entrypoint.py
This should no longer be necessary after all the work done to reduce db connections - and if we do encounter issues, we'd be better off trying to address them.
[noissue]
> Disable DJANGO_ALLOW_ASYNC_UNSAFE for tasking system

- CHANGES/plugin_api/9380.feature
- pulpcore/app/response.py
- pulpcore/app/serializers/__init__.py
- pulpcore/app/serializers/base.py
- pulpcore/plugin/serializers/__init__.py
- pulpcore/plugin/viewsets/__init__.py
Adds a ``TaskGroupResponse`` and corresponding
``TaskGroupResponseSerializer`` allowing viewsets to return a task group
back to users directly.
closes #9380
> Adds machinery to return task groups from viewsets

- pulpcore/plugin/importexport.py
This workaround is no longer needed since django-import-export 2.6.0 was
released. This effectively reverts 225360cabb3e563806234c869734c5965b824ec7.
[noissue]
> Remove JSONField mapping in import/export

- CHANGES/plugin_api/9425.removal
- pulpcore/app/response.py
- pulpcore/app/serializers/__init__.py
- pulpcore/app/serializers/base.py
- pulpcore/plugin/serializers/__init__.py
- pulpcore/plugin/viewsets/__init__.py
> Rename TaskGroupResponse to TaskGroupOperationResponse

- CHANGES/9395.bugfix
- pulpcore/plugin/stages/artifact_stages.py
- pulpcore/tests/functional/api/using_plugin/constants.py
- pulpcore/tests/functional/api/using_plugin/test_content_delivery.py
closes: #9395
https://pulp.plan.io/issues/9395
> Update remote artifact urls on sync if the url of the artifact has changed

- CHANGES/9382.removal
- pulpcore/app/tasks/importer.py
- pulpcore/app/viewsets/importer.py
- pulpcore/tests/functional/api/using_plugin/test_pulpimport.py
> Update the import endpoint to return a task group

- CHANGES/9427.bugfix
- pulpcore/plugin/stages/artifact_stages.py
> Replaced incorrect use of 'filename' with 'natural_keys()' in error log.

- docs/contributing/platform-api/tasking.rst
I only saw these as warnings in the CI by accident.
> Fix autogenerated pulpcore.tasking platform docs

- CHANGES/9428.doc
- docs/installation/storage.rst
I've started a PoC for testing azure storage: https://github.com/pulp/pulp_ansible/pull/649
and found this issue
```
(pulp) [vagrant@pulp3-source-fedora34 pulp_ansible]$ nc 127.0.0.1 4444
> /home/vagrant/devel/pulpcore/pulpcore/app/tasks/importer.py(403)pulp_import()
-> if not default_storage.exists(dest):
(Pdb) dest
'/var/lib/pulp/media/artifact/36/0548ba80e3dce478b7915ca89a5613dc80c650a55b96f5491012a8297e12ac'
(Pdb) default_storage.exists(dest)
*** django.core.exceptions.SuspiciousOperation: Attempted access to '/var/lib/pulp/media/artifact/36/0548ba80e3dce478b7915ca89a5613dc80c650a55b96f5491012a8297e12ac' denied.
(Pdb) default_storage.list_all()
['pulp3/artifact/36/0548ba80e3dce478b7915ca89a5613dc80c650a55b96f5491012a8297e12ac', …
```
> Document Azure storage needs to set MEDIA_ROOT

- CHANGES/9441.bugfix
- pulpcore/app/models/content.py
fixes #9441.
[nocoverage]
Required PR: https://github.com/pulp/pulpcore/pull/1637
> Teach several touch() paths to apply order to avoid deadlocks.

- CHANGES/8750.bugfix
- pulpcore/app/models/content.py
- pulpcore/plugin/stages/artifact_stages.py
- pulpcore/plugin/stages/content_stages.py
Forcing deadlocks requires a lot of time and pulpcore-workers running.
There is therefore no specific CI test for this, but there is a reproducer
script that will force deadlocks to happen (and show that they're fixed) here:
https://github.com/ggainey/pulp_startup/blob/main/8750_deadlocks/file_repro.sh
fixes #8750.
[nocoverage]
> Fix occasional deadlocks when doing multiple similar syncs concurrently.

- CHANGES/9491.bugfix
- pulpcore/download/base.py
- pulpcore/download/http.py
- pulpcore/exceptions/__init__.py
- pulpcore/exceptions/base.py
closes #9491
backports #9301
(cherry picked from commit 8a1db3b9c0bd44f6ea76eeb2a2cdbcd673b199c3)
> Improved messaging around timeout requests.

- CHANGES/9532.feature
- docs/plugins/reference/metadata-signing.rst
- docs/workflows/signed-metadata.rst
- pulpcore/app/models/content.py
closes #9532
https://pulp.plan.io/issues/9532
This will allow for a signing service script that is not hard coded to a
particular key. It should be fully backwards compatibile with all
existing scripts, since they need not make use of the new parameter.
> Pass the public key fingerprint to the signing service subprocess

- CHANGES/9276.bugfix
- pulpcore/content/__init__.py
- pulpcore/content/authentication.py
- pulpcore/content/handler.py
- pulpcore/tests/functional/api/using_plugin/test_distributions.py
- pulpcore/tests/unit/content/test_heartbeat.py
When the authentication middleware was added in pulpcore 3.15, it became the first place
in the content app that made an attempt to use the database. As a result, it is a convinient
place to handle InterfaceError and  OperationalError which are raised when the database
connection has been closed. When this occurs, Handler._reset_db_connection() is called to
clean up the database connection and the middleware tries to use the database again.
If the database connection is closed later in the handling of the request by the content app,
the user will still get a 500 error. However, the next request will be handled properly.
This patch also adds a call to Handler._reset_db_connection() inside the heartbeat method.
fixes: #9276
https://pulp.plan.io/issues/9276
> Handles closed db connections

- CHANGES/8988.bugfix
- pulpcore/app/models/task.py
- pulpcore/tasking/pulpcore_worker.py
Missing worker entries are now kept in the database for seven days
before being cleaned up. This gives time for post-mortem analysis.
It also switches the cleanup of those records to be a bulk operation.
closes #8988
> Cleanup missing worker entries after seven days

- CHANGES/9549.bugfix
- pulpcore/tasking/pulpcore_worker.py
There seems to be a time window, where workers might miss a wakeup call
and end in waiting state, while tasks are still available.
[noissue]
@dalley i decided to turn this into a pr, because it might also fix a rare ci failure where canceling a task is lost in that window.
> Keep listening on pg channels in workers

- CHANGES/9542.bugfix
- pulpcore/plugin/sync.py
The `sync_to_async_iterable` wraps the Artifact queryset, but unlike
querysets, it can't be reused. This causes subsequent iterations
through it to not actually iterate.
closes #9542
> Fixes Artifact redownloading bug

- CHANGES/plugin_api/9591.feature
- pulpcore/download/factory.py
- pulpcore/tests/unit/download/test_factory.py
closes #9591
https://pulp.plan.io/issues/9591
> Move user_agent into DownloaderFactory to expose it in plugin API.

- CHANGES/plugin_api/9592.feature
- pulpcore/app/models/repository.py
closes #9592
https://pulp.plan.io/issues/9592
> Add ability to `Remote.get_downloader` to specify a download factory.

- CHANGES.rst
- CHANGES/9584.bugfix
- docs/configuration/settings.rst
- docs/contributing/platform-api/app/index.rst
- docs/contributing/platform-api/tasking.rst
- docs/installation/index.rst
- pulpcore/plugin/sync.py
- pulpcore/tests/unit/models/test_content.py
The `sync_to_async_iterable` wraps the Artifact queryset, but unlike
querysets, it can't be reused. This causes subsequent iterations
through it to not actually iterate.
backports #9542
fixes #9584
(cherry picked from commit a9431560785c5b16c27708928a3dd10763401899)
> backports Artifact redownloading bug

- pulpcore/backends.py
- pulpcore/tests/unit/roles/test_roles.py
According to Django docs [0] has_perm called with an object should not
honour model level permissions. When needed these need to be checked
independently.
[0] https://docs.djangoproject.com/en/3.2/ref/contrib/auth/#django.contrib.auth.models.User.has_perm
[noissue]
> Do not imply module permissions on objects

- CHANGES/plugin_api/9608.bugfix
- pulpcore/app/apps.py
The deprecation warning about an offending AccessPolicy now includes the
name of the Viewset that has the problem.
closes #9608
> Adds viewset name to accesspolicy deprecations

- CHANGES/9327.removal
- docs/installation/instructions.rst
- pulpcore/tasking/entrypoint.py
The `pulpcore-worker` entrypoint no longer accepts the
`--resource-manager` option.
closes #9327
> Removes the --resource-manager option

- CHANGES/8554.feature
- pulpcore/app/serializers/__init__.py
- pulpcore/app/serializers/purge.py
- pulpcore/app/tasks/__init__.py
- pulpcore/app/tasks/purge.py
- pulpcore/app/viewsets/task.py
- pulpcore/tests/functional/api/using_plugin/test_purge.py
> Added bulk-task-purge feature.

- pulpcore/app/viewsets/base.py
- pulpcore/backends.py
- pulpcore/tests/unit/roles/test_roles.py
Django's interface for get_all_permissions seems to not include the
app_label in the permission strings.
We include them again in the my_permission endpoint, because that is the
way we represent them to our users everywhere.
https://docs.djangoproject.com/en/3.2/ref/contrib/auth/#django.contrib.auth.models.User.get_all_permissions
re #9411
> Fix return value of get_all_permissions

- CHANGES/9639.bugfix
- pulpcore/app/serializers/access_policy.py
- pulpcore/tests/functional/api/test_access_policy.py
These fields were both required by the serializer, which could never
validate.
fixes #9639
> Optional permissions_assignment and creation_hooks

- CHANGES/9660.bugfix
- pulpcore/app/tasks/importer.py
> Fixes PulpImport in the presence of Django path-traversal CVE fix.

- CHANGES/9663.bugfix
- doc_requirements.txt
- pulpcore/app/tasks/importer.py
backports #9660.
[nocoverage]
fixes #9663
(cherry picked from commit ba1b9fa22ff59d63093560c3d03e26b7c0d6973c)
> [3.16.z cp] Fix PulpImport in the presence of Django path-traversal CVE fix.

- CHANGES/9664.bugfix
- pulpcore/app/tasks/importer.py
backports #9660.
[nocoverage]
fixes #9664
(cherry picked from commit ba1b9fa22ff59d63093560c3d03e26b7c0d6973c)
> [3.17.z cp] Fix PulpImport in the presence of Django path-traversal CVE fix.

- .github/workflows/scripts/before_install.sh
- CHANGES/9662.bugfix
- doc_requirements.txt
- functest_requirements.txt
- pulpcore/app/tasks/importer.py
backports #9660.
[nocoverage]
fixes #9662
(cherry picked from commit ba1b9fa22ff59d63093560c3d03e26b7c0d6973c)
> [3.14.z cp] Fix PulpImport in the presence of Django path-traversal CVE fix.

- CHANGES/9666.bugfix
- pulpcore/tasking/pulpcore_worker.py
This adds some logging for cases, where the task executing process dies
unexpectedly (e.g. OOM) and is unable to properly set the task state and
error reason.
fixes #9666
> Add logging around certain ways a task can fail

- pyproject.toml
I introduced this, but actually I was able to move this to pulp-smash
instead so all plugins automatically receive it.
[noissue]
> Remove the pytest entry from pyproject.toml

- CHANGES/2078.bugfix
- pulpcore/download/base.py
> Fix retry logic of partially downloaded files

- docs/bugs-features.rst
@fao89  did this already for the plugins on pulpproject.org 
Updating here also for Pulpcore
[noissue]
> replace redmine with github issues

- CHANGES/9645.bugfix
- pulpcore/app/importexport.py
- pulpcore/app/tasks/importer.py
- pulpcore/constants.py
json.dumps method consumes a lot of memory when converting data
to json string. While processing data, it seems to create
python object which is a number of times larger than the
parsing data. For example, a 5GB data is resulting more than 20GB
consumed.
This commit fixes the issue by processing the dataset in batch
and write into a temporary file.
This commit also fixes the import OOM error by parsing only the
file object to the json.load method instead of reading whole
file into the memory.
closes #9645
> Fix import and export OOM error 

- CHANGES/2057.feature
- docs/configuration/settings.rst
- docs/installation/instructions.rst
- pulpcore/app/redis_connection.py
- pulpcore/app/settings.py
- pulpcore/app/views/status.py
- pulpcore/tests/functional/api/utils.py
- pulpcore/tests/unit/test_cache.py
Pulp does not use redis if not configured by user.
closes: https://pulp.plan.io/issues/9475
> Redis not used by default

- CHANGES/2135.bugfix
- pulpcore/download/base.py
> Reset size and digests when retrying downloads

- CHANGES/2034.feature
- pulpcore/app/models/task.py
- pulpcore/app/serializers/task.py
- pulpcore/tests/functional/api/test_workers.py
Provide the task href of the currently active task, if any, because it's useful information as an admin / support.
closes #2034
https://github.com/pulp/pulpcore/issues/2034
> Added a "current_task" field to the worker

- CHANGES/9670.feature
- pulpcore/app/global_access_conditions.py
> Use url parameter in repository access condition

- CHANGES/2119.bugfix
- pulpcore/content/handler.py
Fixes streamed responses when the remote server declares a
content-encoding.
fixes #2119
> Fixes edge case for streamed responses via the content app

- CHANGES/2102.bugfix
- pulpcore/app/tasks/importer.py
Note: there is no additional test for this, because it's a concurrency
window that is VERY hard to force. Here's a script that can occasionally
force the error:
https://github.com/ggainey/pulp_startup/blob/main/import_export/file_uq_repro.sh
fixes #2102.
[nocoverage]
> Fix import-uq-failure on ContentArtifact.

- CHANGES/2183.bugfix
- pulpcore/tasking/pulpcore_worker.py
Previously, tasks that were canceled without being assigned to a worker
would appear as failed due to worker gone missing.
fixes #2183
> Fix canceling tasks never being picked up

- docs/configuration/applying.rst
The target of link to multiple file formats of Dynaconf does not exist any more (/yet).
So I updated the link with what sounds matching the best to me. Please double check as I don't know Dynaconf.
> Update link to Dynaconf mutiple formats

- CHANGES/2003.feature
- CHANGES/plugin_api/8806.feature
- pulpcore/cache/__init__.py
- pulpcore/cache/cache.py
- pulpcore/content/handler.py
- pulpcore/plugin/cache/__init__.py
> Enable caching for the synchronous context

- CHANGES/2116.feature
- CHANGES/plugin_api/2116.feature
- pulpcore/app/access_policy.py
- pulpcore/app/models/access_policy.py
This change adds the `handle_creation_hooks` interface to the
``AccessPolicyFromDB`` method. If the AccessPolicy configured does not
have that interface, new model instances created will not have
permissions automatically added to them.
closes #2116
> Adds the `handle_creation_hooks` interface

- CHANGES/plugin_api/2209.deprecation
- docs/plugins/plugin-writer/concepts/rbac/adding_automatic_permissions.rst
- pulpcore/app/models/access_policy.py
- pulpcore/app/models/base.py
- pulpcore/app/models/publication.py
- pulpcore/app/models/task.py
The `ACCESS_POLICY_VIEW_NAME` attribute on models is no longer in use by
the RBAC machinery and is discouraged from being defined. If present on
a model a deprecation warning is logged.
closes #2209
> Adds deprecation warning ACCESS_POLICY_VIEW_NAME

- CHANGES/2192.bugfix
- pulpcore/app/importexport.py
- pulpcore/app/modelresource.py
> Corrected PulpImport/Export handling of sub-content.

- CHANGES/2157.bugfix
- pulpcore/app/models/content.py
The deadlock is difficult to capture "in the wild"; see #2157 for
details on reproducing and showing that this fixes it.
fixes #2157.
[nocoverage]
> Fixed touch() deadlock window.

- CHANGES/plugin_api/2148.deprecation
- pulpcore/app/settings.py
- pulpcore/plugin/constants.py
It was turned into a setting.
re #2148
[noissue]
> Deprecate the API_ROOT constant

- pulpcore/app/settings.py
- pulpcore/plugin/constants.py
re #2148
What used to be API_ROOT is V3_API_ROOT_NO_FRONT_SLASH now
https://github.com/pulp/pulpcore/blob/3.17/pulpcore/constants.py#L47
Noticed it when fixing pulp_file tests:
https://github.com/pulp/pulp_file/pull/643
> Use V3_API_ROOT_NO_FRONT_SLASH on deprecation

- CHANGES/2247.bugfix
- pulpcore/app/tasks/importer.py
fixes #8610
[nocoverage]
(cherry picked from commit 2f565c936d03f26c61c4b992c5e98a2b835d7cc7)
> Taught import-task to extract into current-working-dir.

- docs/installation/hardware-requirements.rst
Previously, this was rendering more like a literal
> ..note::
>
> Pulp will mostly automatically manage the following directories for you. Only if you need to adjust permissions or security contexts and perform a manual installation, you need to prepare them accordingly.
> Fix note directives

- CHANGES/2276.feature
- pulpcore/app/viewsets/user.py
Issue: AAH-1409
https://issues.redhat.com/browse/AAH-1409
In the [ansible-hub-ui](https://github.com/ansible/ansible-hub-ui) we would like to filter the roles by description also. This PR makes the filtering available.
> Add a description filter to the RoleFilter

- CHANGES/2047.bugfix
- CHANGES/2267.bugfix
- pulpcore/app/models/repository.py
- pulpcore/tests/conftest_pulp_file.py
- pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
Add_and_remove task might fail with "duplicate key value violates
unique constraint" error after deleting a repository version.
Also added a test to cover this scenario.
fixes #2047
fixes #2267
> Fix delete repository version causing "duplicate key" error

- CHANGES/2047.bugfix
- CHANGES/2267.bugfix
- pulpcore/app/models/repository.py
- pulpcore/tests/conftest.py
- pulpcore/tests/conftest_pulp_file.py
- pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
Add_and_remove task might fail with "duplicate key value violates
unique constraint" error after deleting a repository version.
Also added a test to cover this scenario.
fixes #2047
fixes #2267
(cherry picked from commit a28b7116e550b35241a39d35935007e860face04)
(cherry picked from commit c0f04d8f991e45ccc6a5de13fcaf2564016ce4c7)
(cherry picked from commit 603a60d996c12f1f22bdf924ec5aff8d72306654)
> [3.14 backport] Fix delete repository version causing "duplicate key" error

- CHANGES/2069.bugfix
- CHANGES/plugin_api/2069.bugfix
- pulpcore/plugin/stages/api.py
The runtime was actually slightly slower with the 1000 objects in-memory
and much more memory use.
closes #2069
> Reduces queue size between stages from 1000 to 1

- CHANGES/2381.bugfix
- pulpcore/plugin/stages/artifact_stages.py
The Django Prefetch caching is providing older data previously fetched,
so we need to invaidate the caches when prefetching.
closes #2381
> Fixes RemoteArtifact duplicate key error

- requirements.txt
```
fatal: [fedora-34]: FAILED! => {
"changed": false, 
"cmd": [
"/usr/local/lib/pulp/bin/pip-compile"
], 
"delta": "0:00:40.624751", 
"end": "2022-03-23 18:08:48.547438", 
"failed_when_result": true, 
"rc": 2, 
"start": "2022-03-23 18:08:07.922687"
}
STDERR:
Could not find a version that matches async-timeout<4.0,>=3.0,>=4.0.2 (from redis==4.2.0->pulpcore==3.15.6->-r requirements.in (line 1))
Tried: 1.0.0, 1.0.0, 1.1.0, 1.1.0, 1.2.0, 1.2.0, 1.2.1, 1.2.1, 1.3.0, 1.3.0, 1.4.0, 1.4.0, 2.0.0, 2.0.0, 2.0.1, 2.0.1, 3.0.0, 3.0.0, 3.0.1, 3.0.1, 4.0.0, 4.0.0, 4.0.1, 4.0.1, 4.0.2, 4.0.2
Skipped pre-versions: 4.0.0a0, 4.0.0a0, 4.0.0a1, 4.0.0a1, 4.0.0a2, 4.0.0a2, 4.0.0a3, 4.0.0a3
There are incompatible versions in the resolved dependencies:
async-timeout<4.0,>=3.0 (from …
```
> Pin redis on pulpcore < 3.17

- CHANGES/2038.feature
- pulpcore/app/manage.py
> pulpcore-manager defaults to '/etc/pulp/settings.py'

- CHANGES/2038.feature
- pulpcore/app/manage.py
> Revert "pulpcore-manager defaults to '/etc/pulp/settings.py'"

- pulpcore/tests/functional/api/using_plugin/test_distributions.py
This test fails intermittently in CI. Disabling it for now.
[noissue]
> Skips the test_content_served_after_db_restart

- CHANGES/2420.bugfix
- pulpcore/plugin/stages/artifact_stages.py
Reproducing/testing is at best timeconsuming, and dependent on an empty
pulp instance being set up for high (>10 workers) concurrency. See the
associated issue for manual test process.
fixes #2420
[nocoverage]
> Taught ArtifactSaver to order artifacts prior to attempting bulk-create.

- CHANGES/2061.bugfix
- pulpcore/app/importexport.py
- pulpcore/app/tasks/importer.py
- pulpcore/download/base.py
fixes: #2061
There is also two instances of writing to `/tmp` in [factory.py](https://github.com/pulp/pulpcore/blob/main/pulpcore/download/factory.py#L113-L116) for writing a temp key and cert for the downloader, but that code can be called outside of a worker (like in the content app), so I didn't change it.
> Fix instances of writing to /tmp

- pulpcore/tests/functional/api/using_plugin/test_content_cache.py
- pulpcore/tests/functional/api/using_plugin/test_content_delivery.py
- pulpcore/tests/functional/api/using_plugin/test_content_guard.py
- pulpcore/tests/functional/api/using_plugin/test_crd_publications.py
- pulpcore/tests/functional/api/using_plugin/test_crud_repos.py
- pulpcore/tests/functional/api/using_plugin/test_distributions.py
- pulpcore/tests/functional/api/using_plugin/test_filesystemexport.py
- pulpcore/tests/functional/api/using_plugin/test_generic_list.py
- pulpcore/tests/functional/api/using_plugin/test_pagination.py
- pulpcore/tests/functional/api/using_plugin/test_pulpexport.py
- pulpcore/tests/functional/api/using_plugin/test_pulpimport.py
- pulpcore/tests/functional/api/using_plugin/test_purge.py
- pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
- pulpcore/tests/functional/api/using_plugin/test_sync.py
- pulpcore/tests/functional/api/using_plugin/test_tasking.py
- pulpcore/tests/functional/api/using_plugin/test_tasks.py
To avoid errors the pulpcore tests have been updated to leave to objects
except FileContent and Tasks behind. Also all tests are now independant.
[noissue]
> Make tests independant

- CHANGES/1968.bugfix
- docs/plugins/plugin-writer/concepts/index.rst
- pulpcore/app/settings.py
- pulpcore/tests/unit/test_settings.py
An experimental PR to see if it is possible to do our settings validation using dynaconf's Validators. This should also ensure that plugins that use pulpcore's settings will all receive the same error message if that setting isn't define (https://github.com/pulp/pulpcore/issues/1968). 
I opened this PR to get discussion around this option. I'm not sure how much better this way is or if I even used the Validators correctly (@rochacbruno). Also, I think there is another way to fix #1968 using [hooks](https://www.dynaconf.com/advanced/#hooks) if this way doesn't pan out.
> Use dynaconf validators for settings.py

- .git-blame-ignore-revs
- pyproject.toml
Thought this looked useful:
https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/
> Ignore black commit

- CHANGES/2430.bugfix
- pulpcore/plugin/stages/content_stages.py
See https://bugzilla.redhat.com/show_bug.cgi?id=2062526 for details on
forcing the deadlock and discussion of the fix.
fixes #2430.
[nocoverage]
> Fixed rare bulk_update() deadlock in ContentSaver.

- .github/workflows/scripts/script.sh
- template_config.yml
The pulp_file tests are eventually going to hold all of the tests which
involve pulp_file. Those are needed to assert correctness on pulpcore
though so let's run those with pulpcore too!
[noissue]
> Run pulp_file tests in pulpcore CI

- requirements.txt
> Bump django requirement

- requirements.txt
> Bump django on 3.15

- requirements.txt
> Bump django on 3.16

- CHANGES/2087.bugfix
- pulpcore/app/importexport.py
- pulpcore/app/tasks/upload.py
> [3.16]  Fixed "Too many open files" error during upload. 

- CHANGES/2087.bugfix
- pulpcore/app/importexport.py
- pulpcore/app/tasks/upload.py
closes #2087
(cherry picked from commit dcbf935)
(cherry picked from commit 3fb0e5cd270ce71c722d9a6d8669bf44aac61c45)
> [3.15]  Fixed "Too many open files" error during upload. 

- CHANGES/1910.bugfix
- pulpcore/content/handler.py
fixes: #1910
Working on a couple content app user improvements for 3.20. This one is the simplest change, but maybe the issue wanted something more explicit for this scenario.
> Add error reason for accessing distribution w/o publication

- requirements.txt
> Bump django on 3.17

- requirements.txt
> Bump django on 3.18

- CHANGES/plugin_api/2463.doc
- docs/plugins/plugin-writer/concepts/rbac/access_policy.rst
- docs/plugins/plugin-writer/concepts/rbac/adding_automatic_permissions.rst
- docs/plugins/plugin-writer/concepts/rbac/permissions.rst
- docs/plugins/plugin-writer/concepts/rbac/queryset_scoping.rst
- docs/plugins/plugin-writer/concepts/rbac/users_groups.rst
Explain the concept of roles, their relationship to permissions, how
they are associated with personas and objects and also remove any
mention of django-guardian that is to be removed in 3.20.
fixes #2463
> Update RBAC guide for plugin writers

- CHANGES/2557.bugfix
- pulpcore/plugin/stages/models.py
This bug lead to serious sync performance degredation in some plugins,
because batching was de facto disabled for the ContentAssociation stage.
fixes #2557
> Fix does_batch for resolved content

- CHANGES/plugin_api/2556.removal
- pulpcore/plugin/constants.py
Plugin writers should use the `V3_API_ROOT` or
`V3_API_ROOT_NO_FRONT_SLASH` settings instead.
closes #2556
> Removes pulpcore.plugin.constants.API_ROOT

- pulpcore/tests/functional/__init__.py
- pulpcore/tests/functional/conftest.py
- setup.py
The pulpcore fixtures are moving from pulp-smash to pulpcore so that
they can be versioned properly with pulpcore.
Required PR: https://github.com/pulp/pulp_file/pull/687
[noissue]
> Add pulpcore pytest fixtures from pulp-smash

- CHANGES/2576.bugfix
- pulpcore/download/http.py
[noissue]
Not sure if this has an issue already or not. Related to https://issues.redhat.com/browse/AAH-1202 and test found in: https://github.com/pulp/pulp_file/pull/689
Our downloaders really need to be refactored and will be (https://discourse.pulpproject.org/t/downloader-refactor-sig/393/4), so not sure how useful this fix is. Also, I only fixed this on the http downloader, base and file are unaffected, and if any other downloaders override the `_run` method then this fix won't occur.
> Ensure download has fresh file on retry

- CHANGES/2550.feature
- pulpcore/download/base.py
After applying the changes, an error message looks like this:
```
Content at the URL 'https://fixtures.pulpproject.org/file/1.iso' does not contain at least one trusted hasher which is specified in the 'ALLOWED_CONTENT_CHECKSUMS' setting (['sha512', 'sha224]). The downloader expected one of the following hashers: {'sha256'}
```
closes #2550
> Add more details to an error message

- CHANGES/plugin_api/2634.misc
- pulpcore/app/models/base.py
If plugin writers had set the `ACCESS_POLICY_VIEWSET_NAME` attribute on
a model they would receive a deprecation warning. That's an old warning
and it is now removed.
closes #2634
> Removed an outdated deprecation warning

- CHANGES/2589.bugfix
- pulpcore/app/tasks/importer.py
fixes #2589.
[nocoverage]
(cherry picked from commit d936ce5bb052973133336157fbeb2a1c24f08024)
> Taught pulp-import to retry up to three times on collisions.

- CHANGES/2654.bugfix
- pulpcore/download/http.py
> Improved the error message when HTTP proxies reject requests from Pulp.

- CHANGES/2553.bugfix
- pulpcore/app/serializers/fields.py
This bug would appear when CONTENT_PATH_PREFIX was set to "" or "/".
fixes: #2553
> Replaces "//" with "/" in base_url.

- CHANGES/2643.misc
- functest_requirements.txt
- pulpcore/tests/functional/__init__.py
- pulpcore/tests/functional/api/test_openapi_schema.py
To validate, it needs the `pk_path` param to be True, so for example you
can use:  `/pulp/api/v3/docs/api.json?pk_path=1`.
closes #2643
AAH-1548
> Adds openapi v3 schema validation test

- CHANGES/2307.bugfix
- pulpcore/app/tasks/importer.py
- requirements.txt
> Taught PulpImport how to stream import-files.

- CHANGES/2307.bugfix
- pulpcore/app/tasks/importer.py
- requirements.txt
> [3.18] Taught PulpImport how to stream import-files.

- CHANGES/2307.bugfix
- pulpcore/app/tasks/importer.py
- requirements.txt
> [3.17] Taught PulpImport how to stream import-files.

- CHANGES/2307.bugfix
- pulpcore/app/tasks/importer.py
- requirements.txt
> [3.16] Taught PulpImport how to stream import-files.

- CHANGES/2307.bugfix
- pulpcore/app/tasks/importer.py
- requirements.txt
> [3.15] Taught PulpImport how to stream import-files.

- CHANGES/2307.bugfix
- pulpcore/app/tasks/importer.py
- requirements.txt
> [3.14] Taught PulpImport how to stream import-files.

- docs/configuration/applying.rst
Note that user can use ``/etc/pulp/settings.local.py`` to keep local
settings through installer pulp upgrade.
[noissue]
> [Docs] Note about local settings file

- CHANGES/2476.feature
- CHANGES/plugin_api/2476.feature
- docs/workflows/signed-metadata.rst
- pulpcore/app/management/commands/add-signing-service.py
- pulpcore/app/models/content.py
- pulpcore/app/util.py
- pulpcore/exceptions/__init__.py
- pulpcore/exceptions/validation.py
- pulpcore/plugin/exceptions.py
- pulpcore/plugin/util.py
In this commit, the validation procedure triggered before saving signing services was refactored. As of this commit, users will no longer experience problems with missing keys or improperly configured GnuPG home directory. Public keys are imported to a temporary GnuPG directory where everything is correctly staged for validation purposes.
Also, redundant validation checks in the AsciiArmoredDetached's validate() method were removed as well.
closes https://github.com/pulp/pulpcore/issues/2476
> Enable admins to specify a custom GnuPG directory or keyring

- CHANGES/2782.doc
- docs/conf.py
The extlinks with Sphinx==5.0.0 emitted warnings that were treated as
failures. This updates the extlinks definition to have it work with the
newer versions also.
closes #2782
> Fixes extlinks to be Sphinx==5.0.0 compatible

- CHANGES/2739.bugfix
- pulpcore/app/role_util.py
This fixes two inconsistencies with the guardian interfaces:
- `for_concrete_model=False` makes it so that these functions don't work with proxy models (which guardian allowed)
- `Q(object_id=None)` causes users/groups with model permissions to be returned (which guardian didn't do)
@mdellweg do these changes make sense to you? I've only tested it with `get_groups_with_perms_attached_roles` (which is currently breaking stuff for us in galaxy_ng), so I'm not sure if these changes are going to cause problems for other plugins or not. If it does, we can just create our own function for this in galaxy_ng.
> Update get_[users|groups]_with_perms to match guardian.

- CHANGES/2747.feature
- pulpcore/app/viewsets/base.py
- pulpcore/app/viewsets/user.py
- pulpcore/tests/functional/__init__.py
- pulpcore/tests/functional/api/test_role.py
fixes: #2747
Example usage: http://localhost:8080/pulp/api/v3/roles/?for_object_type=/pulp/api/v3/groups/
Returns roles that only have permissions on the `/pulp/api/v3/groups/` resource type.
> Add ?for_object_type to roles API

- CHANGES/1982.feature
- CHANGES/plugin_api/1982.feature
- pulpcore/app/apps.py
- pulpcore/app/serializers/status.py
- pulpcore/app/views/status.py
- pulpcore/tests/functional/api/test_status.py
Plugins are now required to declare the python package name so pulpcore
can include it in the status API response.
Required PR: https://github.com/pulp/pulp-certguard/pull/184
Required PR: https://github.com/pulp/pulp_file/pull/738
closes #1982
> Adds Python package name to the status API

- CHANGES/plugin_api/2786.feature
- CHANGES/plugin_api/2786.removal
- pulpcore/app/files.py
- pulpcore/app/tasks/upload.py
- pulpcore/plugin/serializers/content.py
- pulpcore/plugin/viewsets/content.py
- pulpcore/tasking/tasks.py
- pulpcore/tests/functional/__init__.py
This is needed to prevent creating orphans in the meantime.
fixes #2786
> Allow uploads to be turned into content directly

- docs/contributing/git.rst
The list of extensions for the towncrier changelog fragments was missing `.doc` for documentation improvements.
> Add `.doc` as possible changelog update extension

- docs/authentication/other.rst
- docs/components.rst
- docs/configuration/settings.rst
- docs/plugins/plugin-writer/concepts/index.rst
- docs/plugins/plugin-writer/concepts/rbac/overview.rst
- docs/plugins/plugin-writer/concepts/rbac/permissions.rst
- docs/plugins/plugin-writer/concepts/subclassing/models.rst
- docs/plugins/reference/how-plugins-work.rst
- pulpcore/app/models/__init__.py
- pulpcore/app/models/base.py
- pulpcore/app/models/fields.py
- pulpcore/app/models/generic.py
- pulpcore/app/models/progress.py
- pulpcore/app/settings.py
- pulpcore/app/wsgi.py
- pulpcore/tests/unit/viewsets/test_base.py
Several references to the official Django documentation used links to a multitude of different versions. This commit makes sure all links to the documentation point to the currently used 3.2 LTS version of Django.
ref #2878
> [noissue] update links to Django documentation

- functest_requirements.txt
- pulpcore/tests/functional/__init__.py
- pulpcore/tests/functional/gpg_ascii_armor_signing_service.py
The new fixtures can be used to auto-setup-and-teardown an
`AsciiArmoredDetachedSigningService`. Pre-generated gpg public and
private keys are used temporarily configure the gpghome dir for use
during the test. Also "local" signing facilities are also available for
tests to produce signatures locally too.
[noissue]
> Adds signing service pytest fixtures

- requirements.txt
Reverts pulp/pulpcore#2896
37.0.3 has been yanked
https://pypi.org/project/cryptography/#history
> Revert "[noissue]: Update cryptography requirement from ~=37.0.2 to ~=37.0.3"

- CHANGES/2856.misc
- requirements.txt
> Changes yarl version requirement to ~=1.0

- CHANGES/plugin_api/2930.feature
- CHANGES/plugin_api/2930.removal
- pulpcore/app/models/content.py
- pulpcore/app/util.py
- pulpcore/exceptions/validation.py
- pulpcore/plugin/util.py
- pulpcore/tests/functional/__init__.py
- pulpcore/tests/functional/gpg_ascii_armor_signing_service.py
> Extend the interface of verify_signature

- CHANGES/2933.bugfix
- pulpcore/app/tasks/export.py
FS Exporter uses the relative_paths of the content_artifacts instead of
the actual publication's relative path when exporting publications.
This commit use published relative paths if a publication is available
> Use published relative paths for FS Exporter

- pulpcore/tests/functional/__init__.py
The old name has a conflict with pytest-django.
[noissue]
> Rename fixture admin_user to pulp_admin_user

- CHANGES/3030.bugfix
- pulpcore/app/views/orphans.py
- pulpcore/app/viewsets/orphans.py
Orphan cleanup tasks can get in each other's way by deleting things
before the other task gets a chance to do so. This pops up as a problem
primarily for the RPM plugin.
closes #3030
> Serialize orphan cleanup tasks to prevent them from getting in each other's way

- CHANGES/3030.bugfix
- pulpcore/app/views/orphans.py
- pulpcore/app/viewsets/orphans.py
Orphan cleanup tasks can get in each other's way by deleting things
before the other task gets a chance to do so. This pops up as a problem
primarily for the RPM plugin.
closes #3030
(cherry picked from commit 5685e59b4c34a80d220c5d8c786d08b765e987b1)
> [3.16] Serialize orphan cleanup tasks to prevent them from overlapping

- CHANGES/3030.bugfix
- pulpcore/app/views/orphans.py
- pulpcore/app/viewsets/orphans.py
Orphan cleanup tasks can get in each other's way by deleting things
before the other task gets a chance to do so. This pops up as a problem
primarily for the RPM plugin.
closes #3030
(cherry picked from commit 5685e59b4c34a80d220c5d8c786d08b765e987b1)
> Serialize orphan cleanup tasks to prevent them from overlapping

- CHANGES/3052.bugfix
- CHANGES/3054.bugfix
- pulpcore/content/handler.py
Fixes 500 error when 'range' header is negative for 'on-demand' content.
Fixes an incomplete response error when 'range' header start value is greater than size of file.
fixes: #3052
fixes: #3054
> Fixes two bugs related to 'range' headers with 'on-demand' content

- CHANGES/3056.bugfix
- pulpcore/app/urls.py
- pulpcore/app/viewsets/base.py
- pulpcore/app/viewsets/content.py
- pulpcore/app/viewsets/publication.py
- pulpcore/app/viewsets/repository.py
The property that it was, was never evaluated, because the routing tree
is determinded with viewset classes and not instances.
fixes #3056
> Changed routable on viewsets to be a classmethod

- .github/workflows/scripts/before_install.sh
- CHANGES/3055.bugfix
- pulpcore/content/handler.py
This patch fixes a bug that would occur when a client would submit a Range with
an end value that is greater than size of on-demand content.
fixes: #3055
> Set the correct value for Content-Length for Range requests

- CHANGES/2952.feature
- pulpcore/app/viewsets/custom_filters.py
- pulpcore/app/viewsets/publication.py
> Enable filtering by content

- CHANGES/3088.feature
- pulpcore/download/base.py
Add ``debug`` log line to check which URL is used to download file.
Helpful to test ACS.
closes: #3088
https://github.com/pulp/pulpcore/issues/3088
> Log downloader URL

- CHANGES/3111.bugfix
- pulpcore/plugin/stages/content_stages.py
Note to Future Self: Nested atomic-transactions are more painful than
one might think.
fixes #3111.
[nocoverage]
> Reworked content_stages bulk_update() deadlock fix.

- CHANGES/3111.bugfix
- pulpcore/plugin/stages/content_stages.py
Note to Future Self: Nested atomic-transactions are more painful than
one might think.
fixes #3111.
[nocoverage]
(cherry picked from commit 609ad733b75198463291f7c45598f0af29d37d11)
> [3.14] Reworked content_stages bulk_update() deadlock fix.

- CHANGES/3115.feature
- docs/components.rst
- docs/configuration/settings.rst
- pulpcore/app/settings.py
- pulpcore/app/tasks/telemetry.py
- pulpcore/app/util.py
By default Pulp systems will now submit anonymous telemetry information
to https://analytics.pulpproject.org/. It documents exactly what is
submitted, and introduces the `TELEMETRY` setting which can be used to
disable anonymous telemetry submission entirely.
closes #3115
> Enable telemetry for users

- CHANGES/2530.feature
- pulpcore/app/viewsets/__init__.py
- pulpcore/app/viewsets/repository.py
All remotes can now be listed at /pulp/api/v3/remotes/, which works
the same as listing distributions at /pulp/api/v3/distributions/.
closes #2530
> Endpoint for listing all Remote objects

- CHANGES/1920.feature
- CHANGES/plugin_api/1920.feature
- docs/plugins/plugin-writer/concepts/subclassing/import-export.rst
- docs/workflows/import-export.rst
- pulpcore/app/modelresource.py
- pulpcore/app/models/repository.py
- pulpcore/app/serializers/importer.py
- pulpcore/app/tasks/importer.py
- pulpcore/app/viewsets/importer.py
- pulpcore/plugin/modelresources.py
As of this commit, repositories are identified as standard import/export resource objects. It allows the automatic creation of importing repositories that were not created beforehand or do not exist.
closes #1920
> Create missing repositories automatically on import

- .github/pull_request_template.md
I observed that no one (including our contributors) does read the pull
request's walkthrough. Almost all of us ignore the paragraph and do not
remove it when publishing a pull request. When reviewing pull requests
of our contributors, we still have to explain to them our workflows (e.g.,
add [noissue], link an issue number) in order to proceed further.
[noissue]
> Remove the pull request template for reading the documentation

- CHANGES/plugin_api/3081.feature
- docs/plugins/plugin-writer/concepts/subclassing/viewsets.rst
- pulpcore/app/serializers/content.py
Attempting to upload existing content now returns the href of the
existing unit instead of raising an exception, possibly also adding
the content into a specified repository if it was not there already.
To make this work for a specific plugin, the retrieve() function
has to be implemented in the content serializer specific for the
given plugin. This commit does not break the behavior of plugins
not containing this implementation yet in any way.
closes #3081
> Allow uploading existing content

- CHANGES/plugin_api/2997.doc
- docs/plugins/plugin-writer/concepts/index.rst
> Adds docs for plugin writers on declaring deps

- CHANGES/3213.bugfix
- pulpcore/app/tasks/telemetry.py
This commit fixes a bug where installations with at least one pre-release plugin installed were posting to the production telemetry site instead of the developer telemetry site.
closes #3213
> Prod telemetry site only receives production data

- pulpcore/app/models/__init__.py
- pulpcore/app/models/base.py
The other PR https://github.com/pulp/pulpcore/pull/3136 merges a change which which would result in some plugins desiring a new migration.  The migration isn't *necessary* for the plugin to work - it would work perfectly fine without it - but in terms of CI and development it might be annoying if not merged. 
The migration would reference this `pulp_uuid()` function provided by pulpcore 3.21, so in normal circumstances the plugin author would want to bump their minimum supported pulpcore version if they merged it, like we would with any other core feature that a plugin wants to leverage (e.g. RBAC).
However, since simply providing that function in pulpcore (without using it anywhere) only requires about 4 lines of absolutely trivial code and doesn't carry any risk (it would also be dead …
> Add stub implementation for pulp_uuid()

- CHANGES/2967.feature
- pulpcore/app/management/commands/add-signing-service.py
- pulpcore/app/management/commands/remove-signing-service.py
- pulpcore/tests/functional/api/test_signing_service.py
- pulpcore/tests/functional/gpg_ascii_armor_signing_service.py
The pulpcore-manager now supports command 'remove-signing-service' which allows for removing signing services specified by name and class.
closes #2967
> Added pulpcore-manager command for removing signing services

- CHANGES/2417.doc
- docs/configuration/applying.rst
- docs/configuration/settings.rst
This improves (and shortens) the documentation on:
* Applying settings in various ways using dynaconf (with examples).
* Which settings are required
closes #2417
> Improves docs on settings

- docs/plugins/plugin-writer/concepts/index.rst
The policy now doesn't consider the semver status of a dependency and instead recommends the upper bound be the latest compatible release. This allows dependabot to test each new release as it comes out.
[noissue]
> Revises docs on plugin writer dep declaration

- CHANGES/1949.bugfix
- CHANGES/3187.bugfix
- pulpcore/app/tasks/export.py
Fixed the fs exporter to handle the case where hardlink method was requested but pulp and export locations are in different partitions so can't share the same inode.
> Fixes #3187 - Fs exporter correctly handles hardlink across partitions

- CHANGES/3124.bugfix
- CHANGES/3244.bugfix
- pulpcore/content/handler.py
closes #3124
closes #3244
(cherry picked from commit 0219fa407707c1fefa7cf44f756e8b9464cd0f5a)
> Fixed content-disposition header for the object storage backend.

- pulpcore/tests/functional/api/test_tasking.py
- pulpcore/tests/functional/utils.py
Since we found that some tests from `pulp_file` not only needed a fixture from `pulpcore` but also make sense to be here, we decided to move those tests and a `download_file` utility into `pulpcore`.
You can follow the discussion that ended up into this PR [here](https://github.com/pulp/pulp_file/pull/845#pullrequestreview-1144801290)
And `pulp_smash` no more.
> [noissue] Moves some tasks tests from pulp_file into pulpcore.

- CHANGES/3284.bugfix
- pulpcore/plugin/stages/content_stages.py
In this episode, we teach content_stages to not do updates that aren't changing anything. This removes an entire class of potential-deadlocks from the overlapping-content path - we don't deadlock, because we have stopped acquiring locks for rows we don't actually need to change.
fixes #3284.
[nocoverage]
> Addressed another deadlock-window in overlapping-content-syncs path.

- CHANGES/2825.feature
- pulpcore/app/serializers/__init__.py
- pulpcore/app/serializers/base.py
- pulpcore/app/serializers/repository.py
- pulpcore/app/serializers/user.py
- pulpcore/tests/unit/serializers/test_repository.py
fixes: [pulp#2825](https://github.com/pulp/pulpcore/issues/2825)
> Add `write_only_fields` to RemoteSerializer

- CHANGES/3370.bugfix
- pulpcore/app/viewsets/exporter.py
Tests handled in pulp_file.
fixes #3370.
[nocoverage]
> Ensure that pulp-export correctly locks repos-being-exported.

- CHANGES/3269.bugfix
- requirements.txt
This should allow to work around an issue of pip-compile failing to find possible combinations of python packages to install when requesting pulpcore and pulp-certguard.
fixes #3269
> Adjust cryptography dependency

- CHANGES/3173.feature
- pulpcore/content/handler.py
This patch returns a 301 redirect when a requested path does not end in a / but should end in a /.
fixes: #3173
> Redirects user to a path that ends in /

- pulpcore/tests/functional/__init__.py
This should help unblock several CI's where tests accidentally share fixtures in an unsafe way.
Reusing server side fixtures is now limited to the same test class.
[noissue]
> Scope test cleanup fixtures by class

- CHANGES/3461.misc
- pulpcore/app/modelresource.py
Testing is covered by test_pulpimport in pulp_file and pulp_rpm.
fixes #3461.
[nocoverage]
> Fixed import-failure due to pulp_labels.

- pulpcore/tests/functional/utils.py
If pulp-smash is installed, we should use the exceptions from there.
[noissue]
> Fix existence of multiple PulpTaskError

- pulpcore/app/apps.py
- pulpcore/app/management/commands/datarepair-labels.py
- pulpcore/app/migrations/0098_pulp_labels.py
Pulpcore migrations can never depend on any migration from a plugin. It will lead to either circular dependencies or inconsistent history if a plugin is installed later.
To make the miration as smooth as possible, a post migrate hook was added to repair the labels as well as possible.
[noissue]
> Remove plugin dependencies from labels migration

- CHANGES/3495.bugfix
- pulpcore/app/apps.py
- pulpcore/app/management/commands/datarepair-labels.py
A not null constraint exception was risen when objects with and without labels of the same type existed. The fix will limit the update to only those objects that actually had labels.
fixes #3495
> Fix the label migration code

- CHANGES/plugin_api/3506.feature
- pulpcore/plugin/serializers/__init__.py
fixes: https://github.com/pulp/pulpcore/issues/3506
For Galaxy_ng repo management feature, in `pulp_ansible/CollectionRemoteSerializer`, we need to expose `last_sync_status` task. For that, we could reuse ~~`MinimalTaskSerializer`, but it's missing `error`~~ `TaskSerializer` field and it's not exposed in `pulpcore.plugin.serializers`
Related PR for `last_sync_status`: https://github.com/pulp/pulp_ansible/pull/1317
(see discussion: https://github.com/pulp/pulp_ansible/pull/1317#issuecomment-1375767586)
AAH issue: [AAH-2076](https://issues.redhat.com/browse/AAH-2076)
> Add TaskSerializer to pulpcore.plugin.serializers

- CHANGES/plugin_api/3368.doc
- CHANGES/plugin_api/3443.doc
- docs/plugin_dev/plugin-writer/concepts/index.rst
This adds docs for two situations:
* Guidance for zero downtime migrations
* tasking backwards compatibility requirements
closes #3368
closes #3443
> Zero downtime upgrade docs for plugin writers

- CHANGES/3413.bugfix
- pulpcore/app/serializers/exporter.py
- pulpcore/app/tasks/export.py
- pulpcore/app/viewsets/exporter.py
It accepts a start repository version and calculates what content artifacts need to get copied over.
> Enables FilesystemExporter to incrementally export rpms

- CHANGES/3584.misc
- pulpcore/app/serializers/base.py
This allows the serializers to be used without explicitely specifying an empty or dummy request in the context.
[noissue]
> Refactor linked serializer fields

- pulpcore/app/serializers/base.py
The refactor somehow broke pulp_container. Reverting the method how to achieve relative links, but keeping the refactor to a mixin here.
[noissue]
re #3584
> Fix linked related fields

- CHANGES/3590.bugfix
- pulpcore/openapi/__init__.py
Some clients that distinguish integer types can choke on large numbers without this.
fixes #3590
> Add format=int64 to integer fields in api spec

- CHANGES/3310.bugfix
- requirements.txt
Bumping dynaconf version for the given fix:
* Handle all failures when pwd does not exist. (https://github.com/dynaconf/dynaconf/pull/857)
Close #3310 and pulp/pulp-oci-images#404
> Bump dynaconf version

- CHANGES/plugin_api/3631.feature
- pulpcore/app/viewsets/custom_filters.py
This allows for plugins to define a custom field to filter pulp labels on. For example, a distribution filterset could add a filter for repository labels like so:
```
class MyFilterset(Filterset):
repository__label_select = LabelFilter(label_field_name="repository__pulp_labels")
```
closes #3631
> Allow customizing the field name on LabelFilter

- CHANGES/3654.bugfix
- pulpcore/content/handler.py
> Properly access artifacts of a generic content in handler.py

- pulpcore/tests/functional/__init__.py
pulp_rpm relies on this fixture.
[noissue]
> Taught download_content_unit() fixture about domains.

- CHANGES/3714.bugfix
- pulpcore/app/models/base.py
- pulpcore/app/models/repository.py
- pulpcore/app/serializers/base.py
- pulpcore/app/serializers/fields.py
- pulpcore/app/util.py
- pulpcore/app/viewsets/content.py
- pulpcore/app/viewsets/publication.py
- pulpcore/app/viewsets/repository.py
This ensures that when listing resources (for content, distributions, publications, remotes, and repositories) the number of DB queries does not increase as the number of objects increases. The optimization comes with two parts: one `select/prefetch_relating` the related fields & two using a utility function `get_model_for_pulp_type` (that I am also using in https://github.com/pulp/pulpcore/pull/3712/) to quickly find the appropriate viewset for the related object without having to call `cast`.
Here's an example of what these two optimizations achieve for `http /pulp/api/v3/content/?limit=100`:
(both optimizations, just the new utility optimization, original)
The `cast` calls for `DetailIdentityField` or `DetailRelatedField` were the biggest culprit for DB performance when doing large …
> Optimized DB queries for list endpoints

- CHANGES/3754.bugfix
- pulpcore/app/serializers/content.py
When two (or more) processes try to create the same content only one can call the "create" successfully so the other one needs to attempt the "retrieve" a second time.
fixes #3754
> Fix a race condition in content creation

- CHANGES/3530.bugfix
- pulpcore/app/tasks/purge.py
When an object could not be deleted, the purge task would fail. This has been reworked  so that the purge continues to delete other tasks and informs the user about tasks that could not be deleted.
fixes: #3530
> Reworked the task purge feature

- CHANGES/3711.bugfix
- pulpcore/app/serializers/base.py
- pulpcore/app/viewsets/task.py
fixes: #3711
`http /pulp/api/v3/tasks/?limit=100` with roughly ~200 tasks in the system (left optimized, right current):
`http /pulp/api/v3/tasks/sync_task_href/` (left optimized, right current):
The number of queries we are currently doing is greatly dependent on the number and type of created resources made during the task. Each repository-version made during a task adds roughly 9-10 queries to the endpoint. For systems performing many syncs & uploads browsing the task endpoint would cause serious hammering of the database.
> Optimize queries for task list endpoint

- CHANGES/2048.feature
- docs/configuration/settings.rst
- pulpcore/app/management/commands/rotate-db-key.py
- pulpcore/app/models/fields.py
- pulpcore/tests/unit/models/test_remote.py
Every line in the file referenced by settings.DB_ENCRYPTION_KEY will be available for decrypting encrypted database fields. Only the on in the first line (at the time of service startup) will be used for encryption. A rotate-db-key management command was added to help key rotation, as well as recipies in the documentation.
fixes #2048
> Add multiple key support to db encryption

- pulpcore/tests/unit/conftest.py
- pulpcore/tests/unit/download/test_factory.py
- pulpcore/tests/unit/stages/test_artifactdownloader.py
- pulpcore/tests/unit/stages/test_stages.py
- unittest_requirements.txt
This fixes some warnings from the seemingly unmaintained asynctest library, whose dependency thereby got removed.
[noissue]
> Refactored async unittests to use pytest-async

- CHANGES/plugin_api/3792.feature
- pulpcore/app/models/task.py
- pulpcore/app/tasks/analytics.py
- pulpcore/tasking/pulpcore_worker.py
- requirements.txt
> Update psycopg to version 3 

- CHANGES/3800.feature
- pulpcore/app/models/domain.py
- pulpcore/app/settings.py
- pulpcore/tests/functional/api/test_crud_domains.py
> Add pre delete hook to domain for orphans

- CHANGES.rst
Reverts pulp/pulpcore#3845
This was a mistake. It was in the proper release from the beginning.
> Revert "Fixup CHANGELOG"

- CHANGES/1917.feature
- pulpcore/app/serializers/task.py
- pulpcore/app/viewsets/task.py
- pulpcore/tests/functional/api/test_tasking.py
fixes: #1917
This is one way to go about solving this issue using values we already store from Roles. We could also add a new field to the `Task` model that is supplied using `django-currentuser` like how the original issue suggests, but I think this approach is easier (no migration!).
> Expose Task creator on serializer

- CHANGES/3737.bugfix
- pulpcore/app/tasks/importer.py
If an expected-reassembled-filename exists, ignore chunk-info and proceed with that file.
Test-coverage will be added in pulp_file once this is in a released version of pulpcore.
fixes #3737.
[nocoverage]
> Taught PulpImport to recover from previously-failed attempt.

- CHANGES/plugin_api/3817.feature
- CHANGES/plugin_api/3818.feature
- docs/plugin_dev/plugin-writer/concepts/index.rst
- docs/plugin_dev/plugin-writer/concepts/subclassing/pull-through.rst
- pulpcore/app/models/content.py
- pulpcore/app/models/repository.py
- pulpcore/content/handler.py
- pulpcore/tests/unit/content/test_handler.py
fixes: #3817
fixes: #3818
TODO:
> Add pull-through caching support for streaming metadata & multi-artifact content types

- CHANGES/plugin_api/3897.feature
- pulpcore/app/models/publication.py
- pulpcore/content/handler.py
Added Distribution.content_headers_for() and call it from inside Handler.response_headers().
This is in support of https://github.com/pulp/pulp_rpm/issues/2947
[noissue]
> Extensions to give plugins a chance to set specific content-headers.

- CHANGES/3869.bugfix
- pulpcore/app/monkeypatch.py
- pulpcore/app/tasks/export.py
Exports will be larger, but should be much faster. There were reports of large exports taking multiple days to complete due to the overhead incurred by compression.
closes #3869
> Use a more appropriate compression level for exports

- CHANGES/plugin_api/3798.misc
- pulpcore/app/models/repository.py
- pulpcore/content/handler.py
The repository model's latest_version function now has a separate asynchronous version called alatest_version.
fixes: #3798
> Provide async version of latest_version

- CHANGES/3945.bugfix
- pulpcore/content/handler.py
```
File "/usr/local/lib/python3.8/site-packages/pulpcore/content/handler.py", line 847, in _save_artifact
cas = list(content.contentartifact_set().select_related("artifact"))
TypeError: __call__() missing 1 required keyword-only argument: 'manager'
```
[noissue]
> Fix the use of content_artifact_set in handler

- CHANGES/plugin_api/3951.feature
- pulpcore/app/serializers/content.py
- pulpcore/plugin/serializers/content.py
- pulpcore/plugin/viewsets/content.py
Refactor the content serializers to reuse more code and share more features.
* Allow to implement 'retrieve' on all content serializers for multiple upload.
* Allow adding all content to a repository on creation.
* Validate that the content type matches the provided repository.
fixes #3951
> Bridge gaps between content serializer features

- CHANGES/3949.feature
- docs/configuration/settings.rst
- pulpcore/app/settings.py
- pulpcore/app/tasks/orphan.py
- pulpcore/app/util.py
- pulpcore/tasking/pulpcore_worker.py
Uploads and PulpTemporaryFiles are cleaned up. Set the *_PROTECTION_TIME settings to None in order to disable this behaviour.
fixes #3949
> Add cleanup tasks to remove stale objects

- CHANGES/3995.bugfix
- pulpcore/app/viewsets/replica.py
This operation requires no body.
fixes #3995
> Fix api schema for `upstream_pulps_replicate`

- CHANGES/3941.bugfix
- pulpcore/app/tasks/export.py
Look at https://github.com/pulp/pulpcore/issues/3941#issuecomment-1601977276 for more information
The initial approach was here https://github.com/pulp/pulpcore/pull/3942 where the code ended up looking exclusively  at the repodata directory which is not ideal in pulpcore. 
This PR tries to address the same issue by saying  all published metadata in a publication should get included automatically.
> Incremental export for file exporter will now include published metadata

- CHANGES/4051.bugfix
- pulpcore/app/tasks/export.py
The export logic [here](https://github.com/pulp/pulpcore/blob/main/pulpcore/app/tasks/export.py#L106-L161) does not correctly account for the start_repository_version for pass through publications like file publications. It seems to include everything in the export.
```python
if publication.pass_through:
relative_path_to_artifacts = {
ca.relative_path: ca.artifact
for ca in content_artifacts.select_related("artifact").iterator()
}
```
This PR tries to address that issue by also checking in the difference_content_artifacts list if a file/other pass through publication was provided.
fixes #4051
Bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=2172564
> Incremental Export fix for File/Pass Through publications

- CHANGES/2250.bugfix
- pulpcore/app/access_policy.py
Which occurs when making repeated large queries against the API service. The cache unintentionally was holding references to entire instances of views, which are substantial.
closes #2250
> Fix a significant memory leak

- CHANGES/4175.bugfix
- pulpcore/app/tasks/replica.py
> Moves TaskGroup.finish() to outside the loop in the replication task

- CHANGES/4068.bugfix
- pulpcore/app/settings.py
- pulpcore/app/tasks/importer.py
IMPORT_WORKERS_PERCENT is configurable in settings. We will
document/expose this in a future PR, to keep this one maximally
backportable. Default behavior remains "all workers".
fixes https://github.com/pulp/pulpcore/issues/4068.
> Taught import to be able to use less than all-available workers.

- CHANGES/4159.bugfix
- pulpcore/app/importexport.py
- pulpcore/app/tasks/export.py
> Taught export to insure de-duplicated Artifact.json.

- pulpcore/tests/functional/__init__.py
> Remove custom pytest hook and move pytest markers from pulp-smash

- CHANGES/4210.bugfix
- pulpcore/app/importexport.py
- pulpcore/app/tasks/export.py
The QuerySet approach introduced a subtle bug the breaks pulp_rpm export. If we want to retain the 'good parts' of that approach, it will need to be its own investigation/PR.
fixes #4210.
> Reset export to using a set() for Artifacts.

- pulpcore/tests/functional/__init__.py
- pulpcore/tests/functional/utils.py
[noissue]
Open questions:
* Do we need to make the timeout configurable?
* How does this play with performance tests?
> Avoid infinite waiting on tasks in tests

- CHANGES/4183.bugfix
- pulpcore/app/serializers/base.py
fixes: #4183
Not sure how to write a test for this. I manually tested this with 
```
http :5001/pulp/api/v3/repositories/file/file/ name=foo & http :5001/pulp/api/v3/repositories/file/file/ name=foo
```
Roughly 1 in 3 attempts will fail with a 500 error, this fixes the race condition and will give a nice 400 error. 
@jlsherrill Interestingly you found this bug when creating domains, but it actually affects all immediate-creation objects in Pulp. :open_mouth:
> Fix 500 error on parallel same-object creates

- CHANGES/4028.bugfix
- pulpcore/constants.py
- pulpcore/content/handler.py
> Fixed content-handler response-headers/object-storage collision.

- CHANGES/plugin_api/4285.feature
- pulpcore/tasking/tasks.py
fixes: #4285
This might break other plugin tests if they expect reserved_resources to be empty for certain tasks. Need to do some testing.
> Always add current domain as a shared resource

- CHANGES/3969.bugfix
- pulpcore/app/models/repository.py
>>> timeit.timeit("len(v.get_content(Package.objects).only('pk'))", globals=globals(), number=10)
105.0813707895577
>>> timeit.timeit("len(v.get_content2(Package.objects).only('pk'))", globals=globals(), number=10)
58.41291802749038
>>> timeit.timeit("v.get_content(Package.objects).count()", globals=globals(), number=10)
62.557361379265785
>>> timeit.timeit("v.get_content2(Package.objects).count()", globals=globals(), number=10)
16.70007463544607
Credits to @newswangerd.
closes #3969
> Enhance get_content() by omitting the version_membership lookup

- CHANGES/4324.bugfix
- pulpcore/app/serializers/publication.py
When the serializer is not meant to perform a partial update, we should not consult the values in the intance for validation.
fixes #4324
> Fix Distribution serializer for PUT calls

- CHANGES/4157.bugfix
- pulpcore/app/models/domain.py
- pulpcore/exceptions/__init__.py
- pulpcore/exceptions/base.py
Fixed an exception that gets raised inside the domain delete hook when there is active content in the domain.
fixes: #4157
> Domain delete hook error fix

- CHANGES/4341.feature
- docs/plugin_dev/plugin-writer/concepts/index.rst
- pulpcore/tasking/entrypoint.py
- pulpcore/tasking/pulpcore_worker.py
This allows to run a pulpcore-worker in the foreground that will handle tasks until no more are available.
This can help to drain the task queue during an upgrade, or overcome a congestion short term.
fixes #4341
> Add burst mode to worker

- CHANGES/4372.bugfix
- docs/plugin_dev/plugin-writer/concepts/index.rst
- pulpcore/app/viewsets/base.py
- pulpcore/app/viewsets/exporter.py
- pulpcore/app/viewsets/repository.py
Deleting repositories casade deletes a lot of RepostoryVersions and RepositoryContent. This can easily extend beyond the gunicorn worker timeout.
fixes #4372
> Marked repository delete as unsafe for immetiate

- pulpcore/app/models/fields.py
According to Django's documentation, from_db_value is the reverse of get_prep_value. So we should also nest the super calls in the opposite direction.
[noissue]
edit: Also this was the version that ended up working both with Django 4.2 and in the backport with Django 3.2. Is that a reason to call it more correct? IDK.
> Refactor the encrypted fields

- CHANGES/4411.bugfix
- CHANGES/4434.bugfix
- pulpcore/app/monkeypatch.py
- pulpcore/app/tasks/export.py
Removes compression entirely, using the special gzip level 0 mode, which packs everything into a gzip archive without actually doing any compression.
The reason for this is that even the lowest level of compression, level 1, is still a massive cost without actually providing much benefits due to the fact that most of the exported artifact payloads (rpms, images, etc) are already compressed.
On a test system, the difference between exporting with gzip level 9 and completely uncompressed was 11.3gb vs 11.8gb, while the former took 2.5x as long.
For most major users of the import/export functionality, storage space is much less of an issue than runtime.
In the future we could do any of the following:
* make the compression level configurable for users who actually do care
* get rid of gzip …
> Remove compression from exports by default

- CHANGES/1936.bugfix
- pulpcore/plugin/stages/artifact_stages.py
fixes: #1936
This should help clean up a worker's directory during a sync and keep their storage usage down, especially for concurrent syncing when duplicate artifacts have been downloaded.
> Delete downloaded tmp files after Artifact creation during sync

- CHANGES/4437.bugfix
- pulpcore/filters.py
- pulpcore/tests/functional/api/test_filter.py
Fix bug where empty list for the `pulp_href__in` and `pulp_id__in` filters return all results instead of no results. The problem is that when using FilterMethod, django-filter just simply ignores empty set and returns the full list of results:
https://github.com/carltongibson/django-filter/blob/e4a70a667a0bf3882fd44b557bc76583d2c65cd1/django_filters/filters.py#L804-L805
There's no way to update the method to prevent this since this logic happens before the method is called. Instead, this change moves the method to the filter and adds a None check.
fixes #4437
> Handle empty list for href and id in filters

- requirements.txt
3.1.0 contains some performance improvements.
[noissue]
> Bump django-import-export dependency version for performance reasons

- CHANGES/4452.bugfix
- pulpcore/download/factory.py
- pulpcore/download/http.py
This flag causes large syncs to fail under certain circumstances, because the port range is used up too fast and reusing ports in time_wait is not appreciated by servers.
We cannot possibly fix all broken http servers in the wild.
fixes #4452
> Removed force_close from all downloaders

- pulpcore/tests/functional/utils.py
This is a fix that was added to pulp-smash but is missing here.
See more here:
https://github.com/pulp/pulp-smash/issues/1309
https://github.com/pulp/pulp-smash/commit/a18afe97de6a5e2eba5be737ceea068333ad3122
---
It also speeds up local testing (at least in `pulp_deb`) because it will no longer try to verify the encoding of extracted archive files 4 times before failing. Which looks like this:
```
9d1d6ce495d7 Giving up download_wrapper(...) after 4 tries (pulpcore.exceptions.validation.DigestValidationError: A file located at the url http://127.0.0.1:59071/debian-update/dists/ragnarok/jotunheimr/binary-armeb/Packages.gz failed validation due to checksum. Expected 'c3d96859b1edfce90bfb47928dad84b0616d9322d6df5a8a8a704d361ab78930', Actual …
```
> Avoid automatic encoding for fixture server

- pulpcore/app/settings.py
- pulpcore/app/tasks/export.py
- pulpcore/app/tasks/importer.py
- pulpcore/app/util.py
If a user enables the flag `_BACKWARDS_INCOMPATIBLE_FAST_EXPORTS` in the settings, the following will happen:
* Exports won't have any gzip wrapper at all.  This primarily improves imports as the gzip wrapper adds a bunch of internal crc32 checksum calculations that are totally unnecessary.
* The checksums used on export and import will be crc32 instead of sha256.  This makes a difference at scale when multiple terabytes are being processed.  
* Both kinds of exports are now supported on the import side transparently
When not bottlenecked on the database, these changes result in a 25-30% improvement in my testing of RHEL9 BaseOS + Appstream (48gb total).
> Allow older releases to opt-in to a faster mode of import/export

- CHANGES/4542.feature
- pulpcore/app/models/fields.py
> Allow whitespace and comments in db key file

- docs/components.rst
Add missing line-break before bullet list and fix mistyped reference link.
[noissue]
---
Obs:
* didn't add changelog entry because its trivial
* I've tested the new reference link locally and it points to the [correct link](https://docs.pulpproject.org/pulpcore/workflows/troubleshooting.html#debugging-tasks)
> Docs: fix formatting and reference link

- CHANGES/4591.bugfix
- pulpcore/app/models/repository.py
closes #4591
We still don't really "know":
* Why this only seems to happen on PG12
* Why the original query change (https://github.com/pulp/pulpcore/pull/4275/files) triggered this
* Why it only seems to happen on capsule syncs (this is most mysterious)
> Works around a sync-time performance regression on PG12

- CHANGES/plugin_api/4651.removal
- pulpcore/tasking/tasks.py
closes #4651
This should have been released in 3.40 but was accidentally overlooked.  We can safely remove it anyway because this isn't something you can really do by accident.
> Removed ability to call non-pulp functions as tasks

- CHANGES/plugin_api/4654.bugfix
- pulpcore/content/handler.py
Needed for pulp_python 3.40 compat release. Backport please :smiley: 
fixes: #4654
> Fix content handler failing to find published/content artifacts for index pages

- CHANGES/+pulpcore-worker-restart.feature
- pulpcore/tasking/entrypoint.py
> Add restart option pulpcore-worker

- CHANGES/2079.feature
- pulpcore/app/management/commands/repository-size.py
- pulpcore/app/models/repository.py
- pulpcore/tests/functional/api/test_repos.py
fixes: #2079
Some plugins (cough, cough RPM) will need to override the new property to get an accurate number for their repositories.
> Add new management command `repository-size` that calculates the size of artifacts stored in a repository

- CHANGES/4724.bugfix
- pulp_file/app/__init__.py
Status report of the pulp_file python_package must be pulp-file.
Technically this is still wrong, because it should be pulpcore, but we
will need another field to present the python module in order to be able
to generate the bindings.
[noissue]
> Fix pulp_file package name in status

- CHANGES/3829.feature
- pulpcore/content/__init__.py
- pulpcore/content/instrumentation.py
- pulpcore/tests/functional/__init__.py
- pulpcore/tests/functional/api/pulp_file/test_telemetry_collection.py
- pulpcore/tests/functional/api/test_status.py
The instrumentation code from the upstream PR was brought down to pulpcore because of https://github.com/pypi/support/issues/3353.
closes #3829
> Add instrumentation to content-app

- CHANGES/4766.bugfix
- CHANGES/plugin_api/4766.feature
- pulpcore/app/models/base.py
- pulpcore/app/viewsets/custom_filters.py
This change adds a `detail_model` property to the master-detail concept and removes a race condition by replacing calls to `cast` with it in `DistributionWithContentFilter`.
fixes #4766
> Fix a race condition in distribution filtering

- pulpcore/tests/unit/stages/test_stages.py
With the latest version of pytest-asyncio, async tests run with individual event loops, and so fixtures providing e.g. queues need to use the same loop.
[noissue]
https://pytest-asyncio.readthedocs.io/en/latest/reference/changelog.html#id11
> Fix async tests using unsafe fixtures

- CHANGES/4776.bugfix
- CHANGES/4806.bugfix
- pulpcore/app/tasks/repository.py
- pulpcore/tests/functional/api/pulp_file/test_domains.py
- pulpcore/tests/functional/api/using_plugin/test_repair.py
The 'current_domain' ContextVar was not getting coppied into the thread that was running the artifact
verification. The context is now explicitly copied into that thread.
This patch also adds repair API tests for S3 and Azure storage backends.
This patch also adds test assertions that a repository version repair task can be run in a non-default
domain.
fixes: #4776
fixes: #4806
> Fixes repository version repair API for non-default domains.

- CHANGES/2705.bugfix
- docs/workflows/repo-versioning.rst
- pulpcore/app/models/repository.py
- pulpcore/app/viewsets/repository.py
- pulpcore/constants.py
- pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
This change protects repo versions from being deleted up if their content is being served by distributions.
fixes #2705
> Protect distributed repo versions from deletion

- CHANGES/4777.bugfix
- pulpcore/app/serializers/exporter.py
- pulpcore/app/tasks/export.py
- pulpcore/app/tasks/importer.py
closes #4777
TODO: still working on the tests, it's a bit difficult to piece together how the fixtures interact...
> Fix division-by-zero on import

- .github/workflows/scripts/build_all_docs.sh
- pulpcore/__init__.py
- pyproject.toml
- staging_docs/index.md
- staging_docs/reference/main.md
- staging_docs/sections/development/guides/How to bind analysis trade..md
- staging_docs/sections/development/index.md
- staging_docs/sections/development/onboarding/About autonomous Model deployment.md
- staging_docs/sections/development/onboarding/On autonomous Database deployment.md
- staging_docs/sections/development/onboarding/On scalable Database ecossystem.md
- staging_docs/sections/development/onboarding/Understanding complex Model deployment.md
- staging_docs/sections/development/quickstart/01-doc-workflow.md
- staging_docs/sections/development/quickstart/02-code-workflow.md
- staging_docs/sections/getting_started/fundamentals/About autonomous Model deployment.md
- staging_docs/sections/getting_started/fundamentals/On autonomous Database deployment.md
- staging_docs/sections/getting_started/fundamentals/On scalable Database ecossystem.md
- staging_docs/sections/getting_started/fundamentals/Understanding complex Model deployment.md
- staging_docs/sections/getting_started/index.md
- staging_docs/sections/getting_started/quickstart/01-overview.md
- staging_docs/sections/getting_started/quickstart/02-setup.md
- staging_docs/sections/getting_started/quickstart/03-installation.md
- staging_docs/sections/getting_started/quickstart/04-configuration.md
- staging_docs/sections/getting_started/quickstart/05-deployment.md
- staging_docs/sections/getting_started/quickstart/06-conclusion.md
- staging_docs/sections/guides/index.md
- staging_docs/sections/learn/index.md
- staging_docs/sections/reference/01-repository-map.md
- staging_docs/sections/reference/02-glossary.md
- staging_docs/sections/reference/index.md
What this does:
- Add base/demo docs content on `/staging_docs` (index.md, overviews, etc)
- Update staging_docs publishing script to use `pulp-docs build` from [`pulp-docs`](https://github.com/pedro-psb/pulp-docs) package.
I've updated `pulp-docs` to fetch directly from main (not using the latest GH release), because otherwise we would have to wait each release to test if everything is okay. Regardless of the download method/strategy, if it puts the files in the right directory everything else should be the same.
> Integrate pulp-docs with staging-docs CI script

- CHANGES/4932.bugfix
- pulpcore/app/global_access_conditions.py
- pulpcore/tests/functional/api/pulp_file/test_rbac.py
> Casts a repository object before checking permission on it.

- requirements.txt
AAP 2.4 uses pulpcore 3.28.z and needs
dynaconf to be at least 3.2.4 to include
a fix for boolean parsing.
Previous versions of dynaconf would parse
```bash
export PULP_DEBUG=False
```
as a str `"False"` causing `if settings.DEBUG:` to evaluate to `True`
On 3.2.2, dynaconf [started parsing](https://github.com/dynaconf/dynaconf/pull/983) `False/True` string as booleans from envvars.
[noissue]
> fix: Bump dynaconf on 3.28.z

- CHANGES/3036.bugfix
- pulpcore/download/factory.py
- pulpcore/tests/functional/api/using_plugin/test_proxy.py
> Taught https-download to trust system certstore.

- pulpcore/tests/functional/__init__.py
This pytest flag used to be provided by pulp-smash, but we no longer want to depend on that. So we need to provide this functionality in the pulpcore pytest plugin. A safeguard is in place to not totally confuse pytest if pulp-smash happens to be installed anyway.
[noissue]
(cherry picked from commit c6135e81ae8aacd9c6dde092856d1a12bfdac8ab)
> Backport the `--nightly` pytest arg

- CHANGES/4589.misc
- pulpcore/tests/unit/test_chunked_file.py
Assure the methods tell, seek and read works as expected and raises with malformed chunks.
closes #4589
> Add unit tests to ChunkedFile class

- CHANGES/4603.feature
- docs/components.rst
- docs/index.rst
- docs/release_process.rst
- docs/tech_preview.rst
- pulpcore/app/models/domain.py
- pulpcore/app/util.py
- pulpcore/app/wsgi.py
- pulpcore/tasking/_util.py
- staging_docs/admin/learn/architecture.md
- staging_docs/admin/learn/tech-preview.md
> Start emitting disk usage metrics for domains

- CHANGES/plugin_api/5086.feature
- pulpcore/plugin/viewsets/__init__.py
- pulpcore/plugin/viewsets/content.py
- staging_docs/dev/learn/triage-needed!/concepts/subclassing/viewsets.md
closes #5086
Replaces https://github.com/pulp/pulpcore/pull/5084
> Add NoArtifactContentViewSet

- CHANGES/4637.bugfix
- pulp_file/pytest_plugin.py
- pulpcore/app/replica.py
- pulpcore/app/tasks/replica.py
- pulpcore/tests/functional/__init__.py
- pulpcore/tests/functional/api/test_replication.py
In case a distribution that is supposed to be subject to replication is referring to a publication (because it was created by someone else) we need to unset the publication field for the replicate task to succeed.
fixes #4637
> Fix replicate for a distribution with publication

- requirements.txt
[noissue]
(cherry picked from commit 6baa23f41fb5d46ac0d45050e7d319c3ca60f79d)
> Pin tablib<3.6 to not-break older versions of django-import-export.

- CHANGES.rst
There seem to have been some changelog entries with a link the should have had none. I suspect this happened due to rendering with an old version of towncrier where the feature was absent or broken.
[noissue]
> Removed dead links from changelog

- pulpcore/app/viewsets/custom_filters.py
I thought the issue was in the CLI, but after looking at the CLI code we don't use the old filter anymore. It seems the filter is always called even when the query isn't specified. Haven't check yet to see if this expected behavior of the filterset, but I think it might be.
> Ensure deprecation message on reserved-resources-record filter only shows when used

- .github/workflows/scripts/build_all_docs.sh
TLDR: because [Griffe looks for the package in the relative path by default](https://github.com/mkdocstrings/griffe/blob/01da648b10aca57d316e74e4b0eef2ca31e92f32/src/griffe/loader.py#L182-L185) (and mkdocstring uses that unchanged), the wrong package is discovered instead the one I've defined programmatically if I'm in A Folder Called Pulpcore.
[noissue]
> Temporary fix for staging-docs build

- .github/workflows/staging-docs.yml
Now that every repository has a staging-docs setup, we want to have the published staging-docs website automatically up-to-date with upcoming changes.
[noissue]
> Make staging-docs publish workflow run nighly

- CHANGES/5243.feature
- pulpcore/app/views/status.py
- pulpcore/tests/functional/api/test_status.py
drf-spectacular doesn't support HEAD requests. That's why this change doesn't have any OpenAPI schema related changes.
https://github.com/tfranzel/drf-spectacular/issues/684
closes: #5243
> Adds HEAD support to Status API

- CHANGES/5199.bugfix
- pulpcore/app/models/upload.py
- pulpcore/tests/functional/__init__.py
- pulpcore/tests/functional/api/test_upload.py
The mixin for automatic calling of creation hooks was missing on the Upload model.
fixes #5199
> Fix creation hooks being called for Upload

- CHANGES/5243.feature
- pulpcore/app/views/status.py
- pulpcore/tests/functional/api/test_status.py
This reverts commit c9cd57bc5ad23a0e8efb7a599b4f076e7f4d25d4.
I was hoping to use this as a livenessProbe in kubernetes but only GET requests are supported for that. Let's remove this before we release it.
> Revert "Adds HEAD support to Status API"

- docs/plugin_dev/plugin-writer/concepts/index.rst
- pulpcore/app/settings.py
- staging_docs/dev/learn/triage-needed!/concepts/index.md
The documentation URLs under https://dynaconf.readthedocs.io/ cause 404 since they were moved to under https://www.dynaconf.com/.
This PR replaces the old URLs with new one.
[noissue]
> docs: correct outdated urls for dynaconf docs

- CHANGES/4592.misc
- pulpcore/app/models/domain.py
- pulpcore/app/serializers/domain.py
This change will also allow me to add GCP support for domains since the `credentials` setting requires a Google object.
> Add support for transfer_config in S3 domain serializer

- .github/workflows/scripts/build_all_docs.sh
The workaround was fixed by mkdocstrings-python 1.9.1 and pulp-docs pinned its dependencies to >=1.9.1
test run on my fork: https://github.com/pedro-psb/pulpcore/actions/runs/8665626487/job/23764717948#step:4:792
pulp-docs-pin: https://github.com/pulp/pulp-docs/pull/37 (just to assure future depsolving won't break us)
[noissue]
> Remove docs-build workaround

- CHANGES/plugin_api/5267.bugfix
- pulpcore/app/models/access_policy.py
- pulpcore/tests/unit/models/test_base.py
When e.g. pulp_container uses a subclass of Upload, we do not want the post create hook to fail. So we just ignore if a viewset cannot be found for the model.
fixes #5267
> Stop failing the post_create hooks with no viewset

- template_config.yml
> Per core-team mtg, remove 3.18/45 from "supported" list.

- CHANGES/5243.feature
- pulpcore/app/urls.py
- pulpcore/app/views/__init__.py
- pulpcore/app/views/status.py
- pulpcore/tests/functional/api/test_status.py
This API is intended to be used as the livenessProbe for the API workers runnign on Kubernetes.
closes #5243
> Adds a Liveness API

- setup.py
Reverts pulp/pulpcore#5326
[noissue]
> Revert "[noissue]: Update django-storages[google] requirement from <=1.14.2,>=1.13.2 to >=1.13.2,<=1.14.3"

- CHANGES/5318.bugfix
- pulpcore/content/handler.py
fixes: #5318
Like the issue said in the template we used to ignored the `None` sizes with the previous if condition, but now that we don't we should filter out the nulls. We can't really test this in pulp_file since on_demand syncs always know what the size of the artifact will be. Only in other plugins were they don't know can this bug be tested.
> Fix content directory list 500 when RemoteArtifact had null size

- CHANGES/5363.bugfix
- pulpcore/tasking/_util.py
These shared objects that may not even have been created by that task must only ever be deleted inside of orphan cleanup. That's the rule.
fixes #5363
> Stop task cleanup to delete Contents and Artifacts

- CHANGES/5375.bugfix
- pulpcore/app/importexport.py
- pulpcore/app/tasks/export.py
> Fix large exports failing

- CHANGES/5462.misc
- pulpcore/app/checks.py
- pulpcore/app/management/commands/openapi.py
- pulpcore/app/settings.py
- pulpcore/tests/unit/test_settings.py
- unittest_requirements.txt
This allows to generate api.json files without starting the whole infrastructure.
fixes #5462
(cherry picked from commit cce64770f562d5e80fc89b06086258630d0c7ab8) (cherry picked from commit eb61f2184bde61df2da773c1da7637cb8e8e536c)
> Add openapi command to pulpcore-manager

- CHANGES/5464.bugfix
- pulpcore/app/replica.py
Pulpcore no longer assumes that every plugin which implements support for the Replication feature supports publications (e.g. container doesn't).
closes #5464
> Replica - stop assuming every plugin supports publications

- CHANGES/5510.bugfix
- pulpcore/app/checks.py
- pulpcore/app/settings.py
This helps circumventing issues where plugins rely on the setting, but a command is bypassing the checks.
fixes #5510
> Add a sentinal value to CONTENT_ORIGIN

- staging_docs/index.md
This index page is not the website index page (that lives in pulp-docs).
This is the presentation page that is opened when you click on a plugins name.
See https://pulpproject.org/pulp-docs/docs/dev/guides/create-plugin-overviews/
I've used the content from the legacy website with slight modifications and link updates.
[noissue]
I took some time to realize that, but there is a rich diff for previewing markdown:
> Update pulpcore index page

- pulpcore/tests/functional/utils.py
We're trying to debug a test failure in the CI that we can't reproduce locally:
https://github.com/pulp/pulp_deb/actions/runs/9898615528/job/27345874499?pr=1061#step:15:3505
Part of the challenge in debugging this is that there's not enough information to go on because the CI is only outputting the task error description. Not sure if there's a better way to handle this but in these cases it seems like printing the entire task details somehow would be more helpful.
[noissue]
> Provide more task info during test failures

- CHANGES/5563.bugfix
- pulpcore/app/templatetags/pulp_urls.py
- pulpcore/tests/unit/test_pulp_urls.py
Also now correctly escapes JSON values for the web.
fixes #5563.
(cherry picked from commit 672a6233d210f62fc4c407531461d6e13012ab67)
> Fix urlize_quoted_hrefs() to make links again.

- .github/workflows/scripts/publish-staging-docs.sh
The current `rsync` command only adds new content to the server, it doesn't remove old files that are no longer being built. Because of that, we have left-overs from older build, such as https://pulpproject.org/pulp-cli/changes/changelog/
The `--delete` option deletes files in <target> that are not present in <source> anymore ([reference](https://explainshell.com/explain?cmd=rsync+--delete)).
**DISCLAIMER:** I've barely used rsync in my life
> Fix old content being persistent on the website server

- requirements.txt
Reason: [3.2.6](https://github.com/dynaconf/dynaconf/releases/tag/3.2.6) comes with important performance fix.
[noissue]
The problem was only observed if the application enabled Access Hooks (enabled on galaxy_ng to alter hostname settings upon access)
Before
```
$ time curl -s http://localhost:5001/api/galaxy/v3/openapi.json 2>&1 > /dev/null
real    0m41.374s
user    0m0.012s
sys     0m0.008s
```
After
```
$ time curl -s http://localhost:5001/api/galaxy/v3/openapi.json 2>&1 > /dev/null
real	0m2.969s
user	0m0.003s
sys	0m0.006s
```
> Bump Dynaconf UB to <3.3.0

- requirements.txt
Reason: 3.2.6 comes with important performance fix.
[noissue]
(cherry picked from commit fd6c397783b84c584fd53cb35ce45e0ab3a3f64d)
> [3.49]Bump Dynaconf UB to <3.3.0

- CHANGES/5337.feature
- docs/static/task-status-v1.yaml
- pulpcore/app/serializers/task.py
- pulpcore/app/settings.py
- pulpcore/tasking/kafka.py
- pulpcore/tasking/tasks.py
- requirements.txt
- staging_docs/admin/guides/integrate-kafka.md
- staging_docs/admin/reference/settings.md
To try locally, you can use the oci-env kafka profile from pulp/oci_env#159.
Set up the oci-env to use the kafka profile:
```
COMPOSE_PROFILE=kafka
```
From a fresh oci-env pulp instance, try:
```shell
export REPO_NAME=$(head /dev/urandom | tr -dc a-z | head -c5)
export REMOTE_NAME=$(head /dev/urandom | tr -dc a-z | head -c5)
oci-env pulp file repository create --name $REPO_NAME
oci-env pulp file remote create --name $REMOTE_NAME \
--url 'https://fixtures.pulpproject.org/file/PULP_MANIFEST'
oci-env pulp file repository sync --name $REPO_NAME --remote $REMOTE_NAME
```
Then inspect the kafka message that is produced via:
```shell
oci-env exec -s kafka \
/opt/kafka/bin/kafka-console-consumer.sh \
--bootstrap-server=localhost:9092 \
--offset earliest \
--partition 0 \
--topic …
```
> Add kafka producer to send task status messages

- CHANGES/5619.bugfix
- pulpcore/app/global_access_conditions.py
This change is similar to #4933, but for the condition function where domain is not enabled.
[noissue]
fixes: #5619
> Casts a repo object before checking permission

- CHANGES/plugin_api/5633.bugfix
- pulp_file/tests/functional/api/test_crud_content_unit.py
- pulpcore/plugin/serializers/content.py
Change the field name `url` to `file_url` to avoid conflict. In pulp-rpm there's already a Package field `url` that is causing problems.
fixes #5633
> Change url field name to avoid plugin conflicts

- CHANGES/+deferred_task_args.feature
- pulpcore/app/models/task.py
- pulpcore/tasking/_util.py
Encrypted task args are no longer loaded and decrypted in codepaths that take no care in them. This can also help to clean up broken tasks in case the encryption key was lost.
[noissue]
> Defer loading task args

- .gitleaks.toml
> Correct the gitleaks.toml to use (correctly) paths instead of files.

- .github/workflows/all-docs.yml
The name of the uploaded artifact did not quite match the one attempted to be downloaded.
[noissue]
> Fix up docs workflow

- CHANGES/5478.doc
- docs/admin/guides/auth/external.md
> Update REMOTE-USER header definition in doc

- CHANGES/5683.bugfix
- pulpcore/app/models/task.py
- pulpcore/app/viewsets/task.py
- pulpcore/tasking/_util.py
- pulpcore/tests/functional/api/test_tasking.py
fixes: #5683
https://access.redhat.com/security/cve/cve-2024-7143 (cherry picked from commit 20cffca49de5f3bfac44e0160c1f0fb262141ea5)
> Fix incorrect RBAC permissions in object creation tasks

- CHANGES/5687.feature
- pulpcore/app/serializers/publication.py
> Exposed `no_content_change_since` on the distribution serializer

- docs/admin/guides/auth/external.md
- docs/admin/guides/sign-metadata.md
- docs/admin/reference/settings.md
- docs/dev/guides/git.md
- docs/dev/guides/plugin-walkthrough.md
- docs/dev/learn/domains/domains_compatibility.md
- docs/dev/learn/other/content-protection.md
- docs/dev/learn/other/how-to-doc-api.md
- docs/dev/learn/other/metadata-signing.md
- docs/dev/learn/other/on-demand-support.md
- docs/dev/learn/plugin-concepts.md
- docs/dev/learn/rbac/access_policy.md
- docs/dev/learn/rbac/adding_automatic_permissions.md
- docs/dev/learn/rbac/index.md
- docs/dev/learn/rbac/permissions.md
- docs/dev/learn/rbac/queryset_scoping.md
- docs/dev/learn/rbac/users_groups.md
- docs/dev/learn/subclassing/models.md
- docs/dev/learn/subclassing/viewsets.md
- docs/dev/learn/sync_pipeline/sync_pipeline.md
- docs/dev/learn/tasks/add-remove.md
- docs/reference/api-reference/download.md
- docs/user/guides/create-domains.md
This does:
- On dev rbac pages
- re-linked links that were not converted and were in the format `` `some-link` ``
- added some code reference links with `[path.to.module][]`. Will work more on this on other PR
- Fixed general admonitions with wrong indent level.
Fixes some of https://github.com/pulp/pulpcore/issues/5496
> General admonition fixes on docs

- pulpcore/tests/functional/api/test_workers.py
The timing in the task schedule tests seems to be a bit tight, leading to a flakey test. By adding two extra seconds waiting time, the test should be reliable again.
[noissue]
> Backport task schedule test improvement

- docs/admin/reference/settings.md
This function is essentially `get_random_secret_key` from Django, extracted to a standalone function. Django [switched](https://github.com/django/django/commit/1d0bab0bfd77edcf1228d45bf654457a8ff1890d) from `random.choice` to `secrets.choice` with Django 3.0. Probably because the secrets module is only available on Python 3.6+.
> Use secrets.choice for SECRET_KEY documentation sample

- CHANGES/+task_cancelling.bugfix
- pulpcore/app/models/task.py
This will log the task pk as well as the original state. Also it is now considered an OK situation if a cancelling task was attempted to be completed by it's worker.
> Fixed logging issues with task state transitions

- CHANGES/5048.bugfix
- pulpcore/app/models/publication.py
- pulpcore/app/models/repository.py
- pulpcore/tests/functional/api/using_plugin/test_crud_repos.py
Django handles cascade deletes itself (as opposed to letting the database handle it) and in doing so it pulls a lot of data out, resulting in a memory spike on repository deletion.
The only solution is to write a custom cascade delete that deletes the objects at the bottom of the cascade tree more incrementally.
closes https://github.com/pulp/pulpcore/pull/2280
> Fix memory spike on repository delete

- docs/dev/learn/plugin-concepts.md
According to Matrix discussion, it sounds like Pulp already supports zero-downtime upgrades. I'm updating the docs to be more clear about this.
> Clarify zero-downtime upgrade docs

- CHANGES/5686.bugfix
- pulp_file/pytest_plugin.py
- pulp_file/tests/functional/api/test_sync.py
- pulpcore/download/http.py
- pulpcore/pytest_plugin.py
> Fix URL encoding issue in HttpDownloader to handle special characters

- CHANGES/5807.doc
- docs/dev/guides/test-pulp.md
I think these ought to be documented. It would greatly have simplified getting the tests running for us.
> Document the environment variables used in bindings_cfg()

- CHANGES/3634.bugfix
- pulpcore/app/viewsets/custom_filters.py
- pulpcore/app/viewsets/publication.py
- pulpcore/app/viewsets/repository.py
- pulpcore/tests/functional/api/test_openapi_schema.py
- pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
> Fix content__in filter

- CHANGES/5686.bugfix
- pulp_file/pytest_plugin.py
- pulp_file/tests/functional/api/test_sync.py
- pulpcore/download/http.py
- pulpcore/pytest_plugin.py
Reverts pulp/pulpcore#5809
Per comment (https://github.com/pulp/pulpcore/pull/5809#issuecomment-2368283179) this was breaking already existing functionality, we need to think some more about this.
> Revert "Fix URL encoding issue in HttpDownloader to handle special characters"

- CHANGES/5766.feature
- docs/dev/learn/subclassing/serializers.md
- pulpcore/app/serializers/__init__.py
- pulpcore/app/serializers/base.py
- pulpcore/app/serializers/task.py
- pulpcore/app/serializers/user.py
- pulpcore/app/util.py
- pulpcore/app/viewsets/__init__.py
- pulpcore/app/viewsets/base.py
- pulpcore/app/viewsets/custom_filters.py
- pulpcore/app/viewsets/publication.py
- pulpcore/app/viewsets/repository.py
- pulpcore/filters.py
- pulpcore/plugin/serializers/__init__.py
- pulpcore/plugin/util.py
- pulpcore/pytest_plugin.py
- pulpcore/tests/functional/api/test_openapi_schema.py
- pulpcore/tests/functional/api/using_plugin/test_prn.py
- pulpcore/tests/functional/api/using_plugin/test_tasks.py
- pulpcore/tests/unit/serializers/test_domain.py
- pulpcore/tests/unit/serializers/test_repository.py
> Add PRN support

- pulpcore/tasking/tasks.py
We have an alerting system that parses pulp worker logs and alerts us when things like publishing a repo fails. The problem is that also alerts us when a package is uploaded that's not valid (which we don't care about). In order to differentiate between user errors like ValidationError and system errors, it'd be helpful to log the task type and exception type.
> Log more info when a task fails

- CHANGES/5817.bugfix
- pulpcore/cache/cache.py
- pulpcore/content/handler.py
- pulpcore/metrics.py
The caching machinery stores all headers from the response coming from content-handler. With this commit, we are introducing an proprietary header that contains the size of the served artifact or artifact available after the redirect, X-PULP-ARTIFACT-SIZE.
closes #5817
> Collect artifact size metrics after caching the content

- CHANGES/pulp_file/5686.bugfix
- pulp_file/app/tasks/synchronizing.py
- pulp_file/tests/unit/test_safe_paths.py
closes #5686
Simiilar to https://github.com/pulp/pulp_deb/blob/b146fad9d894aeab89fe583a4fb60220a270744f/pulp_deb/app/tasks/synchronizing.py#L623 to quote the URL path.
> Fix URL encoding issue in pulp_file

- CHANGES/5864.bugfix
- pulpcore/app/wsgi.py
In addition to that, this commit fixes the attribute's name used for reporting the name of the worker process.
closes #5864
> Emit the name of the Pulp service in all default metrics

- CHANGES/5879.bugfix
- pulpcore/content/handler.py
> Propagate response headers when using Azure, S3 or GCP storage

- CHANGES/5881.bugfix
- pulpcore/app/tasks/purge.py
When a task was dispatched by a task schedule, there is no user attached to it. So purge tasks should just look at all tasks. However when a user gets deleted after dispatching that task, the task will run with current_user=None also. We need to make sure not to purge too many tasks in this case.
fixes #5881
> Fix scheduled task purge failing without user

- CHANGES/5911.bugfix
- pulpcore/app/models/content.py
A signing script usually needs to access `GNUPGHOME`, `HOME` and possibly other variables.
fixes #5911
> fix: Signing scripts needs access to environment variables.

- CHANGES/plugin_api/5912.bugfix
- pulpcore/download/base.py
> Have downloads always end up under WORKING_DIRECTORY

- pulpcore/app/management/commands/migrationstat.py
- pulpcore/app/management/commands/rebasemigrations.py
This is a precurser for merging pulpcore migrations. It helps to rebase the external dependencies in all of a plugins migrations onto a minimum migration in e.g. pulpcore.
As with makemigrations this is soley useful for developers.
> Add rebasemigration as a management command

- CHANGES/+fix-any-type.bugfix
- pulpcore/app/serializers/domain.py
- pulpcore/app/serializers/exporter.py
- pulpcore/app/serializers/fields.py
- pulpcore/app/serializers/importer.py
- pulpcore/app/serializers/task.py
See https://github.com/pulp/pulp_rpm/issues/3639
> Fix Any serializer type regression breaking Ruby bindings

- CHANGES/+fix-any-type.bugfix
- pulpcore/app/serializers/exporter.py
- pulpcore/app/serializers/fields.py
- pulpcore/app/serializers/importer.py
- pulpcore/app/serializers/task.py
See https://github.com/pulp/pulp_rpm/issues/3639
(cherry picked from commit 58425d791296752be427a43cda9df0d2403bc7bc)
> [PR #5936/58425d79 backport][3.22] Fix Any serializer type regression breaking Ruby bindings

- CHANGES/+fix-any-type.bugfix
- pulpcore/app/serializers/exporter.py
- pulpcore/app/serializers/fields.py
- pulpcore/app/serializers/importer.py
- pulpcore/app/serializers/task.py
See https://github.com/pulp/pulp_rpm/issues/3639
(cherry picked from commit 58425d791296752be427a43cda9df0d2403bc7bc)
> [PR #5936/58425d79 backport][3.21] Fix Any serializer type regression breaking Ruby bindings

- requirements.txt
This is supposed to allow consuming a bug in creating the caching key.
> Allow aiohttp <3.10.11

- docs/user/guides/create-domains.md
> Document S3 operations that the AWS access key must be able to perform

- pulpcore/tests/functional/api/using_plugin/test_repair.py
This change unblocks the functional pulp_file repair tests when run on a python 3.11+ environment. Stronger typing for the random.sample function is introduced in 3.11 and requires now a Sequence type as an input or it will throw a TypeError.
see: https://docs.python.org/3.11/library/random.html#random.sample
[noissue]
> Future proof the pulp_file repair tests for python 3.11

- CHANGES/plugin_api/cache-key.feature
- pulpcore/plugin/util.py
cache_key handles domains correctly so plugins using the cache should use this method.
Side question: can we backport additions to the plugin-api?
> Add cache_key to the plugin api

- CHANGES/content-assert.bugfix
- pulpcore/app/models/repository.py
We allow plugins to pass in either a `Content` query or a queryset of `content_ids`, e.g. `RepositoryContent.objects.values_list("content_id")`
> Fix cross-domain content assertion

- pulpcore/download/factory.py
Bumping this req broke Pulp, but only when using the downloader outside of a coroutine, which some plugins do (pulp_container).
(from commit 3b0d218af8ddf97a1d5831dd8cab080194c0c768)
> Finish backporting aiohttp 3.10 bump

- CHANGES/5967.bugfix
- pulpcore/content/handler.py
A user reported that after changing the host and resyncing they would have some some leftover RAs with the invalid url, and that would raise an aiohttp.client_exceptions.ClientConnectionError.
Because that is not a retriable error for content streaming, the right RA wouldnt be tried afterwards.
Closes: #5967
---
We should probably backport these to supported branches.
> Add ClientConnectionError as retriable exception on content-app streaming

- CHANGES/5012.bugfix
- pulp_file/pytest_plugin.py
- pulpcore/content/handler.py
- pulpcore/tests/functional/api/using_plugin/test_content_delivery.py
Because of a design choice of streaming chunk-by-chunk as we receive it from the Remote (to minimize response time and allow only-stream workflow), as soon as we receive the first chunk, all http headers are already sent and we can't roll that back anymore (for example, set a 404).
We could let the user find out about that, but we prefer to prevent it from unecessarily saving/validation something we know is wrong. Because of that, we choose to close the TCP connection and raise a more helpful message on Pulp logs targeted at admins.
fixes #5012
> [SAT-22998] Ensure Pulp closes the connection on corrupted streamed content

- CHANGES/6053.bugfix
- pulpcore/app/entrypoint.py
- pulpcore/content/entrypoint.py
Both content and api worker allow to specify --bind multiple times now.
fixes #6053
> [PULP-205] Allow multiple bind addresses on entrypoints

- CHANGES/5012.bugfix
- pulp_file/pytest_plugin.py
- pulpcore/content/handler.py
- pulpcore/tests/functional/api/using_plugin/test_content_delivery.py
Assuming we want to keep our stream-redirect approach on the content-app, We cant recover from wrong data already sent if the Remote happens to be corrupted (contains wrong binaries).
In order to not give a 200 reponse to client, we decided to close the connection as soon as the request handler realizes the checksum is wrong.
That only happens after we already sent the whole blob minus EOF, so we close the connection before sending the EOF.
Additionally, we put some message on the logs for admins to see and have a chance to manually fix the remote/remote_artifacts.
Co-authored-by: Matthias Dellweg <2500@gmx.de>
fixes #5012
(cherry picked from commit 5801bf9766c67b68d2dcbce423b9421dd73ffdbd)
> [PR #6026/5801bf97 backport][3.49] [SAT-22998] Ensure Pulp closes the connection on corrupted streamed content

- CHANGES/5012.bugfix
- pulp_file/pytest_plugin.py
- pulpcore/content/handler.py
- pulpcore/tests/functional/api/using_plugin/test_content_delivery.py
Assuming we want to keep our stream-redirect approach on the content-app, We cant recover from wrong data already sent if the Remote happens to be corrupted (contains wrong binaries).
In order to not give a 200 reponse to client, we decided to close the connection as soon as the request handler realizes the checksum is wrong.
That only happens after we already sent the whole blob minus EOF, so we close the connection before sending the EOF.
Additionally, we put some message on the logs for admins to see and have a chance to manually fix the remote/remote_artifacts.
Co-authored-by: Matthias Dellweg <2500@gmx.de>
fixes #5012
(cherry picked from commit 5801bf9766c67b68d2dcbce423b9421dd73ffdbd)
> [PR #6026/5801bf97 backport][3.63] [SAT-22998] Ensure Pulp closes the connection on corrupted streamed content

- pulpcore/app/settings.py
- pulpcore/app/tasks/replica.py
- pulpcore/download/factory.py
- requirements.txt
backport #5658 to 3.49
Fix pkg_resources (deprecated) error when loading extra requirements.
Required to be able to merge https://github.com/ansible/django-ansible-base/pull/656 on galaxy_ng
Will require a new patch release.
> Backport #5658 to 3.49

- CHANGES/+core_in_bindings_spec.feature
- pulpcore/openapi/__init__.py
This is supposed to help select proper bindings generator based on the version of pulpcore used.
> Always add core version to the api spec

- CHANGES/5937.bugfix
- pulpcore/content/handler.py
- pulpcore/download/http.py
https://github.com/pulp/pulpcore/issues/5937
I dont know how to write an automated test for that, but I've asserted it through logs by running the `test_remote_content_changed_with_on_demand`, which causes a digest validation error in the on-demand streaming context.
**Before**:
```
[pulp]  | (OMITED) "GET /pulp/api/v3/distributions/file/file/01936f14-21af-7102-b69b-65a30d34596e/ HTTP/1.0" 200 631 "-" "api/using_plugin/test_content_delivery.py::test_remote_content_changed_with_on_demand"',)
[pulp]  | Backing off download_wrapper(...) for 0.8s (pulpcore.exceptions.validation.DigestValidationError: A file located at the url https://127.0.0.1:44247/basic/2.iso failed validation due to checksum. Expected '89a0fbc35e07fe70fb46467326b6ab6a5bc53da48d518f3a6c6ef17dc3fab256', Actual …
```
> [PULP-208] Disable download retry with on demand streaming

- CHANGES/plugin_api/domain-get-create-serializer-mixin.bugfix
- pulpcore/app/serializers/base.py
- pulpcore/tests/unit/serializers/test_base.py
pulp_domain is not processed in model's serializer since the value is auto-set as a context var on request time. This helper method would run into serializer errors if pulp_domain was specified as a natural key (which you need to do when supporting domains).
> Fix GetOrCreateSerializerMixin not working with pulp_domain

- requirements.txt
This adjusts upper bounds of dependencies that were already bumped on the 3.49 branch.
> Update update dependencies to prevent downgrades from 3.49

- .ci/ansible/settings.py.j2
- CHANGES/5404.removal
- CHANGES/plugin_api/5404.removal
- pulp_file/tests/functional/api/test_download_policies.py
- pulpcore/app/apps.py
- pulpcore/app/checks.py
- pulpcore/app/importexport.py
- pulpcore/app/serializers/domain.py
- pulpcore/app/settings.py
- pulpcore/app/tasks/export.py
- pulpcore/app/util.py
- pulpcore/pytest_plugin.py
- pulpcore/tests/functional/api/test_artifact_distribution.py
- pulpcore/tests/functional/api/test_crd_artifacts.py
- pulpcore/tests/functional/api/test_crud_domains.py
- pulpcore/tests/functional/api/test_status.py
- pulpcore/tests/functional/api/using_plugin/test_orphans.py
- pulpcore/tests/unit/models/test_content.py
The setting [DEFAULT_FILE_STORAGE](https://docs.djangoproject.com/en/4.2/ref/settings/#default-file-storage) / [STATCIFILES_STORAGE](https://docs.djangoproject.com/en/4.2/ref/settings/#staticfiles-storage) was deprecated in django 4.2. They've implemented a compatibility layer to enable this legacy setting to be mapped to the new [STORAGES](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-STORAGES), so users could gradually move and Pulp codebase to update to using only STORAGES.
The problem is that Pulp overrides the default (using the legacy setting name), so users can't really use STORAGE, as it raises a django exceptions on mutual exclusion.
This PR does:
1. Updates the codebase to rely on settings.STORAGES instead of DEFAULT_FILE_STORAGE
2. Enable users to start using …
> [PULP-210] Update deprecated django storage config

- pulp_certguard/tests/functional/artifacts/x509/gensrv.sh
None of these scripts are even used AFAICT.  They're just for posterity sake alongside the certs and such that they were used to create.
> Quiet a lint warning about improper flag usage

- CHANGES/plugin_api/6077.removal
- pulpcore/app/replica.py
> Remove deprecated distribution_data on Replicator

- CHANGES/6225.bugfix
- pulpcore/tasking/worker.py
This is supposed to be a very rare corner case up to now only known to happen during a certian upgrade (where unblocked_at was introduced). Since someone decided to run such tasks already, it must be ok to mark them unblocked now.
> [PULP-296] Fixup running tasks that are not unblocked

- docs/admin/guides/_SUMMARY.md
- docs/admin/guides/configure-pulp/configure-storages.md
- docs/admin/guides/configure-pulp/index.md
- docs/admin/reference/settings.md
Depends on this to make sense: https://github.com/pulp/pulpcore/pull/6058
TODO:
- Better scope content that should go in pulpcore and in oci-images (see https://github.com/pulp/pulp-oci-images/issues/649)
> [PULP-265] Add docs about STORAGES settings

- CHANGES/6241.feature
- pulpcore/app/viewsets/task.py
- pulpcore/tests/functional/api/test_tasking.py
Adds the `pulp_created` datetime field as a filter to allow
filtering tasks by its creation date. Also, adds a test to
check if the filter is working as expected.
Closes #6241
> Add pulp_created field as a task filter

- CHANGES/6214.bugfix
- pulpcore/content/authentication.py
- pulpcore/tests/functional/api/using_plugin/test_content_delivery.py
fixes: #6214
Another one solved by the Cursor agent, the commands I issued:
```
Fix the issue described here: @https://github.com/pulp/pulpcore/issues/6214 
The exception catched should be CookieError
Rework the exception to return a 400 with the message 'Received invalid cookies'
Let's add a functional test 
Add a changelog for the issue
```
> Fix 500 error in content app when passed bad cookies

- CHANGES/plugin_api/5928.bugfix
- pulpcore/tasking/tasks.py
fixes: #5928
This one was pretty simple for the Cursor agent to solve. Should I add tests for this?
> Fix immediate tasks to run in temp dir

- pulpcore/app/settings.py
The current query can be super heavy in environments with lots of
packages and really slow down the startup process of Pulp components.
Since we're checking the presence of any number of artifacts using a
certain checksum, limiting it to the first result can speed up the
check itself and the startup process.
> Add LIMIT statement to those queries needed during Pulp startup process.

- pulpcore/tasking/tasks.py
When an immediate task is ran the api worker switches directory to a tmp directory inside the working directory. After the task is finished the tmp directory is deleted, but the api worker still thinks it is in the tmp directory thus causing future cwd to fail. This commit changes the pulpcore code to chdir back after finishing the task.
> Fix a FileNotFound err with tmpDir in immediate tasks

- CHANGES/6293.bugfix
- pulpcore/tasking/tasks.py
> Change workdir even if the immediate task fails

- CHANGES/5235.feature
- docs/admin/reference/settings.md
- pulpcore/app/settings.py
- pyproject.toml
> Allow selecting enabled plugins

- CHANGES/6293.bugfix
- pulpcore/tasking/tasks.py
**This is a backport of PR https://github.com/pulp/pulpcore/pull/6294.**
(cherry picked from commit 703333dc12d0d4eb1ea4f02e7713e7a9fec728d9)
> [PR #6294/703333d backport][3.71] Change workdir even if the immediate task fails

- CHANGES/+acs-optimization.bugfix
- pulpcore/plugin/stages/artifact_stages.py
- pulpcore/plugin/stages/declarative_version.py
So far, I can tell that it at least reduced runtimes by about 75%, but the memory use improvement is minimal.
> Optimize ACS pipeline for runtime and memory

- pulpcore/app/settings.py
- pulpcore/tests/functional/api/test_openapi_schema.py
This change is just a setting and should not even change the api.
But the api specs change a bit more than our tooling can handle at the moment.
Reverts pulp/pulpcore#6296
> Revert "Use openapi 3.1.0 for schema generation"

- CHANGES/6258.doc
- docs/admin/guides/configure-pulp/configure-storages.md
- pulpcore/tests/unit/serializers/test_domain.py
Also, adds a simple test to check if the options needed to configure
AWS CloudFront are valid.
Closes #6258
> Add a new doc about how to use AWS CloudFront as backend storage.

- CHANGES/+default-plugin-settings.bugfix
- pulpcore/app/settings.py
This fixes the change introduced on the new plugin enabled feature (https://github.com/pulp/pulpcore/commit/13750991c887eae4b5648b091cfd4a09b740d0d1), we need to load plugin settings first so that user settings (/etc/pulp/settings.py, ENV vars) will override them.
> Fix plugin defaults overriding user settings

- CHANGES/6225.misc
- pulpcore/tasking/worker.py
Tasks can get stuck in running without a runner in rare instances. The previous patch had a malformed log statement which caused crashes.
fixes #6225
> [PULP-296] Fix an issue with a previous patch for tasks not marked unblocked

- CHANGES/6333.bugfix
- pulpcore/app/models/publication.py
- pulpcore/app/models/repository.py
- pulpcore/tests/functional/api/using_plugin/test_content_cache.py
From my understanding there was a timing window during the sync that probably caused the cache issue. In replicate we sync with auto-publish which means that right after the new repo-version is created we start publishing in the same task. We invalidate the cache after a new repo-version is created, but we were failing to do so when a new publication was created (when domains were turned off). So after the sync you could end up with old items still in the cache if you had clients still fetching content during the sync. 
fixes: #6333
> Fix cache invalidation on publication create & repo-version delete

- docs/admin/guides/configure-pulp/configure-storages.md
- docs/admin/guides/configure-pulp/index.md
- docs/admin/reference/settings.md
This PR does:
- Move general info from storages config to general configuration guide
- Fix and add more inter-links between different settings pages
- Fix markdown formatting errors for tabbed content and listings (should have a space before the bullets).
> [Docs] Improve admin configuration pages

- CHANGES/3234.feature
- pulpcore/app/serializers/orphans.py
- pulpcore/constants.py
- pulpcore/tests/unit/serializers/test_orphans_cleanup.py
This PR adds validation to the `orphans/cleanup/` endpoint to restrict the `orphan_protection_time` value. The allowed range is from 0 to 365 days.
Fixes #3234
> Validate orphan_protection_time in orphans/cleanup

- CHANGES/6375.bugfix
- pulpcore/app/migrations/0131_distribution_checkpoint_publication_checkpoint.py
- pulpcore/app/migrations/0132_alter_content_options.py
See notes in the issue for details.
fixes #6375.
> Fixed 0131 and 0132 migrations to allow upgrading from 3.73.

- CHANGES/6341.bugfix
- pulpcore/app/settings.py
The values of the first pass can now be used to adjust the defaults for the second pass, but the results will be discarded, becuase reusing lead to weird interferences with environment injection.
> Reworked the two pass settings loading

- CHANGES/6380.bugfix
- pulpcore/app/tasks/purge.py
- pulpcore/app/util.py
- pulpcore/app/viewsets/task.py
Guessing the user to scope tasks to purge via the permission framework, requires one to us an access policy based permission class. We should not rely on that.
> Fixed task purge when no user can be infered

- CHANGES/5439.bugfix
- pulpcore/download/factory.py
We were passing None to the timeout items relying that they would fallback to the defaults, but this actually just disables them.
The aiohttp documentation was a bit confusing about this, but the defaults are only applied if no ClientTimeout instance is passed, not at specific timeout attributes.
https://github.com/aio-libs/aiohttp/blob/f3b0610d1207cd6649b28287e2ad19192ffe2f4a/aiohttp/client.py#L311-L312
Closes #5439
> [PULP-238] Fix remote timeout configuration

- CHANGES/6385.bugfix
- pulpcore/content/handler.py
- pulpcore/tests/unit/content/test_handler.py
fixes: #6385
(cherry picked from commit 068cb0d37cad3d27862c866855a3d20fcea3d89e)
> Backport 3.49 - Fix pull-through cache for on-demand content

- CHANGES/+second_ondemand_pullthrough.bugfix
- pulpcore/content/handler.py
- pulpcore/tests/unit/content/test_handler.py
My initial fix forgot to account/test for the second condition in the if statement on line 1065:
https://github.com/pulp/pulpcore/blob/8b72c898a018d5f7954c4998f53ab654d79682d2/pulpcore/content/handler.py#L1064-L1075
When the ContentArtifact already exists then the `bulk_create` will update the exisiting object, but the returned value of this will be the objects from `new_cas`, not the actual saved values from the DB. This results in the later RemoteArtifact saving failing since the ContentArtifact in `cas` would have the wrong `pk`
> Fix second scenario for on-demand pull-through caching

- CHANGES/6390.bugfix
- pulpcore/content/handler.py
Set the X-PULP-ARTIFACT-SIZE header at the handle_response_header function
using the original `Content-Length` header when a `Content-Encoding` header
is not present. Also, remove old code that weren't used to set the header.
Close #6390
> Set the X-PULP-ARTIFACT-SIZE header at the handle_response_header function.

- CHANGES/6174.bugfix
- pulpcore/app/serializers/publication.py
- pulpcore/tests/unit/serializers/test_repository.py
This PR adds validation to the `PublicationSerializer` and `DistributionSerializer` to check if the repo and remote are from different plugins. If they are, an error is raised before the task is spawned.
Follow-up to #6391
Fixes #6174
> Validate repo and remote in PublicationSerializer and DistributionSerializer

- CHANGES/plugin_api/+anon-user-object-create.bugfix
- pulpcore/app/models/access_policy.py
Sometimes our auth (pulp_container) can return an AnonymousUser which will make `add_roles_for_object_creator` fail if they perform an action to create an object.
> Fix add_roles_for_object_creator handling of AnonymousUser

- CHANGES/6500.bugfix
- pulpcore/plugin/stages/artifact_stages.py
Satellite hits this worse than others because their remotes are fully populated with certificates and CAs. select_related() produces new copies of each of those strings per-remote-artifact.
closes #6500
> [PULP-239] Fixed a memory issue triggered by ACS usage

- CHANGES/6510.bugfix
- pulpcore/app/serializers/repository.py
This reverts commit 75461808386e4dc1e60646b4e4c86b2c002386d5.
fixes #6510.
(cherry picked from commit 1cf684ad67372153c0661f236f40394f5741efac)
> Revert "[PULP-270] Validate and clean comments from Remote certs."

- CHANGES/plugin_api/6429.bugfix
- pulpcore/app/tasks/base.py
- pulpcore/app/tasks/test.py
- pulpcore/app/viewsets/base.py
- pulpcore/constants.py
- pulpcore/pytest_plugin.py
- pulpcore/tasking/tasks.py
- pulpcore/tests/functional/api/test_tasking.py
Experiment with creating async version of dispatch to make async timeout work from the content app.
> [PULP-467] Re-add timeout to immediate task with regression fix

- pulpcore/app/replica.py
- pulpcore/app/tasks/__init__.py
- pulpcore/plugin/tasking.py
This PR replaces the deprecated `pulpcore.app.tasks.base.general_update` with `pulpcore.app.tasks.base.ageneral_update`. This change is required to prevent CI failures in all new PRs.
> Update deprecated general_update task

- CHANGES/6529.bugfix
- pulpcore/app/wsgi.py
- **Fix WorkerNameMetricsExporter to not export unless otel is enabled.**
> Fix WorkerNameMetricsExporter to not export unless otel is enabled.

- CHANGES/6521.bugfix
- pulpcore/app/serializers/publication.py
- pulpcore/app/serializers/repository.py
This PR replaces f-strings in `_()` calls with `.format()` to ensure proper `gettext` support.
Fixes #6521
> Fix incorrect use of f-strings in gettext

- CHANGES/6510.bugfix
- pulp_file/tests/functional/api/test_remote_settings.py
- pulpcore/app/serializers/repository.py
This reverts and reworks commit 1cf684a. Multi-cert PEMs are handled correctly, and openssl use is replaced with using python-cryptography directly.
> Reapply "[PULP-270] Validate and clean comments from Remote certs."

- CHANGES/3609.bugfix
- pulpcore/app/management/commands/clean-up-progress-reports.py
- pulpcore/app/models/task.py
- pulpcore/tests/unit/models/test_task.py
Added a manager-command to clean up current data in inconsistent states.
fixes #3609.
> Teach tasks to clean up their ProgressReports states on fail/cancel.

- CHANGES/6021.feature
- docs/admin/reference/settings.md
- pulpcore/app/settings.py
- pulpcore/content/__init__.py
- pulpcore/content/entrypoint.py
- pyproject.toml
The uvloop replaces the asyncio builtin event loop. To enable it, one must set the UVLOOP_ENABLED=True and have the uvloop package installed in the system where the content-app is deployed.
Closes: #6021
> Add uvloop usage as an optional feature on the content-app

- docs/admin/reference/settings.md
- docs/user/learn/on-demand-downloading.md
- pulpcore/app/settings.py
- pulpcore/content/handler.py
- pulpcore/tests/functional/api/using_plugin/test_content_delivery.py
**First commit:**
In the content app on-demand streaming error handler for digest errors, the TCP connection with the client must be closed. Possibly because of some confusion about what connection should be closed, the downloader
session was also closed.
Closing the session is unnecessary to the error handling and it's incompatible with some downloaders. E.g, `RpmFileDownloader` doesn't have a session at all. This causes unintented errors when using file:// remotes.
Also, there is no need to raise a runtime error from the error handling perspective, so a clean error log was used.
**Second commit:**
improves documentation about `REMOTE_CONTENT_FETCH_FAILURE_COOLDOWN`.
> [PULP-423] Fix wrong downloader session close on on-demand streaming 

- pulpcore/content/handler.py
- pulpcore/tests/functional/api/using_plugin/test_content_delivery.py
In the content app on-demand streaming error handler for digest errors, the TCP connection with the client must be closed. Possibly because of some confusion about what connection should be closed, the downloader session was also closed.
Closing the session is unnecessary to the error handling and it's incompatible with some downloaders. E.g, RpmFileDownloader doesn't have a session at all.
Also, there is no need to raise a runtime error from the error handling perspective, so a clean error log was used.
Backport from https://github.com/pulp/pulpcore/pull/6556
> [backport 3.63] Fix wrong downloader session close on on-demand streaming

- pulpcore/content/handler.py
- pulpcore/tests/functional/api/using_plugin/test_content_delivery.py
In the content app on-demand streaming error handler for digest errors, the TCP connection with the client must be closed. Possibly because of some confusion about what connection should be closed, the downloader session was also closed.
Closing the session is unnecessary to the error handling and it's incompatible with some downloaders. E.g, RpmFileDownloader doesn't have a session at all.
Also, there is no need to raise a runtime error from the error handling perspective, so a clean error log was used.
cherry-picked from: 3a3b6d4eee64a6e7d284208d24e47e1a8284751c (https://github.com/pulp/pulpcore/pull/6556)
> [bacport 3.73] Fix wrong downloader session close on on-demand streaming

- pulpcore/app/entrypoint.py
- pulpcore/app/management/commands/dump-publications-to-fs.py
- pulpcore/app/replica.py
- pulpcore/app/serializers/base.py
- pulpcore/app/tasks/repository.py
- pulpcore/tasking/worker.py
This small PR resolves the deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
> Resolve Python logger warnings

- pulpcore/app/models/task.py
- pulpcore/app/openpgp.py
Instead of unsetting state attributes, in the update, reflect them as is on
successful update.
> Reduce db load on tasks state machine

- pulpcore/pytest_plugin.py
- pulpcore/tests/functional/api/test_status.py
Allow reusing of a bunch of fixtures. Specifically the "factory fixtures" should be reusable accross test classes. So classes can provide a scenario including objects like repositories that can be asserted on from several independent tests.
> Extend scope of fixtures

- requirements.txt
See for more context:
https://github.com/pulp/pulpcore/pull/6695
> [3.63] Pin pycares to avoid bug with aiodns combination

- CHANGES/+multithread-file-hashing.feature
- pulpcore/app/files.py
- pulpcore/download/base.py
Note that since the hashing is done by C code inside of hashlib which releases the GIL, threading actually does work here despite the normal GIL rules.
> Test multithreaded file hashing

- pyproject.toml
This should allow to install newer version if a recent version of python is used. It also documents nicely when exactly we can remove the constraint again.
> Add a python version to pycares constraint

- pulpcore/tasking/tasks.py
Django would not know about generated columns otherwise.
> Read a task from db after creating it

- .ci/scripts/calc_constraints.py
- requirements.txt
See for more context:
https://github.com/pulp/pulpcore/pull/6695
(cherry picked from commit b1560306741816770ddafa3d51dadbef4c7b072a)
> [bp/3.39] Pin pycares to avoid bug with aiodns combination

- CHANGES/6772.bugfix
- pulpcore/app/models/repository.py
fixes: #6772
This is the orm magic breaks down to this sql:
```SQL
SELECT *
FROM "core_content" 
WHERE "core_content"."pulp_id" IN (
SELECT unnest(U0."content_ids") AS "cids" 
FROM "core_repositoryversion" U0
WHERE U0."pulp_id" = 01980713-3ed0-7f9a-b1f5-20e774f746ae
)
```
> Fix RepositoryVersion.content query failing when >65K units

- CHANGES/6812.bugfix
- pulpcore/content/handler.py
- pulpcore/tests/functional/api/using_plugin/test_checkpoint.py
Redirect checkpoint URLs without a trailing slash to add a slash
closes #6812
> Redirect checkpoint URLs without a trailing slash

- CHANGES/heartbeat.bugfix
- pulpcore/app/entrypoint.py
- pulpcore/app/models/status.py
- pulpcore/content/__init__.py
- pulpcore/tasking/worker.py
- pulpcore/tests/unit/content/test_heartbeat.py
This is supposed to dectect situations where the workers fail to reach the database and therefore any type of network partitioning. By theory this should improve consistency in the face of partitioning. It sacrifices only the avaliablility of workers, that would not reach the database anyway to perform anything meaningful.
> [PULP-570] Mark a failed heartbeat as a catastrophic failure

- CHANGES/+migration_check.bugfix
- pulpcore/migrations.py
Modern components know how to clean up their status entries, so the check for migrations should not even depend them being missing.
> Fix RequiredVersion migration check

- pulpcore/app/management/commands/optimizemigration.py
This helps to optimize squashed migrations after manally reordering their operations. It uses the same algorithm that Django uses for squashing in the first place, but can be used independently.
> Add optimizemigration management command

- CHANGES/plugin_api/+remove-sync-immediate-suport.removal
- pulpcore/tasking/tasks.py
- pulpcore/tests/functional/api/test_tasking.py
I forget to remove this for 3.85, as announced in https://github.com/pulp/pulpcore/pull/6155
Because we just released 3.85 and are working on related issues, I'm doing it a little late and backporting it.
It's not clear if plugins have to take any action about that. I don't think so...
> Remove support for non-async immediate tasks

- CHANGES/6845.feature
- docs/admin/learn/architecture.md
- pulpcore/app/settings.py
- pulpcore/middleware.py
> Add a setting to set the bucket boundaries for the API request duration metric.

- CHANGES/6868.bugfix
- pulpcore/plugin/repo_version_utils.py
- pulpcore/tests/unit/models/test_repository.py
Repository version validation now allows multiple content units to reference the same artifact at the same relative path. Previously, the validate_version_paths function treated any duplicate relative path as an error, even when multiple content units legitimately shared the same artifact.
closes #6868
> Fix repository validation for shared artifacts

- pulpcore/app/models/repository.py
- pulpcore/app/models/task.py
- pulpcore/app/tasks/repository.py
- pulpcore/plugin/tasking.py
- pulpcore/tasking/tasks.py
- pulpcore/tests/functional/api/test_tasking.py
- pulpcore/tests/unit/content/test_handler.py
Plan:
~- [ ] Change content app to use async pull_through_add_content and remove sync one (only used here)~ (left to another PR)
> [PULP-553] Enable immediate task execution on content app (1/2)

- CHANGES/6917.bugfix
- pulpcore/constants.py
When GCP support was originally added in https://github.com/pulp/pulpcore/pull/3481, the parameters were `response_disposition` and `content_type`. When it was refactored in https://github.com/pulp/pulpcore/pull/4251, the headers for GCS were mistakenly changed and expanded.
These parameters get used by `generate_signed_url` method defined in https://github.com/googleapis/python-storage/blob/a8109e0/google/cloud/storage/blob.py#L463, through
https://github.com/jschneier/django-storages/blob/758ad6f/storages/backends/gcloud.py#L350
This PR ensures only the supported parameters are passed to that function call.
closes #6917
> Fix parameters passed for GCS URL generation

- CHANGES/+task-immediate.misc
- pulpcore/tasking/tasks.py
- pulpcore/tests/unit/content/test_handler.py
When requiring immediate tasks to be async, we had a problem dispatching them from the content app due to the use of django transactions in the dispatch code and how that plays with asyncio.
Now that we no longer have that (due to the app_lock implementation) we can remove the workaround we had in place and prioritize immediate tasks on the worker.
> Enable immediate task from content app (2/2)

- CHANGES/6925.bugfix
- pulpcore/content/instrumentation.py
> Change how the exceptions are propagated on the Content instrumentation middleware.

- CHANGES/6380.bugfix
- pulpcore/app/tasks/purge.py
- pulpcore/app/util.py
- pulpcore/app/viewsets/task.py
Guessing the user to scope tasks to purge via the permission framework, requires one to us an access policy based permission class. We should not rely on that.
fixes #6380
(cherry picked from commit 9949f5fac3746aa76ee204a177aba5c8729f720b)
> [backport/3.63] Fixed task purge when no user can be infered

- CHANGES/+janitor_coordination.feature
- pulpcore/app/util.py
- pulpcore/constants.py
- pulpcore/exceptions/__init__.py
- pulpcore/exceptions/base.py
- pulpcore/tasking/worker.py
All the corresponding cleanup work can equally well be organized using advisory locks within a transaction.
> [PULP-785] Remove advisory lock from janitorial work
