.travis.yml, README.md, docs/contributing/continuous-integration.rst, docs/contributing/pull-request-walkthrough.rst, docs/index.rst, docs/installation/instructions.rst, docs/release-notes/pulpcore/3.0.x.rst
This updates two main things:
- various docs
- the encrypted key for Travis to publish to PyPI. This is an asset that
is encrypted per-repo on Travis so changing the repo requires
regenerating it.
https://pulp.plan.io/issues/4444
re #4444
=> Updates to account for repo name change

.travis/pulp-smash-config.json
this setting is required in order to test `pulp_docker` because plugin repos re-use this same smash settings file
see https://github.com/pulp/pulp_docker/pull/315
[noissue]
=> Adds `content` role to pulp-smash config file.

pulpcore/app/serializers/__init__.py, pulpcore/app/serializers/publication.py
Solution: Add a generic BaseDistributionSerializer
re: #4435
https://pulp.plan.io/issues/4435
re: #4437
https://pulp.plan.io/issues/4437
=> Problem: DistributionSerializer is too prescriptive

pulpcore/app/tasks/__init__.py, pulpcore/app/tasks/distribution.py, pulpcore/app/viewsets/publication.py, pulpcore/tests/functional/api/test_crud_distributions.py, pulpcore/tests/functional/api/using_plugin/test_auto_distribution.py, pulpcore/tests/functional/api/using_plugin/test_content_app.py, pulpcore/tests/functional/api/using_plugin/test_content_promotion.py, pulpcore/tests/functional/api/using_plugin/test_crd_publications.py
Uses resource locking protection to create/update/destroy distributions
asynchronously which prevents race conditions in base_path checking.
fixes #3044
https://pulp.plan.io/issues/3044
=> Makes Distribution CUD operations async

docs/bugs-features.rst, docs/contributing/dev-setup/source.rst, docs/contributing/git.rst, docs/glossary.rst, docs/installation/configuration.rst, docs/installation/storage.rst, pulpcore/app/serializers/repository.py
Misc docs updates.
Most are unrelated, so I decided not to squash the commits.
I tested a build successfully and viewed each modified page.
Note that the glossary change is permissible by sphinx. [You can have 2 terms with 1 definition.](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#glossary)
=> Docs updates

.travis/before_script.sh, .travis/publish_docs.sh, .travis/script.sh, docs/components.rst, docs/contributing/dev-setup/runtests.rst, docs/installation/instructions.rst, docs/integration-guide/rest-api/authentication.rst, pulpcore/app/entry_points.py, setup.py
Solution: remove pulp-manager and update docs
This patch removes pulp-manager wrapper for django-admin. It also updates all the docs with references
to django-admin directly.
re: #4450
https://pulp.plan.io/issues/4450
=> Problem: pulp-manager is not needed

.travis.yml
The Travis creds can't publish to PyPI. This issue started when we moved
the repository from pulp/pulp to pulp/pulpcore. The credentials were
updated when it was moved, but they weren't for the Travis Community
version which we think is the issue. This was generated with the --com
option.
[noissue]
=> Updating Travis creds

pulpcore/app/models/storage.py, pulpcore/app/settings.py, pulpcore/content/handler.py, pulpcore/tests/functional/api/test_crd_artifacts.py, pulpcore/tests/functional/api/using_plugin/test_orphans.py
User can change where files are stored which help
to use with openshift and others cloud systems.
closes: #4380
https://pulp.plan.io/issues/4380
Signed-off-by: Pavel Picka <ppicka@redhat.com>
=> Ensure you can run Pulp without /var/lib/pulp

pulpcore/app/serializers/fields.py
Coercing settings in various places in the code doesn't seem as good as
handling those problems in one place, the settings file. This variable
coercion doesn't make sense to me or seem to be needed at all. If we do
need this type of validation or coercion we can add it back later to the
settings file.
[noissue]
=> Remove settings file variable coercion

pulpcore/app/viewsets/publication.py
Solution: Use AsyncOperationResponseSerializer as the response serializer for swagger_auto_schema
fixes: #4555
https://pulp.plan.io/issues/4555
=> Problem: OpenAPI schema for distribution CUD is wrong

.travis/before_install.sh, .travis/playbook.yml, .travis/script.sh
This makes three changes:
- Clone the pulp/pulp-certguard repo from source in Travis environments
- Configure the Ansible Installer to install that source checkout
- Have py.test run those functional tests to ensure they pass with
pulpcore.
https://pulp.plan.io/issues/4596
closes #4596
=> Configures certguard tests to run with pulpcore

.travis/before_install.sh
Fix pulp-certguard dir allowing tests from this dir to run. Instead of
pulp-file tests.
'[noissue]'
=> Fix pulp-certguard dir

docs/installation/configuration.rst, docs/installation/instructions.rst, pulpcore/app/serializers/repository.py
This started as a simple systemd clarification...
The settings were very confusing in various ways as pointed out by the
user on the mailing list. This rewrite hopefully simplifies things some.
https://pulp.plan.io/issues/4615
closes #4615
=> Clarifies systemd and settings docs

docs/installation/instructions.rst
The path was a generic one, so this uses the default of the ansible-pulp
installer to align them more closely. It also updates the location of
the systemd unit files.
https://pulp.plan.io/issues/4615
closes #4615
=> Clarifies systemd docs and path

docs/contributing/git.rst, docs/index.rst
This moves the version section to the homepage and then links to that
from the git page. The branching page now recommends all code be opened
in a Pull Request against the master branch.
https://pulp.plan.io/issues/4625
closes #4625
=> Revamps the git contributor page

doc_requirements.txt
The tests don't need psycopg2.
https://pulp.plan.io/issues/4639
closes #4639
=> Remove test dependency on psycopg2

pulpcore/tests/functional/api/using_plugin/test_auto_distribution.py, pulpcore/tests/functional/api/using_plugin/test_content_app.py, pulpcore/tests/functional/api/using_plugin/test_content_promotion.py, pulpcore/tests/functional/api/using_plugin/test_crd_publications.py
Distribution creation it was modified to be an async task. A new
response_handler was added to pulp-smash to deal with those cases.
Update distribution creation to use this new response_handler.
'[noissue]'
=> Update distribution creation to use task_handler

pulpcore/tests/functional/api/using_plugin/constants.py, pulpcore/tests/functional/api/using_plugin/test_sync_multiple_plugins.py
This commit will test cross plugin scenario. If the user syncs multiple
plugin contents into the same repo with the option mirror=True, the
existing content should be overwritten.
Closes #4448
=> Adding mirror true check for rpm/file plugin

docs/installation/instructions.rst
When fixing the systemd templates I did not include the pulp-api systemd
template links. This was pointed out on pulp-list so I am fixing now.
https://pulp.plan.io/issues/4629
closes #4629
=> Add in pulp-api systemd template links

docs/installation/instructions.rst
The systemctl command was not updated correctly for the pulp-api service
file change. This fixes that.
https://pulp.plan.io/issues/4629
closes #4629
=> One liner systemd fix

pulpcore/app/openapigenerator.py, pulpcore/app/views/status.py, pulpcore/app/viewsets/task.py
Solution: add operation summaries using swagger_auto_schema
This patch also improves the PulpAutoSchema inspector. The inspector only tries to generate a summary
when the summary is not already provided by swagger_auto_schema decorator.
[noissue]
=> Problem: inaccurate 'operation_summary' for status and task cancel

.travis/script.sh
Due to DJANGO_SETTINGS_MODULE not being inherited from .travis/playbook.yml
Fixes #78 (https://pulp.plan.io/issues/4674)
=> Fix docs not building under Travis

.travis/publish_docs.sh, .travis/pulp-smash-config.json, .travis/script.sh, docs/Makefile, docs/components.rst, docs/contributing/architecture/rest-api.rst, docs/contributing/runtests.rst, docs/installation/instructions.rst, docs/workflows/upload-publish.rst, pulpcore/app/viewsets/repository.py
Change Pulp 3 Default Ports
https://pulp.plan.io/issues/4556
Update docs for changed Pulp 3 Default Ports
https://pulp.plan.io/issues/4594
Content: 8080 -> 24816
API: 8000 -> 24817
This commit includes a change to docs/Makefile that affects the build process.
Note: I am about to submit changes to ansible-pulp & several other repos too. The travis files exist in those other repos in addition to doc updates. They probably all need to be merged at the same time.
Required PR: https://github.com/pulp/pulpcore/pull/79
=>  Change Pulp 3 Default Ports

pulpcore/tests/functional/api/test_crud_distributions.py, pulpcore/tests/functional/api/using_plugin/test_auto_distribution.py, pulpcore/tests/functional/api/using_plugin/test_content_app.py, pulpcore/tests/functional/api/using_plugin/test_content_promotion.py, pulpcore/tests/functional/api/using_plugin/test_crd_publications.py
Tweak in how distributions are created to assure that async tasks are
handled properly.
Adjust to use the `task_handler` response_handler.
See: https://pulp.plan.io/issues/3044
'[noissue]'
=> Tweak distribution creation in tests

pulpcore/app/settings.py, pulpcore/rqconfig.py, pulpcore/tests/unit/test_rqconfig.py, setup.py
This release includes lots of improvements on performance
and changes the way dynaconf searched settings files.
> **NOTE**: This change is not required, Dynaconf must be backwards compatible, the [Pulp's current way](https://dynaconf.readthedocs.io/en/latest/guides/django.html#explicit-mode) of loading dynaconf is still supported
This PR includes:
- Fixed the way settings are loaded on `settings.py` (no more explicit `get(....)` and added dynaconf patching at the end of file with all dynaconf config options in one place)
- Added `INCLUDES_FOR_DYNACONF` pointing to `/etc/pulp/plugins/*`
That means that any dynaconf supported settings file saved on that folder will be loaded,
so plugin installer can drop a `pulp_foo.toml` on that path containing:
```toml
[default]
content_host = …
```
=> Preparing for Dynaconf 2.0.0 (released on April 8)

docs/workflows/upload-publish.rst, pulpcore/app/viewsets/content.py
Solution: Remove JSONParser from ArtifactViewset
The ArtifactViewset viewset was configured to use MultiPartParser, FormParser, and JSONParser. The
JSONParser was added when the ArtifactViewset was extended to accept uploads when creating an
Artifact. It was only needed to allow users to submit not form-encoded requests to the
/pulp/api/v3/artifacts/ endpoint. However, 'drf_yasg' does not support mixing multipart/form-data
and json fields. When such occurs, the body parameters for the operation are simply reported as
'data' dictionary. The bindings generated from such an OpenAPI schema don't form-encode requests
for the 'artifacts_create' operation. This results in a 400 error being returned by the server.
fixes: #4683
https://pulp.plan.io/issues/4683
=> Problem: OpenAPI schema for 'Artifact create' is ambiguous

pulpcore/app/views/orphans.py, pulpcore/app/viewsets/publication.py
Solution: rename 'delete' method on the ViewSet to 'destroy'
This patch also updates the schema for orphan delete.
fixes: #4638
https://pulp.plan.io/issues/4638
=> Problem: OpenAPI schema for distribution delete is wrong

.travis.yml, .travis/script.sh
Solution: build and test bindings continuosly
This patch adds another job to the Travis build matrix. This new build installs pulpcore and pulp_file
and then builds a client library for each. The client libraries are built using pulp-swagger-codegen,
a thin wrapper around swagger-codegen-cli. After building the bindings, this job installs them and runs
a script that performs the following:
- Create a File Remote
- Create a Repository
- Sync a Repository
- Monitor the sync task
- Create an artifact from a local file
- Create a FileContent from the artifact
- Add the new FileContent to a repository version
- Monitor the repo version creation task
- Create a FilePublisher
- Create a publication from the latest version of the repository
- Monitor the publish task
- Create a distribution …
=> Problem: bindings break all the time

docs/installation/configuration.rst
There was not enough info for users to understand the relationship
between the WORKING_DIRECTORY and MEDIA_ROOT settings. This note
clarifies this.
https://pulp.plan.io/issues/4602
closes #4602
=> Deployment note on volumes for working dir

pulpcore/tests/functional/api/using_plugin/constants.py, pulpcore/tests/functional/api/using_plugin/test_tasking.py
Add test to cancel tasks, to delete a running task, and to delete a
nonexistent task.
closes: PulpQE/pulp-smash#976
https://pulp.plan.io/issues/3634
closes:#3634
=> Expand tests related to task system

pulpcore/app/serializers/publication.py
Solution: Move validate() to the Distribution instead
This patch allows classes that inherit from BaseDistribution to call super().validate(data) to get
the validation provided by the ModelSerializer.
This patch also removes base_path from BaseDistribution because it is defined on the Distribution.
DockerDistribution also defines it for itself.
re: #4669
https://pulp.plan.io/issues/4669
=> Problem: BaseDistribution.validate() is too Distribution specific

pulpcore/tests/functional/api/using_plugin/test_content_delivery.py
Add test to verify that content delivery breaks if a remote - using lazy
download policy, is deleted.
Also verify that the content can be downloaded from Pulp once the remote
is recreated and another sync is triggered.
https://pulp.plan.io/issues/4464
closes:#4464
=> Add test to content delivery breaks if remote is deleted

pulpcore/app/serializers/publication.py
Solution: use the RelatedField serializer provided by pulpcore
[noissue]
=> Problem: repository field is returned as a full URL

docs/Makefile, docs/components.rst, docs/index.rst, docs/installation/index.rst
The audiences for this patch are users and plugin writers, each needing
to know how to approach the documentation since it is spread over
multiple repositories. Users of Pulp 2 are especially in need of this,
because the responsibility of documenting workflows have been moved to
the plugin docs.
https://pulp.plan.io/issues/4626
fixes #4626
=> Clarify responsibility for core and plugin docs

.travis/before_install.sh
Solution: explicitly grant permissions to travis user
[noissue]
=> Problem: travis user can't access pulp db

docs/installation/instructions.rst
The docs did not tell users much about how to run an RQ worker. This
tries to clarify that some.
https://pulp.plan.io/issues/4732
closes #4732
=> Adds -c option for RQ workers in docs

.travis/before_install.sh, pulpcore/app/serializers/__init__.py, pulpcore/app/serializers/publication.py, pulpcore/app/serializers/repository.py, pulpcore/tests/functional/api/using_plugin/constants.py, pulpcore/tests/functional/api/using_plugin/test_auto_distribution.py, pulpcore/tests/functional/api/using_plugin/test_content_app.py, pulpcore/tests/functional/api/using_plugin/test_content_delivery.py, pulpcore/tests/functional/api/using_plugin/test_content_path.py, pulpcore/tests/functional/api/using_plugin/test_content_promotion.py, pulpcore/tests/functional/api/using_plugin/test_crd_publications.py, pulpcore/tests/functional/api/using_plugin/test_repo_versions.py, pulpcore/tests/functional/api/using_plugin/test_unlinking_repo.py, pulpcore/tests/functional/api/using_plugin/utils.py, pulpcore/tests/unit/serializers/test_repository.py
refs #4678
https://pulp.plan.io/issues/4678
=> Remove RepositoryPublishURLSerializer and use PublicationSerializer

pulpcore/app/serializers/publication.py
Solution: use RelatedField instead of HyperlinkedRelatedField
The serializer was using the wrong type of field for serializing the Publication's distrubtions field.
fixes: #4590
https://pulp.plan.io/issues/4590
=> Problem: publication's distributions are full URLs

.travis.yml
Solution: only publish when cron is building the project
closes: #4695
https://pulp.plan.io/issues/4695
=> Problem: pulpcore-client ruby gem published too often

pulpcore/tests/functional/api/test_pagination.py, pulpcore/tests/functional/api/using_plugin/test_pagination.py
- Add core pagination test cases as per issue 4221
- Keep only plugin related pagination test on using_plugin folder
https://pulp.plan.io/issues/4221
closes #4221
=> Add core pagination test cases - issue 4221

.travis.yml, .travis/publish_pulpcore_client_pypi.sh
Solution: add another stage that publishes pulpcore-client to PyPI
This patch adds another stage to the deploy pipeline. During this stage, the
pulpcore-client package is generated and pushed to PyPI.
re: #4694
https://pulp.plan.io/issues/4694
=> Problem: pulpcore-client not published to PyPI

docs/integration-guide/index.rst
Solution: provide links to rubygems.org and pypi.org
This patch also provides documentation on generating bindings in any language.
re: #4687
https://pulp.plan.io/issues/4687
=> Problem: docs fail to mention bindings

.travis/publish_pulpcore_client_gem.sh, .travis/publish_pulpcore_client_pypi.sh
Solution: check if the version of the client already exists
This patch adds an additional step to each of the pulpcore-client publish scripts.
This step checks if the version of the client that is about to be built already exists.
If the client version exists, the script exits without trying to build the package again.
re: #4694
https://pulp.plan.io/issues/4694
re: #4695
https://pulp.plan.io/issues/4695
=> Problem: publish to rubygems.org and pypi.org can fail

pulpcore/app/viewsets/repository.py
Solution: remove UpdateModelMixin from RepositoryVersionViewSet
closes: #4750
https://pulp.plan.io/issues/4750
=> Problem: OpenAPI schema for RepositoryVersion is wrong

docs/Makefile
This works around an sshfs bug whereby the `mv` command gives errors
on that filesystem.
https://pulp.plan.io/issues/4791
closes #4791
=> Allow docs building in dev environment

pulpcore/app/serializers/content.py, pulpcore/tests/functional/api/test_crd_artifacts.py
At least the file plugin should be able to support artifacts with empty content.
fixes #4786
https://pulp.plan.io/issues/4786
=> Allow artifacts with empty content

.travis/before_install.sh, .travis/publish_pulpcore_client_gem.sh, .travis/publish_pulpcore_client_pypi.sh, .travis/script.sh
Solution: update to using pulp-openapi-generator
The repo name change because the tooling it uses change.
re: #4691
https://pulp.plan.io/issues/4691
=> Problem: travis config is using old repo name

docs/release-notes/pulpcore/3.0.x.rst, setup.py
This bumps the version to 3.0.0rc2.
It also adds release notes with the current breaking changes written in
their own section.
[noissue]
=> 3.0.0rc2 version bump and release notes

pulpcore/app/urls.py
Solutuion: add the logo URL to the OpenAPI schema
[noissue]
=> Problem: pulp logo missing from REST API docs

containers/README.md, containers/images/pulp-api/Dockerfile, containers/images/pulp-api/container-assets/pulp-api, containers/images/pulp-api/container-assets/pulp-common-entrypoint.sh, containers/images/pulp-api/container-assets/wait_on_database_migrations.sh, containers/images/pulp-content/container-assets/pulp-content, containers/images/pulp-resource-manager/container-assets/pulp-resource-manager, containers/images/pulp-worker/container-assets/pulp-worker
Update to support installation from git nightly
Also some changes necessary for pulp-operator to work
Also some badly needed fixes that were always needed
Other/included fixes/improvements:
> 
> README.md: Update container list
> List all of those that currently can be installed at container build
> time.
> 
> Update for new Pulp 3 default ports
> 
> Update commands to start services; including them matching the systemd
> unit more closely
> 
> Set DJANGO_SETTINGS_MODULE in all container images
> 
> Fix possibly applicable security vulns in images by running `yum update`
> 
> Install nightly version of Pulp (currently limited to always doing so)
> 
> run migrations
> 
> Set pulp admin password if defined
> 
> Run django-admin collectstatic at runtime (so that /var/lib/pulp
> can be a …
=> containers: Update to support Pulp 3.0 rc2

.travis/publish_pulpcore_client_gem.sh, .travis/publish_pulpcore_client_pypi.sh
Solution: switch to using epoch in the version string
The script that generates the version string for the client library assumed that the version in setup.py would always
correspond to a tag in the repository. However, this is not true in days leading up to a release.
This patch is meant as a temporary solution to this problem. In the future, we should reduce the time window between
the update of the version in setup.py and tag creation. When that is done, we can go back to counting commits between
tag and the commit being built.
[noissue]
=> Problem: pulpcore-client version string can be wrong

pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
sync util function was ajusted. Update test to reflect this change.
See: https://github.com/PulpQE/pulp-smash/pull/1206/files
'[noissue]'
=> Adjust sync call to parse response

pulpcore/app/serializers/publication.py
It should not be available by default, but only in those plugins that
implement pull-through caching.
closes #4817
https://pulp.plan.io/issues/4817
=> Remove the "remote" field from the BaseDistributionSerializer

pulpcore/content/handler.py
The `Handler` object was not very subclassable, so this improves it in a
few ways.
- hardcoded `Handler` calls are no longer used
- classmethods replace staticmethods
- the HOP_BY_HOP constant is now available on the object
- add a DISTRIBUTION_MODEL constant that subclasses can declare their
corresponding distribution model type. If declared only that model
type will be matched. If unspecified, `BaseDistribution` will be used.
Unrelated to the subclassing an error case was removed which would
silence all exceptions to the log which is not a good behavior.
https://pulp.plan.io/issues/4719
closes #4719
=> Make `Handler` subclassable

pulpcore/app/openapigenerator.py
Solution: generate schema from Views without querysets
This patch also skips generating schema for views without models associated with them.
fixes: #4794
https://pulp.plan.io/issues/4794
=> Problem: OpenAPI schema can't be generated for some plugins

pulpcore/content/handler.py
The code that gets the latest repo version doesn't filter out incomplete
repo versions. Use the RepositoryVersion latest method to get the
lastest repo version instead.
[noissue]
=> The distribution code doesn't filter incomplete repo versions

pulpcore/content/handler.py
This fix is needed because otherwise inclusion of this model's docstring
in Sphinx will error.
https://pulp.plan.io/issues/4719
closes #4719
=> Small docs indention fix

.travis.yml, .travis/docs-builder.py
Solution: publish tagged builds to 'rc' directory
This patch is a temporary solution to the problem. We will need to make this machinery
more robust before we start publishing GA builds and new betas with 3.1. This effort is
being tracked as https://pulp.plan.io/issues/4853
re: #4821
https://pulp.plan.io/issues/4821
=> Problem: docs for RC are published to 'beta' directory

pulpcore/tests/functional/api/using_plugin/test_crd_publications.py
Remove test related to remote from publications tests.
See:https://github.com/pulp/pulp_file/pull/228
'[noissue]'
=> Remove tests related to remote from publications

docs/release-notes/pulpcore/3.0.x.rst, pulpcore/app/models/progress.py, pulpcore/app/models/repository.py, pulpcore/app/serializers/content.py, pulpcore/app/serializers/progress.py, pulpcore/app/serializers/publication.py, pulpcore/app/serializers/repository.py
Solution: update serializers to accept null
re: #4676
https://pulp.plan.io/issues/4676
=> Problem: REST API does not accept null for string values

docs/workflows/exposing-content.rst
Fix path to file distribution on docs to be
`pulp/api/v3/distributions/file/file/`
'[noissue]'
=> Fix path to file distributions on docs

pulpcore/app/views/status.py
Solution: add the response to the OpenAPI schema
This patch also change the operation_id from 'status_list' to 'status_read'.
fixes: #4870
https://pulp.plan.io/issues/4870
=> Problem: OpenAPI schema for status API is missing a response

pulpcore/app/serializers/publication.py
closes #4792
https://pulp.plan.io/issues/4792
Since all publications are have a repository version, there is no need to display the repository field on read ops.  We just want to be able to create one from the latest version of a repo.
=> Fix serialization of repository field on Publications

pulpcore/tests/functional/api/using_plugin/constants.py
Update RPM constants to be according to the new changes added to RPM
plugin.
See: https://github.com/pulp/pulp_rpm/pull/1354
'[noissue]'
=> Update RPM constants advisory

pulpcore/tests/functional/api/using_plugin/test_distributions.py
Expand create publication distribution test case. Use a publication
field when creating a distribution. Update assertions about just created
distribution.
closes:#4839
=> Expand create publication distribution test case

pulpcore/tests/functional/api/using_plugin/utils.py
Update response_handler used by create_file_publication. Then the
parsing of returned tasks will be done by the response_handler, not the
function itself.
'[noissue]'
=> Update response_handler used by create_file_publication

CHANGES.rst, CHANGES/.TEMPLATE.rst, CHANGES/.gitignore, CHANGES/4875.doc, doc_requirements.txt, docs/changes.rst, docs/contributing/git.rst, docs/contributing/index.rst, docs/contributing/pull-request-walkthrough.rst, docs/index.rst, pulpcore/__init__.py, pyproject.toml
- Adds a changelog update section to the docs
- creates the base CHANGES.rst file
- creates the CHANGES directory for news updates and indicates to git to
store the dir even if empty with a .gitignore.
- adds a release note for this change
- adds a docs section that loads the CHANGES.rst file on the website
https://pulp.plan.io/issues/4875
re #4875
=> Add new changelog process

CHANGES/4883.feature, CHANGES/4883.removal, pulpcore/app/serializers/__init__.py, pulpcore/app/serializers/task.py, pulpcore/app/viewsets/task.py, pulpcore/tasking/util.py, pulpcore/tests/functional/api/using_plugin/test_tasking.py
Solution: switch it to a PATCH method of the task
This patch changes REST API for task cancelation. Users will now be able to make a PATCH
request to the task href and specify the state='canceled'. The response is the fully
serialized task.
fixes: #4883
https://pulp.plan.io/issues/4883
=> Problem: task cancel API is incorrect

pulpcore/app/viewsets/upload.py
Solution: Add Content-Range header to the OpenAPI schema
Required PR: https://github.com/pulp/pulp-openapi-generator/pull/17
fixes: #4896
https://pulp.plan.io/issues/4896
=> Problem: OpenAPI schema for Uploads APIs is wrong

pulpcore/app/viewsets/upload.py
Solution: remove 'pattern' property
This patch removes the 'pattern' attribute from the OpenAPI schema for the Content-Range
header in the Uploads APIs. The regex is now provided as part of the description. The
generated clients no longer will use the regex to enforce correctness of the header.
[noissue]
=> Problem: Content-Range regex not compatible with Ruby

pulpcore/app/viewsets/upload.py
Solution: remove the extra '\'
This escaping characted causes double escaping to occur when generating Ruby client
using openapi-generator.
[noissue]
=> Problem: regex contains extraneous escape character

pulpcore/app/serializers/progress.py
Do not show task href in every underlying progress report.
closes: #4863
https://pulp.plan.io/issues/4863
Signed-off-by: Pavel Picka <ppicka@redhat.com>
=> Hide task href in each progress

CHANGES/3808.doc, CHANGES/3808.feature, docs/glossary.rst, docs/installation/authentication.rst, docs/installation/configuration.rst, docs/installation/index.rst, pulpcore/app/middleware.py, pulpcore/app/settings.py
This adds REMOTE_USER support which is enabled by default. For
reverse proxy deployments, a new setting is introduced controlling
which WSGI environment var contains the trusted authenticated
username.
A new authentication section is added which contains docs on the
default authentication, how to customize or disable them, and how to
install custom authentication.
https://pulp.plan.io/issues/3808
closes #3808
=> Add REMOTE_USER support

CHANGES/4901.feature, pulpcore/app/serializers/repository.py, pulpcore/app/tasks/repository.py, pulpcore/app/viewsets/repository.py
fixes #4901
https://pulp.plan.io/issues/4901
=> Allow users to remove all content units from repo versions

docs/installation/configuration.rst, docs/installation/instructions.rst
1 commit resolves:
Document permissions for installation (without Ansible installer)
https://pulp.plan.io/issues/2881
The 2 other commits resolve the 2 other lack of documentation issues that I discovered while implementing it.
https://pulp.plan.io/issues/4918
https://pulp.plan.io/issues/4919
=> Permissions & related docs updates

.travis/publish_client_pypi.sh, .travis/script.sh, .travis/test_bindings.py, pulpcore/app/openapigenerator.py, pulpcore/app/viewsets/upload.py
Solution: add ability to request shorter operation ids in the schema
This patch adds ability to specify 'bindings' query parameter when requesting the OpenAPI
schema. When specified, a short OperationId is used for each operation.
This patch also changes how the OpenAPI schema operations are grouped together. Each resource
now has its own tag associated with it. This results in better REST API docs and better
experience for users of bindings.
The tag for a resource is determined from it's URL. The plugin name is omitted from the tag. For
example:
URL: /pulp/api/v3/repositories/
Tag: Repositories
URL: /pulp/api/v3/repositories/uuid-of-some-sort/versions/
Tag: Repositories: Versions
URL: /pulp/api/v3/content/file/files/
Tag: Content: Files
URL: /pulp/api/v3/remotes/file/file/
Tag: Remotes: …
=> Problem: Pulp's OpenAPI schema has verbose Operation Ids

.travis/playbook.yml, .travis/publish_client_gem.sh, .travis/publish_client_pypi.sh, .travis/pulpcore_playbook.yml
Solution: remove extra . from the version string
This also brings in the 'pulp_content_host' setting for the playbook used
to install pulpcore on Travis.
[noissue]
=> Problem: client is failing to publish to PyPI

CHANGES/5016.bug, docs/workflows/upload-publish.rst, pulpcore/app/viewsets/content.py
I confirmed that the REST API docs display 'multipart/form-data'.
fixes #5016
https://pulp.plan.io/issues/5016
=> Allow json to be used to create artifacts from upload

CHANGES/4990.bugfix, CHANGES/4990.doc, docs/components.rst, docs/glossary.rst, docs/index.rst, docs/workflows/index.rst, docs/workflows/on-demand-downloading.rst, pulpcore/app/serializers/repository.py
The core's default mode policy='immediate' is the only one that is
guaranteed by all plugins to implement. Users of plugins that haven't
enabled additional modes should receive an error when then create a
Remote.
Now users using policy != 'immediate' will receive an error.
https://pulp.plan.io/issues/4990
closes #4990
=> Core's Remote only validates 'immediate'

.travis/pre_before_install.sh
In our travis scripts, we're only fetching pulp_file and certguards PRs
but we're not actually checking them out.
[noissue]
=> Check out PR after fetching it

pulpcore/tests/functional/api/using_plugin/test_content_delivery.py
The "lazy" variables are renamed to be "on-demand" to match recent
changes in pulp-smash.
Required PR: https://github.com/pulp/pulp_file/pull/255
[noissue]
=> Updates tests for pulp-smash constant rename

.travis/test_bindings.py
Solution: use an absolute path when uploading a file
[noissue]
=> Problem: bindings test script assumes a working directory

CHANGES/4945.bugfix, CHANGES/4945.removal, pulpcore/app/settings.py
The CONTENT_HOST setting was hard to use with the default of `None`. It
would first be checked in many places, and for example with
``Distribution`` it would give a 500.
This makes the default '' which should be much easier to use in many
places.
https://pulp.plan.io/issues/4945
closes #4945
=> Adjust CONTENT_HOST setting default to ''

setup.py
We cannot fix the incompatibility yet because another dependency,
drf-yasg does not support drf 3.10 yet.
https://github.com/axnsan12/drf-yasg/issues/410
https://pulp.plan.io/issues/5125
re #5125
=> Pin DRF to < 3.10 due to breaking changes

CHANGES/5092.bugfix, pulpcore/app/models/upload.py
The method delete() was redefined in order to prevent
an accumulation of an uploaded content which was not
associated with an artifact. Before this commit, data
were deleted from the database, but not from the local
file system.
closes #5092
https://pulp.plan.io/issues/5092
=> Implement delete method for uploads

pulpcore/tests/functional/api/test_upload.py
Instead of downloading the file chunks every time we call upload_chunks, store the chunks. This prevents these chunks from being downloaded more than once.
[noissue]
=> Store file chunks in upload_test

.gitignore, docs/workflows/upload-publish.rst, pulpcore/app/models/upload.py, pulpcore/app/serializers/upload.py, pulpcore/app/viewsets/upload.py, pulpcore/tests/functional/api/test_upload.py
Enable sending checksum for chunk upload.
https://pulp.plan.io/issues/4982
closes #4982
=> 4982 chunk checksums

CHANGES/5160.doc, docs/installation/configuration.rst
Three urls were broken due to using an absolute url style instead of a
`:ref:` syntax.
https://pulp.plan.io/issues/5160
closes #5160
=> Fix broken urls on configuration page

CHANGES/4722.bugfix, pulpcore/app/serializers/task.py
When a user used _href within the fields selection,
the serializer could fetch a correct value from
_href. This commit removes a need to specify _href
while filtering fields from the response.
When the data model will change, this may cause
performance drawbacks due to serializing all fields
of Task objects.
closes #4722
https://pulp.plan.io/issues/4722
=> Fetch all fields when initializing a serializer

.travis/test_bindings.rb
Solution: add a script for testing with Ruby bindings
re: #4896
https://pulp.plan.io/issues/4896
=> Problem: no script for testing Ruby bindings

pulpcore/app/openapigenerator.py, pulpcore/app/viewsets/upload.py, setup.py
Django restframework 3.10.0 has introduced breaking changes
Unpinning DRF now that a drf-yasg blocker has been fixed
fixes #5125
https://pulp.plan.io/issues/5125
=> Fix breaking changes from DRF 3.10

.gitignore, .travis/post_script.sh, containers/README.md, containers/build.yaml, containers/common_tasks.yaml, containers/images/pulp/Dockerfile, containers/push.yaml, containers/vars/defaults.yaml
Implementation includes:
Build stable and master (latest) versions (tags) of both images.
Use an undefined plugins list for no plugins ather than the
dummy pulpcore-plugin.
Use variables for the pulpcore & pulpcore-plugin pip installs
Use vars/vars.yml as an override for vars
(including the images data structure.)
Start work on installing into the container, and limit the CI builds
to only pulpcore & pulpcore-plugin stable.
fixes: #5116
Handle properly whether to build container images with pulpcore stable or dev
(Actually does more than that.)
https://pulp.plan.io/issues/5116
Includes some work on:
re: #5062
Create pulpcore and pulp_file container images automatically via CI
https://pulp.plan.io/issues/5062
=> containers: Build both stable and dev images, and make images far more configurable.

.gitignore, .travis/post_script.sh, containers/README.md, containers/build.yaml, containers/images/pulp/Dockerfile.j2, containers/vars/defaults.yaml
Implementation includes:
Copying the host dirs into the Docker build environment
Setting the Docker build "context" to the parent dir of the checked out pulpcore
(So that it and all the other cloned repos can be accessed during docker build.)
Users must specify host dirs as relative to the parent dir of pulpcore,
and begin them with "./". This triggers copying logic.
Templating the Dockerfile with jinja2, with some Ansible-bundled filters.
(We've outgrown what env vars in the Dockerfile can do.)
Remove unused Dockerfile variable VERSION
.travis/post_script.sh: Build pulpcore & pulpcore-plugin from Travis host dirs
[noissue]
Partially implements:
re: #5062
https://pulp.plan.io/issues/5062
Create pulpcore and pulp_file container images automatically via CI
=> containers: Support pip install from Travis host dirs

pulpcore/app/viewsets/publication.py
In this commit, a list is returned from the method,
instead of a string. In the past, the string was
decomposed into mutliple characters. These characters
were used as unique identifiers that locked resources
(https://github.com/pulp/pulpcore/blob/452ab51d6195a0c0c4cdeb8220b37afb2a747ca5/pulpcore/tasking/tasks.py#L192).
[noissue]
=> Return a list of reserved resources

CHANGES/4681.misc, pulpcore/app/models/base.py
Making mandatory declaring default_related_name
closes #4681
https://pulp.plan.io/issues/4681
=> Avoid collisions between plugin models

CHANGES/4931.feature, pulpcore/app/viewsets/custom_filters.py, pulpcore/app/viewsets/task.py, pulpcore/tests/functional/api/test_tasks.py
closes #4931
https://pulp.plan.io/issues/4931
=> Enable user to filter tasks by created_resources

pulpcore/tests/functional/api/using_plugin/constants.py, pulpcore/tests/functional/api/using_plugin/test_sync_multiple_plugins.py
Add tests to sync different remotes: docker, rpm, file in the same
repository.
https://pulp.plan.io/issues/4274
closes:#4274
=> Add test to sync different remotes same repository

containers/README.md, containers/build.yaml
Due to 2 bugs so far with accessing Fedora mirrors or servers via dnf.
Fedora is fixing them, but disrupts our development temporarily as we
implement specific workarounds.
Solution: Implement the generic workaround of retrying the image
build.
[noissue]
=>  Problem: container images randomly fail to build

CHANGES/5290.misc, pulpcore/app/settings.py
- Includes default settings from `{plugin_name}/app/settings.py`
- This settings overrides the data existing in `/etc/pulp/settings.py`
- This settings are overridden by env vars prefixed with `PULP_`
- So a good practice for plugin writers is to prefix the default configs with plugin name such as `RPM`, `FILE`, `ANSIBLE` etc...
example:
`ANSIBLE_SOMEKEY = 'value'` on  `{plugin_name}/app/settings.py` can be overriden via 
`export PULP_ANSIBLE_SOMEKEY='othervalue'`
closes #5290
https://pulp.plan.io/issues/5290
=> Add load of plugin default settings.

containers/images/pulp/Dockerfile.j2
And we are currently working around it with a generic workaround
of retrying the image build.
solution: Implement a temporary workaround of installing the Fedora
curl Errata that fixes the dnf HTTP2 error:
https://bodhi.fedoraproject.org/updates/FEDORA-2019-ae52a20ff6
[noissue]
=> Problem: Container images randomly fail to build due to dnf HTTP2 error

containers/images/pulp/container-assets/pulp-api, containers/images/pulp/container-assets/pulp-content, containers/images/pulp/container-assets/pulp-resource-manager, containers/images/pulp/container-assets/pulp-worker
Solution: Bind to IPv6, and thus impliclty IPv4.
This implicit listen can reliably happen in containers because of
network namespaces.
Also, standardize container script syntax.
Fixes: #5414
HTTP requests to containers hang over IPv6
https://pulp.plan.io/issues/5414
re: #5375
As a user, I can use a single script to install k3s and launch pulp-operator
https://pulp.plan.io/issues/5375
=> Problem: HTTP requests to containers hang over IPv6

.travis/install.sh
Solution: regenerate with latest plugin-template
[noissue]
=> Problem: CI fails with dependabot, which uses a / in git branch names

.travis.yml
Solution: Disable install phase for all deploy & publish steps.
Which is unnecessary, and slows down the CI.
Solution: regenerate with latest plugin-template
[noissue]
Note: I am only able to partially test this. On Travis mikeded333/pulpcore, the publishing task does not attempt to run the install script. However, it cannot push the docs due to lack of credentials (in Travis env vars.)
https://travis-ci.com/mikedep333/pulpcore/jobs/231988570#L565
=> Problem: Containers are built when publishing plugin to PyPI

CHANGES/5190.doc, pulpcore/app/viewsets/upload.py
closes #5190
https://pulp.plan.io/issues/5190
=> Update REST API docs for `uploads_commit`

pulpcore/app/serializers/content.py
We also should pop the relative_path off validated_data if the
serializer doesn't have the relative_path as a field.
fixes #5445
https://pulp.plan.io/issues/5445
=> Remove the relative_path if not on serializer fields

CHANGES/5533.bugfix, CHANGES/5533.removal, pulpcore/app/viewsets/base.py
If there is no Master viewset, don't automatically try to namespace the
viewset endpoint as it erroneously namespaces the endpoint with the
detail viewset's endpoint_name.
fixes #5533
https://pulp.plan.io/issues/5533
=> Fix Detail viewsets erroneous namespacing

CHANGES/5519.feature, CHANGES/5519.removal, pulpcore/app/openapigenerator.py, pulpcore/app/serializers/base.py, pulpcore/tests/functional/api/test_crud_repos.py, pulpcore/tests/functional/api/test_tasks.py, pulpcore/tests/functional/api/using_plugin/test_crd_publications.py
=> Expose exclude_fields in the REST API schema

pulpcore/app/openapigenerator.py
If a plugin uses a serializer with a HiddenField, the generator
crashed because it did not expect a None value for a field.
Fix this by catching the None case.
[noissue]
=> Fix open API generator crash on hidden field

containers/common_tasks.yaml
Solution: Use Ansible 2.5+ test syntax rather than the deprecated test
syntax, which is now removed (and gets confused with filter syntax) on
2.9.
[noissue]
=> Problem: Container builds fail on Ansible 2.9

CHANGES/5008.misc, pulpcore/app/models/content.py, pulpcore/app/models/repository.py
The `Content` model now supports a `repo_key` attribute which defaults
to (). Plugin writers can specify this, and the tuple field names will
automatically replace another unit of the same type with these field
names.
Required PR: https://github.com/pulp/pulp_file/pull/290
https://pulp.plan.io/issues/5008
closes #5008
=> Add repo_key support for `add_content`

CHANGES/5353.misc, doc_requirements.txt, pulpcore/app/models/content.py, pulpcore/app/models/publication.py, pulpcore/app/models/repository.py, pulpcore/download/__init__.py, pulpcore/download/base.py, pulpcore/download/factory.py, pulpcore/download/file.py, pulpcore/download/http.py, setup.py
Moving all the methods for:
Content, ContentGuard, Remote and Publisher
from pulpcore-plugin to pulpcore
closes #5353
https://pulp.plan.io/issues/5353
=> Moving method from pulpcore-plugin models

CHANGES/5560.feature, docs/installation/configuration.rst, pulpcore/app/settings.py
This changes Pulp to not assume any settings file is needed or looked
for at all. It encourages the user to set one via the `PULP_SETTINGS`
Environment Variable. The settings documentation was updated to reflect
this.
The Installer will continue working as is. The PR below causes the
installer to set `PULP_SETTINGS` correctly allowing settings to work the
same way in those environments.
Required PR: https://github.com/pulp/ansible-pulp/pull/182
https://pulp.plan.io/issues/5560
closes #5560
=> Remove hard coded `/etc/pulp/settings.py` file

CHANGES/5028.misc, pulpcore/app/models/repository.py
Allowing to create a repository version without dispatching a task.
closes #5028
https://pulp.plan.io/issues/5028
=> Repository version creation w/o CreatedResource

CHANGES/5621.bugfix, pulpcore/app/viewsets/base.py
The ordering parameter is used by DRF to order results and should not be
considered an invalid parameter on GET requests.
refs #5621
=> Fix bug where ordering filter raised 400

CHANGES/5631.feature, pulpcore/app/serializers/status.py, pulpcore/app/views/status.py, pulpcore/tests/functional/api/test_status.py
Currently Katello has the ability to query the Pulp storage usage. This is implemented via the smart_proxy_pulp project. This requires the Smart Proxy to be colocated with Pulp. The colocation also makes deployment in Kubernetes harder. It won't work with S3 unless a lot of duplication with Pulp itself is done. By providing it in the Pulp API, this can be
avoided.
Currently it's only implemented for local filesystem storage.
This is currently more of a draft to see what the ideas about implementing this are. If this is not desired at all or if this should be a plugin, I'd rather not waste my time writing a fully working implementation. If there is, I'll look into writing the correct tests and making sure this works properly.
https://pulp.plan.io/issues/5631
=> Provide storage information in the status API

.travis/test_bindings.py, .travis/test_bindings.rb, CHANGES/5574.misc, CHANGES/plugin_api/5574.doc, docs/plugins/reference/how-to-doc-api.rst, pulpcore/app/serializers/base.py
Use the `__init_subclass__` method added in Python 3.6 to customize
subclasses of pulpcore's ModelSerializer class.
If it is not yet defined, set the `Meta.ref_name` attribute according to
the best practice established within Pulp (`'<app label>_<model name>'`).
closes #5574
https://pulp.plan.io/issues/5574
=> Set default `ref_name` attribute for a ModelSerializers's `Meta` class.

.travis/test_bindings.rb, pulpcore/app/serializers/content.py, pulpcore/tests/unit/serializers/test_content.py
When refactoring the upload mechanics away from the artifacts endpoint, this
has been missed.
[noissue]
=> Make file required on ArtifactSerializer

docs/installation/storage.rst
[noissue]
Documented the fact that when the `BlockPublicAcls` option is set either at the bucket or account level, the default value for `AWS_DEFAULT_ACL` of `public-read` will result in AccessDenied errors. To fix it, simply set this setting to None.
=> Documented a gotcha with the default ACL used by django-storages

CHANGES/5378.feature, pulpcore/content/handler.py
This patch enables users to browse each distribution. However, the /pulp/content/ endpoint
continues to return a 404.
When a user requests the 'base_url' of a Distribution or any path that ends in '/' inside the
Distribution's 'base_url' path, the pulpcore-content app looks for either a PublishedArtifact
or ContentArtifact with a relative path equal to <requested path>'index.html'. If no such
relative path is found for the RepositoryVersion or Publication, an HTML page is dynamically
generated and returned.
closes #5378
https://pulp.plan.io/issues/5378
=> Return HTML listing of directories served by content app

CHANGES/5397.feature, pulpcore/content/__init__.py, pulpcore/content/handler.py
This patch enables the user to browse :24816/pulp/content/ to see the list of available
distributions.
closes: #5397
https://pulp.plan.io/issues/5397
=> pulpcore-content return  HTML list of avaiable distributions

CHANGES/5622.bugfix, pulpcore/app/openapigenerator.py, pulpcore/app/serializers/publication.py
https://pulp.plan.io/issues/5622
closes #5622
=> Handling write_only fields on OpenAPISchema

CHANGES/plugin_api/3541.feature, CHANGES/plugin_api/3541.removal, docs/plugins/api-reference/download.rst, docs/plugins/api-reference/stages.rst, docs/plugins/plugin-writer/concepts/sync_pipeline/sync_pipeline.rst, pulpcore/app/models/content.py, pulpcore/app/models/repository.py, pulpcore/app/viewsets/repository.py, pulpcore/download/factory.py, pulpcore/download/http.py, pulpcore/plugin/actions.py, pulpcore/plugin/repo_version_utils.py, pulpcore/plugin/stages/__init__.py, pulpcore/plugin/stages/api.py, pulpcore/plugin/stages/association_stages.py, pulpcore/plugin/stages/declarative_version.py, pulpcore/tests/functional/api/using_plugin/test_pagination.py, pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
This PR adds a central place for plugin writers to put validation and 
content modification code.
* `RepositoryVersion.__exit__` calls `finalize_new_version`
* Moves the `/modify/` endpoint to `pulpcore.plugin.actions` as a mixin
named `ModifyRepositoryActionMixin`.
* Renames `Repository.repo_key` to `Repository.repo_key_fields`.
* Remove the `RemoveDuplicates` stage for plugin writers to instead use 
`Repository.finalize_new_version`
* Remove the implicit usage of `RemoveDuplicates` from
`RepositoryVerison.add_content` and `RepositoryVersion.remove_content`.
* Make the `RemoveDuplicates` available as
`pulpcore.plugin.repo_version_utils.remove_duplicates`.
As an unrelated change, it also replaces the the `>>>` python
codeblocks in various docblocks with python codeblock using `::` and …
=> Add Repository.finalize_new_version

CHANGES/3308.feature, CHANGES/3308.removal, docs/concepts.rst, pulpcore/app/models/repository.py, pulpcore/tests/functional/api/using_plugin/test_crd_publications.py, pulpcore/tests/functional/api/using_plugin/test_distributions.py, pulpcore/tests/functional/api/using_plugin/test_repo_versions.py, pulpcore/tests/functional/api/using_plugin/test_tasks.py
closes: #3308
https://pulp.plan.io/issues/3308
=> Don't create a new repository version if no content was added or removed.

CHANGES/5733.bugfix, CHANGES/plugin_api/5733.bugfix, pulpcore/app/models/base.py
The pulp_type field is different than TYPE (eg file.file vs file).
fixes #5733
https://pulp.plan.io/issues/5733
=> Fix __str__ method pulp_type for master models

.travis/install.sh, .travis/test_bindings.py, .travis/test_bindings.rb, CHANGES/5760.bugfix, pulpcore/app/openapigenerator.py
The prefix for the *_repository_version_href was getting applied to *_repository_href slug
names. This patch limits it to only *_repository_version_href.
re: #5760
https://pulp.plan.io/issues/5760
=> Fix repository parameter name in OpenAPI schema

containers/vars/defaults.yaml
(noissue because it only affects the container vars that are currently only a
reference for manually building the all-in-one image.)
[noissue]
=> containers: Adapt for pulp_container rename

CHANGES/5722.doc, docs/index.rst, docs/integration-guide/index.rst, docs/rest_api.rst
We originally wanted the left-side navigation link to directly link to
the ../restapi.html page, but sphinx doesn't allow for that. The
left-navigation comes from the toctree, which requires each entry to be
a page.
https://pulp.plan.io/issues/5722
closes #5722
=> Move Rest API to its own section.

CHANGES/5673.bugfix, pulpcore/tasking/util.py
https://pulp.plan.io/issues/5673
closes #5673
=> Release resources when worker is cleaned up

CHANGES/5786.bugfix, CHANGES/5786.removal, pulpcore/app/serializers/status.py, pulpcore/app/serializers/task.py, pulpcore/app/views/status.py, pulpcore/tests/functional/api/test_status.py, pulpcore/tests/functional/api/test_workers.py
Having "missing_workers" did not work well when worker names are unique
each time. It accumulated an endless number of worker names.
https://pulp.plan.io/issues/5786
closes #5786
=> Remove "missing_workers" from Status API

CHANGES/5716.doc, docs/components.rst
In this commit, there is also removed a redundant note about configuring static content.
This paragraph started to rot after the following commit https://github.com/pulp/pulpcore/commit/aa79d05c669802e58d75f6bd3340a948ecb9cf93
closes #5716
https://pulp.plan.io/issues/5716
=> Move the section Static Content to Architecture and Deploying

.travis/install.sh, .travis/pre_before_install.sh, template_config.yml
to specify pulp_file's branch instead of pulpcore_branch.
Solution: re-generate with latest template, and update
pre_before_install.sh to read additional_plugins.
re: https://github.com/pulp/pulpcore/pull/409
re: #5810
plugin-template and pulpcore should use additional_plugins var to specify the pulp_file branch
https://pulp.plan.io/issues/5810
[noissue]
=> Problem: plugin-template & pulpcore should use additional_plugins

CHANGES/5787.feature, containers/images/pulp/container-assets/pulp-worker, docs/components.rst, docs/installation/instructions.rst, pulpcore/app/models/task.py, pulpcore/tasking/constants.py, pulpcore/tasking/services/worker_watcher.py, pulpcore/tasking/worker.py, pulpcore/tests/functional/api/test_workers.py
Requiring users to specify a name for task workers was difficult and not
productive. Having workers auto-name as {pid}@{hostname} is much easier
to operate.
This also updates the docs to match.
https://pulp.plan.io/issues/5787
closes #5787
=> Workers now auto-name {pid}@{hostname}

CHANGES/3707.doc, CHANGES/3707.feature, CHANGES/3707.removal, containers/images/pulp/container-assets/pulp-resource-manager, docs/components.rst, docs/installation/instructions.rst, pulpcore/app/models/task.py, pulpcore/tasking/services/worker_watcher.py, pulpcore/tasking/worker.py
The resource manager name must exctly equal `resource-manager` and
multiple of them can be started at once safely.
https://pulp.plan.io/issues/3707
closes #3707
=> Allow multiple resource-managers to be started

CHANGES/plugin_api/5559.feature, doc_requirements.txt, pulpcore/app/files.py, pulpcore/plugin/publication_utils.py, pulpcore/plugin/repo_version_utils.py, pulpcore/tests/unit/test_files.py, setup.py
fixes #5559
https://pulp.plan.io/issues/5559
pulp_file PR: https://github.com/pulp/pulp_file/pull/325
=> Add validation to check for file path overlaps

.travis/install.sh, .travis/pre_before_install.sh, template_config.yml
to specify pulp_file's branch instead of pulpcore_branch.
Solution: re-generate with latest template, and update
pre_before_install.sh to read additional_plugins.
re: https://github.com/pulp/pulpcore/pull/409
re: #5810
plugin-template and pulpcore should use additional_plugins var to specify the pulp_file branch
https://pulp.plan.io/issues/5810
[noissue]
=> 3.0: Problem: plugin-template & pulpcore should use additional_plugins

CHANGES/5688.bugfix, pulpcore/app/models/progress.py, pulpcore/app/models/repository.py, pulpcore/app/util.py, pulpcore/plugin/stages/api.py, pulpcore/plugin/stages/artifact_stages.py, pulpcore/plugin/stages/content_stages.py
https://pulp.plan.io/issues/5688
ref #5688
=> Improve speed and memory performance of syncing

containers/images/pulp/Dockerfile.j2
until they release the Errata.
So that python3-libcomps can have .egg-info metadata available
for pip to see that libcomps is already satisfied for pulp_rpm.
They already released the corresponding Errata for Fedora 31,
so this should be very safe.
Also, cleanup currently unneeded -devel packages.
[noissue]
re: #5840
as a user of pulp_rpm_prerequisites I have libcomps installed from pypi
https://pulp.plan.io/issues/5840
=> containers: Use Fedora 30's test Errata for libcomps

CHANGES/4592.doc, README.md
Pulp is GPLv2+ licensed not GNUv2. GNUv2 isn't technicall a license
either.
https://pulp.plan.io/issues/4592
closes #4592
=> Fix incorrect licensing claim

CHANGES.rst, CHANGES/4592.doc, CHANGES/5563.doc, CHANGES/5688.bugfix, CHANGES/5701.feature, CHANGES/5714.doc, CHANGES/5721.doc, CHANGES/5726.doc, CHANGES/plugin_api/5701.feature
In addition to the `towncrier` auto-generated changelog, this adds a
note about the values of the "name" field in the Task API possibly
changing in future versions.
[noissue]
(cherry picked from commit 10f58a2534f24b597b4c4db315b912b3dcc41918)
=> Adds changelog

CHANGES/5668.removal, docs/plugins/api-reference/stages.rst, pulpcore/plugin/stages/api.py, pulpcore/plugin/stages/content_stages.py, pulpcore/plugin/stages/models.py, pulpcore/tests/unit/stages/test_stages.py
=> Thaw queues on awaiting stuck futures

.travis/before_install.sh, CHANGES/5867.misc, docs/contributing/git.rst, docs/contributing/pull-request-walkthrough.rst, docs/contributing/tests.rst, functest_requirements.txt, pulpcore/tests/functional/api/test_api_docs.py, pulpcore/tests/functional/api/test_crd_artifacts.py, pulpcore/tests/functional/api/test_status.py, pulpcore/tests/functional/api/test_workers.py, pulpcore/tests/functional/api/using_plugin/test_crd_publications.py, pulpcore/tests/functional/api/using_plugin/test_crud_repos.py, pulpcore/tests/functional/api/using_plugin/test_distributions.py, pulpcore/tests/functional/api/using_plugin/test_orphans.py, pulpcore/tests/functional/api/using_plugin/test_repo_versions.py, pulpcore/tests/functional/api/using_plugin/test_tasking.py, pulpcore/tests/functional/api/using_plugin/test_tasks.py
=> Updating references to PulpQE repos

.travis.yml, .travis/nginx.conf, .travis/pre_before_script.sh, CHANGES/5873.misc, pulpcore/tests/functional/api/using_plugin/constants.py
https://pulp.plan.io/issues/5873
closes #5873
=> Generating fixture internally

CHANGES/plugin_api/5706.feature, pulpcore/app/models/repository.py, pulpcore/tests/unit/models/test_repository.py
https://pulp.plan.io/issues/5706
closes #5706
=> List added/removed content according to a given RepositoryVersion

CHANGES/5707.bugfix, pulpcore/app/models/repository.py, pulpcore/tests/unit/models/test_repository.py
When adding and removing the same content in a repository version, don't
update the RepositoryContent record (resulting in an superfluous
RepositoryContent for which version_added == version_removed == current
version).  Instead, just delete the existing record.  This fixes two
problems:
1. Such content is shown as added and removed.
2. Re-adding the content again in the same version leads to a
IntegrityError because the uniqueness constraint is violated.
Handle the "remove then re-add" case analogously.
https://pulp.plan.io/issues/5707
closes #5707
=> Avoid superfluous RepositoryContent records

CHANGES/5870.misc, CHANGES/5941.bugfix, CHANGES/plugin_api/5941.removal, pulpcore/app/models/storage.py
Django would move files in cases where the source was a file:///
repository.
https://pulp.plan.io/issues/5941
closes #5941
https://pulp.plan.io/issues/5870
closes #5870
=> Copy files when they originate out of MEDIA_ROOT

.travis/docs-builder.py, CHANGES/5833.misc
This patch improves the .travis/docs-builder.py script. The script will always publish GA docs to
the root of docs.pulpproject.org. The same docs are also published into the docs.pulpproject.org/en/3.y/
directory. The same docs are also published to docs.pulpproject.org/en/3.y.z/ for long term storage.
Pre-release builds are always published into docs.pulpproject.org/en/<tag>/.
Nightly docs are pubished to docs.pulpproject.org/<branch_name>/nightly/.
closes: #5833
https://pulp.plan.io/issues/5833
=> Publishes GA docs to docs.pulpproject.org/

CHANGES/5955.bugfix, CHANGES/5955.removal, pulpcore/app/authentication.py, pulpcore/app/middleware.py, pulpcore/app/settings.py
Move all authentication fully to DRF. We were incorrectly configuring
webserver auth support in django and not DRF. This ports the setting
`REMOTE_USER_ENVIRON_NAME` to work with DRF instead of Django.
It adjusts the settings.py so there are removal claims even though this
will likely go into a z-release. It's an important FYI for the user.
https://pulp.plan.io/issues/5955
closes #5955
=> REMOTE_USER auth shouldn't trigger csrf rejects

.travis/install.sh
Is due to k3s interpreting the 3.0 image tag as 3 due to lack of
quotes.
And therefore thinking the image does not exist (ImagePullBackoff)
Solution: regenerate with latest plugin-template, but merge in changes
made to pulpcore master but not plugin-template master.
[noissue]
=> Problem: pulpcore 3.0 CI is failing.

CHANGES/6002.bugfix, pulpcore/plugin/actions.py
The OpenAPI schema definition of repository modify operation was missing a human readable
operation summary. This patch adds it.
fixes: #6002
https://pulp.plan.io/issues/6002
=> Adds 'Modify Repository Content' operation summary

CHANGES/plugin_api/6024.feature, pulpcore/app/models/repository.py, pulpcore/tests/unit/models/test_repository.py
Plugins need to iterate over the content in a repository version to create a publication.
`RepositoryVersion.content_batch_qs()` generates content batches to
efficiently iterate over all content.
fixes: #6024
https://pulp.plan.io/issues/6024
=> Add a batching content iterator `content_batch_qs()` to `RepositoryVersion`

CHANGES/6038.bugfix, setup.py
=> Re-pin redis version to fix freezing issue

CHANGES/5949.doc, CHANGES/5949.feature, CHANGES/5949.removal, docs/installation/authentication.rst, pulpcore/app/authentication.py, pulpcore/app/settings.py
This PR comes with a few changes:
- Significantly revamp the authenticaiton docs
- Adds a Pulp Backend that will not create users by default
- Removes the RemoteUserBackend disabling external auth by default
https://pulp.plan.io/issues/5949
closes #5949
=> Remove Remote Auth by Default

CHANGES/4733.bugfix, CHANGES/plugin_api/4733.removal, pulpcore/content/handler.py
The filename is specified as part of the redirect url.
This also changes the Handler's interface for the plugin writer, and
there is a changelog entry with more details.
closes #4733
https://pulp.plan.io/issues/4733
=> Have S3 and Azure redirect specify filename

CHANGES/plugin_api/5868.feature, pulpcore/app/models/fields.py, pulpcore/app/viewsets/base.py
fixes #5868
https://pulp.plan.io/issues/5868
=> Add a "not equal" lookup for filters

CHANGES/5995.bugfix, pulpcore/app/settings.py
This directory name is already being used by Pulp 2. As a result the SELinux policies for Pulp 2 and
Pulp 3 are conflicting. After this change, the two SELinux policies can explicitly name the directories
inside /var/lib/pulp/ that they manage.
re: #5995
https://pulp.plan.io/issues/5995
=> Renames /var/lib/pulp/static/ to /var/lib/pulp/assets/.

CHANGES/6169.bugfix, setup.py
The `yarl` and `requests` packages are sub-dependencies of pulpcore, and
have conflicting version needs for idna. With idna==2.9 released, this
prevents Pulp from installing. This temporary pin will ensure idna==2.8
is released which all versions are satisfied with.
https://pulp.plan.io/issues/6169
closes #6169
=> Pin `idna==2.9` to resolve conflicting packages

CHANGES.rst, CHANGES/5567.bugfix, CHANGES/6045.bugfix, CHANGES/6077.bugfix, CHANGES/6154.bugfix, CHANGES/6169.bugfix, CHANGES/plugin_api/6045.feature
[noissue]
(cherry picked from commit e27753d75d1e9af782b886e0e22953aba9c1a422)
=> Adds 3.1.1 changelog

CHANGES/6025.bugfix, pulpcore/app/serializers/fields.py, pulpcore/app/serializers/repository.py
In this commit, there was also fixed the documentation. The field itself returns a hash of a file content, not a hash of a certificate stored within a file.
closes #6025
https://pulp.plan.io/issues/6025
=> Do not trim leading and trailing whitespace characters

CHANGES/5859.doc, CHANGES/5859.feature, docs/components.rst, docs/contributing/tests.rst, docs/installation/authentication.rst, docs/installation/instructions.rst, docs/plugins/api-reference/profiling.rst, docs/plugins/plugin-writer/concepts/index.rst, docs/plugins/plugin-writer/concepts/subclassing/models.rst, docs/plugins/reference/how-plugins-work.rst, docs/workflows/signed-metadata.rst, pulpcore/app/manage.py, setup.py
This add the `pulpcore-manager` script which is an alias for `manage.py`
only correctly configured to know where the Pulp settings app is
already.
This change includes docs which recommend users apply migrations with
`pulpcore-manager` instead of `manage.py`.
Originally inspired by this PR from @evgeni:
https://github.com/pulp/pulpcore/pull/445/files
https://pulp.plan.io/issues/5859
closes #5859
=> Adds pulpcore-manager console command

CHANGES/6227.bugfix, pulpcore/download/factory.py, pulpcore/download/http.py
Pulp is getting redirected and sending the Remote's credentials to the
redirected location. Looks like if we set the credentials on the request
instead of the session, aiohttp will only send the credentials to
redirected locations when the domains match which is the behavior we
want.
=> Stop sending basic auth credentials to redirect location

containers/images/pulp/Dockerfile.j2
A new version of pip is needed to use Manylinux2014 pre-built wheels.
Pre-built wheels allows us to avoid installing some of the RPMs.
[noissue]
=> Update pip inside of the container

CHANGES/plugin_api/6249.doc, docs/plugins/plugin-writer/concepts/index.rst
The MANIFEST.in part of the webserver was missing from the snippets
guide for plugin writers.
https://pulp.plan.io/issues/6249
closes #6249
=> Added MANIFEST.in part to web server snippets docs

.travis.yml, .travis/before_script.sh, .travis/cherrypick.py, .travis/install.sh, .travis/pre_before_install.sh, .travis/script.sh, containers/images/pulp/Dockerfile.j2, pulpcore/tests/unit/models/test_content.py, template_config.yml
=> Running tests on minio

CHANGES/plugin_api/6342.doc, CHANGES/plugin_api/6342.misc, docs/plugins/reference/metadata-signing.rst, pulpcore/app/models/content.py
fixes #6342
https://pulp.plan.io/issues/6342
This is based on my experience of implementing the `AptReleaseSigingService` class here: https://github.com/pulp/pulp_deb/pull/160
I found that I replicated some of the exact same functions as for the `AsciiArmoredDetachedSigningService` since the only thing that is really different for different signing services is the validation. I therefore moved the reusable functions into the parent class, and split out a dedicated `validate` function from the existing `save` function. The Idea is that this is the one and only function that needs to be provided by each subclass of `SigningService`.
=> Refactor the existing SigningService classes

CHANGES/6373.bugfix, pulpcore/plugin/stages/api.py, pulpcore/plugin/stages/artifact_stages.py, pulpcore/plugin/stages/content_stages.py
Increase the performance of the QueryExisting* stages. pulp_created=None
was originally picked because it wouldn't match with anything, and an empty
Q() object matches with everything. But it's a lookup on an unindexed field
that requires looking at an entirely different table, so it ends up
being incredibly inefficient. It turns out that there is a way to
accomplish the same thing that gets compiled out of the query entirely.
[noissue]
=> Dramatically increase re-sync performance

CHANGES/6372.bugfix, pulpcore/app/openapigenerator.py
This ensures that when the endpoints are sorted, the parent endpoint appears before the
endpoints nested under it.
fixes: #6372
https://pulp.plan.io/issues/6372
=> Normalize PK path parameter names used in openapi schema generation

.travis/install.sh
Solution: Regenerate with latest plugin-template
re: #6405
https://pulp.plan.io/issues/6405
Trailing underscores in branch names breaks CI
[noissue]
=> Problem: Trailing underscores in branch names breaks CI

CHANGES/plugin_api/6362.feature, CHANGES/plugin_api/6362.removal, pulpcore/app/models/repository.py, pulpcore/plugin/repo_version_utils.py
fixes #6362
https://pulp.plan.io/issues/6362
Plugin example: https://github.com/pulp/pulp_file/pull/368
I decided not to update remove_duplicates to handle checking for duplicate content because (a) it would violate the single responsibility principle as remove_duplicates removes existing content from the repo version if it collides with content being added. 
Also (b) [remove_duplicates is called at the beginning of finalize before processing happens](https://github.com/pulp/pulp_rpm/blob/417541e71655f10045f5e6f5f8cb156dff7972ff/pulp_rpm/app/models/repository.py#L127) while validation ought to happen at the end.
=> Checking for dupe content in finalize

CHANGES/6420.bugfix, containers/images/pulp/container-assets/pulp-common-entrypoint.sh
to be run, only "bash"
Solution: Only apply the /bin/ logic for the 4 pulp-* commands.
fixes: #6420
Pulp containers do not allow commands like "/bin/bash" to be run, only "bash"
https://pulp.plan.io/issues/6420
=> Problem: Pulp containers do not allow commands like "/bin/bash"

CHANGES/6461.doc, containers/images/pulp/Dockerfile.j2, docs/client_bindings.rst, docs/contributing/dev-setup.rst, docs/installation/instructions.rst, docs/plugins/plugin-writer/concepts/index.rst
The pulpcore docs are an especially important thing to update, and they deserve a proper changelog entry.
(Especially because ansible-pulp releases correspond to pulpcore releases.)
fixes: #6461
Rename ansible-pulp to pulp_installer in pulpcore
https://pulp.plan.io/issues/6461
=> Rename ansible-pulp to pulp_installer in pulpcore

CHANGES/6482.misc, pulpcore/app/tasks/repository.py
closes: #6482
https://pulp.plan.io/issues/6482
=> Makes repository repair task compatible with Python 3.6

CHANGES/6485.docs, docs/concepts.rst, docs/from-pulp-2.rst, docs/glossary.rst, docs/workflows/promotion.rst
With the release of sphinx 3.0.1 came a new error during docs builds:
/home/travis/build/pulp/pulpcore/docs/components.rst:40:term not in glossary: artifact
fixes #6485
=> Fixing sphinx error about undefined terms

CHANGES/6523.bugfix, containers/images/pulp/Dockerfile.j2
on the pulp-operator pulp container because Fedora's createrepo_c
is too old
Solution: Temporarily replace the createrepo_c RPM with its
build-dependencies, and let createrepo_c get installed &
built from PyPI.
fixes: #6523
=> Problem: pulp_rpm 3.3.0 cannot install

CHANGES/plugin_api/6563.bugfix, pulpcore/plugin/viewsets/__init__.py
Used in plugins: https://github.com/pulp/plugin_template/blob/24dc0c7cb725620ae92b6771dc902edf08386077/templates/bootstrap/plugin_name/app/viewsets.py.j2#L14
fixes #6563
=> Fixed missing RemoteFilter object

CHANGES/6484.feature, CHANGES/6484.removal, pulpcore/app/tasks/importer.py
=> Add child tasks for processing repo version imports

CHANGES/6573.bugfix, pulpcore/app/serializers/task.py
=> Fixed bug where TaskGroup was showing up as null

CHANGES/plugin_api/6603.feature, pulpcore/plugin/models/__init__.py
Somehow this never got added to the plugin API even though I remember making the change, it must have gotten accidentally stashed or something.  There's already a changelog entry... we can send this out in a Y release.
re: #6414
https://pulp.plan.io/issues/6414
=> Add task groups to the Plugin API

CHANGES/6569.bugfix, pulpcore/app/tasks/repository.py, pulpcore/app/viewsets/repository.py
Repository update and delete now use general_update and general_delete, which
automatically select the proper resources to work on.
fixes #6569
https://pulp.plan.io/issues/6569
=> Revamp Repository tasks

CHANGES/plugin_api/6570.feature, CHANGES/plugin_api/6570.removal, docs/plugins/api-reference/content-app.rst, pulpcore/app/models/publication.py, pulpcore/content/handler.py
See https://pulp.plan.io/issues/6570
This implements a `content_handler` function in `BaseDistribution` to allow plugin writers to serve non-Artifact content from their plugin. It also adds a `content_handler_directory_listing` function in `BaseDistribution` that allows plugin writers to add these 'files' to the directory listings.
On how this can be used, see https://github.com/pulp/pulp_rpm/pull/1687
Please comment on the code (and where perhaps an `await` or `async` could be added). Once the code is "good enough", I'll add tests.
=> Add content handler to distribution

CHANGES/6346.bugfix, CHANGES/plugin_api/6346.removal, pulpcore/app/serializers/repository.py
https://pulp.plan.io/issues/6346
closes #6346
=> Return username and password when requesting Remote

CHANGES/6674.doc, docs/installation/instructions.rst
https://pulp.plan.io/issues/6674
close #6674
Inspired by: https://pulp-ansible.readthedocs.io/en/latest/installation.html#install-using-ansible
=> Introduced brief explanation about pulp_installer

CHANGES/6691.removal, pulpcore/app/serializers/__init__.py, pulpcore/app/serializers/fields.py, pulpcore/app/serializers/repository.py
fixes #6691
https://pulp.plan.io/issues/6691
=> Make ssl certs and keys accessible through RESTAPI

CHANGES/6802.bugfix, pulpcore/content/handler.py
fixes: #6802
https://pulp.plan.io/issues/6802
=> Adds proper headers for index.html pages served by content app

pulpcore/tests/functional/utils.py
Adding more info to print statement when a task group fails to complete
in order to better debug some task group failures in Travis.
[noissue]
=> Better debugging for task group monitoring in tests

CHANGES/6831.bugfix, pulpcore/content/handler.py
This header is not needed because the server is not actually encoding the response.
fixes: #6831
https://pulp.plan.io/issues/6831
=> Removes Content-Encoding header from pulpcore-content responses.

CHANGES/6775.bugfix, pulpcore/app/openapigenerator.py
https://pulp.plan.io/issues/6775
closes #6775
=> Splitting seralizers into read and write ones

docs/plugins/plugin-writer/concepts/sync_pipeline/sync_pipeline.rst
Add a hint to batch futures.
[noissue]
=> Remove deprecated warning for does_batch

CHANGES/7017.doc, docs/bugs-features.rst, docs/contributing/pull-request-walkthrough.rst, docs/index.rst, docs/plugins/index.rst, docs/workflows/index.rst
I updated the link to the Pulp 3 plugins that was out of date in the docs.
=> Fix broken link from website update

docs/contributing/git.rst
[noissue]
Just a suggestion.
I find myself repeatedly scanning the page for these and not finding them :wink:
=> Make the permitted changelog extensions more prominent

CHANGES/7073.bugfix, pulpcore/app/tasks/importer.py
THIS IS A TEMPORARY FIX to prevent test_pulpimport failures from
blocking unrelated commits. See the related issue for other
approaches.
Success can be tested in a dev-env with the following bash cmd:
for i in {1..10}; do
(pytest -v -r sx --color=yes --pyargs \
pulpcore.tests.functional.api.using_plugin.test_pulpimport > $i.out &)
done
Without this fix, each run sees 1-4 tests fail due to deadlock.
With the fix, repeated executions have shown no failures.
fixes #7073
=> Prevents deadlock by locking core_content across update.

CHANGES/6915.bugfix, pulpcore/app/viewsets/content.py, pulpcore/app/viewsets/repository.py, pulpcore/app/viewsets/task.py, pulpcore/app/viewsets/upload.py
Changes include:
* Meta.fields list may only reference fields that exist in Meta.model
* 'exact' is redundant in Meta.fields qualifiers (per Mongo docs)
* Upload.completed was removed in cf5bad, remove referencing filter
closes #6915
=> Remove non-model-fields from Meta.fields of filters

CHANGES/6504.bugfix, pulpcore/tasking/services/storage.py
WorkerDirectory.delete() now only tries one additional time to delete its directory tree after encountering a PermissionError
fixes #6504
https://pulp.plan.io/issues/6504
=> Fixed WorkerDirectory.delete() causing infinite recursion when permission errors occur

CHANGES/plugin_api/6735.removal, pulpcore/app/serializers/repository.py
PULP doesn't advice to escape newlines for ca_cert, client_cert and client_key fields.
closes: #6735
https://pulp.plan.io/issues/6735
=> Remote certificate doc strings

CHANGES/7002.bugfix, pulpcore/content/handler.py
When a request for content that was on_demand occured for the first time, no logs where present due to the response not properly being return to the content handler, despite the response actually occuring.
fixes #7002
https://pulp.plan.io/issues/7002
=> Streamed responses are properly returned to handler to be logged

CHANGES/7179.bugfix, pulpcore/content/__init__.py
This aligns the content service to the WSGI service (API) which already sets a default env var for DJANGO_SETTINGS_MODULE. By providing a default, the systemd service doesn't have to duplicate this and makes configuration easier.
fixes #7179
=> Set a default DJANGO_SETTINGS_MODULE env var in content app

CHANGES/7066.bugfix, pulpcore/content/handler.py
this would cause `path` to start with a `/`
and because
```
>>> os.path.split('/path')
('/', 'path')
>>> os.path.split('/')
('/', '')
```
`base` would never end up as `None` but stay as `/` resulting in an infinite loop.
=> don't go into an infinite loop when `CONTENT_PATH_PREFIX` is followed by `/`

docs/bugs-features.rst
=> Add backport tracker information to the docs

CHANGES/plugin_api/7117.feature, pulpcore/download/http.py
=> Revert "`HttpDownloader` control on response codes 400+"

requirements.txt
whitenoise 5.0.0 dropped Python 2 support which is not needed by Pulp. whitenoise 5.2.0 introduces more mime types
and support for a relative static URL which is feature of Django 3.1.
http://whitenoise.evans.io/en/stable/changelog.html#v5-2-0
[noissue]
=> Updates whitenoise dependency to >=5.0.0,<5.3.0

CHANGES/plugin_api/7277.feature, pulpcore/plugin/importexport.py
This saves plugin writers from having to define exclude on any of
their resources that extend QueryModelResources.
fixes #7277
=> Exclude pulp fields for QueryModelResources

CHANGES/plugin_api/7252.feature, docs/plugins/plugin-writer/concepts/subclassing/import-export.rst, pulpcore/app/importexport.py, pulpcore/app/tasks/importer.py, pulpcore/plugin/importexport.py
=> Allow import/export of content not directly tied to repos

CHANGES/plugin_api/7312.bugfix, pulpcore/app/models/access_policy.py
Allow `pulpcore.plugin.models.AutoAddObjPermsMixin.add_for_object_creator`
to skip assignment of permissions if there is no known user. This allows
endpoints that do not use authorization but still create objects in the
DB to execute without error.
closes #7312
=> Skip permissions assignment when there is no user

CHANGES/7245.bugfix, pulpcore/app/serializers/__init__.py, pulpcore/app/serializers/base.py, pulpcore/app/serializers/repository.py, pulpcore/app/serializers/upload.py, pulpcore/app/serializers/user.py, pulpcore/plugin/serializers/__init__.py
All serializers which inherit from the base DRF serializer and are used in a ViewSet should now validate unknown query parameters.
closes #7245
=> Validate unknown fields

CHANGES/7316.feature, CHANGES/plugin_api/7316.feature, pulpcore/app/models/content.py, pulpcore/app/models/upload.py, pulpcore/app/settings.py, requirements.txt
=> Delete associated files from the storage

CHANGES/6856.doc, docs/components.rst
closes #6856
https://pulp.plan.io/issues/6856
=> Added hardware requirements.

.travis/docs-builder.py, CHANGES/7229.misc
re: #7229
https://pulp.plan.io/issues/7229
=> Changes the username and rsync path for doc publishing

CHANGES/7329.bugfix, pulpcore/app/viewsets/user.py
https://pulp.plan.io/issues/7329
closes #7329
=> Fixing groups API validation

CHANGES/plugin_api/7446.bugfix, pulpcore/app/views/orphans.py, pulpcore/openapi/__init__.py, pulpcore/tests/functional/api/using_plugin/test_orphans.py, pulpcore/tests/functional/utils.py
https://pulp.plan.io/issues/7446
closes #7446
=> Remove customized operation_id from OrphansView

docs/plugins/plugin-writer/concepts/index.rst
In the provided code snippets, there was used the return value from the save() method. However, the method returns None. This was fixed along with the documentation's structure describing PulpTemporaryFile.
[noissue]
=> Fix the documentation for PulpTemporaryFile

requirements.txt
Fix installer CI issue.
[dynaconf 2.22](https://github.com/rochacbruno/dynaconf/blob/2.2.2/setup.py#L50) is conflicting with [black](https://github.com/psf/black/blob/master/setup.py#L73)
Ref: https://pulp.plan.io/issues/7479
=> Upgrade dynaconf

CHANGES/7459.bugfix, pulpcore/app/tasks/export.py
=> When export creates a dir, make sure the group can write to it.

CHANGES/7510.bugfix, requirements.txt
First, pin drf-spectacular to 0.9.13 since our code no longer works
against 0.9.12.
Secondly, add a changelog entry to call out that we've fixed the
schema/bindings.
=> Pin drf-spectular to 0.9.13 and add changelog

CHANGES/7521.bugfix, pulpcore/app/models/exporter.py, pulpcore/tests/functional/api/using_plugin/test_filesystemexport.py
Just removing the call since we're already validating the path in the serializer. Also, adding some tests so we don't break this functionality again later.
Required PR: https://github.com/pulp/pulp_file/pull/429
fixes #7521
=> Fixed failing filesystem export due to undefined validate_path method

CHANGES/6463.bugfix, pulpcore/app/models/repository.py
closes: #6463
https://pulp.plan.io/issues/6463
=> Fix duplicate key error after incomplete sync task

CHANGES/plugin_api/7471.doc, docs/plugins/plugin-writer/concepts/index.rst
The snippets feature of plugins can be used to customize the behavior of
the reverse proxy by including "more specific" routes that take
precedence over less-specific routes the installer provides.
closes #7471
=> Adds docs on reverse proxy url customization

CHANGES/plugin_api/7523.doc, docs/plugins/plugin-writer/concepts/index.rst
The plugin writer docs "custom install tasks" section was recommending
plugins to ship their own Ansible roles, which is out of date. Now
plugins can contribute their installation needs  directly to the
installer.
closes #7523
=> Rewrites "custom install tasks" section

pulpcore/app/viewsets/base.py
re: #7483
https://pulp.plan.io/issues/7483
=> Provide a way to get PK from resource URI without evaluating query

CHANGES/7610.bugfix, MANIFEST.in
https://pulp.plan.io/issues/7610
closes #7610
(cherry picked from commit 573d809704198cd528c812ac85bcfcf78d603eb8)
=> Including functest_requirements.txt on MANIFEST.in

template_config.yml
Unset stable_branch since it's only used for the cherry pick processor
which we aren't using for pulpcore.
[noissue]
=> Unset stable_branch

CHANGES/plugin_api/7624.feature, pulpcore/plugin/__init__.py
Give plugin writers a way to access the pulpcore version.
This is possiblyuseful in case they want to support more than one
version of the plugin API at the same time.
[noissue]
=> Expose pulpcore_version to plugin writers

CHANGES/7634.bugfix, pulpcore/app/templates/rest_framework/api.html
Change dropped DRF filter to django urlize.
closes: #7634
https://pulp.plan.io/issues/7634
=> Rest framework template

CHANGES/4559.bugfix, pulpcore/tasking/util.py, pulpcore/tasking/worker.py
_release_resources() task checks whether task status is still set to
"running". In the case of cancelation, that is still true if the
transaction hasn't been committed yet.
closes: #4559
https://pulp.plan.io/issues/4559
=> Get rid of failure message on task cancellation

CHANGES/7147.bugfix, pulpcore/plugin/stages/artifact_stages.py
If the very first Content in a batch has already been prefetched in a previous call to prefetch_related_objects,
Django does not set the attribute specified in 'to_attr' when prefetching the rest of the items in the batch. As
a result, the '_remote_artifact_saver_cas' attribute is not set on the Content instances and AttributeError is
raised when '_remote_artifact_saver_cas' is accessed by the RemoteArtifactSaverStage.
This patch removes any existing '_remote_artifact_saver_cas' attributes on Content before calling into Django's
prefetch_related_objects().
fixes: #7147
https://pulp.plan.io/issues/7147
=> Handles duplicate content in the stages API.

CHANGES/7487.feature, pulpcore/app/settings.py
=> Added check for ALLOWED_CONTENT_CHECKSUMS that Artifacts are missing

CHANGES/7682.bugfix, requirements.txt
I've had to debug a few bugs in dynaconf that were caused by older
versions of dynaconf:
https://github.com/rochacbruno/dynaconf/issues/443
https://github.com/rochacbruno/dynaconf/issues/391
Update the dynaconf requirement to prevent users from using older
versions that cause bugs.
=> Update dynaconf dependency

CHANGES/7656.bugfix, MANIFEST.in, pyproject.toml
=> Using check-manifest to update manifest

CHANGES/7720.feature, pulpcore/content/handler.py, pulpcore/tasking/worker.py
6a2e7f304c31adcbf12d964753f639c5e3ea4cce already set this in one place for the handler, but this does it everywhere before calling django.setup. This means the services files don't need to.
=> Always set a default for DJANGO_SETTINGS_MODULE

CHANGES/7690.misc, pulpcore/tests/functional/api/test_crd_artifacts.py, pulpcore/tests/functional/api/test_status.py, pulpcore/tests/functional/api/test_upload.py
fixes: #7690
https://pulp.plan.io/issues/7690
=> Removes use of pulpcore.app.settings from functional tests.

requirements.txt
Today I spent some time debugging a strange sync issue. Turns out it was [a bug in aiohttp 3.7.0](https://github.com/aio-libs/aiohttp/issues/5110). We should set stricter requirements to avoid this situation in the future.
[noissue]
=> Pin some requirements

CHANGES/7757.bugfix, pulpcore/app/models/content.py, pulpcore/app/models/upload.py, pulpcore/app/settings.py, requirements.txt
This reverts commit f508d6b2ba4d624d64bcdbfa6c851afe159c6fac.
closes #7757
https://pulp.plan.io/issues/7757
backports #7676
https://pulp.plan.io/issues/7676
(cherry picked from commit cf31c5a9021f4156c14e38c73f1e8306491041a7)
=> CP for 3.7.z: Revert "Delete associated files from the storage"

CHANGES/plugin_api/7759.feature, pulpcore/plugin/serializers/__init__.py
Currently it is only possible to import  `ProgressReportSerializer` through
`pulpcore.app.serializers` and it is useful to have it on
`pulpcore.plugin.serializers`
Related PR: https://github.com/ansible/galaxy_ng/pull/526
closes #7759
=> Expose ProgressReportSerializer on pulpcore.plugin

CHANGES/7758.bugfix, pulpcore/app/models/content.py, pulpcore/app/models/upload.py, pulpcore/app/settings.py, requirements.txt
This reverts commit f508d6b2ba4d624d64bcdbfa6c851afe159c6fac.
closes #7758
https://pulp.plan.io/issues/7758
backports #7676
https://pulp.plan.io/issues/7676
(cherry picked from commit cf31c5a9021f4156c14e38c73f1e8306491041a7)
=> CP for 3.8.z: Revert "Delete associated files from the storage"

functest_requirements.txt, pulpcore/tests/functional/api/using_plugin/test_orphans.py
re: #7690
https://pulp.plan.io/issues/7690
=> Removes use of django.conf.settings from orphan cleanup tests

pulpcore/plugin/stages/artifact_stages.py, pulpcore/plugin/stages/content_stages.py
10% of resync time (file plugin) was spent inside these tight loops that we can replace with cheaper dictionary lookups.  No queries changed.
Time spent inside Python code of the QueryExistingContent stage (excluding function calls) drops from 11.4% to 0.4%
[noissue]
=> Minor resync perf improvement

CHANGES/7850.bugfix, pulpcore/app/templates/rest_framework/api.html
As of 3.12.2 version of django-rest-framework the embeded
jquery version is now 3.5.1 (vs 3.3.1)
=> Fix jquery version for API html rendering

docs/contributing/record-a-demo.rst
* Update record-a-demo file
[noissue]
We discussed this in a team meeting on Nov 16th and agreed it would be good to restrict the terminal size so we don't have embedded videos of various shapes and sizes on the demo page of the website. 
Should I also add a line to tag me, or send the video to me, so I can add it to the site?
=> Add asciinema terminal params

CHANGES/plugin_api/7897.feature, pulpcore/plugin/constants.py
=> Expose the ALL_KNOWN_CONTENT_CHECKSUMS constant in the plugin api

CHANGES/7829.bugfix, pulpcore/app/tasks/export.py
Adding check that exporter path exists before trying to create and modify it.
fixes #7829
=> Adding check that exporter path exists

CHANGES/7902.misc, pulpcore/tasking/constants.py, pulpcore/tasking/util.py, pulpcore/tasking/worker.py, requirements.txt
closes: #7902
https://pulp.plan.io/issues/7902
=> Replace custom task cancellation with RQ 1.7 functionality

pulpcore/app/settings.py
As of Django 1.9 there is no need to add the _pycopg2 postfix as the
backend was renamed.
See: https://docs.djangoproject.com/en/3.1/releases/1.9/
[noissue]
=> Simplify DATABASE engine name

CHANGES/7907.bugfix, pulpcore/tasking/services/worker_watcher.py
As another layer of security to guard against lock cleanup not occuring
due to Redis not delivering the _release_resource task, ensure all locks
are also cleaned up even for tasks that are in their final states.
closes #7907
=> Adds additional lock cleanup to worker cleanup

CHANGES/7909.bugfix, pulpcore/app/tasks/repository.py
closes #7909
https://pulp.plan.io/issues/7909
=> Use subclaassed plugin downloaders during the pulp repair.

pulpcore/tests/functional/api/test_crd_artifacts.py
This is effectively the same, but clearly signals in the test report that it didn't ran.
=> Use skipTest instead of returning

CHANGES/7890.misc, pulpcore/tests/functional/api/using_plugin/test_filesystemexport.py
fixes #7890
This gets the test passing. I filed an issue to better support exporting to the same location multiple times: https://pulp.plan.io/issues/7918.
=> Fixing FilesystemExporter test

CHANGES/7836.bugfix, pulpcore/app/modelresource.py
=> Fix import/export bug when sha384 or sha512 are null

CHANGES/8033.bugfix, pulpcore/app/serializers/user.py, pulpcore/app/viewsets/user.py, pulpcore/openapi/__init__.py
This disambiguates the group permission paths in the api docs and uses
the proper parent viweset href for nested "list" and "create" views.
=> Fix openapi doc paths for nested endpoints

pulpcore/app/models/access_policy.py
In order to support customized user models, the User model should be
determined with the get_user_model method.
[noissue]
=> User get_user_model in access_policy

CHANGES/plugin_api/8059.feature, pulpcore/app/viewsets/__init__.py, pulpcore/plugin/viewsets/__init__.py
=> Make DistributionFilter accessible via the plugin API

CHANGES/8094.feature, pulpcore/app/viewsets/base.py
=> Allow looking up names using icontains, contains and startswith.

pulpcore/app/models/access_policy.py
When using Galaxy:
```
"/home/vagrant/devel/pulpcore/pulpcore/app/apps.py:72: FutureWarning: The plugin `galaxy` is missing a version attribute. Starting with pulpcore==3.10, 
plugins are required to define their version on the PulpPluginAppConfig subclass.
warnings.warn(msg, FutureWarning)
Traceback (most recent call last):
File \"/usr/local/lib/pulp/bin/pulpcore-manager\", line 33, in <module>
sys.exit(load_entry_point('pulpcore', 'console_scripts', 'pulpcore-manager')())
File \"/home/vagrant/devel/pulpcore/pulpcore/app/manage.py\", line 11, in manage
execute_from_command_line(sys.argv)
File \"/usr/local/lib/pulp/lib64/python3.9/site-packages/django/core/management/__init__.py\", line 381, in execute_from_command_line
utility.execute()
File …
```
=> Avoid circular import when getting User

CHANGES/CHANGES/7888.bugfix, pulpcore/app/templates/rest_framework/api.html
Fixes X-CSRFToken Header not being sent for Ajax Requests
fixes #7888
=> Fixes Put request on api.html

CHANGES/8018.bugfix, CHANGES/plugin_api/8018.removal, pulpcore/app/settings.py
fixes #8018
https://pulp.plan.io/issues/8018
=> Restrict default permissions to admin users

CHANGES/8099.removal, docs/settings.rst, pulpcore/app/models/storage.py, pulpcore/app/settings.py
This patch changes the default value of CHUNKED_UPLOAD_DIR to `upload`.
This value is a relative path inside the MEDIA_ROOT. Doc strings have
also been updated to match the actual behavior of functions used to
form the path used by the UploadChunk's file field. The documentation
was also updated to make it more clear that CHUNKED_UPLOAD_DIR is
supposed to be a relative path inside MEDIA_ROOT.
fixes: #8099
https://pulp.plan.io/issues/8099
=> Fix the default value of CHUNKED_UPLOAD_DIR

.github/workflows/scripts/func_test_script.sh, CHANGES/8099.removal, docs/settings.rst, pulpcore/app/models/storage.py, pulpcore/app/settings.py
In 1b6c736 uploads were changed to use the default storage (uses
settings.MEDIA_ROOT). Anything that's written outside of storage
location raises a SuspiciousOperation. That already made the implicit
requirement that CHUNKED_UPLOAD_DIR was relative.
Users could hit this if they modified MEDIA_ROOT in their settings
but kept CHUNKED_UPLOAD_DIR default.
If a relative path is used, Django prepends the location and it is
guaranteed to be a safe location. This changes the default value to be
relative and updates the documentation to reflect this.
fixes: #8099
https://pulp.plan.io/issues/8099
=> Make CHUNKED_UPLOAD_DIR a relative path

CHANGES/plugin_api/8161.feature, pulpcore/app/global_access_conditions.py
Plugins can leverage it at least in policies for repository version viewsets.
closes #8161
https://pulp.plan.io/issues/8161
=> Add repo attribute check to global access conditions

docs/bugs-features.rst
=> Added clarifications around backport requests.

CHANGES/7178.feature, docs/settings.rst, pulpcore/app/apps.py, pulpcore/app/checks.py, pulpcore/app/models/storage.py, pulpcore/app/settings.py, pulpcore/tests/functional/api/test_crd_artifacts.py, pulpcore/tests/functional/api/using_plugin/test_orphans.py, pulpcore/tests/functional/api/using_plugin/test_repair.py, pulpcore/tests/unit/models/test_content.py
This changes the default deployment layout. The main change is that MEDIA_ROOT gets its own directory. This allows limiting the file permissions in a shared Pulp 2 + Pulp 3 deployment and the SELinux file contexts. Another benefit is compatibility with django_extensions' unreferenced_files command which lists all files in MEDIA_ROOT that are not in the database.
Other paths are kept on the same absolute paths, but the diff looks bigger because they used derive from MEDIA_ROOT.
The documentation is updated to show the latest best practices.
fixes #7178
=> Change the default deployment layout

CHANGES/plugin_api/7935.deprecation, pulpcore/plugin/storage.py
fixes: #7935
https://pulp.plan.io/issues/7935
=> Deprecate get_plugin_storage_path() method in plugin API

CHANGES/plugin_api/7930.removal, pulpcore/app/apps.py
It adds enforcement that the version to be set on the
`PulpPluginAppConfig` subclass. If an installed plugin does not specify
its version Pulp will refuse to start.
closes #7930
=> Requires Pulp plugins to provide version

pulpcore/tasking/tasks.py
Otherwise it can get cancelled when we check for missing tasks/jobs.
re #7912
https://pulp.plan.io/issues/7912
=> Ensure that a task is created in pulp not earlier than the job in redis

CHANGES/8203.misc, pulpcore/app/migrations/0042_rbac_for_tasks.py, pulpcore/app/migrations/0050_namespace_access_policies.py
In various places in the migrations Models are imported directly and then
used. This is a hazard for future changes because when the model
definition changes this code can break.
This PR switches data migrations to use apps.get_model(...) intead. It
also fixes a syntax migration I noticed on the downmigrate in migration
50.
closes #8203
=> Fixes migration imports to use apps.get_model

.github/workflows/scripts/install.sh, .github/workflows/scripts/script.sh, CHANGES/8246.removal, CHANGES/plugin_api/8246.removal, docs/settings.rst, pulpcore/app/settings.py, template_config.yml
The md5 and sha1 checksums are not considered secure and therefore
should not be included as available hashers for Pulp to perform Artifact
integrity checks with.
This PR:
* Removes them from the default in settings
* Updates the `ALLOWED_CONTENT_CHECKSUMS` settings documentation.
* Re-applies the plugin_tepmlate to no longer modify the set of allowed
checksums in the CI environment.
closes #8246
=> Removes md5 and sha1 from checksum defaults

CHANGES/7876.bugfix, pulpcore/plugin/stages/artifact_stages.py
Not all d_artifact objects have remotes, e.g. the migration plugin does
not. Other places in the code account for this, but there is one area
that does not. This adds an additional check to one codepath that checks
for equality of `d_artifact.remote.pk` only if `d_artifact.remote`
exists.
closes #7876
=> Adds additional d_artifact.remote check

pulpcore/app/viewsets/task.py
This change will issue an error response instead of an empty list, if an
invalid state is provided to filter by.
[noissue]
=> Add choices to task state filter

.ci/ansible/start_container.yaml, .github/workflows/scripts/before_install.sh, CHANGES/8198.removal, pulpcore/app/views/status.py, pulpcore/openapi/__init__.py, template_config.yml
The Status API and the OpenAPI schema API now both use the Django name.
This is a backwards incompatible change, but necessary to fix the bug
which was using Python package names incorrectly instead.
This also reapplies the plugin template changes required from the PR
below:
https://github.com/pulp/plugin_template/pull/341/files
closes #8198
=> Switches plugin reporting to use Django name

CHANGES/8202.removal, pulpcore/app/serializers/repository.py, pulpcore/tests/functional/api/using_plugin/test_crud_repos.py
=> Make sensitive Remote fields write_only

CHANGES/7928.doc, docs/settings.rst
=> Released handle-artifact-checksum from tech-preview.

pulpcore/app/settings.py
In production we don't need django to load .env files.
[noissue]
=> Disable Dynaconf loading of .env files

CHANGES/7854.feature, pulpcore/plugin/stages/artifact_stages.py
=> Remove enforcement of RemoteArtifact forbidden checksums for 3.11

CHANGES/7985.feature, pulpcore/app/settings.py
Revert the RemoteArtifact warning for 3.11 as users don't have a way to remedy the problem and also it doesn't handle plugins who can have RemoteArtifact without checksums.
=> Revert "Add warning if on-demand content does not have allowed checksum"

CHANGES/8342.doc, docs/settings.rst
The ALLOWED_CONTENT_CHECKSUMS is not fully enforcing with 3.11, so this
adds a banner to the settings page that identifies this for users.
closes #8342
=> Document ALLOWED_CONTENT_CHECKSUMS as not finished

CHANGES/plugin_api/8231.deprecation, CHANGES/plugin_api/8231.doc, docs/plugins/plugin-writer/concepts/index.rst, docs/plugins/reference/metadata-signing.rst, pulpcore/app/access_policy.py, pulpcore/plugin/stages/declarative_version.py, pulpcore/plugin/storage.py, pulpcore/tasking/storage.py
Additionally document the use of tempfile.TemporaryDirectory.
fixes #8231
https://pulp.plan.io/issues/8231
=> Deprecate WorkingDirectory

CHANGES/8395.bugfix, CHANGES/plugin_api/8397.removal, pulpcore/app/access_policy.py
=> Removed addressing AccessPolicy via the viewset's classname.

CHANGES/plugin_api/8398.removal, pulpcore/app/models/content.py
This was deprecated, since the SigningService contains the information
in the public_key field already.
closes #8398
https://pulp.plan.io/issues/8398
=> Remove "key" field from signing service response

CHANGES/7986.feature, docs/settings.rst, pulpcore/app/management/commands/handle-artifact-checksums.py, pulpcore/app/models/repository.py
`pulpcore-manager handle-artifact-checksums --report` reports local and remote artifacts with forbidden checksum type and approx size of it.
re #7986
https://pulp.plan.io/issues/7986
=> Artifact checksums report

CHANGES/8430.bugfix, pulpcore/plugin/stages/content_stages.py
In the case where there's a unique constraint that isn't part of the
natural key, using q() won't find the record. This erroneously raises a
DoesNotExist exception.
fixes #8430
=> Fix error for unique constraint violation

CHANGES/8427.bugfix, pulpcore/content/handler.py
closes #8427
https://pulp.plan.io/issues/8427
=> Fixed azure artifacts path download.

CHANGES/7989.feature, pulpcore/content/handler.py
In https://pulp.plan.io/issues/8435 we added a check to downloader to
prevent the download of files without allowed checksums. This code 
updates the downloader to handle the exception that gets raised.
fixes #7989
=> Have the content app handle UnsupportedDigestValidationError 

CHANGES/8445.bugfix, pulpcore/plugin/stages/artifact_stages.py
Don't check RemoteArtifact by artifact check in stages.
closes: #8445
https://pulp.plan.io/issues/8445
=> Don't check RemoteArtifact by artifact check

CHANGES/8423.feature, pulpcore/app/models/content.py, pulpcore/plugin/stages/artifact_stages.py, pulpcore/tests/unit/models/test_content.py
RemoteArtifacts are checked for forbidden checksums.
closes: #8423
https://pulp.plan.io/issues/8423
=> RemoteArtifacts checksum type check

CHANGES/7438.bugfix, CHANGES/7438.removal, pulpcore/app/viewsets/exporter.py, pulpcore/tests/functional/api/using_plugin/test_filesystemexport.py, pulpcore/tests/functional/api/using_plugin/test_pulpexport.py, pulpcore/tests/functional/api/using_plugin/utils.py
Exporter is a resource that needs to be reserved to change it. Running
an export task, while the exporter is being changed can lead to problems
otherwise.
fixes #7438
=> Wrap Exporter update and destroy calls in tasks

CHANGES/plugin_api/8438.bugfix, pulpcore/app/viewsets/base.py
Allow plugins to set `queryset_filtering_required_permission` attribute to
`None` and have it behave the same way as if the attribute were not present.
fixes #8438
https://pulp.plan.io/issues/8438
=> Allow plugins to unset attribute in NamedModelViewSet

CHANGES/8450.misc, functest_requirements.txt
=> Use pulp-smash from source

CHANGES/8377.bugfix, pulpcore/plugin/stages/artifact_stages.py
Only encountered while 2to3-migrating specific content in specific orders.
fixes #8377
[nocoverage]
=> Fixed artifact_stages edge case for multi-artifact/multi-remote batches.

CHANGES/8475.bugfix, pulpcore/content/handler.py, pulpcore/tests/functional/api/using_plugin/constants.py, pulpcore/tests/functional/api/using_plugin/test_content_promotion.py
fixes: #8475
https://pulp.plan.io/issues/8475
This fixes a regression that was introduce here https://github.com/pulp/pulpcore/commit/a9a536a2765ce84fc863434047496343e01cc040.  This should be backported to 3.11
=> Fixed distributions not being viewable in content app

CHANGES/plugin_api/8385.deprecation, pulpcore/app/models/publication.py, pulpcore/app/serializers/publication.py, pulpcore/app/viewsets/publication.py
This deprecates the following objects and adds warnings when they are
used:
* `pulpcore.plugin.models.BaseDistribution`
* `pulpcore.plugin.viewset.BaseDistributionViewSet`
* `pulpcore.plugin.viewset.DistributionFilter`
* `pulpcore.plugin.serializer.BaseDistributionSerializer`
* `pulpcore.plugin.serializer.PublicationDistributionSerializer`
* `pulpcore.plugin.serializer.RepositoryVersionDistributionSerializer`
closes #8385
=> Deprecates BaseDistribution and related objects

CHANGES/7980.bugfix, pulpcore/tasking/util.py, pulpcore/tasking/worker.py, requirements.txt
closes: #8143
https://pulp.plan.io/issues/8143
=> Fix another scenario where canceled tasks could be marked failed

CHANGES/plugin_api/8505.deprecation, pulpcore/tasking/tasks.py
The use of non-JSON serializable `args` and `kwargs` is now deprecated.
closes #8505
=> Non-JSON serializable args and kwargs deprecated

CHANGES/plugin_api/8496.deprecation, CHANGES/plugin_api/8496.feature, docs/plugins/plugin-writer/concepts/subclassing/viewsets.rst, pulpcore/app/models/publication.py, pulpcore/app/response.py, pulpcore/app/serializers/publication.py, pulpcore/app/tasks/importer.py, pulpcore/app/views/orphans.py, pulpcore/app/views/repair.py, pulpcore/app/viewsets/base.py, pulpcore/app/viewsets/exporter.py, pulpcore/app/viewsets/importer.py, pulpcore/app/viewsets/publication.py, pulpcore/app/viewsets/repository.py, pulpcore/app/viewsets/upload.py, pulpcore/plugin/actions.py, pulpcore/plugin/tasking.py, pulpcore/plugin/viewsets/content.py, pulpcore/tasking/storage.py, pulpcore/tasking/tasks.py
This adds a new `pulpcore.plugin.tasking.dispatch` interface which will
replace the `pulpcore.plugin.tasking.enqueue_with_reservation`
interface. This also deprecates the
`pulpcore.plugin.tasking.enqueue_with_reservation` and causes it to
emit warnings if used.
Additionally the `pulpcore.plugin.viewsets.OperationPostponedResponse`
has been ported to support both the `dispatch` and
`enqueue_with_reservation` interfaces.
closes #8496
=> Adds new `dispatch` call and deprecate the old one

pulpcore/app/loggers.py, pulpcore/app/models/publication.py, pulpcore/app/serializers/publication.py, pulpcore/app/viewsets/publication.py, pulpcore/tasking/storage.py, pulpcore/tasking/tasks.py
manage.py commands like "collectstatic" would fail due to circular
import as a result of confusing logging.py with the logging module in
stdlib.
[noissue]
=> Rename pulpcore.app.logging module to prevent name shadowing

CHANGES/7626.feature, CHANGES/plugin_api/7626.feature, pulpcore/app/migrations/0062_add_new_distribution_mastermodel.py, pulpcore/app/models/publication.py, pulpcore/app/models/repository.py, pulpcore/plugin/stages/artifact_stages.py, pulpcore/plugin/stages/declarative_version.py, pulpcore/tests/functional/api/using_plugin/test_distributions.py
closes: #7626
https://pulp.plan.io/issues/7626
=> Add support for automatic publishing

CHANGES/8352.bugfix, pulpcore/app/models/task.py, pulpcore/tasking/tasks.py, pulpcore/tasking/worker_watcher.py
closes: #8352
https://pulp.plan.io/issues/8352
=> Fix race condition in handling of reserved resources

setup.py
This fixes publishing this package to pypi, since they do not accept
direct dependencies.
=> Remove test section from extra dependencies

CHANGES/8525.bugfix, pulpcore/rqconfig.py
closes: #8525
https://pulp.plan.io/issues/8525
=> Fix missing REDIS_SSL parameter in rqconfig.py

CHANGES/8540.bugfix, requirements.txt
https://github.com/advisories/GHSA-8q59-q68h-6hv4
https://nvd.nist.gov/vuln/detail/CVE-2020-14343
closes #8540
https://pulp.plan.io/issues/8540
=> Allow to use PyYAML 5.4 which addresses CVE-2020-14343

CHANGES/8541.bugfix, pulpcore/app/serializers/fields.py
When submitting form data, pulp_labels is a MultiValueDict which is a
type of dict. isinstance() will recognize if data is a subclass of dict.
fixes #8541
=> Fix pulp_labels type check

CHANGES/8477.doc, docs/installation/instructions.rst
fixes #8477
I find it problematic that we have Pulp installer docs in two places. 
I have found that they are out of date. I think @mikedep333 mentioned that there might be an error here. 
I want to leave no doubt for the user which version of the docs is the most important. 
I tried to express this here. 
Happy to make any changes needed. 
=> Be explicit about Pulp installer doc

pulpcore/app/models/repository.py
These fields are TextFields not FileFields
[noissue]
=> Fix bad Remote docstring for cert fields

CHANGES/plugin_api/8580.bugfix, pulpcore/plugin/serializers/__init__.py
fixes #8580
backports #8578
https://pulp.plan.io/issues/8578
(cherry picked from commit e009492dcb8cbcf9918c5b1cf0ce1decd570fa7d)
=> Add RepositoryVersionRelatedField to plugin API

CHANGES/8597.doc, docs/installation/storage.rst
If it is OK with everyone, I would like to change the style of these docs to a set of sequential steps with the use of imperative voice. 
I would also like to be more specific. In these Storage docs, there is a mention of "Pulp settings". Is this draft, I've used settings.py although I know that's more than likely wrong. Can we be specific here about the exact file? 
fixes #8477
part of general installation work
=> Add sequential steps for storage docs

CHANGES/8550.doc, docs/installation/instructions.rst
small pulp-installer docs section in pulpcore was perpetually outdated. 
Pulp installer folks decided that the best course of action would be to remove the instructions. 
fixes #8550
=> Remove pulp installer doc sample

CHANGES/8396.bugfix, pulpcore/app/serializers/task.py, pulpcore/app/serializers/user.py, pulpcore/app/util.py, pulpcore/app/viewsets/user.py
In pulp_container, we are relying on the request's context when retrieving the host from a URL in ContainerDistributionSerializer. Since object-level permissions are tied to specific objects, the linked error was triggered only during the serialization of ContainerDistribution objects. Similarly, when a user tried to list permissions which contained task permissions, the missing context caused CreatedResourceSerializer to raise an internal error.
As of this commit, all RBAC-related serializers can benefit from the initial request's context.
closes #8396
=> Pass the request's context to the serializers

CHANGES/8668.doc, docs/installation/authentication.rst
Add an example of how to specify an array value and a dict key in the auth methods section (which is particularly useful for people using k8s).  Also expand/clarify a bit what the existing example is doing.
Fixes #8668
(refs GH #1203, which I don't have permission to reopen)
=> Add dynaconf nested value example

CHANGES/8711.bugfix, pulpcore/app/settings.py
Since 9a9a06f1e37f5367e36a24b9aa3aca6ca78dab53 DB access is always needed. In later commits this was extended with additional checks.
However, collectstatic should be a fully offline operation that doesn't access the network. As such, content checking is not needed.
Doing this allows the Foreman/Katello installer to run it more freely.  The alternative is to add additional ordering. However, I'd argue that this is better and also slightly faster.
Fixes #8711
=> Skip allowed content checks on collectstatic

CHANGES/4832.feature, CHANGES/plugin_api/4832.deprecation, pulpcore/app/management/commands/handle-artifact-checksums.py, pulpcore/app/models/publication.py, pulpcore/app/models/repository.py, pulpcore/app/urls.py, pulpcore/app/viewsets/__init__.py, pulpcore/app/viewsets/publication.py, pulpcore/app/viewsets/repository.py, pulpcore/tests/functional/api/using_plugin/constants.py, pulpcore/tests/functional/api/using_plugin/test_publications.py, pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
Views to show repository_versions or publications which contain specific content.
closes: #4832
https://pulp.plan.io/issues/4832
=> Content contained in RepoVer and Publication

CHANGES/8721.feature, docs/components.rst, docs/installation/instructions.rst, pulpcore/tasking/entrypoint.py, pulpcore/tasking/worker.py, requirements.txt, setup.py
With this change, workers should be started with `pulpcore-worker` and
the resource-manager with `pulpcore-worker --resource-manager`
accordingly.
fixes #8721
https://pulp.plan.io/issues/8721
=> Use a common entrypoint for workers

CHANGES/plugin_api/8723.feature, pulpcore/tasking/tasks.py
fixes #8723
https://pulp.plan.io/issues/8723
=> Undeprecate the use od UUID in task args

CHANGES/8691.bugfix, pulpcore/app/models/upload.py, requirements.txt
Switches the ArtifactFileField handling to use
`django.db.models.fields.Field` and specifies the `name` which causes
Django to no longer try to generate one from the filename.
closes #8691
=> Adds compatability with Django==2.2.21

CHANGES/7316.bugfix, pulpcore/app/models/upload.py
According to the Django docs, the `on_delete=models.CASCADE` option does
not call Model.delete(), but it does call the Model.post_delete() signal
handler.
This replaces the `UploadChunk.delete()` with an
`UploadChunk.post_delete()` signal handler which correctly handles
the `UploadChunk.file` file deletion.
closes #7316
=> Fixes deletion of UploadChunk when Upload deletes

CHANGES/8609.doc, CHANGES/8609.feature, docs/workflows/signed-metadata.rst, pulpcore/app/management/commands/add-signing-service.py
Please look at the two commits separately.
In the second one i added a service command to produce a AsciiArmoredSigningService, but i don't know it it is ready for consumption, as it is not yet able to create e.g. a pulp_deb provided one.
=> Update signing docs

CHANGES/8689.bugfix, pulpcore/download/factory.py, pulpcore/tests/functional/api/using_plugin/test_crud_repos.py, pulpcore/tests/functional/api/using_plugin/test_repo_versions.py, pulpcore/tests/unit/download/test_factory.py
The Remotes APIs accepts a list of headers to be sent with each request during
sync. However, the headers were not being properly passed to aiohttp. This patch
fixes how the headers are passed to aiohttp.
fixes: #8689
https://pulp.plan.io/issues/8689
=> Fixes ability to specify custom headers on a Remote

CHANGES/8633.bugfix, pulpcore/app/modelresource.py, pulpcore/app/tasks/importer.py
There's a race condition in django-import-export's get_or_init_instance()
that is exercised by importing repo-versions concurrently. We attempt
an import and check for errors, retrying ONCE if encountered. On a
second error, fail the attempt.
The test added for pulp_rpm #7904 cover this case.
fixes #8633
ref #7904
[nocoverage]
=> Taught PulpImporter to retry (once) on _import_file() failure.

CHANGES/8761.misc, pulpcore/app/serializers/publication.py
Bring back some of the Distribution validation around "repository"
re: #8761
https://pulp.plan.io/issues/8761
=> Bring back some of the Distribution validation around "repository"

requirements.txt
This reverts commit 935fac880e5f0b70e8cccc75fa22b614da96ef47.
Additionally since pulpcore is compatible with both 7.y and 8.y versions
of click we can just ensure we don't break when click 9.0 comes out.
[noissue]
=> Revert "[noissue]: Update click requirement from ~=7.1.2 to ~=8.0.0"

CHANGES/8760.feature, pulpcore/content/handler.py, pulpcore/tests/functional/api/using_plugin/test_content_promotion.py, pulpcore/tests/functional/api/using_plugin/test_distributions.py
@bmbouter Here is the problem(and assumption) I ran into https://pulp.plan.io/issues/8760#note-2
fixes: #8760
https://pulp.plan.io/issues/8760
=> Content app auto-distributes latest publication

CHANGES/7747.doc, docs/contributing/index.rst, docs/glossary.rst
=> Removed PUP references in the docs.

CHANGES/8784.doc, docs/contributing/platform-api/app/auth.rst, docs/contributing/platform-api/app/fields.rst, docs/contributing/platform-api/tasking.rst
Autodoc was failing to find several python modules, but these failures
didn't cause formal docs build errors. In cases where code was moved,
this PR fixes the paths to resolve the error. In cases where code was
removed, it removes those autodoc entries.
closes #8784
=> Fixes autodoc build errors

CHANGES/8793.bugfix, pulpcore/app/models/repository.py, pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
Fixed a bug in the retained versions code where content wasn't being
properly moved to newer repo versions when old versions were cleaned up.
fixes #8793
=> Fixed retained version bug where content wasn't updated

CHANGES/plugin_api/8792.bugfix, pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
fixes: #8792
https://pulp.plan.io/issues/8792
The modified test won't pass till https://pulp.plan.io/issues/8793 is resolved. (a separate bug with retained_versions)
This is needed for https://github.com/pulp/pulp_file/pull/506
=> Fixed auto-distribute tests

.github/workflows/ci.yml, .github/workflows/scripts/before_install.sh, .github/workflows/scripts/script.sh, pulpcore/tests/upgrade/post/test_publish.py, pulpcore/tests/upgrade/pre/test_publish.py, template_config.yml
=> Upgrade tests

CHANGES/6837.doc, docs/installation/authentication.rst, docs/installation/instructions.rst
=> Fixed a number of broken links in the installation/ section of docs.

CHANGES/8801.doc, docs/authentication/basic.rst, docs/authentication/index.rst, docs/authentication/other.rst, docs/authentication/overview.rst, docs/authentication/webserver.rst, docs/configuration/settings.rst, docs/installation/instructions.rst
This moves all of the authentication into one place and organizes it
into and Overview, Basic, Webserver, and Other sections.
It also deletes the 'disabling auth' docs. Upon testing Django refuses
to start if you follow those docs.
closes #8801
=> Consolidates existing auth into top-level section

CHANGES/8821.misc, pulpcore/content/__init__.py, pulpcore/content/handler.py
The standard async executor is single-threaded (which is perfectly fine for async code)
but blocking IO shreds its throughput. Let's create a separate ThreadPool executor for 
blocking IO so that our async code is actually async.
[noissue]
=> Pass blocking IO in content handler to a separate executor

CHANGES/8869.bugfix, pulpcore/app/views/repair.py
Links the RepairSerializer with the view for `/pulp/api/v3/repair/`.
Without this no arguments can be passed in through bindings.
closes #8869
=> Fixes request schema for `/pulp/api/v3/repair/`

.github/dependabot.yml
Trying [the method of ignoring versions from the github dependabot docs](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#ignore)
since [the current method doesn't seem to work](https://github.com/pulp/pulpcore/pull/1389).
[noissue]
=> Try a different method of ignoring versions in dependabot

CHANGES/plugin_api/8480.deprecation, CHANGES/plugin_api/8480.feature, pulpcore/app/viewsets/__init__.py, pulpcore/app/viewsets/publication.py, pulpcore/plugin/viewsets/__init__.py
This add `pulpcore.plugin.viewsets.DistributionFilter` to replace
`pulpcore.plugin.viewsets.NewDistributionFilter`. The
`pulpcore.plugin.viewsets.NewDistributionFilter` is now deprecated and
will emit warnings if used.
closes #8480
=> Adds DistributionFilter

CHANGES/plugin_api/8480.feature, CHANGES/plugin_api/8729.removal, pulpcore/app/models/repository.py, pulpcore/tasking/tasks.py
This remotes the deprecated `versions_containing_content` method from
`RepositoryVersion`.
closes #8729
=> Removes the versions_containing_content method

CHANGES/8670.bugfix, pulpcore/content/handler.py, requirements.txt
The aio URL object mangles query strings when they're passed in. Specifically, it unescapes http entities which are escaped but which don't need escaped.  This is normally ok, but in the case of signed CloudFront URLs, changing anything about the URL invalidates the signature, including the querystring.  By pre-creating a yarl.URL object before raising the redirect exception, the parsing doesn't happen in aiohttp.  Passing in the "encoding=True" stops the reparsing when the object is created.
Fixes #8670
Relates to #1294, and boto/botocore#2363
=> Stabilize URLs before generating redirects

CHANGES/8708.bugfix, pulpcore/tasking/tasks.py
During a small window between checking it's existance and looking up the
ReservedResource, this object may be deleted in another thread.
This condition will lead to task remaining in waiting state forever.
fixes #8708
https://pulp.plan.io/issues/8708
=> Close a race condition with ReservedResource

CHANGES/8891.feature, pulpcore/app/viewsets/task.py
fixes #8891
https://pulp.plan.io/issues/8891
This should help to find "all the tasks that were triggered by xxx frontend api call".
=> Add logging_cid filter to task list view

CHANGES/8867.bugfix, CHANGES/8881.feature, CHANGES/plugin_api/8881.deprecation, CHANGES/plugin_api/8881.feature, pulpcore/app/migrations/0066_download_concurrency_and_retry_changes.py, pulpcore/app/models/repository.py, pulpcore/app/serializers/repository.py, pulpcore/download/factory.py, pulpcore/download/http.py
Extend retry logic to cover all HTTP 5xx errors as well as some types of connection errors, and make the number of retries configurable by the user and plugin writer.
closes: #8881
https://pulp.plan.io/issues/8881
closes: #8867
https://pulp.plan.io/issues/8867
=> Extend retry logic to cover more types of errors

pulpcore/download/http.py
The default value isn't used by normal code due to downloader factory,
but RPM plugin unit tests construct the downloader manually and expect it to not be null.
[noissue]
=> Fix bad default value

CHANGES/8868.bugfix, CHANGES/plugin_api/8868.bugfix, pulpcore/openapi/__init__.py, pulpcore/tests/functional/api/using_plugin/test_pulpexport.py, pulpcore/tests/functional/api/using_plugin/test_pulpimport.py
The tag generation code was deleting the second element from the end instead of deleting the
second element in the list of operation keys. This worked for operations that had 3 elements
in the operations keys list, however, anything longer produced wrong operation tags.
fixes: #8868
https://pulp.plan.io/issues/8868
=> Fix OpenAPI schema tag generation

.github/workflows/scripts/script.sh, CHANGES/8658.feature, pulpcore/app/serializers/__init__.py, pulpcore/app/serializers/orphans.py, pulpcore/app/tasks/orphan.py, pulpcore/app/urls.py, pulpcore/app/viewsets/__init__.py, pulpcore/app/viewsets/orphans.py, pulpcore/tests/functional/api/test_correlation_id.py, pulpcore/tests/functional/api/test_crd_artifacts.py, pulpcore/tests/functional/api/using_plugin/test_content_delivery.py, pulpcore/tests/functional/api/using_plugin/test_content_path.py, pulpcore/tests/functional/api/using_plugin/test_distributions.py, pulpcore/tests/functional/api/using_plugin/test_generic_list.py, pulpcore/tests/functional/api/using_plugin/test_orphans.py, pulpcore/tests/functional/api/using_plugin/test_publications.py, pulpcore/tests/functional/api/using_plugin/test_pulpexport.py, pulpcore/tests/functional/api/using_plugin/test_pulpimport.py, pulpcore/tests/functional/api/using_plugin/test_repair.py, pulpcore/tests/functional/api/using_plugin/test_repo_versions.py, pulpcore/tests/functional/api/using_plugin/test_tasking.py
This adds a new endpoint `/pulp/api/v3/orphans/cleanup/`. When called
with `POST` and no parameters it is equivalent to calling `DELETE
/pulp/api/v3/orphans/`. Additionally the optional parameter
`content_hrefs` can be specified and must contain a list of content
hrefs. When `content_hrefs` is specified, only those content units will
be considered to be removed by orphan cleanup.
closes #8658
=> Adds `/pulp/api/v3/orphans/cleanup/`

pulpcore/app/serializers/repository.py
[noissue]
Adds an additional hint on how to look for the default values and by
extension what one might plausibly change the value to.
This is kind of implied already by the `(q.v.)` abbreviation, but I think there might be the odd user who is helped by it, and I don't think slightly longer help strings in the API docs ever really hurt. Any thoughts?
If there is agreement that this is an improvement I can create an issue to go with it, if desired.
=> Improve the help text for the remote timeout options

CHANGES/8980.bugfix, pulpcore/content/handler.py
After the client receives the last chunk of the response, it closes the connection
with the content app. This causes all scheduled coroutines to be cancelled. If the
the thread that is performing the Artifact/Content save has not finished running,
the Content is never saved.
This patch ensures that the Artifact and the Content are fully saved to the
database after being streamed to the user.
fixes: #8980
https://pulp.plan.io/issues/8980
=> Shields coroutine that is saving Artifact and Content

CHANGES/8946.doc, docs/index.rst
fixes #8946
Problem: people don't scroll. The "How to Navigate the pulpcore and plugin docs" section, I think, should be up front and centre when a user lands. We have a lot of docs, but knowing how to navigate them seems to be a challenge. 
Any/all feedback welcome. 
=> Add stronger user orientation to docs

CHANGES/8947.doc, docs/components.rst, docs/installation/hardware-requirements.rst, docs/installation/index.rst
Move hw & fs info into installation section 
As a user, I expect to find hw requirements before I go to install something. 
To me, it is not architecture.
I cannot tell the difference between deployment & installation in this context either, so removed "deployment". 
fixes #8947
=> Separate Architecture from Deployment docs

CHANGES/8805.feature, docs/configuration/settings.rst, pulpcore/app/models/publication.py, pulpcore/app/models/repository.py, pulpcore/app/settings.py, pulpcore/cache/__init__.py, pulpcore/cache/cache.py, pulpcore/content/handler.py, pulpcore/tasking/connection.py, pulpcore/tests/functional/api/using_plugin/test_content_cache.py, pulpcore/tests/unit/test_cache.py, requirements.txt
fixes: #8805
https://pulp.plan.io/issues/8805
Still a heavily WIP PR and lots of work to be done, but it does work and pretty nicely too!  I didn't put much thought into the cache api design(except for the fact that I wanted it to be a decorator added to any handler/view function) so it is a bit of a mess and needs refactoring.  ~The one big problem I ran into was that the content app should use async methods when talking to redis, but all of the other Django code requires non-async methods to talk to redis.  This made designing a shared base class non-trivial.~ Another problem is that aiohttp requests/responses are different from Django requests/responses so an all inclusive cache api would be difficult(but not impossible) to create and would probably need to be in separate objects. …
=> Use Redis to cache responses from content app

.github/workflows/release.yml, CHANGES.rst
This change also adds a script that will allow the new changelog to be published during a re-run of 3.14.0 release workflow.
=> Fix changelog for 3.14.0

CHANGES/plugin_api/8479.removal, pulpcore/app/viewsets/__init__.py, pulpcore/app/viewsets/publication.py, pulpcore/plugin/viewsets/__init__.py
Removes the `pulpcore.plugin.viewsets.NewDistributionFilter`. Instead
use `pulpcore.plugin.viewsets.DistributionFilter`.
The final step is a long plan!
closes #8479
=> Removes `NewDistributionFilter`

.ci/assets/bindings/test_bindings.rb, CHANGES/9008.bugfix, pulpcore/app/serializers/__init__.py, pulpcore/app/serializers/base.py, pulpcore/app/serializers/exporter.py, pulpcore/app/serializers/task.py
This patch clearly defines the exported_resources as a list of URI strings. The implementation for
the ExportedResourceSerializer is shared with CreatedResource serializer. They now both inherit from
a new RelatedResourceField.
fixes: #9008
https://pulp.plan.io/issues/9008
=> Removes ambiguity from OpenAPI schema for Exports.

CHANGES/8865.bugfix, pulpcore/content/handler.py, pulpcore/tests/functional/api/using_plugin/test_distributions.py
This unskips the `Range` header and adds support for it to the content
app.
closes #8865
=> Adds Range header support to content app

CHANGES/9024.bugfix, pulpcore/download/http.py
fixes: #9024
https://pulp.plan.io/issues/9024
=> Use proxy auth from the Remote config.

pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
Sometimes the assertion returns 2 which causes the test to fail. There's
probably a test that's not properly cleaning up its repo versions.
[noissue]
=> Fix test that fails intermittently

CHANGES/9057.bugfix, CHANGES/9058.bugfix, CHANGES/9059.bugfix, CHANGES/9068.bugfix, pulpcore/app/models/publication.py, pulpcore/app/serializers/fields.py, pulpcore/content/handler.py, pulpcore/download/http.py, pulpcore/tests/functional/api/using_plugin/test_distributions.py
- Use proxy auth from the Remote config.
- Make auto-distribute feature more intuitive
- Replace DictField with JSONField
- Adds Range header support to content app
=> 3.14.2 backports

CHANGES/8996.misc, docs/configuration/settings.rst, pulpcore/app/settings.py
If Redis goes down then its persisted data can get out of sync with
Pulp, because cache invalidation events cannot occur. We should mitigate
the impact by letting cache entries expire after a shorter period of
time.
closes: #8996
https://pulp.plan.io/issues/8996
=> Reduce the cache entry expiration TTL

CHANGES/9070.bugfix, pulpcore/app/serializers/status.py, pulpcore/app/views/status.py, pulpcore/tests/functional/api/test_status.py
Redis is only used when cache is enabled or RQ tasking is used. In other cases, the connection is not needed. We've changed the Foreman installer to [only install Redis if needed](https://github.com/theforeman/puppet-pulpcore/commit/7a5543b1a47de8d76a1cad1fb76e12db7bbf8e45), just to stop wasting resources. However, this leads to warnings.
This PR changes the status view to only include Redis if it's used.
Right now there are no tests since I first want to discuss if this is even the right direction. That's also why this PR is a draft.
https://pulp.plan.io/issues/9070
=> Conditionally include Redis connection information

CHANGES/9080.bugfix, pulpcore/app/serializers/repository.py, pulpcore/tests/functional/api/using_plugin/test_crud_repos.py
Before this change, it was not possible to determine why did the synchronization fail when a user provided a seemingly valid URL. This commit also adds more relevant information to the error message.
Having set `ALLOWED_EXPORT_PATHS` to `["/tmp", "/home/vagrant/test"]`, the following error messages are shown:
```
$ pulp file remote create --name test --url file://error/vagrant/test/centos-7/PULP_MANIFEST
Error: {"url":["The path 'error/vagrant/test/centos-7/PULP_MANIFEST' needs to be an absolute pathname."]}
$ pulp file remote create --name test --url file:///error/vagrant/test/centos-7/PULP_MANIFEST
Error: {"url":["The path '/error/vagrant/test/centos-7/PULP_MANIFEST' is not in allowed import paths"]}
```
closes #9080
=> Validate absolute pathnames in remotes' URLs

CHANGES/8986.bugfix, pulpcore/tasking/pulpcore_worker.py
When hitting ctrl-c twice, workers should also kill their supervised
tasks. And shut them down.
fixes #8986
https://pulp.plan.io/issues/8986
=> Fixed non-gracefully shutting down workers

.github/dependabot.yml
```
The property '#/updates/0/ignore' of type null did not match the following type: array
```
=> Fix dependabot error

CHANGES/plugin_api/8913.removal, pulpcore/download/__init__.py, pulpcore/download/http.py, pulpcore/plugin/download/__init__.py
This is no longer needed in the plugin API because, starting with
`pulpcore==3.14` the `HttpDownloader.run()` method uses it directly so
plugins no longer have to use it on their `_run()` subclass definitions.
closes #8913
=> Removes `http_giveup` method from plugin API

CHANGES/8779.bugfix, pulpcore/tasking/tasks.py, pulpcore/tasking/worker.py
This is a first attempt to be more thought full around missing / dirty
workers when assiging new tasks.
TODO:
- ~Pin down the real issue~
- ~Define what the solution really is~
- ~change this commit from "re" to "fixes"~
re #8779
=> Prevent tasks being assigned to missing workers

CHANGES/9000.bugfix, pulpcore/content/__init__.py, pulpcore/content/handler.py, pulpcore/tests/unit/content/test_handler.py
As of this commit, content app is no longer storing temporary files in the /var/run/ directory. The temporary files were created during on-demand downloading and were not removed until, e.g., restarting pulp services.
closes #9000
=> Change content app's working directory dynamically

CHANGES/9103.bugfix, CHANGES/9110.bugfix, pulpcore/app/models/storage.py, pulpcore/content/__init__.py, pulpcore/content/handler.py, pulpcore/tests/unit/content/test_handler.py
=> 3.14-cherrypicks

pulpcore/tasking/pulpcore_worker.py
This was introduced in 794a8799.
[noissue]
^ Before anyone asks: I believe, this does not need a changelog (or issue), because i found that bug in a nightly build and it has never been in a release. So there is no benefit in telling there even _was_ a bug.
=> Fixed a bug with logging on task cancel

CHANGES/9171.misc, pulpcore/plugin/stages/artifact_stages.py
Django 3.2 contains a fix for the bug that required a workaround.
https://code.djangoproject.com/ticket/32089
closes: #9171
https://pulp.plan.io/issues/9171
=> Removes workaround in RemoteArtifactSaver

CHANGES/9159.deprecation, pulpcore/tasking/tasks.py
This commit deprecates the old style tasking system in preparation for
it to be removed with pulpcore==3.16.
closes #9159
=> Adds deprecation of old tasking system

CHANGES/plugin_api/9160.deprecation, CHANGES/plugin_api/9160.misc, pulpcore/app/apps.py
fixes #9160
I'd like to get this in as a 3.16 blocker, as it brings the deprecation cycle promise back that the drf-access-policy upgrade broke.
=> Workaround breaking drf-access-policy upgrade

CHANGES/8974.bugfix, CHANGES/plugin_api/8974.feature, docs/plugins/plugin-writer/concepts/rbac/access_policy.rst, docs/plugins/plugin-writer/concepts/rbac/overview.rst, pulpcore/app/access_policy.py, pulpcore/app/settings.py, pulpcore/app/viewsets/task.py, pulpcore/app/viewsets/user.py
The `AccessPolicyFromDB` object is now declared by default in the
settings file, and it provides a fallback behavior to the `IsAdmin`
functionality that was there before.
closes #8974
=> `AccessPolicyFromDB` is now used by default

CHANGES/9146.bugfix, pulpcore/app/checks.py, pulpcore/app/models/storage.py, pulpcore/app/settings.py
Copy files from all other sources. Since users are able to change the
WORKING_DIRECTORY settings, this patch also ensures that we check that
the WORKING_DIRECTORY and MEDIA_ROOT are on the same device. Django's
FILE_UPLOAD_TEMP_DIR is now set to the value of WORKING_DIRECTORY.
fixes: #9146
https://pulp.plan.io/issues/9146/
=> Move files to artifact storage from WORKING_DIRECTORY.

CHANGES/8133.bugfix, CHANGES/plugin_api/8133.bugfix, pulpcore/app/files.py, pulpcore/app/models/publication.py, pulpcore/plugin/repo_version_utils.py, pulpcore/plugin/stages/artifact_stages.py, pulpcore/tests/unit/test_files.py
There are RPM repositories "in the wild" that violate Pulp's assumptions
about what is 'legal' in an incoming repository version. This commit
changes some fatal errors into log-warnings, along with some heuristics
around how to get a 'reasonable' repository in the face of suboptimal
data.
It also handles an exception during repo-version-failure-cleanup that
could result in losing error info.
fixes #8133
[nocoverage]
=> Loosen the constraints around what can be in a new-repository-version.

pulpcore/plugin/stages/profiler.py
Before this commit, the error `can only concatenate str (not \"UUID\") to str` was raised.
[noissue]
=> Fix the concatenation error

CHANGES/plugin_api/9234.feature, pulpcore/app/models/content.py
fixes TBA
This was just a random thought i had when writing these lines: https://github.com/pulp/pulp_container/blob/d25b01d4fb8aed1b264a9dcfc91461fe92d630b8/pulp_container/app/viewsets.py#L748
Not sure if it really helps there, also it's really kind of late for 3.14. If you like this i can do the issue dance for it.
=> Add touch to QuerySets of artifacts or content

CHANGES/9243.bugfix, pulpcore/plugin/stages/artifact_stages.py, pulpcore/plugin/stages/content_stages.py
This patch only addresses part of the problem described in issue #9243. Another patch
is needed to address the inefficiency of the repository version modify operation.
re: #9243
=> Use bulk touch() when processing Artifacts and Content

CHANGES/9275.bugfix, pulpcore/content/handler.py
It's a workaround for yet another `connection already closed` issue.
closes #9275
https://pulp.plan.io/issues/9275
https://pulp.plan.io/issues/9276 is filed to investigate that issue more.
=> Reset a db connection in content app distribution matching code
