pulp/pulpcore

README.md

Switches the travis badge to use travis-ci.com

---

.travis/script.sh
pulpcore/tests/functional/content_with_coverage.py
pulpcore/tests/functional/worker_with_coverage.py

Collect coverage from rq worker

---

pulpcore/app/serializers/fields.py

https://pulp.plan.io/issues/4391
Reissued: https://github.com/pulp/pulp/pull/3870

Distribution base_url no longer default to request netloc.

---

pulpcore/app/migrations/0002_distribution_remote.py

fixes #4528
https://pulp.plan.io/issues/4528

Fix migration reference

---

docs/installation/instructions.rst

Update instructions to install db extras

---

pulpcore/app/entry_points.py
pulpcore/app/manage.py
pulpcore/app/settings.py
pulpcore/app/wsgi.py
pulpcore/content/handler.py
pulpcore/rqconfig.py
pulpcore/tasking/connection.py
pulpcore/tasking/worker.py

Solution: load DynaConf settings directly in the pulpcore.app.settings
re: #4450
https://pulp.plan.io/issues/4450

Problem: DynaConf integration requires modifying entry points

---

docs/release-notes/pulpcore/3.0.x.rst
setup.py

Adds release notes for beta 22

---

pulpcore/app/models/repository.py

Add human readable name to RepositoryVersion

---

docs/release-notes/pulpcore/3.0.x.rst
setup.py

Beta 23 release notes and version bump

---

.travis/before_install.sh
.travis/install.sh
docs/contributing/dev-setup/index.rst
docs/installation/instructions.rst

https://pulp.plan.io/issues/4508
re #4508

Switch to new ansible-pulp git repository

---

.travis/playbook.yml

Use renamed roles from ansible-pulp

---

.travis/script.sh

Related to https://pulp.plan.io/issues/4495
[noissue]

Rename wsgi to match latest ansible-pulp

---

setup.py

rq 1.0 will have backwards incompatible changes that may or may not
affect us. In any case, it's expected to release soon, and it would be
bad if it broke our RC immediately after release.
[noissue]

Pin rq at <1.0

---

docs/release-notes/pulpcore/3.0.x.rst
setup.py

Preparing for 3.0.0rc1

---

docs/contributing/index.rst

closes: #4569
https://pulp.plan.io/issues/4569
Signed-off-by: Pavel Picka <ppicka@redhat.com>

Fix dead-link in docs

---

docs/installation/instructions.rst

Other installations should work, but Ansible is preferred
[noissue]

Show that Ansible installer is recommended

---

docs/installation/instructions.rst

The systemd docs were incomplete in various ways and regularly out of
date. This rewrites that section to link users to the Ansible
Installer's templates for these files which are maintained and will be
up to date.
https://pulp.plan.io/issues/4629
closes #4629

systemd docs use Ansible Installer Template

---

docs/_templates/restapi.html

Make docs title Pulp specific

---

docs/installation/configuration.rst

https://pulp.plan.io/issues/4602
closes #4602

Wording fix

---

bin/pulp-content

Solution: explicitly bind pulp-content to port 24816
[noissue]

Problem: pulp-content binds to port 8080

---

.travis.yml
.travis/test-container-images.sh
containers/README.md
containers/ansible.cfg
containers/build.yaml
containers/images/pulp-api/Dockerfile
containers/images/pulp-api/container-assets/pulp-api
containers/images/pulp-api/container-assets/wait_on_database_migrations.sh
containers/images/pulp-api/container-assets/wait_on_postgres.py
containers/images/pulp-content/Dockerfile
containers/images/pulp-content/container-assets/pulp-content
containers/images/pulp-resource-manager/Dockerfile
containers/images/pulp-resource-manager/container-assets/pulp-resource-manager
containers/images/pulp-worker/Dockerfile
containers/images/pulp-worker/container-assets/pulp-worker
containers/push.yaml
containers/vars/defaults.yaml

Fixes #4188: Add Pulp 3 container image built from PyPi

---

.travis/script.sh

Add a way to require bindings PRs

---

pulpcore/tests/functional/api/using_plugin/test_repo_versions.py

Add test to assure that repository version can not be updated using HTTP
PATCH neither PUT.
https://pulp.plan.io/issues/4667
closes:#4667

Add test that repo version can not be updated

---

.travis/before_install.sh
.travis/script.sh

Solution: refactor the scripts that clone / build bindings
[noissue]

Problem: bindings testing fails on Travis

---

.travis/publish_pulpcore_client_gem.sh
.travis/publish_pulpcore_client_pypi.sh

Solution: use commit count instead of hash
re: #4694
https://pulp.plan.io/issues/4694

Problem: python client publishes bad version string

---

.travis.yml

Solution: configure Travis to only publish on CRON builds
re: #4694
https://pulp.plan.io/issues/4694

Problem: pulpcore-client is published too frequently

---

pulpcore/app/viewsets/content.py
pulpcore/app/viewsets/custom_filters.py

Solution: add a custom filter for querying artifacts by repo version
fixes: #4806
https://pulp.plan.io/issues/4806

Problem: artifacts can't be filtered by repository version

---

docs/release-notes/pulpcore/3.0.x.rst

Update release notes further for default ports change.

---

docs/workflows/exposing-content.rst
pulpcore/tests/functional/api/using_plugin/constants.py
pulpcore/tests/functional/api/using_plugin/test_content_delivery.py
pulpcore/tests/functional/api/using_plugin/test_content_path.py
pulpcore/tests/functional/api/using_plugin/test_content_promotion.py
pulpcore/tests/functional/api/using_plugin/test_crd_publications.py
pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
pulpcore/tests/functional/api/using_plugin/test_unlinking_repo.py
pulpcore/tests/functional/api/using_plugin/utils.py

refs #4270
https://pulp.plan.io/issues/4720
Required PR: https://github.com/pulp/pulp_file/pull/221

Update tests since file publishers were removed

---

.travis/publish_pulpcore_client_gem.sh
.travis/publish_pulpcore_client_pypi.sh

Solution: don't include epoch for tagged builds
[noissue]

Problem: version string for client includes epoch all the time

---

.travis.yml

Solution: add additional stages for tagged releases
[noissue]

Problem: client libraries not published for tagged releases

---

pulpcore/tests/functional/api/using_plugin/test_crd_publications.py

Add test to assert that an HTTP exception is raised when creating
publication with repository and repository_version.
closes: #4854

Assert HTTP exception raised when created publication with repo and repo_version

---

pulpcore/tests/functional/api/using_plugin/constants.py
pulpcore/tests/functional/api/using_plugin/test_repo_versions.py

Add tests to filter artifacts by repository version.
closes:#4811

Tests to filter artifacts by repository_version

---

pulpcore/tests/functional/api/using_plugin/test_distributions.py

Add basic CRUD tests to distributions.
ref:#4862

Add basic CRUD tests to distributions

---

pulpcore/app/serializers/__init__.py
pulpcore/app/serializers/content.py
pulpcore/app/serializers/fields.py

refs #4827
https://pulp.plan.io/issues/4827
See https://github.com/pulp/pulp_file/pull/233 for usage.

Adding checksum serializer for content

---

pulpcore/tests/functional/api/using_plugin/test_crd_publications.py

Add test to create publication only using repository version.
Add test to create publication using repository that does not have any
version.
closes:#4874

Add test to create publication using repo version

---

pulpcore/tests/functional/api/using_plugin/test_distributions.py

Test overlapping of base_path when creating distributions.
Assuming that a distributions base_path is foo/bar. Assert that
this base_path or part of it can not be used as a new base_path for
a different distribution. No overlapping.
closes:#4882

Add back test for overlapping `base_path`

---

pulpcore/tests/functional/api/using_plugin/test_distributions.py

Assert that published metadata and content is served from a publication
distribution.
closes:#4847

Verify that content is served from publication distribution

---

pulpcore/app/serializers/content.py

Fix ContentChecksumSerializer model

---

pulpcore/__init__.py
setup.py

Bumps verison to 3.0.0rc3.dev

---

pulpcore/app/serializers/repository.py

Solution: add more details to the help text for ssl fields of Remote
[noissue]

Problem: docs for Remote ssl fields are not informative enough

---

.travis/script.sh

Solution: update script with correct library names
[noissue]

Problem: script that installs bindings is wrong

---

.travis/before_install.sh
.travis/script.sh

https://pulp.plan.io/issues/5056
re #5056

Use the template to fix Required PR logic

---

.travis/test_bindings.py
pulpcore/app/viewsets/upload.py

Shorten upload operation id names

---

CHANGES/feature.4988
pulpcore/app/viewsets/upload.py

Also added a filter to filter by incomplete.
fixes #4988

Allow deletion of uploads

---

CHANGES.rst
CHANGES/3808.doc
CHANGES/3808.feature
CHANGES/4486.feature
CHANGES/4488.feature
CHANGES/4488.removal
CHANGES/4676.removal
CHANGES/4714.removal
CHANGES/4875.doc
CHANGES/4881.doc
CHANGES/4881.feature
CHANGES/4883.feature
CHANGES/4883.removal
CHANGES/4901.feature
CHANGES/4988.feature
CHANGES/4990.bugfix
CHANGES/4990.doc
pulpcore/__init__.py
setup.py

Set 3.0.0rc3 version and generate changelog

---

pulpcore/__init__.py
setup.py

Bump version to 3.0.0rc4.dev

---

CHANGES/4662.bugfix
pulpcore/app/models/task.py
pulpcore/tasking/tasks.py
pulpcore/tasking/util.py

fixes #4662
https://pulp.plan.io/issues/4662

Set fields on orphan cleanup task

---

pulpcore/tests/functional/api/using_plugin/constants.py
pulpcore/tests/functional/api/using_plugin/test_upload.py

Add test to create artifact using chunk upload.
https://pulp.plan.io/issues/4197
ref: #4197

Add test to create artifact using chunk upload

---

pulpcore/tests/functional/api/test_upload.py

closes #5145
https://pulp.plan.io/issues/5145

Add test for testing the delete method of uploads

---

setup.py

Manually require packaging for now

---

template_config.yml

Teach template_config about build-notifications

---

pulpcore/app/serializers/__init__.py
pulpcore/app/serializers/upload.py
pulpcore/app/viewsets/upload.py
pulpcore/tests/functional/api/test_upload.py

display chunks on upload payload

---

pulpcore/tests/functional/api/test_upload.py

using correct handler

---

pulpcore/tests/functional/api/test_upload.py

Tweak upload tests assertions.
'[noissue]'

Tweak upload tests

---

.travis/test_bindings.py
docs/workflows/upload-publish.rst
pulpcore/app/models/upload.py
pulpcore/app/serializers/__init__.py
pulpcore/app/serializers/content.py
pulpcore/app/tasks/__init__.py
pulpcore/app/tasks/upload.py
pulpcore/app/viewsets/upload.py
pulpcore/tests/functional/api/test_upload.py

https://pulp.plan.io/issues/5087

Upload creating artifact asynchronously 

---

CHANGES.rst
CHANGES/4662.bugfix
CHANGES/4722.bugfix
CHANGES/4945.bugfix
CHANGES/4945.removal
CHANGES/4982.feature
CHANGES/4998.bugfix
CHANGES/5016.bugfix
CHANGES/5087.bugfix
CHANGES/5087.removal
CHANGES/5092.bugfix
CHANGES/5150.feature
CHANGES/5160.doc
pulpcore/__init__.py
setup.py

RC4 release

---

pulpcore/__init__.py
setup.py

Version bump to 3.0.0rc5.dev

---

.travis/script.sh
.travis/test_bindings.rb

Solution: run the .travis/test_bindings.rb with each PR
re: #4896
https://pulp.plan.io/issues/4896

Problem: ruby client is not tested

---

.travis/func_test_script.sh
.travis/script.sh

Adding functional tests to func_test_script.sh file

---

pulpcore/app/serializers/publication.py

assure exclusivity on repository serializer

---

containers/README.md
containers/images/pulp/Dockerfile
containers/images/pulp/container-assets/pulp-api
containers/images/pulp/container-assets/pulp-common-entrypoint.sh
containers/images/pulp/container-assets/pulp-content
containers/images/pulp/container-assets/pulp-resource-manager
containers/images/pulp/container-assets/pulp-worker
containers/images/pulp/container-assets/wait_on_database_migrations.sh
containers/vars/defaults.yaml

Also includes some other fixes/improvements that are related, or were related during development/troubleshooting.
fixes: #5176
https://pulp.plan.io/issues/5176
"Port pulp containers to Fedora 30"
Required PR: https://github.com/pulp/pulp-operator/pull/10

Switch containers to Fedora with pulp-rpm

---

.dependabot/config.yml
CHANGES/5196.feature
setup.py

https://pulp.plan.io/issues/5196

Pinning dependencies and using dependabot to manage updates

---

doc_requirements.txt

The issues we had with search in 1.8.0 seem to be resolved
[noissue]

Unpin sphinx

---

CHANGES/5182.feature
pulpcore/app/viewsets/custom_filters.py

closes #5182
https://pulp.plan.io/issues/5182

As a user I can filter char fields by multiple values

---

.travis/pulpcore_playbook.yml

Solution: travis user needs to not be using 'pulp' group
[noissue]

Problem: travis tries to connect using role 'pulp'

---

pulpcore/app/models/fields.py

re #3810
https://pulp.plan.io/issues/3810

Allow artfacts to be pre-stored in the Pulp 3 storage

---

pulpcore/tests/functional/api/test_tasks.py

closes #5180
https://pulp.plan.io/issues/5180

Add test for filtering created_resources fields

---

pulpcore/tests/functional/api/test_tasks.py

Tweak FilterTaskCreatedResourcesTestCase test case. Simplify clean up,
and consolidate the test in one test case only.
'[noissue]'

Tweak FilterTaskCreatedResourcesTestCase test case

---

CHANGES/5210.bugfix
pulpcore/app/serializers/repository.py

re #5210
https://drf-yasg.readthedocs.io/en/stable/custom_spec.html#support-for-serializermethodfield

SerializerMethodField presentation on OpenAPI

---

.travis/post_script.sh

Solution: temporarily disable building of containers for every PR
[noissue]

Problem: travis is failing to build a container

---

CHANGES/5210.misc
pulpcore/app/serializers/task.py

improve openapi schema for task

---

pulpcore/tests/functional/api/using_plugin/test_repo_versions.py

Verify how delete of repository version affects distribution/publication
associated with that particular repository version.
closes:#5303

Verify how delete of repo version affects distribution/publication

---

pulpcore/tests/functional/api/using_plugin/test_repo_versions.py

Add test to clear all units.
closes:#4956

Add test to clear all units

---

pulpcore/tests/functional/api/using_plugin/constants.py
pulpcore/tests/functional/api/using_plugin/test_sync_multiple_plugins.py

Update constants related to docker plugin.
'[noissue]'

Update constants related to docker

---

docs/installation/storage.rst

[noissue]: Updating S3 storage documentation

---

.travis.yml
.travis/script.sh
containers/images/pulp/Dockerfile.j2
containers/images/pulp/container-assets/pulp-api

refs #5321
Note that I based this branch on my branch for https://github.com/pulp/pulpcore/pull/280 . Please merge that 1st.
Please merge the changes to plugin_template also:
https://github.com/pulp/plugin_template/pull/101/files

Remove generate migrations

---

CHANGES/4992.bugfix
pulpcore/app/openapigenerator.py

closes #4992
https://pulp.plan.io/issues/4992

Adding fields parameter to OpenAPI schema

---

.gitignore
CHANGES/5282.removal
pulpcore/exceptions/base.py

closes #5282
https://pulp.plan.io/issues/5282

Removing code from task errors.

---

CHANGES.rst
CHANGES/4681.misc
CHANGES/4931.feature
CHANGES/4992.bugfix
CHANGES/5120.feature
CHANGES/5182.feature
CHANGES/5190.doc
CHANGES/5196.feature
CHANGES/5208.doc
CHANGES/5210.bugfix
CHANGES/5210.misc
CHANGES/5282.removal
CHANGES/5290.misc
CHANGES/5324.bugfix
CHANGES/5324.removal
pulpcore/__init__.py
setup.py

RC5 release

---

CHANGES/5445.bugfix
pulpcore/app/serializers/content.py

fixes #5445
https://pulp.plan.io/issues/5445

Ensure that relative_path is defined on the serializer

---

pulpcore/app/serializers/upload.py
pulpcore/app/viewsets/upload.py

Refactor upload serializers

---

pulpcore/__init__.py
setup.py

Bumping release for rc6

---

CHANGES/5009.removal
pulpcore/app/openapigenerator.py
pulpcore/app/settings.py

fixes #5009
https://pulp.plan.io/issues/5009

Filter out html by default in REST API docs

---

CHANGES/5478.bugfix
pulpcore/app/tasks/repository.py

fixes #5478
https://pulp.plan.io/issues/5478

Fix NoneType error when removing content units

---

CHANGES/5403.feature
docs/workflows/upload-publish.rst
pulpcore/app/tasks/base.py

Originally from PR from @mdellweg  https://github.com/pulp/pulpcore/pull/305

Add context general create

---

CHANGES/5403.feature
pulpcore/app/tasks/base.py

re #5403
https://pulp.plan.io/issues/5403

Add context to the general_create task

---

CHANGES/5129.doc
CHANGES/5129.removal
docs/installation/instructions.rst
setup.py

fixes #5129
https://pulp.plan.io/issues/5129

Drop support of mariadb

---

CHANGES/5507.bugfix
pulpcore/content/handler.py

closes: #5507
https://pulp.plan.io/issues/5507

Set Content-Type and Content-Encoding headers in content-app responses

---

.travis/test_bindings.py
.travis/test_bindings.rb

Use relative_path and artifact kwrd args when creating FileContent

---

CHANGES.rst
pulpcore/__init__.py
setup.py

3.0.0rc6 release

---

pulpcore/__init__.py
setup.py

3.0.0rc7.dev

---

CHANGES/5535.misc
pulpcore/app/viewsets/__init__.py
pulpcore/app/viewsets/content.py

closes #5535
https://pulp.plan.io/issues/5535

Introduce a ReadOnlyContentViewSet

---

setup.py

Updating drf-yasg to 0.17.0

---

CHANGES/4554.misc
docs/contributing/runtests.rst
docs/installation/instructions.rst
pulpcore/tasking/services/manage_workers.py
pulpcore/tasking/services/worker_watcher.py
pulpcore/tests/functional/api/test_workers.py

closes #4554
https://pulp.plan.io/issues/4554

Rename pulp services

---

CHANGES/5311.bugfix
pulpcore/app/viewsets/base.py
pulpcore/app/viewsets/upload.py

closes #5311
https://pulp.plan.io/issues/5311

Fix schemas

---

.travis.yml
.travis/before_install.sh
.travis/before_script.sh
.travis/install.sh
.travis/script.sh
CHANGES/5425.bugfix
pulpcore/app/settings.py
template_config.yml

fixes: #5425
https://pulp.plan.io/issues/5425

Load /etc/pulp/settings.py last when loading settings

---

CHANGES/5516.removal
pulpcore/app/models/repository.py
pulpcore/app/viewsets/repository.py

closes #5516
https://pulp.plan.io/issues/5516

fixing repository filter

---

CHANGES/5548.removal
pulpcore/app/serializers/repository.py
pulpcore/tests/functional/api/test_crud_repos.py
pulpcore/tests/functional/api/test_tasks.py
pulpcore/tests/functional/api/using_plugin/test_crd_publications.py
pulpcore/tests/functional/api/using_plugin/test_orphans.py
pulpcore/tests/functional/api/using_plugin/test_pagination.py
pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
pulpcore/tests/functional/api/using_plugin/test_sync_multiple_plugins.py

_versions_href to pulp_versions_href
_latest_version_href to pulp_latest_version_href
ref #5548
https://pulp.plan.io/issues/5548

Renaming RepositoryVersion fields

---

.travis/before_install.sh
.travis/script.sh

Allow installing pulpcore-plugin from source when building a tag

---

.travis/install.sh

Install pulpcore-plugin from source when building a tag

---

.travis.yml

Skip before_* scripts when publishing to PyPI

---

pulpcore/__init__.py
setup.py

Version bump for 3.0.0rc8.dev

---

CHANGES/4780.bugfix
pulpcore/app/viewsets/base.py

closes #4780
https://pulp.plan.io/issues/4780

Raise meaningful error for invalid filters

---

containers/images/pulp/Dockerfile.j2

Please merge before PR: https://github.com/pulp/pulpcore/pull/342
re: #5560
PULP_SETTINGS environment variable does not work
https://pulp.plan.io/issues/5560
[noissue]

Containers: Adds the PULP_SETTINGS Env Var

---

docs/integration-guide/index.rst

Improve docs about generating bindings.

---

pulpcore/app/settings.py
setup.py

Load plugin settings before loading user specified settings

---

.travis/before_install.sh
.travis/publish_client_gem.sh
.travis/publish_client_pypi.sh
.travis/validate_commit_message.py
CHANGES/plugin_api/.gitignore
CHANGES/plugin_api/5628.doc
docs/contributing/git.rst
docs/contributing/index.rst
pyproject.toml

https://pulp.plan.io/issues/5628
closes #5628

Add Plugin API section to changelog

---

docs/installation/storage.rst

This is embarrassing, but I didn't format the hyperlinks properly in the RST... I didn't install pulp from source just to make the docs, so I didn't verify before submitting the PR. This should work fine.

Fixed broken hyperlinks in #366.

---

.travis/install.sh
.travis/script.sh
CHANGES/5629.feature
CHANGES/5649.removal
CHANGES/plugin_api/5629.feature
docs/installation/configuration.rst
pulpcore/app/serializers/fields.py
pulpcore/app/settings.py
pulpcore/tests/functional/api/using_plugin/test_content_promotion.py
pulpcore/tests/functional/api/using_plugin/test_distributions.py
template_config.yml

Add content origin

---

.travis/publish_docs.sh
CHANGES/5686.misc

Set CONTENT_ORIGIN in Travis when publishing docs

---

CHANGES/plugin_api/3541.removal
pulpcore/plugin/repo_version_utils.py

https://pulp.plan.io/issues/3541
closes #3541

Fixup release note and docstring

---

CHANGES/5728.bugfix
pulpcore/app/tasks/repository.py

fixes #5728
https://pulp.plan.io/issues/5728

Fix lack of casting on Repository

---

pulpcore/__init__.py
setup.py

Version bump to 3.0.0rc9.dev

---

CHANGES/plugin_api/5734.feature
pulpcore/app/models/repository.py

fixes #5734
https://pulp.plan.io/issues/5734

Add a previous() method to RepositoryVersion

---

CHANGES/5770.bugfix
pulpcore/download/factory.py

fixes #5770
https://pulp.plan.io/issues/5770

Fix references to ssl_client_key and ssl_client_certificate

---

.travis.yml
.travis/check_commit.sh
.travis/install.sh
.travis/publish_client_pypi.sh
.travis/publish_plugin_pypi.sh
.travis/script.sh
.travis/validate_commit_message.py
template_config.yml

Update travis config

---

CHANGES/5718.doc
docs/installation/distributed-installation.rst
docs/installation/index.rst

https://pulp.plan.io/issues/5718
closes #5718

Remove empty Distributed Installation page.

---

CHANGES/5757.feature
pulpcore/app/models/repository.py
pulpcore/tests/functional/api/using_plugin/test_orphans.py
pulpcore/tests/functional/api/using_plugin/test_pagination.py
pulpcore/tests/functional/api/using_plugin/test_repo_versions.py

fixes #5757
https://pulp.plan.io/issues/5757

Create an initial repo version when repos get created

---

CHANGES/5717.doc
docs/installation/index.rst
docs/installation/migration.rst

https://pulp.plan.io/issues/5717
closes #5717

Remove installation/migration page.

---

setup.py

also drop www as it redirects anyways

use HTTPS for url in setup.py

---

CHANGES/5660.doc
docs/index.rst
docs/plugins/index.rst

https://pulp.plan.io/issues/5660
closes #5660

Fix Plugin API broken link on homepage

---

containers/images/pulp/Dockerfile.j2

Remove outdated workarounds from dockerfile

---

CHANGES/5723.doc
docs/client_bindings.rst
docs/glossary.rst
docs/index.rst

https://pulp.plan.io/issues/5723
closes #5723

Add Client Bindings page to left-navigation

---

CHANGES/plugin_api/5827.feature
pulpcore/app/models/publication.py

Add a new finalize_new_publication() method for Publications

---

.travis.yml
.travis/docs-builder.py
.travis/publish_docs.sh
CHANGES/5777.misc

closes: #5777
https://pulp.plan.io/issues/5777

Publish docs to a directory that matches either tag or branch name

---

pulpcore/tests/unit/test_files.py

Add more unit tests for validate_file_paths

---

CHANGES/5726.doc
docs/glossary.rst

Glossary fixes

---

CHANGES/5714.doc
docs/index.rst
docs/versioning.rst

Simplifying the docs index page

---

CHANGES/5721.doc
docs/workflows/promotion.rst

Add text to promotion page

---

docs/rest_api.rst

Update link to REST API docs.

---

CHANGES/5563.doc
docs/installation/storage.rst
docs/settings.rst
pulpcore/app/management/commands/stage-profile-summary.py

Label things as tech preview

---

CHANGES/5668.removal
CHANGES/plugin_api/5668.feature
CHANGES/plugin_api/5668.removal

https://pulp.plan.io/issues/5668
closes #5668

Update release notes for Batching change

---

CHANGES/5896.bugfix
setup.py

https://pulp.plan.io/issues/5896
closes #5896

Label pulpcore as Production/Stable

---

.travis.yml
.travis/before_install.sh
.travis/cherrypick.py
.travis/cherrypick.sh
.travis/script.sh
CHANGES/5795.misc
template_config.yml

Adding automated cherry picking

---

.travis/cherrypick.py

Updating the cherry pick script.

---

CHANGES/5894.bugfix
pulpcore/app/models/repository.py

fixes #5894
https://pulp.plan.io/issues/5894

Fix call to Task.current()

---

setup.py

Remove redis-py dep, update setuptools dep

---

pulpcore/app/models/repository.py

refs #5706
https://pulp.plan.io/issues/5706

Renaming method for RepositoryContent relationhships

---

.travis.yml

Update Travis platform to Ubuntu 18.04

---

CHANGES/5968.feature
pulpcore/app/viewsets/__init__.py
pulpcore/app/viewsets/custom_filters.py
pulpcore/app/viewsets/publication.py
pulpcore/plugin/viewsets/__init__.py
pulpcore/tests/functional/api/using_plugin/test_crd_publications.py

https://pulp.plan.io/issues/5968
ref 5968

Allow to filter publications by `repository_version` and `pulp_created`

---

docs/installation/storage.rst

Update S3 docs

---

.travis/cherrypick.py

Update travis config to fix cherrypick squash failure

---

.travis/before_install.sh
.travis/script.sh

Required PR: https://github.com/pulp/pulp-smash/pull/1228
This PR requires a pulp-smash PR ^^^ as a proof of concept. If the PR passes, then we should be good.
[noissue]

Update travis to fix Required PR failure for closed PRs

---

.travis/docs-builder.py

Passes list into make_directory_with_rsync()

---

CHANGES.rst
CHANGES/5707.bugfix
CHANGES/5833.misc
CHANGES/5867.misc
CHANGES/5870.misc
CHANGES/5873.misc
CHANGES/5894.bugfix
CHANGES/5896.bugfix
CHANGES/5941.bugfix
CHANGES/5955.bugfix
CHANGES/5955.removal
CHANGES/plugin_api/5706.feature
CHANGES/plugin_api/5941.removal

[noissue]
(cherry picked from commit 5c317f6d76f9128867249cfb6c3eaf45373e1359)

Adds 3.0.1 changelog

---

.travis.yml

Only publish continuous docs from master branch

---

.travis/before_install.sh
.travis/script.sh
functest_requirements.txt

Update travis to install bindings

---

docs/plugins/reference/metadata-signing.rst
docs/workflows/index.rst
docs/workflows/signed-metadata.rst

Mark signing as tech preview

---

.travis.yml

Remove matrix section from Travis config
[noissue]

Update from plugin template

---

pulpcore/__init__.py
setup.py

Version bump to 3.2.0.dev

---

pulpcore/__init__.py
setup.py

Version bump to 3.1.1.dev

---

CHANGES/5995.bugfix

Corrects changelog entry for issue #5995

---

CHANGES/plugin_api/6045.feature
pulpcore/content/handler.py

fixes #6045
https://pulp.plan.io/issues/6045

Fix "connection already closed" error in content app

---

CHANGES/6077.bugfix
pulpcore/app/models/content.py

closes #6077
https://pulp.plan.io/issues/6077

Fix an invalid logical operator

---

CHANGES/6154.bugfix
pulpcore/content/handler.py

https://pulp.plan.io/issues/6154
closes #6154

Fixing broken S3 redirect

---

CHANGES/5567.bugfix
pulpcore/app/models/repository.py

https://pulp.plan.io/issues/5567
closes #5567

Duplicate repo_key_fields raises an error

---

template_config.yml

Bump stable_branch to 3.1

---

CHANGES/6045.bugfix
CHANGES/plugin_api/6045.feature

https://pulp.plan.io/issues/6045
re #6045

Add bugfix changelog entry for 6045

---

setup.py

More info: https://github.com/psf/requests/pull/5342
fixes #6169

Unpin idna

---

setup.py

This reverts commit 579647e1a5accec7eed6f28ba58118987ad368a8.
[noissue]

Repin idna as requests still hasn't had a release

---

CHANGES/6190.feature
setup.py

https://pulp.plan.io/issues/6190
closes #6190

Resolve DNS faster with aiodns

---

docs/plugins/api-reference/models.rst
docs/plugins/api-reference/serializers.rst
docs/plugins/api-reference/tasking.rst
docs/plugins/api-reference/viewsets.rst

[docs] Adjust titles in api-reference

---

CHANGES/5964.bugfix
pulpcore/app/models/repository.py
pulpcore/plugin/repo_version_utils.py
pulpcore/tests/functional/api/using_plugin/test_repo_versions.py

https://pulp.plan.io/issues/5964
closes #5964

Considering base version when removing duplicates

---

docs/plugins/reference/on-demand-support.rst

Maybe the text can be improved (suggestions welcome).
But another option is deleting that paragraph, as the option is already documented above.

Document deferred_download flag for d_artifacts

---

pulpcore/app/models/repository.py
pulpcore/plugin/repo_version_utils.py

Instead handle base_version in remove_duplicates().
ref #5964
https://pulp.plan.io/issues/5964

Revert the behavior change in previous()

---

CHANGES.rst
CHANGES/5859.doc
CHANGES/5859.feature
CHANGES/5964.bugfix
CHANGES/5995.bugfix
CHANGES/6025.bugfix
CHANGES/6038.misc
CHANGES/6147.bugfix
CHANGES/6147.removal
CHANGES/6190.feature
CHANGES/6202.misc
CHANGES/6227.bugfix
CHANGES/plugin_api/5868.feature
CHANGES/plugin_api/6209.doc
pulpcore/__init__.py
setup.py
template_config.yml

3.2.0 version bumps and changelog

---

CHANGES/6121.bugfix
pulpcore/app/models/repository.py

fixes #6121
https://pulp.plan.io/issues/6121

Fetch excluded content directly from the database

---

CHANGES/plugin_api/6270.bugfix
pulpcore/tasking/tasks.py

https://pulp.plan.io/issues/6270
closes #6270

Allows tasks to dispatch tasks

---

CHANGES/6155.misc
functest_requirements.txt
pulpcore/tests/functional/api/test_crd_artifacts.py
pulpcore/tests/functional/api/test_status.py
pulpcore/tests/functional/api/test_upload.py
pulpcore/tests/functional/api/using_plugin/test_orphans.py

ref #6155
https://pulp.plan.io/issues/6155

Fix pulpcore tests against s3

---

pulpcore/plugin/repo_version_utils.py

Handle no-previous-version case in remove_duplicates util

---

.travis/pre_before_install.sh

Ref: https://travis-ci.com/github/pulp/pulpcore/jobs/296620001#L298

Fix Required PR failure

---

pulpcore/__init__.py
setup.py

Bumping 3.2 branch to 3.2.1.dev

---

.travis/script.sh

Fix versioning on ruby bindings

---

CHANGES.rst
CHANGES/6244.misc

Adds changelog for 3.2.1

---

CHANGES/6336.doc
docs/contributing/git.rst

Added documentation around changelog messages

---

pulpcore/plugin/stages/content_stages.py

Minor optimization

---

CHANGES/6284.bugfix
pulpcore/plugin/actions.py

fixes #6284
https://pulp.plan.io/issues/6284

Fixed 500 error on repository modify

---

CHANGES/5826.misc
pulpcore/app/urls.py

https://pulp.plan.io/issues/5826
closes #5826

Including license on python bindings client

---

CHANGES/6308.bugfix
pulpcore/app/viewsets/repository.py
pulpcore/tests/functional/api/using_plugin/test_repo_versions.py

fixes #6308
https://pulp.plan.io/issues/6308

Prevent deletion of repo version 0

---

.github/pr_processor.py
.github/workflows/pr_processor.yml

Update CI code with new PR Processor

---

CHANGES/6128.removal
pulpcore/app/settings.py

https://pulp.plan.io/issues/6128
ref #6128

Changing STATIC_URL

---

CHANGES/6384.doc
docs/installation/instructions.rst
docs/settings.rst

closes: #6384
https://pulp.plan.io/issues/6384

Clear up a misleading line re: database support

---

docs/contributing/pull-request-walkthrough.rst

Add note about reviewing PRs and cp label

---

containers/images/pulp/Dockerfile.j2

Adds deps needed for pulp-certguard

---

.travis/install.sh
.travis/script.sh

Adds pulp_certguard-bindings to CI

---

CHANGES/6221.doc
docs/client_bindings.rst

https://pulp.plan.io/issues/6221
closes #6221

Bindings installation for a dev environment

---

CHANGES/plugin_api/6439.bugfix
pulpcore/app/models/repository.py

Fix bug where RepositoryVersion.artifacts is None

---

docs/workflows/signed-metadata.rst

Fix the name of the imported class

---

.travis/before_script.sh

Solution: Regenerate with plugin-template
[noissue]

Problem: Travis config is out-of-date

---

CHANGES/5613.feature
docs/workflows/index.rst
docs/workflows/repairing-repository-versions.rst
pulpcore/app/tasks/repository.py
pulpcore/app/viewsets/repository.py
pulpcore/tests/functional/api/using_plugin/test_repair.py

Repair repository version

---

CHANGES/6128.removal

Improve changelog message for 6128

---

CHANGES/6347.bugfix
CHANGES/6347.feature
pulpcore/app/ordering.py
pulpcore/app/settings.py

https://pulp.plan.io/issues/6347
closes #6347

Fixed non unique content units on content list

---

CHANGES/6443.doc
docs/installation/storage.rst

Removing tech preview note for alt storage

---

.travis/before_install.sh
.travis/before_script.sh
.travis/script.sh
CHANGES/6450.bugfix
CHANGES/6451.misc
pulpcore/tests/functional/api/test_crd_artifacts.py
pulpcore/tests/functional/api/test_status.py
pulpcore/tests/functional/api/using_plugin/test_orphans.py
pulpcore/tests/functional/api/using_plugin/test_repair.py

Fix storage testing

---

CHANGES/6454.doc
docs/workflows/import-export.rst
docs/workflows/index.rst

Added tech preview note for importers/exporters.

---

CHANGES/6481.misc
pulpcore/tests/functional/api/using_plugin/test_repo_versions.py

fixes: #6481
https://pulp.plan.io/issues/6481

Adds orphan cleanup to begining of repository version tests

---

pulpcore/__init__.py
setup.py

Bump verison to 3.3.1.dev

---

template_config.yml

Update the stable branch to 3.3

---

docs/installation/storage.rst

https://pulp.plan.io/issues/5687
[noissue]

Changing S3 example to use dynaconf casting

---

CHANGES/6364.doc
docs/workflows/import-export.rst

Adding some importer workflow docs

---

CHANGES/6457.removal
pulpcore/app/serializers/exporter.py

Changing repositories on PulpExporter to href field

---

CHANGES/6456.feature
pulpcore/app/importexport.py

Make export code work with S3

---

docs/plugins/plugin-writer/concepts/index.rst
docs/plugins/plugin-writer/concepts/subclassing/import-export.rst
docs/workflows/import-export.rst

Added docs for the export-side of import/export

---

CHANGES/6507.bugfix
pulpcore/app/serializers/fields.py
pulpcore/tests/functional/api/using_plugin/test_content_promotion.py
pulpcore/tests/functional/api/using_plugin/test_distributions.py

Add a missing trailing slash

---

CHANGES/plugin_api/6514.removal
docs/plugins/plugin-writer/concepts/subclassing/import-export.rst
pulpcore/app/modelresource.py
pulpcore/plugin/importexport.py

Rehome QueryModelResource to pulpcore.plugin.importexport

---

CHANGES.rst
CHANGES/6485.docs

Fixed missing changelog entry due to bad file extension

---

CHANGES/6468.bugfix
pulpcore/app/viewsets/base.py

fixes: #6468
https://pulp.plan.io/issues/6468

Fixes KeyError during OpenAPI schema generation.

---

CHANGES/plugin_api/6579.feature
pulpcore/plugin/constants.py

Expose constants via the plugin api

---

CHANGES/plugin_api/6281.feature
docs/components.rst
docs/glossary.rst
docs/plugins/plugin-writer/concepts/subclassing/viewsets.rst
docs/workflows/on-demand-downloading.rst
pulpcore/app/files.py
pulpcore/app/tasks/base.py
pulpcore/plugin/serializers/__init__.py
pulpcore/plugin/serializers/content.py
pulpcore/plugin/viewsets/__init__.py
pulpcore/plugin/viewsets/content.py

Add NoArtifactContentUploadSerializer

---

CHANGES/6521.bugfix
CHANGES/plugin_api/6521.feature
pulpcore/app/serializers/base.py
pulpcore/app/serializers/content.py
pulpcore/app/serializers/exporter.py
pulpcore/app/serializers/importer.py
pulpcore/app/serializers/publication.py
pulpcore/app/serializers/repository.py
pulpcore/plugin/serializers/content.py

fixes #6521
https://pulp.plan.io/issues/6521

Add view_name_pattern to DetailRelatedField

---

CHANGES/6565.bugfix
pulpcore/app/serializers/fields.py

closes #6565
https://pulp.plan.io/issues/6565

Fixed partial and general update calls.

---

CHANGES/6583.misc
doc_requirements.txt
setup.py

fixes #6583
https://pulp.plan.io/issues/6583

Remove coreapi dependency

---

.travis/publish_docs.sh

[noissue]
Please review very cautious, as this is not executed on PRs.

Fix publishing nightly docs

---

.travis/publish_docs.sh

Activate pulp config for docs publishing

---

template_config.yml

Fix broken builds for 3.3 branch

---

CHANGES/6565.bugfix
CHANGES/6573.bugfix
CHANGES/plugin_api/6603.feature
pulpcore/app/serializers/fields.py
pulpcore/app/serializers/task.py
pulpcore/plugin/models/__init__.py

Cherry picks to 3.3

---

CHANGES/6572.misc
pulpcore/app/importexport.py
pulpcore/app/tasks/export.py
pulpcore/app/util.py
pulpcore/tests/functional/api/using_plugin/test_pulpexport.py

Add version.json to top level of export.tar.gz

---

CHANGES.rst
CHANGES/6565.bugfix
CHANGES/6573.bugfix
CHANGES/plugin_api/6603.feature
pulpcore/__init__.py
setup.py

Release 3.3.1

---

CHANGES/6465.bugfix
pulpcore/app/viewsets/task.py
pulpcore/tasking/util.py
pulpcore/tests/functional/api/using_plugin/test_tasking.py

fixes #6465
https://pulp.plan.io/issues/6465

Fix response when trying to cancel a completed task

---

CHANGES.rst
CHANGES/6565.bugfix
CHANGES/6573.bugfix
CHANGES/plugin_api/6603.feature

[noissue]
(cherry picked from commit fd121e36fc86c654c47a9022fc81cc7a9faf57e5)

3.3.1 changelog

---

.travis/cherrypick.py
pulpcore/content/__init__.py
pulpcore/content/handler.py
pulpcore/tasking/worker.py

* update travis from plugin_template
[noissue]
ping @daviddavis

Fix new flake issues

---

CHANGES/6566.feature
docs/workflows/import-export.rst
pulpcore/app/models/exporter.py
pulpcore/app/tasks/export.py
pulpcore/app/viewsets/exporter.py
pulpcore/tasking/tasks.py
pulpcore/tests/functional/api/using_plugin/test_pulpexport.py

Teach PulpExport to export specific repo-versions when invoked with versions:= .

---

CHANGES/6695.misc
pulpcore/app/serializers/base.py

fixes 6695
https://pulp.plan.io/issues/6695

Add class info to warning around `view_name`

---

CHANGES/6702.bugfix
pulpcore/app/openapigenerator.py

https://pulp.plan.io/issues/6702
closes #6702

Only uses multipart when dealing with file fields

---

CHANGES/6542.misc
pulpcore/tests/functional/api/using_plugin/test_pulpimport.py
pulpcore/tests/functional/utils.py

Add test for pulp imports

---

CHANGES/6556.bugfix
pulpcore/app/models/__init__.py
pulpcore/app/models/exporter.py
pulpcore/app/openapigenerator.py
pulpcore/app/serializers/__init__.py
pulpcore/app/serializers/exporter.py
pulpcore/plugin/models/__init__.py
pulpcore/plugin/serializers/__init__.py
pulpcore/tests/functional/api/using_plugin/test_pulpexport.py
pulpcore/tests/functional/api/using_plugin/test_pulpimport.py

fixes: #6556
https://pulp.plan.io/issues/6556

Fixes the OpenAPI schema for import and export APIs

---

CHANGES/6136.feature
docs/plugins/plugin-writer/concepts/subclassing/import-export.rst
docs/workflows/import-export.rst
pulpcore/app/importexport.py
pulpcore/app/tasks/export.py
pulpcore/tests/functional/api/using_plugin/test_pulpexport.py

Respond to full=False by creating an incremental export.

---

.travis/docs-builder.py

[noissue]
Fixing:
https://travis-ci.com/github/pulp/pulpcore/jobs/338129670

Fix docs-builder

---

CHANGES/6758.doc
docs/installation/instructions.rst

https://pulp.plan.io/issues/6758
closes #6758

Updated the required roles names

---

CHANGES/6564.bugfix
pulpcore/app/models/exporter.py
pulpcore/tests/functional/api/using_plugin/test_pulpexport.py

Normalize tarfile-path for PulpExports.

---

CHANGES/6558.feature
pulpcore/app/tasks/importer.py

Add version checking to import

---

.travis/script.sh

https://github.com/pulp/plugin_template/pull/222
[noissue]

Adding check for uncommitted migrations

---

CHANGES.rst
CHANGES/6692.doc
docs/components.rst
docs/installation/authentication.rst
docs/rest_api.rst

closes #6692
https://pulp.plan.io/issues/6692

Add warning that REST API is not safe for multi-user use

---

CHANGES/6532.feature
pulpcore/app/tasks/importer.py

Added repo type check during import

---

.bumpversion.cfg
.travis/release.py
CHANGES/6803.misc
CHANGES/6804.misc
requirements.txt
setup.py

Release script

---

.travis/install.sh

S3 tests are failing due to https://github.com/minio/minio/issues/9736.
[noissue]

Use previous minio docker image

---

CHANGES/6836.doc
docs/installation/instructions.rst

https://pulp.plan.io/issues/6836
ref #6836

Updating installation docs

---

template_config.yml

Bump the stable_branch to 3.4

---

.bumpversion.cfg
CHANGES.rst
CHANGES/6888.bugfix
pulpcore/__init__.py
setup.py

Redmine query of issues to close:
https://pulp.plan.io/issues?set_filter=1&status_id=*&issue_id=6888
Release commit == c3514be

Release 3.4.1

---

CHANGES/6483.misc
pulpcore/tests/functional/api/using_plugin/test_pulpimport.py

Adding a test to import a PulpExport twice

---

CHANGES/6925.misc
doc_requirements.txt

Add doc requirement on requirements.txt

---

CHANGES/6992.doc
docs/installation/authentication.rst

closes #6992
https://pulp.plan.io/issues/6992

No longer claim that there is a default password.

---

CHANGES/plugin_api/6832.feature
docs/plugins/reference/how-to-doc-api.rst
pulpcore/app/openapigenerator.py

https://pulp.plan.io/issues/6832
closes #6832

Views can specify the tag name

---

CHANGES/6771.bugfix
pulpcore/app/settings.py

Provide a more descriptive error message

---

.travis/smash-config.json
CHANGES/6925.misc
doc_requirements.txt

Cherry picking changes to get the 3.4 branch passing again.

3.4 cherry pick fixes

---

docs/installation/instructions.rst

Update installer docs

---

CODEOWNERS

Remove QE as codeowner

---

CHANGES/6919.doc
docs/workflows/import-export.rst

Also made examples consistent.

Fixed a number of typos in import/export docs.

---

pulpcore/app/viewsets/base.py

Prevent a crash when generating the api schema

---

CHANGES/7087.removal
pulpcore/app/openapigenerator.py

Revert "Splitting seralizers into read and write ones"

---

.bumpversion.cfg
pulpcore/__init__.py
setup.py

Bumps version to 3.5.1.dev

---

template_config.yml

Updates stable_branch in template_config.yml to 3.5

---

docs/contributing/git.rst

[noissue]
This documents: https://github.com/pulp/plugin_template/pull/241

Document selecting ci base image in PRs

---

CHANGES/plugin_api/7187.feature
pulpcore/plugin/viewsets/__init__.py

https://pulp.plan.io/issues/7187
closes #7187

Add Task and TaskGroup viewsets to the plugin api

---

CHANGES/plugin_api/7191.feature
pulpcore/app/viewsets/__init__.py
pulpcore/app/viewsets/repository.py
pulpcore/plugin/viewsets/__init__.py

Required by https://github.com/pulp/pulp_container/pull/127.
closes #7191

 Enable plugin writers to inherit from ImmutableRepositoryViewSet

---

.travis/Containerfile.j2
.travis/before_install.sh
.travis/before_script.sh
.travis/install.sh
template_config.yml

Updates template config's branch for pulp_file

---

CHANGES/7196.misc
pulpcore/app/response.py

Fix the response's structure returned by OperationPostponedResponse

---

CHANGES/plugin_api/7021.feature
pulpcore/app/models/repository.py

Allow plugins to modify logic for repo version artifacts

---

CHANGES/plugin_api/7117.feature
pulpcore/download/http.py

https://pulp.plan.io/issues/7117
closes #7117

`HttpDownloader` control on response codes 400+

---

CHANGES/plugin_api/7233.bugfix
pulpcore/openapi/__init__.py

https://pulp.plan.io/issues/7233
closes #7233

Making operation_id unique

---

CHANGES/plugin_api/7237.bugfix
pulpcore/openapi/__init__.py

https://pulp.plan.io/issues/7237
closes #7237

Making ReDoc OpenAPI summary human readable

---

.travis.yml
template_config.yml

Per our pulpcore team meeting today.
[noissue]

Disabling cherry pick processor

---

CHANGES/7209.bugfix
pulpcore/openapi/__init__.py

fixes #7209
https://pulp.plan.io/issues/7209

Namespace href placeholder in schema generation

---

CHANGES/plugin_api/7258.bugfix
pulpcore/openapi/__init__.py

https://pulp.plan.io/issues/7258
closes #7258

OpenAPI schema generation from CLI

---

pulpcore/openapi/__init__.py

Stop preventing to render the status endpoint

---

docs/bugs-features.rst

Fix formatting of the numbered list.

---

CHANGES/7292.doc
docs/Makefile

https://pulp.plan.io/issues/7292
closes #7292

REST API docs

---

CHANGES/7142.misc
pulpcore/app/models/content.py
pulpcore/plugin/stages/artifact_stages.py

Use "IN" instead of "OR" which is easier for PostgreSQL to optimize.
[noissue]

Rewrite QueryExistingArtifacts stage for performance

---

CHANGES/plugin_api/7296.doc
docs/plugins/plugin-writer/concepts/subclassing/import-export.rst

Added plugin writer docs for BaseContentResource

---

CHANGES/7065.doc
docs/installation/instructions.rst

fixes #7065
Make passwords consistent across Ansible installer and Pulp core docs.

Update password variable term

---

CHANGES/7306.bugfix
pulpcore/openapi/__init__.py

fixes #7306
https://pulp.plan.io/issues/7306

Decouple plugin filter apidoc from "bindings"

---

CHANGES/7231.feature
CHANGES/7232.feature
pulpcore/app/serializers/__init__.py
pulpcore/app/serializers/user.py
pulpcore/app/viewsets/__init__.py
pulpcore/app/viewsets/user.py

https://pulp.plan.io/issues/7231
closes #7231

Read API for Users, Group membership, and Permissions

---

CHANGES/7285.doc
docs/installation/instructions.rst

fixes: #7285
https://pulp.plan.io/issues/7285

Adds docs about SSL certificate configuration

---

pulpcore/app/views/orphans.py

Specify proper operationId for orphan_delete

---

CHANGES/7310.feature
CHANGES/7311.feature
pulpcore/app/serializers/user.py
pulpcore/app/viewsets/__init__.py
pulpcore/app/viewsets/user.py

https://pulp.plan.io/issues/7311
closes #7311

Remove permissions associated with groups

---

CHANGES/6305.doc
docs/installation/instructions.rst

closes #6305
https://pulp.plan.io/issues/6305

Updated Pypi installation step.

---

docs/plugins/plugin-writer/concepts/subclassing/models.rst

Fix broken quotes

---

requirements.txt

ref: https://github.com/pulp/pulp_installer/pull/396#discussion_r472528997
[noissue]

Jinja2 as requirement

---

CHANGES/plugin_api/7351.feature
pulpcore/plugin/tasking.py

fixes: #7351
https://pulp.plan.io/issues/7351

Add add_and_remove task to pulpcore.plugin.tasking

---

CHANGES/plugin_api/7347.bugfix
pulpcore/openapi/__init__.py

https://pulp.plan.io/issues/7347
closes #7347

OpenAPI: do not discard components without properties

---

template_config.yml

Set stable branch to 3.6

---

CHANGES/plugin_api/5927.doc
docs/plugins/plugin-writer/concepts/index.rst

fixes #5927
https://pulp.plan.io/issues/5927

Add documentation for validating models

---

CHANGES/6255.doc
docs/from-pulp-2.rst

closes #6255
https://pulp.plan.io/issues/6255

Add pulp 2 obsolete concepts (consumers, applicability).

---

.travis/docs-builder.py
CHANGES/7229.misc

re: #7229
https://pulp.plan.io/issues/7229

Updates the location of where docs are published on pulpproject.org

---

.travis.yml
.travis/Containerfile.j2
.travis/before_install.sh
.travis/before_script.sh
.travis/docs-builder.py
.travis/install.sh
.travis/publish_plugin_pypi.sh
.travis/release.py
.travis/settings.py.j2
.travis/start_container.yaml
.travis/update_redmine.sh
CHANGES/6305.doc
CHANGES/6856.doc
CHANGES/7229.misc
CHANGES/7329.bugfix
CHANGES/plugin_api/7341.bugfix
CHANGES/plugin_api/7347.bugfix
dev_requirements.txt
docs/components.rst
docs/installation/instructions.rst
pulpcore/app/viewsets/user.py
pulpcore/openapi/__init__.py
template_config.yml

Cherry-picks for 3.6.1. This includes 4 bug fixes, documentation improvements, and changes to where Travis will publish docs.

3.6.1 cherry picks

---

.travis/validate_commit_message.py
CHANGES/7415.feature
CHANGES/plugin_api/7415.feature
docs/contributing/git.rst
pyproject.toml

Added deprecations to the changelog.

---

CHANGES/6844.feature
functest_requirements.txt
setup.py

https://pulp.plan.io/issues/6844
closes #6844
Ref: https://github.com/pypa/pip/issues/3147#issuecomment-144656466

Extra require: postgres, s3, azure, prometheus and test

---

CHANGES.rst
CHANGES/6305.doc
CHANGES/6856.doc
CHANGES/7229.misc
CHANGES/7329.bugfix
CHANGES/plugin_api/7341.bugfix
CHANGES/plugin_api/7347.bugfix

Building changelog for 3.6.1

---

.bumpversion.cfg
CHANGES.rst
CHANGES/plugin_api/7446.bugfix
pulpcore/__init__.py
pulpcore/app/views/orphans.py
pulpcore/openapi/__init__.py
pulpcore/tests/functional/api/using_plugin/test_orphans.py
pulpcore/tests/functional/utils.py
setup.py

This PR contains a cherry-pick from master branch along with the changelog for 3.6.2 release.

Release 3.6.2

---

CHANGES.rst
CHANGES/plugin_api/7446.bugfix

Building changelog for 3.6.2

---

.bumpversion.cfg
CHANGES.rst
CHANGES/7450.misc
pulpcore/__init__.py
setup.py

Release 3.6.3

---

CHANGES.rst

Building changelog for 3.6.3

---

CHANGES/6449.bugfix
pulpcore/tasking/tasks.py

closes: #6449
https://pulp.plan.io/issues/6449

Fix tasks stuck in waiting state on redis connection failure

---

pulpcore/tasking/tasks.py

Don't raise 500 error if Redis is unavailable

---

CHANGES/plugin_api/7270.misc
docs/plugins/plugin-writer/concepts/subclassing/viewsets.rst
pulpcore/app/tasks/base.py
pulpcore/plugin/viewsets/content.py

Use PulpTemporaryFile instead of Artifact when passing temporary data

---

pulpcore/tests/functional/api/using_plugin/test_pulpexport.py

Fixed test_pulpexporter so it runs more reliably when not in isolation.

---

.travis/Containerfile.j2
.travis/before_install.sh
.travis/validate_commit_message.py

Update travis files with plugin_template

---

pulpcore/openapi/__init__.py

Addressing drf-spectacular 0.9.13 breaking changes

---

.travis.yml

Remove services we don't need in Travis

---

README.md

Removing outdated badges

---

CHANGES/7497.bugfix
pulpcore/app/models/__init__.py
pulpcore/app/models/task.py
pulpcore/tasking/tasks.py

Setting the reserved resource record when creating the task

---

CHANGES/7444.bugfix
pulpcore/openapi/__init__.py

https://pulp.plan.io/issues/7444
closes #7444

Fix OpenAPI status code response

---

CHANGES/7510.bugfix
pulpcore/openapi/__init__.py
requirements.txt

Cherrypick drf-spectacular fixes to 3.6

---

CHANGES/plugin_api/7413.doc
docs/plugins/plugin-writer/concepts/index.rst
docs/plugins/reference/releasing.rst

* Adds docs on how the deprecation process works
* Adds docs on how to depend on pulpcore with this policy
closes #7413

Add deprecation policy to plugin writer guide

---

CHANGES/7487.feature
pulpcore/app/settings.py

Added check for ALLOWED_CONTENT_CHECKSUMS that Artifacts are missing

---

CHANGES/7460.bugfix
pulpcore/app/tasks/orphan.py

closes #7460
https://pulp.plan.io/issues/7460

Remove orphan content in a loop to clean up subrepos' content as well.

---

CHANGES/plugin_api/6828.doc
docs/plugins/reference/how-plugins-work.rst

https://pulp.plan.io/issues/6828
closes #6828

Document the URLField OpenAPI issue

---

CHANGES/7541.bugfix
pulpcore/app/viewsets/user.py

Query app label when looking up permissions.

---

CHANGES/plugin_api/7555.doc
docs/bugs-features.rst
docs/plugins/api-reference/index.rst
docs/plugins/index.rst

Remove mentions of semver for plugin-api

---

.bumpversion.cfg
CHANGES.rst
CHANGES/7510.bugfix
pulpcore/__init__.py
setup.py

Release 3.6.4

---

CHANGES.rst

3.6.4 changelog

---

CHANGES/4921.bugfix
pulpcore/tasking/util.py

closes: #4921
https://pulp.plan.io/issues/4921

Set ProgressReport states to canceled when task is canceled

---

CHANGES/7610.bugfix
MANIFEST.in

https://pulp.plan.io/issues/7610
closes #7610

Including functest_requirements.txt on MANIFEST.in

---

CHANGES/plugin_api/7624.feature
pulpcore/plugin/__init__.py

Revert "Expose pulpcore_version to plugin writers"

---

CHANGES/7637.feature
docs/settings.rst
pulpcore/app/settings.py
pulpcore/app/urls.py

closes: #7637
https://pulp.plan.io/issues/7637

Configurable URL for Django admin site

---

CHANGES.rst
CHANGES/7610.bugfix

Building changelog for 3.7.1

---

CHANGES/7568.bugfix
pulpcore/content/handler.py

https://pulp.plan.io/issues/7568
closes #7568

Enable on demand sync for RepositoryVersionDistribution

---

CHANGES/7657.doc
docs/bugs-features.rst

Document that we do not support backporting migrations

---

CHANGES/7655.doc
docs/workflows/upload-publish.rst

closes: #7655
https://pulp.plan.io/issues/7655

Fix erroneous content upload url

---

docs/workflows/upload-publish.rst

Fix content upload urls, actually

---

requirements.txt

Using == since this package isn’t at 1.0 yet. 
[noissue]

Pin drf-nested-routers to new release

---

CHANGES/7475.doc
docs/contributing/tests.rst

Mentioned `prestart`, `pminio`, `pfixtures` and `phelp`.
fixes #7475
https://pulp.plan.io/issues/7475

Improve testing section in Pulp contributor docs

---

CHANGES/5247.doc
docs/workflows/exposing-content.rst
docs/workflows/import-export.rst
docs/workflows/upload-publish.rst

closes #5247
https://pulp.plan.io/issues/5247

Updated examples of auto-distribution.

---

.bumpversion.cfg
CHANGES.rst
CHANGES/4559.bugfix
CHANGES/4921.bugfix
CHANGES/5247.doc
CHANGES/6992
CHANGES/7147.bugfix
CHANGES/7475.doc
CHANGES/7487.feature
CHANGES/7568.bugfix
CHANGES/7634.bugfix
CHANGES/7637.feature
CHANGES/7655.doc
CHANGES/7656.bugfix
CHANGES/7657.doc
CHANGES/7682.bugfix
CHANGES/7720.feature
CHANGES/plugin_api/7555.doc
pulpcore/__init__.py
setup.py

Release 3.8.0

---

.bumpversion.cfg
pulpcore/__init__.py
setup.py

Bump to 3.8.1.dev

---

CHANGES/7735.bugfix
pulpcore/app/tasks/repository.py

closes: #7735
https://pulp.plan.io/issues/7735

Fix file descriptor leak in repo version repair

---

CHANGES/plugin_api/7718.feature
pulpcore/app/serializers/task.py

Pass an adjusted request object to the serializer

---

CHANGES/7569.feature
pulpcore/openapi/__init__.py

fixes #7569
https://pulp.plan.io/issues/7569

Add version information to apidoc

---

CHANGES/7676.bugfix
pulpcore/app/models/content.py
pulpcore/app/models/upload.py
pulpcore/app/settings.py
requirements.txt

This reverts commit f508d6b2ba4d624d64bcdbfa6c851afe159c6fac.
closes: #7676
https://pulp.plan.io/issues/7676

Revert "Delete associated files from the storage"

---

.gitignore
CHANGES/7753.misc
flake8.cfg
functest_requirements.txt

Adding missing pytest dependency

---

CHANGES.rst
CHANGES/6992

[noissue]
(cherry picked from commit dbe03eb816ccaf394436069524b2b1e278e6ea6c)

Building changelog for 3.7.2

---

docs/plugins/plugin-writer/concepts/sync_pipeline/sync_pipeline.rst

Fix typo in docs

---

.travis/before_install.sh
.travis/install.sh
template_config.yml

Configure travis for the z releases on the 3.8 branch

---

.bumpversion.cfg
CHANGES.rst
CHANGES/7758.bugfix
pulpcore/__init__.py
setup.py

Release 3.8.1

---

CHANGES/7701.feature
pulpcore/app/models/content.py

Raise an error when a user tries to update a signing service

---

CHANGES/7793.doc
docs/installation/instructions.rst

[noissue]
Discussed this with @mikedep333 last week. 
Let me know if any changes are needed.

Remove SELinux from installer note

---

CHANGES/7703.doc
docs/contributing/dev-setup.rst
docs/contributing/index.rst
docs/contributing/record-a-demo.rst

fixes #7703
* fix typo in dev-setup
I just wanted to get the ball rolling with this one. 
I tried to strike a balance wrt what the *requirement* is.
I'm happy to make any amendments that you see fit.

Add record a demo requirement

---

CHANGES.rst

[noissue]
(cherry picked from commit b6cd9d257db2053cc2666bd13b7b4e1ba904b55f)

Building changelog for 3.8.1

---

.bumpversion.cfg
.travis/update_redmine.sh
pulpcore/__init__.py
setup.py

Redmine Query: https://pulp.plan.io/issues?set_filter=1&status_id=*&issue_id=7737
Redmine Milestone: https://pulp.plan.io/versions/154.json
[noissue]

Releasing 3.6.5.post2

---

.bumpversion.cfg
pulpcore/__init__.py
setup.py

Bump to 3.6.6.dev

---

pulpcore/tests/functional/api/using_plugin/test_repair.py

re: #7690
https://pulp.plan.io/issues/7690

Removes use of django.conf.settings from repair test

---

pulpcore/openapi/__init__.py
requirements.txt

Bump drf-spectacular from 0.10.0 to 0.11.0

---

CHANGES.rst

[noissue]
(cherry picked from commit 81be3118e450829e4bc90e727415964d099ecd0a)

Building changelog for 3.6.5

---

CHANGES/plugin_api/7833.feature
pulpcore/plugin/models/__init__.py

Import the models Upload and UploadChunk

---

docs/plugins/plugin-writer/concepts/sync_pipeline/sync_pipeline.rst
pulpcore/plugin/stages/content_stages.py

Added information about dropping DeclarativeContent

---

pulpcore/tests/functional/api/using_plugin/test_filesystemexport.py

Fix test that causes /tmp to be deleted

---

CHANGES/7710.bugfix
docs/plugins/plugin-writer/concepts/rbac/access_policy.rst
docs/plugins/plugin-writer/concepts/rbac/overview.rst
pulpcore/app/apps.py
pulpcore/app/viewsets/task.py

fixes #7710
https://pulp.plan.io/issues/7710
@bmbouter Time for a first look at my design of this.

Add access policies with post_migrate signal

---

CHANGES/plugin_api/7696.feature
pulpcore/app/models/content.py
pulpcore/exceptions/__init__.py
pulpcore/exceptions/validation.py
pulpcore/plugin/exceptions.py
pulpcore/tests/unit/models/test_content.py

Added pre_save hook to Artifact to enforce checksum rules.

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
.github/workflows/release.yml

Update GHA - Fix nightly bindings test

---

CHANGES/6559.feature
docs/plugins/plugin-writer/concepts/index.rst
pulpcore/app/importexport.py
pulpcore/app/tasks/importer.py
pulpcore/tests/functional/api/using_plugin/test_pulpexport.py
pulpcore/tests/functional/api/using_plugin/test_pulpimport.py

Add progress reporting for imports

---

.ci/assets/bindings/test_bindings.py
.ci/assets/bindings/test_bindings.rb

Switch binding tests to use fixtures.pulpproject.org

---

CHANGES/7561.feature
CHANGES/7914.feature
docs/settings.rst
pulpcore/app/management/commands/handle-artifact-checksums.py
pulpcore/app/settings.py
pulpcore/download/factory.py

Added command to populate missing checksums.
closes #7561
https://pulp.plan.io/issues/7561

As a user, I have artifacts compliant with the allowed checksums.

---

.github/workflows/nightly.yml
.github/workflows/release.yml

Updating github actions file from plugin_template

---

.ci/scripts/release.py

Release script set version bump commit correctly

---

pulpcore/tests/functional/api/using_plugin/test_filesystemexport.py
pulpcore/tests/functional/api/using_plugin/test_orphans.py
pulpcore/tests/functional/api/using_plugin/test_pulpimport.py
pulpcore/tests/functional/utils.py

Required PR: https://github.com/pulp/pulp-smash/pull/1247
[noissue]

Consolidate some utility functions

---

CHANGES/7878.doc
docs/contributing/dev-setup.rst

fixes #7878
https://pulp.plan.io/issues/7878
This depends on https://github.com/pulp/pulp_installer/pull/498

Updated pulplift references in the docs

---

CHANGES/7750.doc
docs/components.rst
docs/installation/storage.rst

fixes #7750
https://pulp.plan.io/issues/7705

Add filesystem layout to installation docs

---

CHANGES/7982.bugfix
pulpcore/app/settings.py

closes: #7982
https://pulp.plan.io/issues/7982

Hide django_guid log messages

---

CHANGES/7975.feature
pulpcore/app/viewsets/user.py
pulpcore/tests/functional/api/test_users_groups.py

fixes #7975
https://pulp.plan.io/issues/7975

Add filter to users and groups endpoints

---

pulpcore/app/models/base.py
pulpcore/app/serializers/base.py
pulpcore/app/serializers/content.py
pulpcore/app/serializers/exporter.py
pulpcore/app/serializers/fields.py
pulpcore/app/serializers/publication.py
pulpcore/app/serializers/repository.py
pulpcore/app/serializers/task.py
pulpcore/app/tasks/importer.py
pulpcore/plugin/stages/profiler.py

Fixing unnecessary split strings

---

.ci/scripts/schema.py
.github/workflows/scripts/script.sh
pulpcore/app/serializers/user.py
pulpcore/openapi/__init__.py

Validate OpenAPI schema

---

CHANGES/3387.bugfix
pulpcore/app/serializers/content.py

Have a more descriptive artifact error message

---

docs/contributing/pull-request-walkthrough.rst

Adding a pulp-cli item to PR checklist

---

requirements.txt

commas are important ;)
[noissue]

correct rq requirement

---

CHANGES/plugin_api/8117.feature
pulpcore/app/viewsets/__init__.py
pulpcore/plugin/viewsets/__init__.py

closes #8117
https://pulp.plan.io/issues/8117

Add NAME_FILTER_OPTIONS to the plugin API

---

CHANGES/8131.doc
docs/plugins/index.rst

Add links to plugin docs

---

CHANGES.rst
CHANGES/7890.misc
CHANGES/8099.removal

Building changelog for 3.9.1

---

CHANGES/8152.bugfix
pulpcore/app/access_policy.py
pulpcore/app/apps.py
pulpcore/app/util.py

closes #8152
https://pulp.plan.io/issues/8152

Take into account parent_viewset url when dealing with access policies

---

requirements.txt

https://github.com/rsinger86/drf-access-policy/issues/46
[noissue]

Carry pyparsing dependency

---

.ci/ansible/smash-config.json

Update the port for pulp-fixtures

---

pulpcore/tests/functional/__init__.py
pulpcore/tests/functional/api/__init__.py
pulpcore/tests/functional/api/test_api_docs.py
pulpcore/tests/functional/api/test_auth.py
pulpcore/tests/functional/api/test_crd_artifacts.py
pulpcore/tests/functional/api/test_status.py
pulpcore/tests/functional/api/test_upload.py
pulpcore/tests/functional/api/test_workers.py
pulpcore/tests/functional/api/using_plugin/__init__.py
pulpcore/tests/functional/api/using_plugin/constants.py
pulpcore/tests/functional/api/using_plugin/test_content_delivery.py
pulpcore/tests/functional/api/using_plugin/test_content_path.py
pulpcore/tests/functional/api/using_plugin/test_content_promotion.py
pulpcore/tests/functional/api/using_plugin/test_crd_publications.py
pulpcore/tests/functional/api/using_plugin/test_crud_repos.py
pulpcore/tests/functional/api/using_plugin/test_distributions.py
pulpcore/tests/functional/api/using_plugin/test_orphans.py
pulpcore/tests/functional/api/using_plugin/test_pagination.py
pulpcore/tests/functional/api/using_plugin/test_pulpexport.py
pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
pulpcore/tests/functional/api/using_plugin/test_tasking.py
pulpcore/tests/functional/api/using_plugin/test_tasks.py
pulpcore/tests/functional/api/using_plugin/test_unlinking_repo.py
pulpcore/tests/functional/api/using_plugin/utils.py
pulpcore/tests/functional/api/utils.py
pulpcore/tests/functional/utils.py

Remove setting of coding

---

CHANGES/8185.bugfix
CHANGES/8189.feature
pulpcore/app/serializers/access_policy.py
pulpcore/app/viewsets/access_policy.py

Also make viewset_name readonly.

Add filtering to access policies

---

pulpcore/app/global_access_conditions.py

re #8161
https://pulp.plan.io/issues/8161

Fix repo attribute check to work with the detail model

---

CHANGES/8067.feature
CHANGES/plugin_api/8067.feature
pulpcore/app/viewsets/custom_filters.py
pulpcore/app/viewsets/publication.py
pulpcore/app/viewsets/repository.py
pulpcore/plugin/viewsets/__init__.py
pulpcore/tests/functional/api/using_plugin/test_labels.py

Add pulp_label_filter for filtering by pulp_labels

---

CHANGES/7549.feature
docs/workflows/import-export.rst
pulpcore/app/serializers/__init__.py
pulpcore/app/serializers/importer.py
pulpcore/app/urls.py
pulpcore/app/views/__init__.py
pulpcore/app/views/importer.py
pulpcore/tests/functional/api/using_plugin/test_pulpimport.py

Added import-check command, tests, and doc.

---

CHANGES/8193.feature
pulpcore/app/viewsets/content.py

As an authenticated user I can create and view artifacts.

---

CHANGES/7888.bugfix
CHANGES/CHANGES/7888.bugfix

Also line-wrap to 100 chars per the Pulp style guide.
re #7888

Move changelog to correct folder.

---

pulpcore/app/viewsets/custom_filters.py
pulpcore/tests/functional/api/using_plugin/test_labels.py

Fix label inequality filtering

---

CHANGES/8157.doc
docs/workflows/index.rst
docs/workflows/labels.rst

Add workflow doc for labels

---

requirements.txt

Bump drf-access-policy to 0.8.6.

---

docs/plugins/index.rst

Update migration docs link

---

docs/plugins/plugin-writer/concepts/rbac/queryset_scoping.rst

Added info about klass parameter for the custom queryset scoping.

---

CHANGES/plugin_api/7815.feature
pulpcore/tasking/storage.py
pulpcore/tasking/worker.py

closes: #7815
https://pulp.plan.io/issues/7815

Enable nesting WorkingDirectory() calls

---

pulpcore/content/handler.py

Likely insignificant in the grand scheme.
[noissue]

Small optimizations of content app queries

---

CHANGES/7797.misc
pulpcore/tests/functional/api/using_plugin/test_pulpexport.py
pulpcore/tests/functional/api/using_plugin/test_pulpimport.py

Skip import/export tests if /tmp not in ALLOWED.

---

.github/workflows/scripts/before_install.sh
.github/workflows/scripts/script.sh
template_config.yml

Enable CLI test

---

requirements.txt

Upgrading drf-spectacular

---

functest_requirements.txt

Fix dependabot bug

---

CHANGES/8283.bugfix
pulpcore/app/viewsets/publication.py
pulpcore/tests/functional/api/using_plugin/test_generic_list.py

Returned content_guards API to correct contentguards.

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/scripts/install.sh

Show pip dependencies in the CI

---

CHANGES/7985.feature
pulpcore/app/settings.py

Add warning if on-demand content does not have allowed checksum

---

CHANGES/7927.doc
docs/settings.rst

Remove correlation id feature from tech preview

---

CHANGES/7854.feature
pulpcore/plugin/stages/artifact_stages.py

Raise exception when disallowed checksum found in QueryExistingArtifacts
stage.
closes: #7854
https://pulp.plan.io/issues/7854

Raise exception when disallowed checksum

---

CHANGES/8291.feature
docs/settings.rst
pulpcore/app/models/task.py
pulpcore/app/settings.py
pulpcore/tasking/constants.py
pulpcore/tasking/worker.py
pulpcore/tasking/worker_watcher.py

The heartbeat rate will scale proportional to that timeout.
fixes #8291

Turn WORKER_TTL into a setting

---

CHANGES/8315.misc
pulpcore/app/models/content.py
pulpcore/app/serializers/content.py

Fix bad i18n

---

.bumpversion.cfg
.github/workflows/ci.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
CHANGES.rst
CHANGES/8373.bugfix
pulpcore/__init__.py
setup.py

Release 3.7.4

---

CHANGES.rst

[noissue]
(cherry picked from commit 1e0ffe19e6fd7d9d22676949ec38ba8f6593e37d)

CP changelog for 3.7.4

---

pulpcore/app/settings.py
pulpcore/openapi/__init__.py
requirements.txt

Bump drf-spectacular from 0.13.2 to 0.14.0

---

pulpcore/app/settings.py

Refactor script check in settings

---

CHANGES/8325.doc
docs/settings.rst

Update docs with how to properly change 'ALLOWED_CONTENT_CHECKSUMS' setting.
closes: #8325
https://pulp.plan.io/issues/8325

Allow content checksums doc

---

CHANGES/7985.feature
pulpcore/app/settings.py

Add warning if there are remote artifacts with no allowed checksums

---

CHANGES/8357.bugfix
CHANGES/plugin_api/8357.feature
pulpcore/download/base.py
pulpcore/exceptions/validation.py

Added url to the size and digest validation error messages.

---

CHANGES/8116.bugfix
pulpcore/app/tasks/importer.py
pulpcore/tests/functional/api/using_plugin/test_pulpexport.py
pulpcore/tests/functional/api/using_plugin/test_pulpimport.py
pulpcore/tests/functional/api/using_plugin/utils.py

Also taught import and export tests to share more utility code.
fixes #8116

Taught PulpImport to not rely on next_version from upstream.

---

requirements.txt

Bump gunicorn requirement

---

CHANGES/8489.bugfix
pulpcore/plugin/stages/artifact_stages.py

Teach artifact_stages:_needed_remote_artifacts() to not return dupes.

---

CHANGES/8499.removal
docs/plugins/plugin-writer/concepts/index.rst
pulpcore/app/logging.py
pulpcore/app/models/publication.py
pulpcore/app/serializers/publication.py
pulpcore/app/viewsets/publication.py
pulpcore/tasking/storage.py

Fixed bug where deprecation warnings weren't being logged

---

.ci/scripts/docs-builder.py
.ci/scripts/publish_client_gem.sh
.ci/scripts/publish_client_pypi.sh
.ci/scripts/publish_plugin_pypi.sh
.ci/scripts/release.py
.github/workflows/release.yml
template_config.yml

Updating CI

---

CHANGES/8454.feature
pulpcore/app/models/repository.py
pulpcore/app/serializers/fields.py
pulpcore/app/tasks/repository.py
pulpcore/app/viewsets/repository.py
pulpcore/tests/functional/api/using_plugin/test_repo_versions.py

Allow users to delete repo version 0

---

pulpcore/openapi/__init__.py
requirements.txt

Bump drf-spectacular from 0.14.0 to 0.15.1

---

docs/installation/storage.rst

With this PR, I try to put manners on this section. It's a prerequisite section in reality. 
In another PR in the coming days, I'll link to the Amazon S3 docs in Pulp installer. 
[noissue]

Add steps to S3 storage prereqs

---

.ci/scripts/docs-builder.py

Bring docs-builder.py up to date on 3.7 branch to avoid release failures

---

.bumpversion.cfg
pulpcore/__init__.py
setup.py

Prep release 3.7.5.post0

---

.bumpversion.cfg
pulpcore/__init__.py
setup.py

Bump version to 3.7.6.dev

---

CHANGES.rst

[noissue]
(cherry picked from commit 4347b3fcf0487f4db221185ab43137970f4c30f4)

CP of 3.7.5 changelog

---

CHANGES/plugin_api/8354.removal
pulpcore/plugin/tasking.py
pulpcore/tasking/storage.py

Remove deprecated WorkinDirectory from tasking

---

CHANGES/8524.misc
pulpcore/app/apps.py
pulpcore/app/settings.py
pulpcore/tests/unit/models/test_task.py

Disable django guardian's anonymous user.

---

CHANGES/plugin_api/8578.bugfix
pulpcore/plugin/serializers/__init__.py

closes: #8578
https://pulp.plan.io/issues/8578

Add RepositoryVersionRelatedField to plugin API

---

docs/installation/authentication.rst

Fix authentication docs spelling mistakes

---

pulpcore/app/tasks/export.py
pulpcore/app/viewsets/exporter.py

Fix pulp export creation task dispatching

---

CHANGES/8595.bugfix
pulpcore/tasking/storage.py

https://pulp.plan.io/issues/8595

fix Directory not empty error

---

CHANGES.rst

Pulling in 3.12.1 changelog

---

pulpcore/app/models/publication.py
pulpcore/app/serializers/publication.py
pulpcore/app/viewsets/publication.py
pulpcore/openapi/__init__.py

Reformat with black 21.4b0

---

CHANGES/8625.bugfix
pulpcore/plugin/stages/artifact_stages.py

Fix artifact_stages to not uniquify based on an empty checksum-type.

---

docs/installation/storage.rst

Underscore was in the wrong place, breaking the link. 
[noissue]

Fix broken link

---

CHANGES/6068.feature
pulpcore/app/serializers/repository.py

Add repository field to repository versions endpoint

---

CHANGES/8636.bugfix
pulpcore/content/handler.py

fixes: #8636
https://pulp.plan.io/issues/8636

Fixed new distributions not showing up in content app

---

CHANGES/8603.bugfix
pulpcore/app/models/task.py

Fix reservation cleanup race condition

---

CHANGES.rst

Cherrypicking 3.11.1 changelog

---

.ci/scripts/docs-builder.py

The release of 3.11.1 failed on the docs publish step. This fix is needed to fix it: https://github.com/pulp/plugin_template/commit/2567426240d19e4fffbd2ac65aa6d307a96c2ffc
[noissue]

Fixing docs-builder script on 3.11 branch

---

CHANGES.rst

Changelog cps

---

pulpcore/plugin/stages/content_stages.py

Fix small mistake

---

requirements.txt

Pin django to 2.2.20 until https://pulp.plan.io/issues/8691 is resolved.
[noissue]

Temporarily pin django

---

.ci/scripts/publish_client_pypi.sh

Fix publish pypi client job

---

.dependabot/config.yml
.github/dependabot.yml

Upgrade to GitHub-native Dependabot

---

pulpcore/app/models/repository.py

Remove duplicate code to set objects

---

docs/plugins/api-reference/download.rst

Fix docs building with Sphinx 4.0

---

CHANGES/plugin_api/8497.removal
pulpcore/app/response.py
pulpcore/plugin/tasking.py
pulpcore/tasking/tasks.py

Removed ``pulpcore.plugin.tasking.enqueue_with_reservation``.

---

pulpcore/openapi/__init__.py
requirements.txt

Bump drf-spectacular from 0.15.1 to 0.16.0

---

.ci/ansible/settings.py.j2
.ci/scripts/cherrypick.sh
.ci/scripts/publish_client_gem.sh
.ci/scripts/publish_client_pypi.sh
.ci/scripts/publish_plugin_pypi.sh
.ci/scripts/release.py
.ci/scripts/validate_commit_message.py
.github/workflows/release.yml
.github/workflows/scripts/before_install.sh
.github/workflows/scripts/check_commit.sh
.github/workflows/scripts/script.sh
template_config.yml

Updating CI files for 3.11 branch

---

CHANGES/8628.bugfix
pulpcore/app/serializers/exporter.py
pulpcore/tests/unit/serializers/test_pulpexport.py

Taught PulpExportSerializer to validate chunk-size-max.

---

CHANGES/7019.doc
docs/installation/instructions.rst

I added a note. 
I can link to instructions on how to do so if necessary but didn't see precedent for this. 
fixes #7019
**Edited the issue number

Add note to use UTF-8 with postgres db

---

docs/installation/instructions.rst

[noissue]
@ipanova if it were me writing this section, I'd chunk like this rather than add notes. 
I just did this as an example. I don't mind if this isn't accepted, but it might be helpful for someone scanning the doc. 

Chunk info in postgres section

---

CHANGES/6703.doc
docs/installation/instructions.rst

fixes #6703
https://pulp.plan.io/issues/6703

Add documentation not to create new migrations

---

CHANGES/8584.doc
docs/index.rst

fixes #8584
I haven't tested this link. 
I will add to pulpproject.org as well. 

Add security info to pulpcore doc homepage

---

CHANGES/6990.doc
docs/concepts.rst

fixes: #6990
https://pulp.plan.io/issues/6990
Take a look at https://docs.pulpproject.org/pulpcore/concepts.html and tell me if I also need to change the diagrams or if this one sentence is enough to clarify everything.

Mention repositories are typed in concepts page

---

.ci/scripts/cherrypick.sh
.github/workflows/scripts/before_install.sh
.github/workflows/scripts/before_script.sh
.github/workflows/scripts/install.sh
.github/workflows/scripts/script.sh
template_config.yml

Update CI from template

---

CHANGES/8774.doc
docs/components.rst
docs/workflows/index.rst
docs/workflows/troubleshooting.rst

Currently this section contains tips to recover a jammed tasking system.
fixes #8774

Add troubleshooting section to documentation

---

pulpcore/tasking/worker_watcher.py

Fix typo in worker_watcher

---

CHANGES/plugin_api/8844.feature
pulpcore/plugin/viewsets/__init__.py

Expose AsyncUpdateMixin to the plugin writers.

---

requirements.txt

Release notes: https://docs.djangoproject.com/en/3.2/releases/2.2.24/

Update django requirement to 2.2.24

---

docs/workflows/import-export.rst

Added a note about presence of destination repository during the import

---

pulpcore/tests/functional/api/using_plugin/test_distributions.py

Add test for content app range requests

---

CHANGES/8803.doc
docs/authentication/index.rst
docs/authentication/keycloak.rst

* Provide documentation for Keycloak integration using python social auth
* Define dependencies
* Document generic python social auth updates
* Provide instructions for specific Keycloak settings and Keycloak setup
fixes #8803
https://pulp.plan.io/issues/8803

Document Keycloak authentication for Pulp

---

README.md
docs/plugins/plugin-writer/concepts/index.rst
pyproject.toml
template_config.yml

Remove references to freenode and travis

---

pulpcore/app/management/commands/handle-artifact-checksums.py
pulpcore/app/tasks/repository.py

Make sure we close file descriptor if error is thrown

---

CHANGES/8926.bugfix
requirements.txt

More info:
https://github.com/django/django/commit/837ffcfa681d0f65f444d881ee3d69aec23770be
https://github.com/psycopg/psycopg2/issues/1293

Pin psycopg2 to < 2.9

---

pulpcore/tasking/pulpcore_worker.py

Also add traceback to logging on failed tasks.
[noissue]

Adjust loglevels in pulpcore-worker

---

pulpcore/tests/upgrade/pre/test_publish.py

Adds the pre-upgrade test

---

pulpcore/tasking/pulpcore_worker.py

Without this, the new working dir is created, but it isn't changed into
so plugin code writes temp files into the wrong area.
[noissue]

Make new tasking system cd into working dir

---

CHANGES/8883.bugfix
pulpcore/app/apps.py

Update default access policies if unmodified

---

CHANGES/8930.feature
pulpcore/tasking/pulpcore_worker.py

fixes #8930
https://pulp.plan.io/issues/8930

Graceful worker shutdown

---

CHANGES/8949.doc
docs/concepts.rst

Just trying to reduce jargon and make this easier to read. 
It definitely needs a David Davis job done on it. Low priority though. 
fixes #8949

Add subheadings and simplify conceptual intro

---

docs/authentication/keycloak.rst

I just got time now to review the Keycloak docs. 
Late to the party, and I think they are fine tbh. 
You can close this PR if it is of no value. 
[noissue]

Tiny suggested edits to keycloak docs

---

.github/workflows/scripts/install.sh

Properly specifies the package name that needs to be installed

---

CHANGES/8987.bugfix
pulpcore/tasking/pulpcore_worker.py

fixes #8987
https://pulp.plan.io/issues/8987

Attempt to cancel aborted tasks on worker shutdown
